### ISSUE TITLE
event subscriber syntax not compatible with Telescope 3.x

### ISSUE THREAD

**Issue by lucaspanik** [laravel/telescope#1007]
- Telescope Version: 3.5.1
- Laravel Version: 7.30.0
- PHP Version: 7.4.9
- Database Driver & Version:

### Description:
I am facing the same problem as the reference ticket in version 3.x of Telescope.

References:
[#952](https://github.com/laravel/telescope/issues/952)
[#953](https://github.com/laravel/telescope/pull/953)

Solution:
https://github.com/laravel/telescope/commit/a69fc6f4f5fd5b0ac5a242981e162774cbb69e17

Error:
![image](https://user-images.githubusercontent.com/7035554/106310192-f5226380-6241-11eb-9758-9aaf0f2c289d.png)

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
