### ISSUE TITLE
Telescope records sensitive information present in the session's old input

### ISSUE THREAD

**Issue by simioluwatomi** [laravel/telescope#1008]
- Telescope Version: 4.4.0
- Laravel Version: 8.20.1
- PHP Version: 7.4.13
- Database Driver & Version: MySQL  8.0.22

### Description:
I'm logging all Telescope requests to a log file using a Custom Watcher because I want to retain this information for a long time. I basically just copied the `recordRequest` method in `Laravel\Telescope\Watchers\RequestWatcher` and added an additional line to enable logging like so
```
\Log::channel('nameOfCustomChannel')->debug(json_encode($incomingEntry));
```
While going through the logs backed up on S3, I discovered that Telescope logs sensitive information from the request when it is present in the `_old_input` session array.

```
'session' => $this->payload($this->sessionVariables($event->request)),
```

```
private function sessionVariables(Request $request)
{
    return $request->hasSession() ? $request->session()->all() : [];
}
```

```
protected function payload($payload)
{
    return $this->hideParameters($payload,
        Telescope::$hiddenRequestParameters
    );
}
```

```
protected function hideParameters($data, $hidden)
{
    foreach ($hidden as $parameter) {
        if (Arr::get($data, $parameter)) {
            Arr::set($data, $parameter, '********');
        }
    }

    return $data;
}
```

### Steps To Reproduce:
1. Fill a form that fails to submit successfully and redirects back to the form
2. Check the database to find the telescope entry that was just recorded. Copy the value of the `content` column
3. Sensitive request details are present in `session->_old_input`

**Comment by driesvints** [comment]
I'm not sure what sensitive information you're talking about? Logging old input could be useful for debugging purposes.

**Comment by simioluwatomi** [comment]
Well for one, `password` and `password_confirmation` fields are logged. Is there a circumstance in which those should be logged even for debugging purposes?

**Comment by driesvints** [comment]
Ah I see what you mean. That's a good remark. I'm wondering if this is more a Laravel issue than a Telescope issue for having those values in session in the first place. I'll check in on that with the team and get back to you.

**Comment by simioluwatomi** [comment]
Well, I wasn't sure if it's a framework issue or a Telescope one. If it's a framework issue, I think Telescope should have a workaround for it until the framework decides how best to remedy this.

What makes me think this is a Telescope issue however is that the framework already has a mechanism for not flashing sensitive information to the session in `Handler.php`. It doesn't explicitly mean those inputs are not present in the session; they are just not flashed for validation exceptions

My workaround is to override the `sessionVariables` method in my CustomRequestWatcher like so

```
private function sessionVariables(Request $request)
{
    if ($request->hasSession()) {
        $clone = $request->session()->all();

        if ($request->session()->hasOldInput()) {
            $clone['_old_input'] = $this->payload($clone['_old_input']);
        }
    } else {
        $clone = [];
    }

    return $clone;
}
```

**Comment by driesvints** [comment]
Yes but like you said that's only when validation exceptions occur. The values are still flashed for successful form submissions. So the exception handler doesn't apply there. I'm currently thinking about implementing a `$dontFlash` array also on the `InteractsWithFlashData`.

**Comment by driesvints** [comment]
@simioluwatomi you're gonna have to write some examples on how to reproduce this because no matter what I try no `_old_input` ends up in the logged requests for me. Can you please create a repo with a fresh laravel app and telescope and the minimum amount of code needed to reproduce this? Please commit your changes separately from the skeleton.

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue and we'll re-open this issue.
