### ISSUE TITLE
Gate watcher does not take after interceptors into account

### ISSUE THREAD

**Issue by RSpeekenbrink** [laravel/telescope#1014]
- Telescope Version: 4.4.2
- Laravel Version: 8.27.0
- PHP Version: 7.4
- Database Driver & Version: MariaDB 

### Description:
When I was using the Spatie Laravel Permission package I came to the conclusion that the Gate watchers for Laravel Telescope do not take the Gate interceptors into account. When I made an interceptor function to give a wildcard to users with the admin role, all gate calls show as "denied" in telescope while in reality they return as "allowed".

### Steps To Reproduce:
1. Create an authorization ability.
2. Create a Gate interceptor function (https://laravel.com/docs/master/authorization#intercepting-gate-checks) that returns the opposite of the expected result.
3. Wrong value gets displayed in telescope.

**Comment by driesvints** [comment]
Please provide all code in order to reproduce this issue, thanks.

**Comment by RSpeekenbrink** [comment]
Sorry I might should have done a little more research into the interceptors and the GateWatcher before creating the issue.

I found out it just has to do with the `after` interceptor, the before interceptor works fine. As it states in the laravel documentation the after interceptor will be called after all the other Authorization checks so it might be expected that Telescope doesn't take after interceptors into account? Anyway this is the example I used it with:

In AuthServiceProvider:

```
Gate::define('test-gate', function ($user) {
   return null;
});

Gate::after(function ($user, $ability) {
    return true;
});
```

When I call `$user->can('test-gate')` this returns `true` due to the after interceptor but telescope will still state that the gate has been denied. 

It looks like with AutoLoading the TelescopeServiceProvider the Gate watcher registers the telescope `after` gate https://github.com/laravel/telescope/blob/2544c879631e1d8e48aef1c7ee79b3dee8cbb833/src/Watchers/GateWatcher.php#L26 before the AuthServiceProvider does thereby adding the after check after telescope registering them.

**Comment by driesvints** [comment]
Hey @RSpeekenbrink, thanks for that detailed explanation. That was helpful.

Were working on a specific fix for this by adding a new method to the Gate in Laravel that will serve as a specific fix to this problem. Will probably still be somewhere next week until we can push that through.

https://github.com/laravel/framework/pull/36329
