### ISSUE TITLE
Non-string model keys breaking tag insert

### ISSUE THREAD

**Issue by olsgreen** [laravel/telescope#1016]
- Telescope Version: 3.5.1 
- Laravel Version: 6.20.16
- PHP Version: 7.4.14
- Database Driver & Version: MySQL 5.7.32

### Description:

A project we're working on is using binary based primary keys on a certain model. The current [formatter](https://github.com/laravel/telescope/blob/966d462c0d658b27560ea73279de3fb85c63a930/src/FormatModel.php#L17) assumes that the return from a call to a models `getKey()` method is safe to use as a string based tag. Due to this, when telescope is trying to tag our model, it generates an SQL error due to it trying to insert binary data:

`SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xEBq\x02\x98uv...' for column 'tag'`

I can't see an easy way to work around this, I was thinking of submitting a PR that changes the [formatter](https://github.com/laravel/telescope/blob/966d462c0d658b27560ea73279de3fb85c63a930/src/FormatModel.php#L17) to check for the existence of a `getTelescopeKey()` method, then to prefer it over `getKey()`. Thoughts?  

### Steps To Reproduce:

- Install telescope
- Create a model type with a binary primary key
- Try saving

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by olsgreen** [comment]
@driesvints Your support policy states v6 bug fixes stop on September 7th, 2021? Telescope 4.x doesn't support v6?
