### ISSUE TITLE
GET /telescope-api/requests throws 500

### ISSUE THREAD

**Issue by sinnrrr** [laravel/telescope#1017]
- Telescope Version: 4.4.3
- Laravel Version: 8.28.1
- PHP Version: 8.0.2
- Database Driver & Version: php-mysql 2:8.0+80+ubuntu20.04.1+deb.sury.org+1

### Description:
Going to domain.com/telescope/requests throws 500

In DevTools saw that problem is in following route:
https://evoraid.test/telescope/telescope-api/requests?tag=&before=&take=50&family_hash=

```
{
    "message": "Type of Laravel\\Telescope\\Storage\\EntryModel::$casts must be array (as in class Illuminate\\Database\\Eloquent\\Model)",
    "exception": "Symfony\\Component\\ErrorHandler\\Error\\FatalError",
    "file": "/home/sinnrrr/Work/evoraid/vendor/laravel/telescope/src/Storage/EntryModel.php",
    "line": 9,
    "trace": []
}
```

### Steps To Reproduce:
```
composer require laravel/telescope
php artisan telescope:install
php artisan migrate
```

GET /telescope

**Comment by driesvints** [comment]
Please set up a repo which reproduces this issue with the minimum code needed. Please commit your custom changes separately from the base Laravel skeleton.

**Comment by sinnrrr** [comment]
Apparantly, doing fresh install of laravel, and moving all the business logic to it, then installing telecope resolved the issue. I think there were some package conflitcs. Thanks for sparing somw time for this issue.
