### ISSUE TITLE
[Feature Request] A Toolbar ?

### ISSUE THREAD

**Issue by Ronan-Lenor** [laravel/telescope#1021]
Hello,

i was wondering if we could have a toolbar at the bottom of a page, so we could have a quick view if a problem occur.
i know there is a package call "fruitcake/laravel-telescope-toolbar" but it doesn't work right now and i don't especially want to use a third party package anyway.
I think that a toolbar from " laravel/telescope " would be much more relevant.

thanks,

**Comment by driesvints** [comment]
No plans for this sorry.
