### ISSUE TITLE
Enabling Telescope causes dd() helper to stop working!

### ISSUE THREAD

**Issue by byGits** [laravel/telescope#1026]
- Telescope Version: 4.4.5
- Laravel Version: 8.32.1
- PHP Version: 7.4.12
- Database Driver & Version: MySQL 5.7.32

### Description:
When I enable Telescope, Laravel's `dd()` helper function stops working! (it does exit() the code, but displays only a blank white page with nothing in the source)

For example I tried `dd('test')`, the page turns blank, but as soon as I change `.env` file and set `TELESCOPE_ENABLED=false`, it works!

### Steps To Reproduce:
Just enabling Telescope causes this for me, this is a fresh project and the only other package I've installed is `barryvdh/laravel-debugbar`.

**Comment by driesvints** [comment]
See the answers above.

**Comment by robtesch** [comment]
Hi guys, I've only just noticed this behaviour myself (only spent about 3 hours debugging it!). It makes complete sense for "dump" calls, but for surely not for "dd".

Is there any chance this behaviour can be changed specifically for "dd" calls?

**Comment by byGits** [comment]
> Hi guys, I've only just noticed this behaviour myself (only spent about 3 hours debugging it!). It makes complete sense for "dump" calls, but for surely not for "dd".
> 
> Is there any chance this behaviour can be changed specifically for "dd" calls?

Hi @robtesch,

After some searching, I realized you can easily disable it by adding `TELESCOPE_DUMP_WATCHER=false` to my `.env` file

IMHO this should be the default behavior though, and only enabled if needed, but I'm still grateful the option is there.

**Comment by robtesch** [comment]
That's true (and I saw that higher up in the thread too) but in an ideal
world calls to "dump" would get picked up by telescope but calls to "dd"
would operate normally.

I looked into the code for this though and it doesn't look like that's
going to be particularly easy to do without a bunch of hackery, so simply
disabling the watcher is probably the way to go for now.

**Comment by driesvints** [comment]
We tagged v4.4.6 that should fix this.
