### ISSUE TITLE
Filter requests per more than one tag

### ISSUE THREAD

**Issue by LeonardoLpds** [laravel/telescope#1027]
Should be nice if we can filter requests per more than one tag.
For instance, I created a tag for uri, so I can filter **uri:/login** then I created a tag for client id to filter requests like that **id:123**, What I want to do is search both tags simultaneously

**Comment by driesvints** [comment]
Heya, if you want to propose something like this, just feel free to send in a PR so we can look at the code needed to make this happen. Thanks
