### ISSUE TITLE
Since Telescope Version 4.4.5 the VarDumper (dd, dump) doesnt work

### ISSUE THREAD

**Issue by webcodecs** [laravel/telescope#1028]
- Telescope Version: 4.4.5
- Laravel Version: 8.32.1
- PHP Version: 7.3.24
- Cache-Driver: redis

### Description:
I was working on my project with laravel/framework 8.28.1 and telescope 4.4.3. Everything was fine. After a complete composer update, i noticed that the output of the VarDumper doesnt work anymore. The application dies with dd but i doesnt get any output. I rolled back the composer update and updated each package separatly.

framework version / telescope version
8.28.1 / 4.4.3        - is working
8.29.0 / 4.4.5       - is not working
8.32.1 / 4.4.5       - is not working
8.32.1/ 4.4.3        -  is working

### Steps To Reproduce:
Its easy to reproduce if you try the not working combinations above.
I took a look in to the changes of the 4.4.5 version and remeber something depends on caching. In my environment i use Redis as cache driver

**Comment by driesvints** [comment]
This is an issue with Symfony. Please report on their tracker.

**Comment by webcodecs** [comment]
@driesvints I dont understand. The telescope version is changing and its a problem with symfony? The new VarDumper versions are just spelling corrections. Can you please give me an idea, which symfony package do you mean, causes the error?

**Comment by webcodecs** [comment]
And if i disable the DumpWatcher (which changed in laravel/telescope 4.4.5) my dumps are working. Please consider to reopen this issue, because i think its an issue with the dumpWatcher and not with symfony.

**Comment by webcodecs** [comment]
Okay i researched a bit more. The problem is that with an enabled DumpWatcher all dumps were collected to telescope. That is working fine if your are using dump(). But if you are using dd(), the applications exits without sending the dump to telescope

**Comment by driesvints** [comment]
Sorry, I misunderstood this at first. We reverted the change that broke this and tagged 4.4.6. Thanks for reporting.
