### ISSUE TITLE
`dd` broken since telescope:dump-watcher cache check is moved to `VarDumper ::setHandler` callback

### ISSUE THREAD

**Issue by Levivb** [laravel/telescope#1029]
Hey

This commit: https://github.com/laravel/telescope/commit/897d2e03278718551badede7ed612893d61b8e49
broke the `dd` utility in Laravel (with Ignition)

I'm under the impression `$this->cache->get('telescope:dump-watcher')` only resolves to `true` when the dump call is executed via `src/Http/Controllers/DumpController.php:44`, since only in that location the `telescope:dump-watcher` is set to `true` for 4 seconds.

Right now, running a plain `dd` in for example a Http Controller will run the callback:
```
VarDumper::setHandler(function ($var) use ($htmlDumper) {
            if (! $this->cache->get('telescope:dump-watcher')) {
                return;
            }

            $this->recordDump($htmlDumper->dump(
                (new VarCloner)->cloneVar($var), true
            ));
        });
```

resolving `$this->cache->get('telescope:dump-watcher')` to false and thus ending the var dumper without any output. The next call in `dd` is `exit(1)`:
```
    function dd(...$vars)
    {
        foreach ($vars as $v) {
            VarDumper::dump($v);
        }

        exit(1);
    }
```

I recon the previously registered var dumper should be executed instead?

**Comment by driesvints** [comment]
Thanks. We tagged v4.4.6 that reverts the change. Please fill out the issue template next time.

**Comment by Levivb** [comment]
Oh, an issue template was not provided when creating an issue 🤔  Would have done it otherwise of course 👍 

Thanks for the quick rollback!

**Comment by driesvints** [comment]
@Levivb it wasn't for you?

![Screenshot 2021-03-11 at 14 46 13](https://user-images.githubusercontent.com/594614/110796715-8db3f680-8278-11eb-8e58-9a44b35c395a.jpg)

**Comment by Levivb** [comment]
No, I think it has something to do with the automatic logout (https://github.blog/2021-03-08-github-security-update-a-bug-related-to-handling-of-authenticated-sessions/) which caused me to login again.

To reproduce:
1. Open incognito window and navigate to https://github.com/laravel/telescope/issues
2. Click on `New issue`
3. A registration modal opens up
4. Click on "Already on GitHub? Sign in to your account"
5. Login to Github (with 2FA as far as it matters)
6. You'll be redirected to https://github.com/laravel/telescope/issues/new

Navigating to https://github.com/laravel/telescope/issues/new in here with an active session also opens up a vanilla issue form.

Seems like a bit of a Github bug since you'd actually want people to end up here: https://github.com/laravel/telescope/issues/new/choose

**Comment by driesvints** [comment]
@Levivb that's a very interesting edge case. I'd indeed not expect people to end up with a blank issue since we've explicitly disabled that: https://github.com/laravel/telescope/blob/4.x/.github/ISSUE_TEMPLATE/config.yml#L1

I'll forward this to GitHub.
