### ISSUE TITLE
Suggestion: rename "queued" tag for successfully mailable (if it is not my mistake)

### ISSUE THREAD

**Issue by chrisfritsche** [laravel/telescope#1032]
Hello everyone!

I don't know if something is missing in my implementation but, recently the "queued" tag assigned to my successfully mailable's has caused some inconvenience. So I would like to suggest that, like the Jobs tag, this tag also be changed to "processed", since the term "queued", in my opinion, is closer to the idea that the entry was made, than the output generated successfully.

But it also can be my mistake. In this case, please, any orientation what it could be?

Thank you very much in advance!

![image](https://user-images.githubusercontent.com/59613648/110867707-7d773800-82c7-11eb-8e83-566e6f6b185c.png)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
