### ISSUE TITLE
Freezes the page for detail sql query

### ISSUE THREAD

**Issue by mayken** [laravel/telescope#1042]
- Telescope Version: 4.4.7
- Laravel Version: 8.36.0
- PHP Version: 7.3.24
- Database Driver & Version: PostgreSQL 12

### Description:
After update to latest release i have bug when viewing detailed information about a SQL query, the page freezes. Downgrade to version 4.3.2 helped me.

**Comment by driesvints** [comment]
Did you republish the assets after updating? https://laravel.com/docs/8.x/telescope#upgrading-telescope

**Comment by JexPY** [comment]
Got the same problem.

- Telescope Version: 4.4.7
- Laravel Version: 8.36.0
- PHP Version: 7.4.13
- Database: Mysql 8.0.22

p.s
I have republished assist after updating, had no problem before only with Telescope@4.4.7.

**Comment by mayken** [comment]
> Did you republish the assets after updating? https://laravel.com/docs/8.x/telescope#upgrading-telescope

Yes

**Comment by driesvints** [comment]
Released v4.4.8 with a fix. Thanks for reporting 👍
