### ISSUE TITLE
[Octane] Telescope logs requests to Telescope dashboard

### ISSUE THREAD

**Issue by Namoshek** [laravel/telescope#1043]
- Telescope Version: 4.4.4
- Laravel Version: 8.36.0
- PHP Version: 8.0.3
- Database Driver & Version: SQL Server (latest)

### Description:
After installing Octane using the Swoole driver (literally the only config), I noticed that Telescope is logging the own requests from the Telescope dashboard. The request times are sick :rocket:, but I have not seen this before. I can confirm this does not happen when running php-fpm with nginx in front instead (using the very same code base and package versions).

![image](https://user-images.githubusercontent.com/8877609/113752177-f6be4b00-970c-11eb-9639-56f751813ca0.png)

### Steps To Reproduce:
- Install Octane and Telescope
- Checkout the Telescope dashboard

**Comment by taylorotwell** [comment]
Update your Telescope installation please.
