### ISSUE TITLE
Extra Whitespaces in SQL format

### ISSUE THREAD

**Issue by tomirons** [laravel/telescope#1046]
@driesvints with the update to `sql-formatter` there are now whitespaces where they shouldn't be. You can fix this by setting the `language` on the formatter to `mysql` but I'm not sure how it would act with a _postgres_ database.

Here is the new output:
```sql
select
  *
from
  ` database `.` table `
where
  ` database `.` table `.` column ` = 1
limit
  1
```

_Originally posted by @tomirons in https://github.com/laravel/telescope/issues/1039#issuecomment-816020331_

**Comment by driesvints** [comment]
Escalated to sql-formatter. Next time please fill out the issue template.

https://github.com/zeroturnaround/sql-formatter/issues/139

**Comment by tomirons** [comment]
@driesvints my apologies, I created it straight from the comment I made on the related pull request. I'll be sure to use the template next time.

**Comment by driesvints** [comment]
I've temporarily downgraded sql-formatter to fix the issue: https://github.com/laravel/telescope/pull/1050
