### ISSUE TITLE
Payload, Session and Response Format

### ISSUE THREAD

**Issue by rcerljenko** [laravel/telescope#1047]
- Telescope Version: 4.4.8
- Laravel Version: 8.36.2
- PHP Version: 7.4.16
- Database Driver & Version: MySql 8.0.21

### Description:

With the release of 4.4.7 version in Request Details view the Payload, Session and Response tabs no longer contain whitespace in JSON dump.

### Steps To Reproduce:

Execute any request with Payload or Response JSON data.

**Comment by driesvints** [comment]
Thanks, this PR will fix this. Apparently vue-json-pretty introduced a breaking change on a minor release 😞 https://github.com/leezng/vue-json-pretty/releases/tag/v1.7.0

https://github.com/laravel/telescope/pull/1049
