### ISSUE TITLE
Prune command started throwing exception when telescope is disabled

### ISSUE THREAD

**Issue by Eldair** [laravel/telescope#1048]
- Telescope Version: 4.4.8
- Laravel Version: 8.36.2
- PHP Version: 8

### Description:
After the latest update `telescope:prune` started throwing exception `There are no commands defined in the "telescope" namespace` when telescope is disabled. It might be a desired effect but it is not documented in changelog so users could add proper check for when command is scheduled.

### Steps To Reproduce:
Disable telescope and run `telescope:prune`

**Comment by driesvints** [comment]
This has already been fixed and will be tagged next Tuesday at the latest: https://github.com/laravel/telescope/pull/1045
