### ISSUE TITLE
Mail and Jobs

### ISSUE THREAD

**Issue by crlcu** [laravel/telescope#105]
Look like the mails that are send from a queued job are not stored. The same is happening for the jobs.

**Comment by themsaid** [comment]
> Weird, it works now.

That says something :) You need to debug that yourself sense it's reproducible by any of the maintainers. Could be something special with your app(s).

**Comment by ardian-c** [comment]
> Same here I guess. I have "We didn't find anything - just empty space" on every tabs, except "Exceptions" and "Schedule".

I have the same issue too, but I can only access Commands, Schedule, and Queries in production.

**Comment by Medalink** [comment]
Most likely it's the `Telescope::filter` in your TelescopeServiceProvder. Local enables everything while non-local limits.

**Comment by NSpehler** [comment]
That was it! Thank you @Medalink!

**Comment by edgrosvenor** [comment]
@themsaid - This is what was actually causing the issue I raised yesterday about not monitoring all my servers. Might be something to mention in the docs.

**Comment by themsaid** [comment]
We're still writing the docs for Telescope, will make sure this is included.

**Comment by hopeseekr** [comment]
Every single tab is blank for me.
