### ISSUE TITLE
Can't run migrations for Telescope

### ISSUE THREAD

**Issue by zmudzinski** [laravel/telescope#1052]
- Telescope Version: 4.4
- Laravel Version: 8.38
- PHP Version: 8.0.3
- Database Driver & Version: MySql 5.7

### Description:
After installing Laravel Telescope migrations are not running. 
Telescope installed successfully. After `php artisan` the commands shows on the list. Also `php artisan telescope:clear` can be run, but the missing table in database Exception is thrown: 
```
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db.telescope_entries' doesn't exist (SQL: delete from `telescope_entries`).
```

### Steps To Reproduce:
1. Install Laravel 8.38
2. Install Telescope as follows: https://laravel.com/docs/8.x/telescope#installation
3. Try to run `php artisan vendor:publish --tag=telescope-migrations` (Error `Unable to locate publishable resources.`, should shown)

**Comment by driesvints** [comment]
Works fine for me:

![Screenshot 2021-04-22 at 12 05 35](https://user-images.githubusercontent.com/594614/115696626-2a32e380-a363-11eb-93e2-dbf4660e4ce6.jpg)
![Screenshot 2021-04-22 at 12 06 05](https://user-images.githubusercontent.com/594614/115696632-2b641080-a363-11eb-87a2-91b1238ae810.jpg)
