### ISSUE TITLE
ResizeObserver loop limit exceeded

### ISSUE THREAD

**Issue by joshmakar** [laravel/telescope#1053]
- Telescope Version: 4.3.3
- Laravel Version: 8.18.1
- PHP Version: 7.4.10
- Database Driver & Version: MySQL: 8.0.21

### Description:

My Bugsnag is reporting an error occasionally `ResizeObserver loop limit exceeded`. After some research, it appears to be something to do with this `window.requestAnimationFrame`, [see here](https://stackoverflow.com/questions/49384120/resizeobserver-loop-limit-exceeded).

I searched my application and the only reference to `window.requestAnimationFrame` I could find seems to be from Telescope.

![image](https://user-images.githubusercontent.com/9956440/116433326-63fa6300-a817-11eb-8032-a4fd74d18d3f.png)

The error appears to be harmless, but if it is in fact from Telescope, I just wanted to bring it to someone's attention.

### Steps To Reproduce:

Unable to reproduce as it happens randomly.

**Comment by driesvints** [comment]
Thanks. Since this isn't breaking any code I guess there's nothing much to do about it.
