### ISSUE TITLE
Malformed UTF-8 characters, possibly incorrectly encoded

### ISSUE THREAD

**Issue by mrchrisoliver** [laravel/telescope#1054]
- Telescope Version: 4.4
- Laravel Version: 8.12
- PHP Version: 7.4.16
- Database Driver & Version: SQLSRV MSSQL 2017 14.0.3048.4

### Description:
On Telescope pages for Requests, Views, etc keep showing "Scanning...", and the network tab shows "Malformed UTF-8 characters, possibly incorrectly encoded"
This is on my iMac. I have close to similar setup (as I can get) on my Macbook and Telescope runs fine on the same project.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
