### ISSUE TITLE
500 error to load failed Jobs.

### ISSUE THREAD

**Issue by rakishii13** [laravel/telescope#1056]
- Telescope Version: 4.4.9
- Laravel Version: 8.40.0
- PHP Version: 7.4.3
- Database Driver & Version: mysql

### Steps To Reproduce:

1. Update Horizon to v5.7.6 
2. Stay on the above version of Telescope.
3. Trigger a failed job.
4. You can see the failed job load on Horizon but not on Telescope.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by rakishii13** [comment]
It is a big. I gave you the steps to reproduce. Did you try to reproduce?

**Comment by driesvints** [comment]
@rakishii13 this is the only report we've gotten for this. I believe if the issue you reported actually happened we'd get lots more reports since it's widely used. Please try a support channel first.

**Comment by rakishii13** [comment]
Okay, I will take a look, Considering that that Horizon version came out only few days ago, maybe it will take some time for the issues to appear.
