### ISSUE TITLE
Cannot run Telescope commands outside console

### ISSUE THREAD

**Issue by arxeiss** [laravel/telescope#1057]
- Telescope Version: 4.4.9
- Laravel Version: 8.40.0
- PHP Version: 7.4.x

### Description:
This is related to changes in #1048 . Currently, you cannot run Telescope commands from code, if the code is not executed from console. I have created some helpers which I can execute from the admin interface. But it is failing because commands are not registered then.

### Steps To Reproduce:
Put this code into routes/web.php or some controller `Artisan::call('telescope:prune', ['--hours' => 24]);` and it will fail.

**Comment by driesvints** [comment]
I think in your case it's better to resolve `Laravel\Telescope\Contracts\PrunableRepository` and call the `->prune` method.. These commands are really meant to be run either through the CLI or on the scheduler.

**Comment by LWlook** [comment]
Why is this behavior restricted to only the CLI? 
I updated from 3.5 to the newest Version and it took me nearly 6 hours to find this ticket. I had a scheduler calling `Artisan::call('telescope:prune', ['--hours' => 48]);` and nowhere in the upgrade guide is this breaking change mentioned.

**Comment by LWlook** [comment]
Thank you @arxeiss. I just used the PrunableRepository:

``` php
    public function __invoke(Request $request, PrunableRepository $prunableRepository) {
        $prunableRepository->prune(Carbon::now()->subDays(2));
    }
```

But I'm still wondering why they made a breaking change in a minor release and the only resource you can find is this ticket.
