### ISSUE TITLE
Add support of nonce for inline script

### ISSUE THREAD

**Issue by JonathanGuo** [laravel/telescope#1058]
### Background

We have CSP headers for our project. The headers we enable for the local environment as well to ensure everyone follows the best practice.  However, since we are using a random `nonce` value, the telescope's inline script no longer works :

The script defines the global telescope object in the view:

```php
<!-- Global Telescope Object -->
<script>
    window.Telescope = @json($telescopeScriptVariables);
</script>
```

### Proposal:

Add a method to register a nonce, e.g.

```php
// Pass as a string
Telescope::addNonce(csp_nonce());

// Pass as a callback
Telescope::addNonce(fn () => csp_nonce());
```

Please let me know your thoughts. I am more than happy to submit a PR for it.

**Comment by paras-malhotra** [comment]
I think we would first need to send a PR at the framework level first for a simple way to deal with nonces. Then, all Laravel packages like Horizon, Telescope, etc. can consume the API.

**Comment by JonathanGuo** [comment]
> I think we would first need to send a PR at the framework level first for a simple way to deal with nonces. Then, all Laravel packages like Horizon, Telescope, etc. can consume the API.

That's a good idea. But some packages like `spatie/laravel-csp` already provides a good solution for CSP directives with a global `csp_nonce()` helper function. In this case, we are most likely making a PR just for internal use.

**Comment by driesvints** [comment]
Please propose something with a PR to laravel/framework.

**Comment by JonathanGuo** [comment]
> Please propose something with a PR to laravel/framework.

No worries. Thanks for the advice. I've made a PR https://github.com/laravel/framework/pull/37284. Please let me know if anything needs to change.

**Comment by driesvints** [comment]
Looks like Taylor doesn't wants to add this at this time, sorry.
