### ISSUE TITLE
Support non-PDO connections in QueryWatcher

### ISSUE THREAD

**Issue by cweiske** [laravel/telescope#1059]
In our laravel application we send GraphQL queries to fetch data, and log those queries via `\Illuminate\Database\Events\QueryExecuted` events into Sentry and the Laravel Debugbar.

With Telescope this fails, because our dummy Connection class returns `null` in `getPdo()`.

Laravel debugbar already caters for this use case by checking if the connection actually returns a PDO instance:
https://github.com/barryvdh/laravel-debugbar/blob/master/src/DataCollector/QueryCollector.php#L121

It would be nice if Telescope's QueryWatcher would do the same and not fail on non-pdo connections.

**Comment by driesvints** [comment]
I don't think GraphQL queries belong in the Query watcher. The Query watcher is catered to databases, not API requests.

**Comment by cweiske** [comment]
I disagree. It does not matter if I send my queries via SQL or an REST API. They are still queries.

**Comment by driesvints** [comment]
@cweiske sorry we disagree on that. I don't think that's the same thing.
