### ISSUE TITLE
'Assets not published' exception thrown with default Vapor setup

### ISSUE THREAD

**Issue by bakerkretzmar** [laravel/telescope#1062]
- Telescope Version: 4.4.9
- Laravel Version: 8.41.0
- PHP Version: 8.0.3
- Database Driver & Version: n/a

### Description:

By default with a fresh Laravel app running on Vapor, it's not possible to view Telescope at all. The "Telescope assets are not published" exception is always thrown, because it checks `public_path('vendor/telescope/mix-manifest.json')` which doesn't exist on the lambda runner. Telescope **can** load its assets normally from S3/Cloudfront where Vapor uploads them, but it's impossible to get to that point because of the exception being thrown.

It is possible to work around this by adding `php artisan telescope:publish` to Vapor's build hooks and including all of Telescope's assets in the build artifact, but this adds about 1.5MB to the build and is redundant since the assets are _also_ always uploaded to S3/Cloudfront.

### Steps To Reproduce:

New Laravel app, install Telescope, deploy to Vapor, see the "Telescope assets are not published" exception if you try to view Telescope on Vapor.

**Comment by driesvints** [comment]
I don't think this is really a Telescope issue but a Vapor issue. Let's see how your PR goes.
