### ISSUE TITLE
Telescope breaks when attempt quote the bindings from an PDO_ODBC connection

### ISSUE THREAD

**Issue by juanparati** [laravel/telescope#1065]
- Telescope Version: 4.4
- Laravel Version: ^8.0
- PHP Version: 8.0
- Database Driver & Version: PDO_ODBC with unixODBC

### Description:
The following error is raised by Telescope when a query is recorded:

`PDOException with message 'SQLSTATE[IM001]: Driver does not support this function: driver does not support quoting'`

The reason is that telescope uses `$event->connection->getPdo()->quote($binding)` in order to binding the quotes, however according to [PHP documentation](https://www.php.net/manual/en/pdo.quote.php) PDO::quote is not supported by PDO_ODBC.

### Steps To Reproduce:

1. Setup a ODBC source in Laravel (You can install the package a [Laravel ODBC package](https://github.com/yoramdelangen/laravel-pdo-odbc)).
2. Activate Telescope.
3. Run a query against the ODBC connection.

### Notes

A possible solution to this problem it could be verify if PDO driver is different than ODBC, and use an alternative method of quoting the bindings.

It's possible to check the driver using:

```
DB::connection('odbc')
  ->getPdo()
  ->getAttribute(PDO::ATTR_DRIVER_NAME);
```

**Comment by driesvints** [comment]
PDO_ODBC is not supported by Laravel, sorry.

**Comment by driesvints** [comment]
Sorry, I'm mistaken. It is supported: https://laravel.com/docs/8.x/database#mssql-configuration

**Comment by driesvints** [comment]
Can you send in a PR for that?

**Comment by juanparati** [comment]
I will do it.

**Comment by driesvints** [comment]
Thanks! :)
