### ISSUE TITLE
Illegal string offset 'count' under ModelWatcher

### ISSUE THREAD

**Issue by daison12006013** [laravel/telescope#1068]
- Telescope Version: v4.4.3
- Laravel Version: 8.14.0
- PHP Version: v7.4.16
- Database Driver & Version: MySQL Ver 14.14 Distrib 5.7.33-36, for debian-linux-gnu (x86_64) using  7.0

### Description:
I was trying to simulate the telescope thru test cases (ton of test cases functional/unit) with telescope enabled, moreover I am getting this error 

```
[ErrorException] Illegal string offset 'count'

#1  /var/www/xxxxx/app/Services/Telescope/Watchers/ModelWatcher.php:42
#2  /var/www/xxxxx/vendor/laravel/telescope/src/Watchers/ModelWatcher.php:49
#3  /var/www/xxxxx/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:388
#4  /var/www/xxxxx/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:236
#5  /var/www/xxxxx/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasEvents.php:189
#6  /var/www/xxxxx/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:434
#7  /var/www/xxxxx/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:324
#8  Illuminate\Database\Eloquent\Builder->Illuminate\Database\Eloquent\{closure}
#9  /var/www/xxxxx/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:323
#10 /var/www/xxxxx/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php:23
```

I came across debugging the `IncomingEntry.php` and for some reason the property `$content` turns out to be a json!? weird!

![image](https://user-images.githubusercontent.com/4581415/120289223-a53cd180-c2f3-11eb-835f-263474643783.png)

Here's how I dumped above
![image](https://user-images.githubusercontent.com/4581415/120289357-cdc4cb80-c2f3-11eb-8406-0f90238fdc60.png)

### Steps To Reproduce:
it's not a roadblock when using telescope thru manual testing, but it's really noisy in our Sentry / Kibana, reproducing it seems really hard, because the initial state its an array then some of the hydrated entries became json string.

### Work Around:
- We can disable the ModelWatcher's `telescope.ModelWatcher*.hydrations` to be **false** OR
- My work around was to extend the class and modify the config to use this class and I am checking first if the content was string then just json_decode it to be an array.
![image](https://user-images.githubusercontent.com/4581415/120289850-4e83c780-c2f4-11eb-8369-0b770fa36984.png)

**Comment by driesvints** [comment]
What database are you using? Are you using a custom model for Telescope? For some reason the JSON casting didn't work on that record.

**Comment by daison12006013** [comment]
@driesvints, sorry I forgot to put the DB name, it's mysql.

> Are you using a custom model for Telescope

Can you ellaborate? i'm using Eloquent
```
namespace App\Models;

class Profile extends \Illuminate\Database\Eloquent\Model
{
    ...
}
```

> For some reason the JSON casting didn't work on that record.

From which line of code the casting you're referring to?

**Comment by driesvints** [comment]
> Can you ellaborate? i'm using Eloquent

Nvm, forgot you can't customize this in Telescope.

> From which line of code the casting you're referring to?

https://github.com/laravel/telescope/blob/e098dd11a04f2964169939c1825ed632e779d813/src/Storage/EntryModel.php#L33

I'm investigating this.

**Comment by daison12006013** [comment]
Found the solution @driesvints 

```
        // src/Storage/DatabaseEntriesRepository.php Line 143
        $entries->chunk($this->chunkSize)->each(function ($chunked) use ($table) {
            $table->insert($chunked->map(function ($entry) {
                $originalContent = $entry->content;
                $entry->content = json_encode($originalContent);
                $arr = $entry->toArray();
                $entry->content = $originalContent;

                return $arr;
            })->toArray());
        });
```

We can't directly modify the collection it's like a pointer, I guess we should retain the original content as an array.

**Comment by daison12006013** [comment]
It seems hard to replicate for started project,

I will close this for now and will check see more time to time.

**Comment by markjaquith** [comment]
I've also experienced this, but only when running on Laravel Vapor.

I'm using RDS MySQL 8.0 there.

When running locally on Valet, using MySQL 5.7, there are no issues.

I just set `'hydrations' => false` to hide the problem.

**Comment by driesvints** [comment]
Hi all. I tried to dig into this and think I found a reason why this happens specifically on Vapor. I've written a lengthy explanation on a PR I sent in. I'd appreciate it if anyone could try that out on their app: https://github.com/laravel/telescope/pull/1174

**Comment by markjaquith** [comment]
Testing that out now. For anyone else who wants to test it out:

`composer require cweagans/composer-patches`

**composer.json**

```json
        "patches": {
            "laravel/telescope": {
                "GitHub #1174": "https://github.com/laravel/telescope/commit/391c8b40fcd69a26bfbcae6e12b313ff10ad92c5.diff"
            }
        }
```

And then make sure you haven't disabled hydrations:

**config/telescope.php**

```
		Watchers\ModelWatcher::class => [
			'enabled' => env('TELESCOPE_MODEL_WATCHER', true),
			'events' => ['eloquent.*'],
			// Make sure this next line does not exist or is commented out:
			// 'hydrations' => false,
		],
```
