### ISSUE TITLE
error showing the date of the occurrence

### ISSUE THREAD

**Issue by jltrevizon** [laravel/telescope#1069]
- Telescope Version:  "4.4"
- Laravel Version: "8.44.0"
- PHP Version: 7.3.20
- Database Driver & Version: ms-sql (MS SQL Server)

### Description:
error showing the date of the occurrence

### Steps To Reproduce:
update laravel/framework from 7 to 8, install telescope with command: composer require laravel/telescope

![image](https://user-images.githubusercontent.com/22945459/120378005-df09da00-c2eb-11eb-9470-e9cb26b4ce34.png)

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by jltrevizon** [comment]
the error comes from the migration in the field "created_at" of type dateTime that in sql server according to the format could be dd-mm-yyyy or mm-dd-yyyy this is due to the default format of sql server, in the telescope configuration It should have an option to indicate the date format to record in the database.

**Comment by jltrevizon** [comment]
Another option is to change the database driver from telescope to mysql and separate it from the application database.
