### ISSUE TITLE
json data type in 'telescope_entries' make issues in mysql version 4.7.7

### ISSUE THREAD

**Issue by AmitM13** [laravel/telescope#107]
Hi, I have installed telescope and when run migrate it gives error for data type json in content field of telescope_entries table. later i changed it to text type. yah then it worked fine.
![screen shot 2018-10-24 at 12 53 17 pm](https://user-images.githubusercontent.com/22081666/47413421-de038a00-d78b-11e8-8809-859ce84b54c8.png)

**Comment by johanvanhelden** [comment]
This is already changed, just not released yet.

https://github.com/laravel/telescope/commit/5a0bdce6bb2c0abf73dafad6896cfdbf809e38d4#diff-d0338a552593100720ef3020499718cd
