### ISSUE TITLE
$assetsAreCurrent is undefined

### ISSUE THREAD

**Issue by appml** [laravel/telescope#1070]
- Telescope Version: 4.4.10
- Laravel Version: 8.44.0
- PHP Version: 7.4.3
- Database Driver & Version: mysql  Ver 15.1 Distrib 10.4.14-MariaDB

### Description:

Getting the error: 

`$assetsAreCurrent is undefined`

The function is now gone from `Telescope.php`, which probably is the culprit.

### Steps To Reproduce:

Just need to load `telescope/layout.blade.php` in browser.

**Comment by az-iar** [comment]
@appml Had the same issue. Fixed this by running `php artisan view:clear`.

**Comment by driesvints** [comment]
Run the above.
