### ISSUE TITLE
Deadlock detected for telescope 

### ISSUE THREAD

**Issue by Algeneralo** [laravel/telescope#1075]
- Telescope Version: 4.0
- Laravel Version: 8.31
- PHP Version: 7.4.10
- Database Driver & Version: postgresql

### Description:
As you can see here in [flare](https://flareapp.io/share/v5pzyD6P#F27), I faced this issue many times, and have no idea what is that

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by Algeneralo** [comment]
@driesvints  Isn't a bug with telescope itself?
