### ISSUE TITLE
Telescope does not record in production environment

### ISSUE THREAD

**Issue by myckhel** [laravel/telescope#1076]
- Telescope Version: v4.4.10
- Laravel Version: v8.46.0

### Description:
Upon enabling telescope in production environment still it does not record requests or any other watches.

![Screenshot 2021-06-11 at 15 42 03](https://user-images.githubusercontent.com/34090541/121704728-ebe8b380-cacb-11eb-859c-be9d6923332d.png)

### Steps To Reproduce:
- switch environment to production
- watch telescope recording from dashboard

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by myckhel** [comment]
Keep discouraging people on reporting issues.

I never had the courage to report the issue at first because i know what the response would be, i just decided to try my luck.

You think i will just waste my time to create an unnecessary issue?

You just close issues without checking if the problems exists.

Atleast leave it opened and let the community contribute to the issue rather than closing it without any means of solution. 

I would tell you to stop causing hatred to this beautiful framework.

**Comment by ducvu91** [comment]
Hello,
i have same Issue.
My telescope not work on the production environment, not need view but at leat it must insert record to DB. Not thing.
Please help me how to enable insert record in production environment.

**Comment by myckhel** [comment]
if you published the telescope service provider


> Hello,
> i have same Issue.
> My telescope not work on the production environment, not need view but at leat it must insert record to database. it does nothing.
> Please help me how to enable insert record in production environment.

if you published the telescope service provider

Goto: `app/Providers/TelescopeServiceProvider.php`
at `register` method

```php
public function register()
    {
        // Telescope::night();

        $this->hideSensitiveRequestDetails();

        Telescope::filter(function (IncomingEntry $entry) {
            if ($this->app->environment('local')) {
                return true;
            }
            // temporarily return true if you want recording in production env
            return true;

            return $entry->isReportableException() ||
                   $entry->isFailedRequest() ||
                   $entry->isFailedJob() ||
                   $entry->isScheduledTask() ||
                   $entry->hasMonitoredTag();
        });
    }
```

**Comment by Riaz-Mahmud** [comment]
Add this line on TelescopeServiceProvider -> register()

`$isLocal = $this->app->environment('local') || $this->app->environment('production');`
