### ISSUE TITLE
Client Request Watcher fails when there's a file upload

### ISSUE THREAD

**Issue by rcerljenko** [laravel/telescope#1079]
- Telescope Version: 4.5.0
- Laravel Version: 8.47.0
- PHP Version: 7.4.20
- Database Driver & Version: MySQL 8.0.21

### Description:

Error happens in Watchers/ClientRequestWatcher.php on line 162 with message `strlen() expects parameter 1 to be string, resource given`. It happens when there's a file upload attached to the request.

**Comment by driesvints** [comment]
Ping @gdebrauwer
