### ISSUE TITLE
loop/crash when using tag with sanctum 

### ISSUE THREAD

**Issue by ivanomatteo** [laravel/telescope#1083]
- Telescope Version: 4.5.1
- Laravel Version: 8.49.0
- PHP Version: 7.4.20
- Sanctum: 2.11.2
- Database Driver & Version:  MySql 5.7

### Description:

when using Sanctum middleware EnsureFrontendRequestsAreStateful,
the current user is authenticated with web guard,
and an ajax request is performed, triggering the sanctum middleware (EnsureFrontendRequestsAreStateful)

if I try to access to current user inside tag() method:

```
Telescope::tag(function (IncomingEntry $entry) {
            $tags = ['AppMode:'.config('app.mode')];
            $u = Auth::user();  //here it crash
            //........
            return $tags;
        });
```

the request will be stuck, and will fail by timeout.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and I'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
