### ISSUE TITLE
Http client watcher didnt capture anything

### ISSUE THREAD

**Issue by nogamenofun98** [laravel/telescope#1084]
- Telescope Version: 4.5.1
- Laravel Version:  8.32.1
- PHP Version: 7.4.9
- Database Driver & Version: 8.0.21

### Description:
Http client request didn't record any http client api call. 
![image](https://user-images.githubusercontent.com/9070825/124455466-3522df00-ddbc-11eb-8e33-f5b4fd985621.png)

With the Http client ( i calling with Illuminate\Support\Facades\Http)  get call like this: 
![image](https://user-images.githubusercontent.com/9070825/124455545-49ff7280-ddbc-11eb-8be3-e65793297315.png)

I tried with simple www.google.com, but it also doesn't get record

**Comment by driesvints** [comment]
Works fine for me:

```php
Route::get('/test', function () {
    Http::get('https://google.com');

    return 'ok';
});
```

![Screen Shot 2021-07-05 at 12 22 46](https://user-images.githubusercontent.com/594614/124457110-bf068400-dd8b-11eb-8d69-0150d4946dfd.jpg)

Please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks.

**Comment by nogamenofun98** [comment]
![image](https://user-images.githubusercontent.com/9070825/124459922-4cb09680-ddc1-11eb-9e1b-936beb3801b3.png)
![image](https://user-images.githubusercontent.com/9070825/124459932-51754a80-ddc1-11eb-979d-8f1b332e3069.png)
![image](https://user-images.githubusercontent.com/9070825/124459955-576b2b80-ddc1-11eb-9d5b-f1de6139efc8.png)


It doesn't save, dont have any exception log also

**Comment by nogamenofun98** [comment]
ok i found the issue, the event `ResponseReceived` is added after 8.32.1, so my laravel version dont have the event class yet, just it doesnt throw any error. Anyways, I type here so anyone saw this can know also.
