### ISSUE TITLE
Telescope issue with JWT Auth

### ISSUE THREAD

**Issue by ScriptMint** [laravel/telescope#109]
Laravel: 5.7.10
PHP Version: 7.2.*
tymondesigns/jwt-auth: 0.5.12 and 1.0.0-rc.3

Not able to generate JWT Token, no issue in Laravel log & still throwing 500 error.

Tried removing telescope & everything works fine. This is very strange.

**Comment by themsaid** [comment]
You'll need to debug it more, what's the stack trace of the exception? This issue is not clear.

**Comment by vesper8** [comment]
I'm using JWT with the API laravel app I just installed Telescope on.. didn't cause any issues.. I don't understand how telescope could have interfered with JWT at all.. or do you mean that you are trying to access the telescope route after authenticating via JWT?

**Comment by themsaid** [comment]
please open a new issue if you happen to find a problem with Telescope.

**Comment by pietros23** [comment]
> Hello guys!
> 
> I faced a similar issue and the reason was the `bcmath` extension that the `telescope` needed.
> Hope it helps!

I solved installing `bcmath` extension as @pespantelis said.

**Comment by shadywallas** [comment]
@ScriptMint 
i debugged it and fixed with this 
`TELESCOPE_EXCEPTION_WATCHER=false` in my env file
try and let me know so we can fill a proper bug in telescope if it's the same for you

**Comment by ScriptMint** [comment]
Yes, it works but does it mean that telescope will no longer watch for exceptions?
