### ISSUE TITLE
get_class() expects parameter 1 to be object, string given in NotificationWatcher.php

### ISSUE THREAD

**Issue by ilyavaiser** [laravel/telescope#1094]
- Telescope Version: 4.5.1
- Laravel Version: 8.49.2
- PHP Version: 7.4

### Description:

  "error": "get_class() expects parameter 1 to be object, string given",
  "record": null,
  "status": 500,
  "exception": "ErrorException",
  "file": "/app/vendor/laravel/telescope/src/Watchers/NotificationWatcher.php",
  "line": 79,

### Steps To Reproduce:

'''
$notification = new AuthTokenNotification($token->getToken());
Notification::send($identity->id(), $notification);
'''

@method static void send(\Illuminate\Support\Collection|array|mixed $notifiables, $notification)

$notifiables is easily converted to string inside Laravel, you need to consider this case

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
