### ISSUE TITLE
Queue::failing $event empty when running Telescope

### ISSUE THREAD

**Issue by avido** [laravel/telescope#1098]
- Telescope Version: 4.5.1
- Laravel Version: 8.49.0
- PHP Version: 8.0.7
- Database Driver & Version: MySql 8.0.22

### Description:
If Telescope service is registered 
```php
            $this->app->register(\Laravel\Telescope\TelescopeServiceProvider::class);
            $this->app->register(TelescopeServiceProvider::class);
```

the `JobFailed $event` is empty when using Queue failing facade. 
```php
Queue::failing(function (JobFailed $event) {
});
```
### Steps To Reproduce:
- fresh laravel app
- install telescope
- setup a fake job which fails immediately 
- register telescope in `AppServiceProvider` 
- register Queue failing facade in `AppServiceProvider`
- Dispatch job

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by avido** [comment]
not unwilling to do so.. but how can this as described above in a fresh app be different then a bug?
