### ISSUE TITLE
Loading more jobs throw an error 

### ISSUE THREAD

**Issue by alihassan-ib** [laravel/telescope#1102]
- Telescope Version: 3.5.1
- Laravel Version: 7.30.0
- PHP Version: 7.4.11
- Database Driver & Version:
MySQL 

### Description:
I face problem while loading more jobs after 4 or 5 pages console throw error : 
Uncaught TypeError: Cannot read property 'content' of undefined

this error is in app.js updateEntries functions while checking for status

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
