### ISSUE TITLE
Loading more jobs throw an error 

### ISSUE THREAD

**Issue by alihassan-ib** [laravel/telescope#1108]
- Telescope Version: 4.6.0
- Laravel Version: 8.52.0
- PHP Version: 8
- Database Driver & Version:
MySQL

### Description:

I face problem while loading more jobs after 4 or 5 pages console throw error :
Uncaught TypeError: Cannot read property 'content' of undefined

this error is in app.js updateEntries functions while checking if job status is pending

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
