### ISSUE TITLE
configuration to ignore gate in blade directives.

### ISSUE THREAD

**Issue by AMoktar** [laravel/telescope#1109]
Hello guys, I hope you having a nice day.

first of all Telescope is an awesome package , makes our life easy .

I'm suggesting to offer a config key for ignoring gate watcher in blade directives like @can , @cannot 
```
Watchers\GateWatcher::class => [
            'enabled' => env('TELESCOPE_GATE_WATCHER', true),
            'ignore_abilities' => [],
            'ignore_packages' => true,
        ],
```

```
Watchers\GateWatcher::class => [
            'enabled' => env('TELESCOPE_GATE_WATCHER', true),
            'ignore_abilities' => [],
            'ignore_packages' => true,
+           'ignore_blade' =>true,
        ],
```

this will be better when logging my telescope gate logs , won't be bluted and clear .

I hope that make sense and helpfull .

Thanks a lot

**Comment by driesvints** [comment]
No plans for this sorry
