### ISSUE TITLE
[Suggestion] Option to prevent monitored tags from being pruned?

### ISSUE THREAD

**Issue by jackcruden** [laravel/telescope#111]
I'm trying to keep an eye on which queries are being tagged `slow` but because my app is processing a lot of requests my monitored tags rapidly get pruned.

Would it benefit others as well to have a switch next to each monitored tag to disabled pruning of those tagged entries?

I believe this would also be useful to tag a specific user, switch the tag to 'prevent pruning', then have them perform a specific action.

**Comment by paras-malhotra** [comment]
I've added pull request #256 to address this

**Comment by themsaid** [comment]
we've removed pruning from Telescope, people are free to manage trimming the records in any way they see.

**Comment by deleugpn** [comment]
@themsaid that's really sad as Pruning was the best feature in Telescope. From a GDPR standpoint, I loved the fact that I didn't have to worry about storing personal data for too long.
I understand people wanting a more complex pruning feature, but the simple one is perfect for GDPR.
Do you have any plans on providing an easy way to prune records again?

**Comment by paras-malhotra** [comment]
@deleugpn I'll create a small package to add pruning. I understand the thought process - I think there were too many ways to think about what logic to apply for pruning. So best left for a third party package I guess. I'll post the link on this thread once I create it.

**Comment by themsaid** [comment]
@deleugpn everyone wanted it in a different way, and when this is the case it's best to leave it for people to decide what to do without enforcing one way.

**Comment by deleugpn** [comment]
This is good enough for me: https://github.com/laravel/telescope/pull/268#issuecomment-434362849

Thank you for that feedback.

**Comment by themsaid** [comment]
@paras-malhotra just notice that if you prune you must make sure you don't prune part of the related entries and leave the rest, so for example if a monitored tag is on the request entry, but that entry has related queries, notifications, mails, etc... if you keep only the request and prune the rest of the related entries the kept entry might not be useful at all.

That's one thing to keep in mind.

**Comment by paras-malhotra** [comment]
Oh I see, I didn't think about that. That makes a lot of sense, thanks for your help @themsaid! I'll make sure I keep that in mind based on `batch_id`!

**Comment by paras-malhotra** [comment]
I've created a package for intelligent pruning: https://github.com/insenseanalytics/laravel-telescope-pruning

This takes care of pruning limits, whitelisting of monitored and/or specific tags and also separate limits for whitelisted tags. All pruning is done in batches so that the relevant entries are kept as per @themsaid's [suggestion](https://github.com/laravel/telescope/issues/111#issuecomment-434366577). Suggestions/comments would be most appreciated!
