### ISSUE TITLE
Wrong Jobs status when using Laravel Horizon

### ISSUE THREAD

**Issue by ilyavaiser** [laravel/telescope#1111]
- Telescope Version: v4.6.1
- Laravel Version: v8.48.2
- PHP Version: 7.4.22
- Database Driver & Version: 

### Description:

Telescope shows pending status for jobs when using Horizon, even if the task is successful.

I am using Queued Laravel Notifications and they work great. The Horizon Dashboard displays the jobs information correctly. Notifications are sent to users. Everything is fine, but when I look at the list of jobs in Telescope, they are all displayed in the pending status.

I looked in Redis, there are no these jobs in pending status, the queue is empty.

### Steps To Reproduce:

Create any Queues Notification Job and process it through Horizon

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
