### ISSUE TITLE
Assets are broken (Telescope not found and Google Content Security Policy directive)

### ISSUE THREAD

**Issue by einnar82** [laravel/telescope#1112]
- Telescope Version: 3.5.1
- Laravel Version: ^6.2
- PHP Version: 7.2
- Database Driver & Version: MySQL 

### Description:
The whole Laravel Telescope dashboard was broken. I tried to update the Telescope from v2.1.7 to v3.5.1 and republished the assets.

![image](https://user-images.githubusercontent.com/23412411/129165414-1d8d2b64-586d-4624-9cdc-309b27c81857.png)

![image](https://user-images.githubusercontent.com/23412411/129165487-d9f69654-1612-4c83-b7c3-56b1a21464d2.png)

Please see the errors below.

![image](https://user-images.githubusercontent.com/23412411/129165609-c9dac988-0c04-4546-9584-9aeea8fbe694.png)

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
