### ISSUE TITLE
Getting a "This watcher is turned off" message when extending a default watcher

### ISSUE THREAD

**Issue by JakeBooher** [laravel/telescope#1117]
- Telescope Version: 4.6.2
- Laravel Version: 8.53.1
- PHP Version: 8.0.9
- Database Driver & Version: MySQL 8.0

### Description:

If you extend a default watcher (In this case `RequestWatcher`) to change its behavior (In my case specifically I needed to sanitize GraphQL queries/mutations in addition to normal JSON requests as these weren't handled by the default watcher) you get a "This watcher is turned off" message at the top of the page, even though the data is still being recorded. Guessing this is happening because it's comparing the full class name rather than checking with `instanceof`

<img width="950" alt="Screen Shot 2021-08-20 at 2 40 29 PM" src="https://user-images.githubusercontent.com/179180/130285540-3b349cf7-c378-4473-bb37-b1c3c566acfc.png">

**Comment by driesvints** [comment]
Appreciating a PR for this, thanks.
