### ISSUE TITLE
Error on rename running migrations

### ISSUE THREAD

**Issue by xtfer** [laravel/telescope#1120]
- Telescope Version: 4.6.2
- Laravel Version: 8.56.0
- PHP Version: 8.0.9
- Database Driver & Version: mysql 10.6.4 MariaDB

### Description:

When installing Telescope I get the following error during `php artisan migrate`...

```
  SQLSTATE[HY000]: General error: 1025 Error on rename of './xxx/telescope_entries_tags' to './xxx/#sql-backup-3a5-d3' (errno: 168 "Unknown (generic) error from engine") (SQL: alter table `telescope_entries_tags` add constraint `telescope_entries_tags_entry_uuid_foreign` foreign key (`entry_uuid`) references `telescope_entries` (`uuid`) on delete cascade)
  ```

### Steps To Reproduce:

Following the steps on the Local Install https://laravel.com/docs/8.x/telescope#local-only-installation

**Comment by xtfer** [comment]
@driesvints It's your migration thats failing. Fine if you think thats a support problem, but to me it looks like a bug.

**Comment by driesvints** [comment]
It works just fine for me.
