### ISSUE TITLE
telescope_entries table queries are shown in Query Watcher

### ISSUE THREAD

**Issue by ismaail** [laravel/telescope#1126]
- Telescope Version: v4.6.3
- Laravel Version:  v8.61.0
- PHP Version: 8.0.10
- Database Driver & Version: MySQL 8

### Description:
`telescope_entries` table queries are shown in Query Watcher.

https://user-images.githubusercontent.com/4411670/133323960-38047e8f-2556-42af-9e59-f4a8fa4df2ad.mp4

### Steps To Reproduce:
1. Upgrade Laravel Telescope to version 4.6.3
2. Have `TELESCOPE_DOMAIN` in the `.env` file with empty value or remove it.

**Comment by RTippin** [comment]
I can confirm having this behavior as well after updating to `v4.6.3`. Even my request watcher was showing all telescope `POST` to the internal `telescope-api`.

**Comment by metalogico** [comment]
Yes, same problem for me. I just left a comment on the commit which is likely to cause the issue.

**Comment by SaaberDev** [comment]
facing same issue .... 😫😫

**Comment by ismaail** [comment]
@SaaberDev workaround: add `TELESCOPE_DOMAIN` to `.env` with the app domain as its value.

**Comment by SaaberDev** [comment]
@ismaail 

![image](https://user-images.githubusercontent.com/60372951/133658127-29c0a4d2-2edc-48ea-86b7-0d826db72cd0.png)


Not working ....

**Comment by ismaail** [comment]
@SaaberDev try without `https://`

**Comment by SaaberDev** [comment]
@taylorotwell .... Thanks boss .. Got the new update just now and fixed ❤❤
