### ISSUE TITLE
Add channel to logs interface

### ISSUE THREAD

**Issue by samuelecarpene** [laravel/telescope#1129]
I think it can be helpful to add the information about the channel of provenience of a log. In my projects i use multiple channels for specific tasks ( 1 log file for an artisan task, 1 log for describing a frontend process that can be erroneusly, etc.). At the moment the channel is not stored in database so it must be added when writing to table "telescope_entries". I would like to make a pull request but I don't know vue. Thank you in advance.

**Comment by driesvints** [comment]
Atm we don't have plans to work on this ourselves, sorry.
