### ISSUE TITLE
Undefinded Moontoast\Math\bcadd()

### ISSUE THREAD

**Issue by richard457** [laravel/telescope#113]
this method: `* Sets the value of this BigNumber to a new value
     *
     * @param mixed $number May be of any type that can be cast to a string
     *                      representation of a base 10 number
     * @return BigNumber for fluent interface
     */
    public function setValue($number)
    {
        // Set the scale for the number to the scale value passed in
        $number = bcadd(
            $this->filterNumber($number),
            '0',
            $this->getScale()
        );
 
        $this->numberValue = $number;
 
        return $this;
    }` is returning `"Call to undefined function Moontoast\Math\bcadd()"`

**Comment by themsaid** [comment]
https://github.com/laravel/telescope/issues/25
