### ISSUE TITLE
Client Request Watcher to hide parameters before checking if content is within limits

### ISSUE THREAD

**Issue by gthedev** [laravel/telescope#1130]
Currently, for JSON responses, the `ClientRequestWatcher` will check if the response content size is within accepted limits and purge it completely if not. If it is within limits, it will hide some parameters before recording it.

I would propose this to be done the other way round, so that the parameters are first hidden and then the limit is checked. Main reason for that would be to allow hiding some large field(s) to still record the rest of the response rather than purging the whole response because of potentially one or a few large attributes.

**Comment by driesvints** [comment]
We don't have any plans for this atm, sorry.
