### ISSUE TITLE
Schedule Watcher seem not working when use with Laravel Octane/PHP 8.0.10

### ISSUE THREAD

**Issue by nogamenofun98** [laravel/telescope#1132]
- Telescope Version: 4.6.4
- Laravel Version: 8.61.0
- Laravel Octane Version: v1.0.11
- PHP Version: 8.0.10
- Database Driver & Version: 

### Description:
I got a scheduler cronjob to run on every minutes, and it is working in php7.4.
When I switch to PHP 8.0.10 and run on octane, seem like telescope doesnt record the scheduler record, the first one with "/usr/bin/php8.0" is I run from "php artisan schedule:run" and select the item to run, other than that, no record is found. I'm not sure is bug or not.
![image](https://user-images.githubusercontent.com/9070825/135194985-329c31e2-2a01-4823-ba88-fc9ea24d396a.png)

The syslog does show the cron has run successfully every minutes.
![image](https://user-images.githubusercontent.com/9070825/135195469-41c2d7a9-402e-48d4-bd2a-c2e8e9a2dcee.png)

### Steps To Reproduce:
1) Run laravel on PHP 8.0.10, Telescope with Octane.
2) Run on any schedule task on cronjob

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
