### ISSUE TITLE
Information about duplicate SQL queries

### ISSUE THREAD

**Issue by tabuna** [laravel/telescope#1148]
- Telescope Version: 4.6.7
- Laravel Version: 8.72.0
- PHP Version: 8.0.12
- Database Driver & Version: MySQL 8.0

### Description:

When debugging in the UI, I see a hint that I have duplicate queries:

![image](https://user-images.githubusercontent.com/5102591/142283768-b82cac02-597f-4afc-b9f1-d2b8ccb056ee.png)

But this information is not valid, which has a negative impact since developers can spend time looking for a mirage. This is because the calculated hash sum does not take into account the parameters. That is:

```php
User::find(1);
// and
User::find(2);
```

It will be counted as duplication. Because it will take a string without taking into account the parameters:

```sql
select * from `users` where `users`.`id` = ? limit 1
```

The piece of code responsible for this:

https://github.com/laravel/telescope/blob/505623831a5b35454491add4a4a2fd0af34d21b9/src/Watchers/QueryWatcher.php#L63-L73

### Steps To Reproduce:

Create 2 queries with different parameters as in the example above. 
Then open the UI and you will see the duplicate warning.

### Describe the solution you'd like

We could add to the string that calculates the hash sum and all the parameters that were passed in the request. For example:
```php
public function familyHash($event)
{
    return md5($event->connectionName.$event->sql.implode($event->bindings));
}
```

### Additional context

I may be misunderstanding this information about duplication. And I think that only completely identical SQL queries to the same connection should be displayed.

If my reasoning is incorrect, then perhaps it is worthwhile to write down the note in the UI in more detail to avoid misunderstandings.

**Comment by barryvdh** [comment]
This is usually because of eager loading, you have the same queries bit for different IDs. So not exactly the same, bit with different bindings.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by driesvints** [comment]
Thanks @barryvdh
