### ISSUE TITLE
Telescope should be publicly available **ONLY** on local env

### ISSUE THREAD

**Issue by mshamaseen** [laravel/telescope#1151]
- Telescope Version: ^4.6
- Laravel Version: ^8.0
- PHP Version: 8.0
- Database Driver & Version:

### Description:

In the [document](https://laravel.com/docs/8.x/telescope#dashboard-authorization):

> You should ensure you change your APP_ENV environment variable to production in your production environment. Otherwise, your Telescope installation will be publicly available.

There are 2 concenrs here:

1- I think this is NOT the case, we have a development server with env equal `development` and telescope is not publicly available.
2- Telescope should be publicly available **ONLY** on local env, not on every non production env.

**Comment by driesvints** [comment]
`development` isn't `production` so telescope is publicly available. You can also configure authorisation more granularly through https://laravel.com/docs/8.x/telescope#dashboard-authorization
