### ISSUE TITLE
Telescope issue on PHP8.1 after first refresh (forge)

### ISSUE THREAD

**Issue by binaryk** [laravel/telescope#1152]
- Telescope Version: v4.6.7
- Laravel Version: v8.73.2
- PHP Version: 8.1.0
- Database Driver & Version: 8.0.2 

### Description:

As soon I deploy the app on forge (using forge default deployment script) the app loads once, but after the second page refresh it shows the following error:

![CleanShot 2021-11-29 at 18 18 02@2x](https://user-images.githubusercontent.com/6833714/143904376-0deb6e3c-cfc4-429f-93d6-970affd4923c.png)

I removed the `facade/ignition` as it tried to instantiate the `LogManager` and showed `500` instead (see [this](https://github.com/facade/ignition/issues/430)). 

I had a similar issue locally, but after opening the autoload and app.php file manually (see [this](https://github.com/facade/ignition/issues/430)) it worked locally (weird, I know!)

### Steps To Reproduce:

Deploy a fresh app (with telescope, debugbar, ignition) on forge using PHP8.1 and (!important) a domain with SSL alias to the server. Refresh it once, then refresh few more times. 

IE app: https://github.com/binaryk/laravel8

**Comment by driesvints** [comment]
Hi @binaryk, can you please contact Forge support about this?

**Comment by themsaid** [comment]
I don't see how this is related to Forge @driesvints ?

**Comment by driesvints** [comment]
@binaryk seems this is related to your app specifically. Please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

**Comment by binaryk** [comment]
It might be, I'll deploy a fresh app on forge using a subdomain to ensure that. Thank you!

**Comment by binaryk** [comment]
@themsaid 

The thing is that after deleting `telescope` the app works properly, it's on nova btw: 
![CleanShot 2021-11-30 at 13 21 32@2x](https://user-images.githubusercontent.com/6833714/144038571-0b672142-f4b2-4651-b372-18ee63aec374.png)

**Comment by binaryk** [comment]
I found the issue! 💯 

Basically, [Restify](https://restify.binarcode.com/) emits an event from the `boot` method of his service provider
[provider](https://github.com/BinarCode/laravel-restify/blob/6.x/src/RestifyApplicationServiceProvider.php#L24) -> [event](https://github.com/BinarCode/laravel-restify/blob/6.x/src/Restify.php#L101). 

Then, `Telescope` is trying to register this event in logs, but it's not yet fully booted. 

I had a similar issue before, could it be a good idea to inform people on the documentation that they should not emit events in provider's `boot` methods?

Thank you!
