### ISSUE TITLE
Cannot access offset of type string on string - when calling Model::pluck('id', 'string column');

### ISSUE THREAD

**Issue by bretto36** [laravel/telescope#1162]
- Telescope Version: #4.6.9
- Laravel Version: 8.65
- PHP Version: 8.1
- Database Driver & Version: mysql 5.7

### Description:

When having telescope enabled i am getting an error `Cannot access offset of type string on string` when calling Model::pluck() with the second parameter as a string column. 

78         if (! isset($this->hydrationEntries[$modelClass])) {
79             $this->hydrationEntries[$modelClass] = IncomingEntry::make([
80                 'action' => 'retrieved',
81                 'model' => $modelClass,
82                 'count' => 1,
83             ])->tags([$modelClass]);
84 
85             Telescope::recordModelEvent($this->hydrationEntries[$modelClass]);
86         } else {
87             **$this->hydrationEntries[$modelClass]->content['count']++;**
88         }
89     }

Turning off the Model watcher stops the error and my code completes correctly.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
