### ISSUE TITLE
Serialization of 'Closure' is not allowed issue when trying to send queued notifications

### ISSUE THREAD

**Issue by 4unkur** [laravel/telescope#1163]
- Telescope Version: 4.6.9
- Laravel Version: 8.76.2
- PHP Version: 7.4.25
- Database Driver & Version: MySQL 8.0.27

### Description:

I have a queued notification which throws an error `Serialization of 'Closure' is not allowed`
The error occurs only when telescope is enabled (I use `TELESCOPE_ENABLED` .env variable)
The notification code: https://paste.laravel.io/917583d1-df98-4355-957a-4ab3ee453bc8
Queue Driver is Redis. Also, I use Horizon if this somehow might affect.
There is a collect()->each(fn part which I also tried to rewrite using foreach loop but the error still occurred. 
I'm not sure if this is just specific case but I was able to solve the issue only by disabling Telescope

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
