### ISSUE TITLE
When viewing logs in a request, the display order should be first message first to display (ascending) for debugging

### ISSUE THREAD

**Issue by ajcastro** [laravel/telescope#1167]
For a specific request, I think the normal viewing of logs is the first logs first, ascending time manner, just like how we view logs in `laravel.log` file for debugging purpose. 

Currently it is displayed in reverse which is not good when debugging. 

![image](https://user-images.githubusercontent.com/4918318/148403845-fd4516fe-65a6-44de-8335-633a0d6377b4.png)

Consider this log for debugging:
```
logger('first');
logger('second');
```
Then it will be displayed reversed, it makes tracking a bit more awkward.
Thanks! 😇

**Comment by driesvints** [comment]
I see what you mean but this will make this view different from all the others. I believe there's a difference between a Telescope view and a log file. I don't think we'll be changing this right now sorry.

**Comment by ajcastro** [comment]
No worries @driesvints . But can you give me a hint on what file in the source code  I need to look or change so I can customize it in my fork?

**Comment by driesvints** [comment]
Guess it's either https://github.com/laravel/telescope/blob/4.x/resources/js/screens/logs/index.vue or the query that provides the results.
