### ISSUE TITLE
Not recording while DB is in a transaction

### ISSUE THREAD

**Issue by ZacharyDuBois** [laravel/telescope#1168]
- Telescope Version: 4.6.10
- Laravel Version: 8.6.10
- PHP Version: 8.1.1
- Database Driver & Version: Tested with SQLite and PostgreSQL.

### Description:
When code is executing within `DB::beginTransaction()`, nothing gets logged if the request errors out. 

### Steps To Reproduce:

Create a vanilla Laravel project with a SQLite DB (or your choice of DB), install Telescope, and add and load the following route.
```php
Route::get('/', function () {
    DB::beginTransaction();
    // Do some work...
    throw new Exception('Oops! Something with my work went wrong!');
    DB::commit();
});
```

Telescope will not have recorded the request at all.

A solution to this would possibly allow for telescope to use a different DB connection or make a dedicated DB connection for Telescope. Another possible solution would be to detect if the current DB is in a transactional state and hold entries until the transaction either commits or fails.

**Comment by driesvints** [comment]
This indeed isn't supported, sorry.

**Comment by ZacharyDuBois** [comment]
@driesvints would this not be a bug vs just something that you wouldn't want to support since it occurs with a common DB practice?

Side note for those with the same issue:
So I was able to resolve it by duplicating the primary DB connection and explicitly telling Telescope to use it. I feel there would be a more elegant solution though.

**Comment by driesvints** [comment]
I don't think we'll be working on this soon sorry.

**Comment by LWlook** [comment]
@driesvints Is there a possibility, that this issue is at least mentioned in the Laravel documentation? It took me an hour to find this ticket and the helpful comment from @ZacharyDuBois.

**Comment by ZacharyDuBois** [comment]
@LWlook yeah - I pretty much copied the primary database config, renamed it to telescope and then set the telescope environment parameters to that database. 

This is less than ideal as it will start two DB connections (putting pretty much double the connection load on your DB). I would not recommend it for anything passed a small production app (which is 99% of everything anyways).

**Comment by driesvints** [comment]
We'd welcome PR's to the docs.

**Comment by ZacharyDuBois** [comment]
I will see what I can do this week. I've been a bit busy. I keep making comments that I will do a PR but it never comes to light as I get sidetracked easily. 

I set a reminder this time!

**Comment by Brynn18** [comment]
Any update on this issue? Thankyou

**Comment by rainbowMeh** [comment]
Any update on this issue? 
Thanks

**Comment by Stalinko** [comment]
+1 for this feature

Right now I'm trying to figure out what transactions are being created and unfortunately Telescope doesn't log any transaction commands.
