### ISSUE TITLE
 telescope:prune pure performerce

### ISSUE THREAD

**Issue by tczaude** [laravel/telescope#1169]
- Telescope Version: x.x.x
- Laravel Version: x.x.x
- PHP Version: x.x.x
- Database Driver & Version: mysql

### Description:

When executing the prune command, Telescope charges the base blocking access to the table. For larger data sets, it can even lead to destabilization of the system operation. The problem is the lack of an index after which the "prune" command searches for records to be deleted. In order to solve this problem, we have 2 solutions

1. Simple index addition - ALTER TABLE `telescope_entries` ADD INDEX` telescope_entries_date` (`created_at`);
2. Implementation of the Truncate command with partition rebalance, but it seems to me too big element for quick implementation, so probably as Future

Looking at migrations this is true for all versions 

### Steps To Reproduce:

`php artisian telescope:prune`

generate 

`delete from `telescope_entries` where `created_at` < '2022-01-10 09:28:41' limit 1000 /* COMMAND artisan telescope:prune */` 

explain without index

```
id|select_type|table            |type|possible_keys|key|key_len|ref|rows   |Extra      |
 1|SIMPLE     |telescope_entries|ALL |             |   |       |   |1081549|Using where|
```

after apply index

```
id|select_type|table            |type |possible_keys          |key                    |key_len|ref|rows|Extra      |
 1|SIMPLE     |telescope_entries|range| telescope_entries_date| telescope_entries_date|6      |   |1   |Using where|
```

**Comment by driesvints** [comment]
This table should already have an index: https://github.com/laravel/telescope/blob/4.x/database/migrations/2018_08_08_100000_create_telescope_entries_table.php#L56

Please also fill out the version numbers next time.

**Comment by tczaude** [comment]
ehh ok im blind 
But i have test with telescope in v4.6.1 and laravel Laravel Framework 8.53.1 and i don't have this index. 
I try find  why this index was wanished
