### ISSUE TITLE
Gate filter on user id

### ISSUE THREAD

**Issue by fridzema** [laravel/telescope#117]
I think it is more convenient to check on user id in in the viewTelescope Gate.

Reasons:
User email can easily be changed and breaks access to telescope.
Performance.

**Comment by SimonJ** [comment]
Laravel Spark use Email aswell

**Comment by vesper8** [comment]
Depending on the email is much safer. What if you're testing a feature that lets you delete your user so you can re-register it.. you might do this on your own user in a production environment, then you'd have to change the hardcoded gate

**Comment by themsaid** [comment]
No plans to support this at the moment.
