### ISSUE TITLE
Tried to bind parameter number 2101.  SQL Server supports a maximum of 2100 parameters.

### ISSUE THREAD

**Issue by michele-grifa** [laravel/telescope#1171]
- Telescope Version: 4.7.0
- Laravel Version: 8.80.0
- PHP Version: 8.0
- Database Driver & Version: SQL Server 2017

### Description:
I'm currently using SQL Server 2017 and i tried to install Telescope, but when i execute any query, the log file shows this error:
```
Tried to bind parameter number 2101.  SQL Server supports a maximum of 2100 parameters. (SQL: insert into [telescope_entries] ([batch_id], [content], [created_at], [family_hash], [type], [uuid])
```

To make it works, i also published the migrations and added `precision` 2 to `created_at` column, without this other errors pops out.

### Steps To Reproduce:

- Install Laravel Telescope
- Execute a query
- The log file show the error.

**Comment by driesvints** [comment]
You can indeed work around this by publishing migrations: https://laravel.com/docs/8.x/telescope#migration-customization

**Comment by michele-grifa** [comment]
> You can indeed work around this by publishing migrations: https://laravel.com/docs/8.x/telescope#migration-customization

Yes but the error happen when telescope tries to insert the data in the table.
