### ISSUE TITLE
ERROR: ErrorException: Undefined array key 0

### ISSUE THREAD

**Issue by yasirhashmi88** [laravel/telescope#1178]
- Telescope Version: 4.7.1
- Laravel Version: 8
- PHP Version: 8
- Database Driver & Version: MySQL 8.0.23

### Description:

Getting `ERROR: ErrorException: Undefined array key 0 in /var/www/hr/vendor/laravel/telescope/src/Watchers/ModelWatcher.php:74`

- If I set `'hydrations' => false,` in `telescope.php`, it works.
- I noticed the key of an array comes as string like `model` and doesn't comes as `0`

### Steps To Reproduce:

1 - I have existing Laravel app which have different models but I believe this can be replicated on fresh Laravel installation.
2 - Run `composer require laravel/telescope:4.7.1 --dev`. I have tried multiple versions but still no luck.
3 - Try open your app in browser. You should see the error in the console or your logs.

**Comment by driesvints** [comment]
I think this is related to my PR here: https://github.com/laravel/telescope/pull/1174. Seems that associative keys are kept because of the decoding. But it's beyond me why they're being recorded again.

**Comment by driesvints** [comment]
@yasirhashmi88 can you try out https://github.com/laravel/telescope/pull/1180 ?

**Comment by yasirhashmi88** [comment]
> @yasirhashmi88 can you try out #1180 ?

@driesvints Yes. That's fixes the issue.
