### ISSUE TITLE
Observer to analyze the runtime of classes and methods

### ISSUE THREAD

**Issue by rjlfurtado** [laravel/telescope#1184]
1st - I see that the Telescope could be better if it had an observer for classes and methods.
Example:
identify slow points through classes and methods using runtime.

2nd - I felt the lack of graphics, the view of the tables is very wide but it leaves me with my eyes closed. Currently I can't get a complete and simplified view of everything.
That would be very interesting.

**Comment by driesvints** [comment]
Feel free to attempt some PR's 👍
