### ISSUE TITLE
Wrong asset URLs for telescope

### ISSUE THREAD

**Issue by saulamsal** [laravel/telescope#1185]
- Telescope Version: ^4.7
- Laravel Version: ^8.20.1
- PHP Version: 8.0.0
- Database Driver & Version: MySQL  Ver 8.0.28

### Description:
I had the Laravel application running on a local network of 192.168.1.54 previously. I've recently moved to a new device and also a new network(192.168.1.92). Now, when loading Telescope, it doesn't load the assets. When I looked up the assets, it was still referencing to 192.168.1.54(previous URL). 
I tried removing all packages and reinstalling fresh packages again but Telescope still seem to be using previous network URL.  When I looked at the layout.blade.php file inside telescope, it is referencing asset via mix.

`<script src="{{ asset(mix('app.js', 'vendor/telescope')) }}"></script>
`
 
The mix is working just fine for the frontend app, using the current network, but the telescope isn't respecting new network URL.

**Comment by driesvints** [comment]
This doesn't seem Telescope related but rather some configuration gone wrong or maybe browser caching. Telescope doesn't control your web address. Please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)
