### ISSUE TITLE
Passing null to parameter $domain of type string is deprecated when using Telescope with Octane

### ISSUE THREAD

**Issue by rmundel** [laravel/telescope#1189]
- Telescope Version: 4.7.2
- Laravel Version: 8.83.0 
- PHP Version: 8.1.2 | 8.0.14
- Database Driver & Version: Postgres 14

### Description:
https://app.honeybadger.io/fault/97659/d82cc959e1dfe859bbad5448244d7a45

### Steps To Reproduce:
Just access Telecope running from Octane.

**Comment by driesvints** [comment]
Thanks, I've sent in a PR for this: https://github.com/laravel/octane/pull/478
