### ISSUE TITLE
Requests search can search url, http response instead only tags

### ISSUE THREAD

**Issue by Messhias** [laravel/telescope#1192]
Hi,

I tried to check the documentation but unfortunately, I couldn't find anything that reflects the request (if you already have it, I'll send my apologies in advance).

But in the quest part, it would be nice if it were possible to search not only tags but also other information that is associated with them.

Attached is a demo image of what I mean.

I believe that using queries with LIKE would be more effective for him with this kind of feature.

Thanks,

<img width="985" alt="image" src="https://user-images.githubusercontent.com/1161283/154534371-0dec5aac-a5ff-4f1e-90ae-c99689caba28.png">

**Comment by driesvints** [comment]
Atm we have no plans for this but you can always attempt a PR if you want. Worst case, you could maintain a fork of Telescope that does what you want.
