### ISSUE TITLE
Requests table not displaing correctly

### ISSUE THREAD

**Issue by gennarobotta** [laravel/telescope#1193]
- Telescope Version: 4.7.3
- Laravel Version: 8.81.0
- PHP Version: 7.4.27
- Database Driver & Version: mysql with 8.0.17

### Description:
Requests table not displaying correctly due to long URL
![issue](https://user-images.githubusercontent.com/15877216/155097741-91286fba-aa90-44f1-8f7e-cb7132d6f778.PNG)

### Steps To Reproduce:
Make a request with a long url

**Comment by driesvints** [comment]
The url is abbreviated on purpose.

**Comment by gennarobotta** [comment]
I know the URL is abbreviated on purpose. It's the table that is wrong, look at the eye on the right, the background is different.

**Comment by driesvints** [comment]
Did you publish the updated asset files with `php artisan telescope:publish`? https://laravel.com/docs/9.x/telescope#upgrading-telescope

**Comment by gennarobotta** [comment]
I did and i noted that the bug happen not just if it's a long URL but has to be a long word in path param.
For example in the case below is correct
![not_issue](https://user-images.githubusercontent.com/15877216/155603768-38fbaebb-4b38-4fc8-9045-9e64db6a1b90.PNG)

**Comment by driesvints** [comment]
Thanks for that, I managed to reproduce this and sent in a fix: https://github.com/laravel/telescope/pull/1195
