### ISSUE TITLE
ERROR:  could not create unique index "telescope_entries_pkey"

### ISSUE THREAD

**Issue by LocalHeroPro** [laravel/telescope#1196]
- Telescope Version: #.#.#
- Laravel Version: 8.83.2
- PHP Version: 8.1.3
- Database Driver & Version: PostgreSQL 13.6, 14.2

### Description:
I try to make backup and after that, restore it 1:1.

### Steps To Reproduce:

```shell
// dump in PostgreSQL 13.6
$ PGPASSWORD="secret" pg_dump --username=some_user --port=5433 --host=127.0.0.1 --dbname=database_name --no-owner --format=d --jobs=8 --file=/data/backups/timestamp
// restore in PostgreSQL 14.2
$ /usr/bin/pg_restore --dbname=database_name --no-owner --format=d --schema=public --username=another_user --host=localhost --port=5434 /path/to/dump
pg_restore: while PROCESSING TOC:
pg_restore: from TOC entry 3369; 2606 415390 CONSTRAINT telescope_entries telescope_entries_pkey database_name
pg_restore: error: could not execute query: ERROR:  could not create unique index "telescope_entries_pkey"
DETAIL:  Key (sequence)=(1) is duplicated.
Command was: ALTER TABLE ONLY public.telescope_entries
    ADD CONSTRAINT telescope_entries_pkey PRIMARY KEY (sequence);
pg_restore: warning: errors ignored on restore: 1
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
