### ISSUE TITLE
Add option to record dumps even though the dump watcher tab is not open

### ISSUE THREAD

**Issue by superDuperCyberTechno** [laravel/telescope#1198]
I propose that you add the option to record dumps regardless of whether or not the dump watcher tab is open in the Telescope interface.

This could be done by allowing the `TELESCOPE_RECORD_DUMP_WATCHER_ALWAYS` environment variable to control this outcome.

This can easily be achieved if we change [L43 in `DumpWatcher`](https://github.com/laravel/telescope/blob/5a2702a7fe4bccc36d798e472d12efc60bc0ba45/src/Watchers/DumpWatcher.php#L43) to the following:

```
if (! env('TELESCOPE_RECORD_DUMP_WATCHER_ALWAYS', false) && ! $this->cache->get('telescope:dump-watcher')) {
    return;
}
```

**Comment by driesvints** [comment]
Feel free to attempt a PR 👍

**Comment by superDuperCyberTechno** [comment]
Will do.
