### ISSUE TITLE
Problem with telescope when using redis cache

### ISSUE THREAD

**Issue by SI-IC** [laravel/telescope#1208]
- Telescope Version: 4.8.0
- Laravel Version: 9.4.1
- PHP Version: 8.1.3
- Database Driver & Version: mysql 8.0.28

### Description:
I have installed laravel sail and telescope. When I use in my code something like

`$config = Cache::rememberForever('config', function () {
    return 'hello';
});`

everything works great and laravel returns me cache value, but I get a large number of next errors:

`[2022-03-23 12:35:27] local.ERROR: Class "Redis" not found {"exception":"[object] (Error(code: 0): Class \"Redis\" not found at /home/alex/Documents/EVO/Marriott/fullstack/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php:75)
[stacktrace]
#0 /home/alex/Documents/EVO/Marriott/fullstack/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php(28): Illuminate\\Redis\\Connectors\\PhpRedisConnector->createClient()
#1 /home/alex/Documents/EVO/Marriott/fullstack/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php(32): Illuminate\\Redis\\Connectors\\PhpRedisConnector->Illuminate\\Redis\\Connectors\\{closure}()
#2 /home/alex/Documents/EVO/Marriott/fullstack/vendor/laravel/framework/src/Illuminate/Redis/RedisManager.php(112): Illuminate\\Redis\\Connectors\\PhpRedisConnector->connect()
#3 /home/alex/Documents/EVO/Marriott/fullstack/vendor/laravel/framework/src/Illuminate/Redis/RedisManager.php(91): Illuminate\\Redis\\RedisManager->resolve()
#4 /home/alex/Documents/EVO/Marriott/fullstack/vendor/laravel/framework/src/Illuminate/Cache/RedisStore.php(258): Illuminate\\Redis\\RedisManager->connection()
#5 /home/alex/Documents/EVO/Marriott/fullstack/vendor/laravel/framework/src/Illuminate/Cache/RedisStore.php(62): Illuminate\\Cache\\RedisStore->connection()
#6 /home/alex/Documents/EVO/Marriott/fullstack/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(97): Illuminate\\Cache\\RedisStore->get()
#7 /home/alex/Documents/EVO/Marriott/fullstack/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(418): Illuminate\\Cache\\Repository->get()
#8 /home/alex/Documents/EVO/Marriott/fullstack/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(242): Illuminate\\Cache\\CacheManager->__call()
#9 /home/alex/Documents/EVO/Marriott/fullstack/vendor/laravel/telescope/src/Telescope.php(255): cache()
#10 /home/alex/Documents/EVO/Marriott/fullstack/vendor/laravel/telescope/src/Telescope.php(149): Laravel\\Telescope\\Telescope::startRecording()
#11 /home/alex/Documents/EVO/Marriott/fullstack/vendor/laravel/telescope/src/TelescopeServiceProvider.php(33): Laravel\\Telescope\\Telescope::start()
#12 /home/alex/Documents/EVO/Marriott/fullstack/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\\Telescope\\TelescopeServiceProvider->boot()
#13 /home/alex/Documents/EVO/Marriott/fullstack/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#14 /home/alex/Documents/EVO/Marriott/fullstack/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#15 /home/alex/Documents/EVO/Marriott/fullstack/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#16 /home/alex/Documents/EVO/Marriott/fullstack/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\\Container\\BoundMethod::call()
#17 /home/alex/Documents/EVO/Marriott/fullstack/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(928): Illuminate\\Container\\Container->call()
#18 /home/alex/Documents/EVO/Marriott/fullstack/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(909): Illuminate\\Foundation\\Application->bootProvider()
#19 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}()
#20 /home/alex/Documents/EVO/Marriott/fullstack/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(910): array_walk()
#21 /home/alex/Documents/EVO/Marriott/fullstack/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#22 /home/alex/Documents/EVO/Marriott/fullstack/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(239): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap()
#23 /home/alex/Documents/EVO/Marriott/fullstack/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(310): Illuminate\\Foundation\\Application->bootstrapWith()
#24 /home/alex/Documents/EVO/Marriott/fullstack/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(127): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#25 Command line code(1): Illuminate\\Foundation\\Console\\Kernel->handle()
#26 {main}
"} `

I tried to set alias in app config for Redis `'Redis' => Illuminate\Support\Facades\Redis::class` and I got next errors:

`[2022-03-23 13:24:27] local.ERROR: Please make sure the PHP Redis extension is installed and enabled. {"exception":"[object] (LogicException(code: 0): Please make sure the PHP Redis extension is installed and enabled. at /home/alex/Documents/EVO/Marriott/fullstack/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php:77)
[stacktrace]
#0 /home/alex/Documents/EVO/Marriott/fullstack/vendor/laravel/framework/src/Illuminate/Support/helpers.php(302): Illuminate\\Redis\\Connectors\\PhpRedisConnector->Illuminate\\Redis\\Connectors\\{closure}()
#1 /home/alex/Documents/EVO/Marriott/fullstack/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php(121): tap()
#2 /home/alex/Documents/EVO/Marriott/fullstack/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php(28): Illuminate\\Redis\\Connectors\\PhpRedisConnector->createClient()
#3 /home/alex/Documents/EVO/Marriott/fullstack/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php(32): Illuminate\\Redis\\Connectors\\PhpRedisConnector->Illuminate\\Redis\\Connectors\\{closure}()
#4 /home/alex/Documents/EVO/Marriott/fullstack/vendor/laravel/framework/src/Illuminate/Redis/RedisManager.php(112): Illuminate\\Redis\\Connectors\\PhpRedisConnector->connect()
#5 /home/alex/Documents/EVO/Marriott/fullstack/vendor/laravel/framework/src/Illuminate/Redis/RedisManager.php(91): Illuminate\\Redis\\RedisManager->resolve()
#6 /home/alex/Documents/EVO/Marriott/fullstack/vendor/laravel/framework/src/Illuminate/Cache/RedisStore.php(258): Illuminate\\Redis\\RedisManager->connection()
#7 /home/alex/Documents/EVO/Marriott/fullstack/vendor/laravel/framework/src/Illuminate/Cache/RedisStore.php(62): Illuminate\\Cache\\RedisStore->connection()
#8 /home/alex/Documents/EVO/Marriott/fullstack/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(97): Illuminate\\Cache\\RedisStore->get()
#9 /home/alex/Documents/EVO/Marriott/fullstack/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(418): Illuminate\\Cache\\Repository->get()
#10 /home/alex/Documents/EVO/Marriott/fullstack/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(242): Illuminate\\Cache\\CacheManager->__call()
#11 /home/alex/Documents/EVO/Marriott/fullstack/vendor/laravel/telescope/src/Telescope.php(255): cache()
#12 /home/alex/Documents/EVO/Marriott/fullstack/vendor/laravel/telescope/src/Telescope.php(149): Laravel\\Telescope\\Telescope::startRecording()
#13 /home/alex/Documents/EVO/Marriott/fullstack/vendor/laravel/telescope/src/TelescopeServiceProvider.php(33): Laravel\\Telescope\\Telescope::start()
#14 /home/alex/Documents/EVO/Marriott/fullstack/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\\Telescope\\TelescopeServiceProvider->boot()`

I have `CACHE_DRIVER=redis` in my .env and I didn't change initial cache and database configs.

What I do wrong?
Thanks in advance.

### Steps To Reproduce:
Install Laravel with sail and telescope, and try to use cache.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
