### ISSUE TITLE
No duration when using Octane

### ISSUE THREAD

**Issue by Livijn** [laravel/telescope#1212]
- Telescope Version: 4.7.3
- Laravel Version: 8.83.2
- PHP Version: 8.1
- Database Driver & Version: MySQL 8

### Description:
I am using Laravel Vapor and whenever I use Octane on Vapor my request durations come out as `-` in the Telescope dashboard.

![](https://i.gyazo.com/105c02eb0f2ab32f0ff2b14abb70050d.png)

**Comment by driesvints** [comment]
Can you please email Vapor support? Thanks.

**Comment by nunomaduro** [comment]
https://github.com/laravel/vapor-core/pull/127
