### ISSUE TITLE
MySQL connections not closing on Vapor

### ISSUE THREAD

**Issue by Livijn** [laravel/telescope#1214]
- Telescope Version: v4.8.0
- Laravel Version: v8.83.5
- PHP Version: 8.1.3
- Database Driver & Version: MySQL 8.0.27

### Description:
I am using Vapor and saw a huge number of DB connections. I pinned down the problem to Telescope and tried disabling it. As soon as I did, the DB connections was working as expected.

This issue is related to #818 and that whole issue should be taken in consideration. I have been in contact with your support team and came to the conclusion that an issue here would be best.

**Comment by driesvints** [comment]
Seems like your support ticket is still pending so please be patient while my colleagues triage it. Thanks

**Comment by taylorotwell** [comment]
Potential fix: https://github.com/laravel/telescope/pull/1215

**Comment by Livijn** [comment]
Have tried it for a few minutes and it seems to work!
