### ISSUE TITLE
I can't find POST requests to API on Request tab of telescope. but I see GET requests. What can I do to see all request?

### ISSUE THREAD

**Issue by parmonov98** [laravel/telescope#1228]
- Telescope Version:^4.9
- Laravel Version: ^8.40
- PHP Version: 8.0
- Database Driver & Version: mysql

### Description:
https://stackoverflow.com/questions/72372230/i-cant-find-post-requests-to-api-on-request-tab-of-telescope-but-i-see-get-req

### Steps To Reproduce:
composer require, telescope:install, publish, add api to middlewares in telescope.php and go to /telescope

make POST requests to api/any route.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by parmonov98** [comment]
I asked no reply but no reply
