### ISSUE TITLE
Queued Database Writes

### ISSUE THREAD

**Issue by billriess** [laravel/telescope#1231]
Is there any interest in queuing the data to the database instead of directly writing it? If the telescope database times out or is under too much load it will make the originating requests fail. This could be resolved if the data was queued.

**Comment by driesvints** [comment]
Hey @billriess. I'll check in with the team for this one to see if this is something what we can do.

**Comment by driesvints** [comment]
Hey there @billriess. We talked this over internally but right now don't have plans for this. If you keep having issues with this then maybe you can try smaller chunk sizes? 

https://github.com/laravel/telescope/blob/4.x/src/Storage/DatabaseEntriesRepository.php#L30

**Comment by billriess** [comment]
@driesvints thanks for taking the time to review this idea.

I've tried both increasing and reducing the chunk size already, it doesn't really solve my problem. The issue is that telescope can flood the database with too many connections and timeouts. There are some other posts floating around the community that seem to have similar issues and there was a discussion on Discord about potentially queuing the data which could solve the issue. At the end of the day, it's better to miss a request in telescope (queue failed) than for the originating request to fail.

I understand if the Laravel team is too busy to work on this task, would a PR be helpful or is this just something that is off the table for now?

**Comment by driesvints** [comment]
I'm afraid it's off the table, sorry.
