### ISSUE TITLE
Class "Laravel\Telescope\TelescopeServiceProvider" not found when running cache:config in prod env

### ISSUE THREAD

**Issue by giagara** [laravel/telescope#1243]
- Telescope Version: 4.9.1
- Laravel Version: 9.22.1
- PHP Version: 8.1.8
- Database Driver & Version: no needed for this scenario

### Description:
In production env, when i try to run `php artisan route:cache` or `php artisan config:cache` i get the error: `Class "Laravel\Telescope\TelescopeServiceProvider" not found`. 
I've followed the tutorial in here https://laravel.com/docs/9.x/telescope#local-only-installation.

The strange thing is that i have a `Log::debug("telescope loading..")` before the actual registration in AppServiceProvider, and that log entry is not displayed

Already checked with other logs that app is in prod. Checked also with tinker.

AppServiceProvider:
```
public function register()
    {
        if ($this->app->environment('local')) {
            Log::debug("Loading telescope...");
            $this->app->register(\Laravel\Telescope\TelescopeServiceProvider::class);
            $this->app->register(TelescopeServiceProvider::class);
        }
   } 
```

### Steps To Reproduce:
Install telescope following https://laravel.com/docs/9.x/telescope#local-only-installation
Put the app in prod.
Run php artisan config:cache

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
