### ISSUE TITLE
Telescope doesn't listen inside async functions (Ratchet)

### ISSUE THREAD

**Issue by alexandre-tobia** [laravel/telescope#1249]
- Telescope Version: 4.9.2
- Laravel Version: 9
- PHP Version: 8.1.9
- Database Driver & Version: Mysql 8

### Description:
Hi everyone,

When using an websocket tools like https://github.com/ratchetphp/Ratchet, the jobs dispatched inside it, is not recorded. (But the job is actually executed)

### Steps To Reproduce:
```php
  dispatch(function() {
      dd('Job is listed on telescope ');
  });
  
  \Ratchet\Client\connect($stream_endpoint)->then(function ($conn) use ($loop, $pool) {

      dispatch(function() {
          dd('Not listed on telescope');
      });

  }, function ($e) {
      echo "Could not connect: {$e->getMessage()}\n";
  });
```
![Capture d’écran 2022-09-05 à 17 46 57](https://user-images.githubusercontent.com/5537783/188484225-7d289a1f-a94c-47e1-9355-67ac5ff3ea8d.png)

Any clues ?

Thanks a lot

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by alexandre-tobia** [comment]
Hi @driesvints i don't understand why "this is a question which can be asked on a support channel", look like something not working with telescope.

Thanks

**Comment by driesvints** [comment]
We don't provide support for tools like Ratchet, sorry.
