### ISSUE TITLE
DatabaseEntriesRepository->storeExceptions updating should_display_on_index to false when it's already false

### ISSUE THREAD

**Issue by md5** [laravel/telescope#1251]
The `UPDATE` query to set `should_display_on_index = false` in `storeExceptions` is unnecessarily updating rows where the value is already `false`. It would be ideal to add a `where('should_display_on_index', true)` condition to the update to only touch rows where it will actually be changed. Under conditions of heavy exception logging, these unnecessary updates are causing excessive load on the `telescope_entries` table.

**Comment by driesvints** [comment]
If you want, you can attempt a PR.

**Comment by md5** [comment]
Going through the Open Source approval process at my employer is unfortunately too onerous to do for a simple one-line change to a project that I have no other reason to contribute to, given that we have only a handful of legacy applications built in Laravel.

I hope you will reconsider making this change yourself, since it's a clear and uncontroversial improvement for your users.

**Comment by md5** [comment]
I probably should have mentioned that the database in question here was PostgreSQL. I don't think this problem affects MariaDB/MySQL in the same way.

In PostgreSQL, the constant addition of new versions of the tuples for these rows causes sequential scans on the table to take increasingly longer amounts of time as more and more versions are added. If this also results in the `autovacuum` process falling behind on cleaning up the table, this can result in queries for tables that nominally only have a few thousand exceptions having to scan millions of row to run the `SELECT COUNT(*)` or `UPDATE should_display_on_index = false` queries run by `storeExceptions`.
