### ISSUE TITLE
JobWatcher causes duplicate queries

### ISSUE THREAD

**Issue by mpskovvang** [laravel/telescope#1255]
- Telescope Version: 4.9.3
- Laravel Version: 9.29.0
- PHP Version: 8.0.21
- Database Driver & Version: PostgreSQL 9.6.6

### Description:

When `JobWatcher` is enabled, jobs with model properties and `SerializesModels` trait will cause duplicate queries.

The reason is that the job is unserialized twice - first by the queue worker and later by the `JobWatcher`. Every time the job is unserialized, the trait will restore every model property.

Debug backtraces:
```
{
"file": "/app/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php",
"line": 97,
"function": "unserialize",
...
}
```

```
{
"file": "/app/vendor/laravel/telescope/src/Watchers/JobWatcher.php",
"line": 216,
"function": "unserialize",
...
}
```

The `unserialize` happens when the `updateBatch` method tries to extract properties from the command.

https://github.com/laravel/telescope/blob/a8d769ea573f05a26656f7e20b3cf25daaac2e89/src/Watchers/JobWatcher.php#L186

The issue can be resolved by disabling recording. However, I doubt that is the preferable way to solve this since the queries remain but skips recording.

```PHP
Telescope::$shouldRecord = false;

$command = $this->getCommand($payload['data']);

Telescope::$shouldRecord = true;
```

### Steps To Reproduce:

Create a job:

```PHP
class Test implements ShouldQueue
{
    use SerializesModels;
    
    protected User $user;
    
    public function __construct(User $user)
    {
        $this->user = $user;
    }
    
    public function handle()
    {
        Log::debug($this->user->name);
    }
}
```

Dispatch job: `dispatch(new Test($user));`

Run queue worker: `php artisan queue:work`

**Comment by driesvints** [comment]
I think ideally there indeed wouldn't be duplicate queries but maybe we should try the quick fix for now. Can you send in a PR?

**Comment by driesvints** [comment]
I sent in a PR for this: https://github.com/laravel/telescope/pull/1257
