### ISSUE TITLE
Filtering or grouping of specific requests

### ISSUE THREAD

**Issue by kai0310** [laravel/telescope#1260]
Thanks for a simple yet powerful package :)

### Description:
As you know, Laravel has a package called Livewire that performs asynchronous communication in the background.

By using it, you can send requests from certain components asynchronously.
In practice, however, it is often not necessary to check all of the many polling processes.

These are logs of requests from a Livewire component that polls the order list every 5 seconds.

![logs of requests from a Livewire component that polls](https://user-images.githubusercontent.com/52205108/194902504-7db7cc2a-f424-4bf7-8d40-c2eb4c6b494e.png)

### Solutions

1. **Disables the display of requests to specific URLs.**
For example, for Livewire only, you can exclude requests from Livewire by excluding the paths following `/livewire/*`.
This solution is very useful for use cases other than background processes, and we believe it is a very simple solution.

2. **Grouping specific identical requests**
This solution is also not just for Livewire requests or background requests that are requested in sequence.
For the same request by the same user, the Laravel Telescope console can be displayed beautifully by grouping them together.

**Comment by driesvints** [comment]
Hi there. We don't maintain Livewire ourselves. Right now we don't have any plans to add Livewire specific features to Telescope, sorry.

You can already ignore this path if you want to: https://github.com/laravel/telescope/blob/4.x/config/telescope.php#L98
