### ISSUE TITLE
Provide a means to disable the Telescope front-end/routes independent of Telescope itself

### ISSUE THREAD

**Issue by 6XGate** [laravel/telescope#1261]
In our environment, we don't want Telescope to expose its user interface in certain environments/`APP_ENV` roles. We prefer it only be available locally or from the main web server environment, but not in our queue runners that are supervised by Horizon or other servers not serving our SPA.

It would be great if we could control route registration by either:
- Using a closure; for example: `Telescope::registerRoutes(fn () => $this->app->environment(['local', 'production']))`
- Using a simple boolean; for example: `Telescope::registerRoutes($this->app->environment(['local', 'production']))`
- Using a variable in `.env`
- Or all of the above

**Comment by driesvints** [comment]
I guess this is similar to the Horizon issue you posted? Feel free to attempt a PR 👍 

I think that we can maybe just return a 404 by default in production and a 403 in local development.
