### ISSUE TITLE
Cannot use .env encrypt if telescope is enabled

### ISSUE THREAD

**Issue by pyr0hu** [laravel/telescope#1262]
- Telescope Version: 4.9.4
- Laravel Version: 9.33.0
- PHP Version: 8.1
- Database Driver & Version: Does not matter

### Description:

I want to use the new environment file encryption feature in Laravel. If I call `php artisan env:encrypt --env=staging` , it fails because it tries to connect to the staging instance's Redis but from my local computer I cannot access that. The staging instance has Telescope enabled (as it's on an company-wide network and it helps with debugging). But Laravel loads the whole environment from the .env.staging file, therefore overwriting my local Redis configuration. Telescope will try to use the staging's Redis connection to check for `pause-recording` and all of these stuff. As it cannot connect, the whole encryption command fails with a timeout error.

### Steps To Reproduce:

.env.staging:
TELESCOPE_ENABLED=true
REDIS_HOST=unaccessible redis host

php artisan env:encrypt --env=staging

**Comment by driesvints** [comment]
Gonna let @joedixon check into this when he's back.

**Comment by joedixon** [comment]
I have just submitted a PR which should resolve this. It would great if you could run a quick test with your setup @pyr0hu using the PR to ensure it works for you: https://github.com/laravel/framework/pull/44758

**Comment by pyr0hu** [comment]
@joedixon Yup, using that fix works!

**Comment by joedixon** [comment]
@pyr0hu thanks for testing so quickly!
