### ISSUE TITLE
TypeError: Cannot create property 'basePath' on string '$telescopeScriptVariables'

### ISSUE THREAD

**Issue by jbnv** [laravel/telescope#1263]
- Telescope Version: 4.9
- Laravel Version: 9.0
- PHP Version: 8.1

### Description:

Nothing but a blank screen rendered for all Telescope paths. Console reports the following error: `app.js?id=7328e77177db89b6ec830fb908e3df6c:2 Uncaught TypeError: Cannot create property 'basePath' on string '$telescopeScriptVariables'`. The source of the page appears to be there, but no content or HTML elements appear in the browser window.

**Comment by driesvints** [comment]
Can't reproduce this on the latest Telescope.

**Comment by jbnv** [comment]
Nice to see that the attitude of the Laravel community is that if it's broken, tough scraps. I'll remember this the next time I'm discussing Laravel with anyone, including my boss.
