### ISSUE TITLE
Not reeporting special event

### ISSUE THREAD

**Issue by idanieldrew** [laravel/telescope#1264]
- Telescope Version: 4.9.3
- Laravel Version: 9.19
- PHP Version: 8.1
- Database Driver & Version: pgsql:14.2

### Description:
All jobs and event are displayed well,except for a log that is specific to user verification.
(event is execute but there is no trace in telescope)

### Steps To Reproduce:
How i use it.[(like this)](https://laravel.com/docs/9.x/verification#model-preparation)
```
use Illuminate\Auth\Events\Registered;
 
event(new Registered($user));
```

**Comment by driesvints** [comment]
framework events are ignored by default. Try adding `Telescope::recordFrameworkEvents()` to the register method of your AppServiceProvider. But beware that this can lead to lots of events being recorded.

**Comment by idanieldrew** [comment]
Thanks

**Comment by driesvints** [comment]
Heya, I sent in a PR to make this more easily: https://github.com/laravel/telescope/pull/1289

**Comment by taylorotwell** [comment]
Extend the base Register event with your own App level Register event (that is empty other than extending the base class).
