### ISSUE TITLE
 ERROR: SQLSTATE[22018]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Conversion failed when converting the nvarchar value 'Auth:24' to data type int. 

### ISSUE THREAD

**Issue by mvehar** [laravel/telescope#1268]
- Telescope Version: 4.9.3
- Laravel Version: 9.30.1
- PHP Version: 8.0
- Database Driver & Version:
[Microsoft][ODBC Driver 17 for SQL Server][SQL Server]
PHP 8 running on IIS connecting to MSSQL 2012

### Description:
Bulk inserting tags fails since:
Illuminate\Database\QueryException : SQLSTATE[22018]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Conversion failed when converting the nvarchar value 'Auth:24' to data type int. (SQL: insert into [telescope_entries_tags] ([entry_uuid], [tag]) values (97a9adb2-1a26-4e82-a332-e55f1d15a791, Auth:24), (97a9adb2-1f9e-4d67-b243-c13955492c01, Auth:24), (97a9adb2-3170-436e-8c44-4b6c96586cae, Auth:24), (97a9adb2-3a00-4332-a60b-78ff5dc184db, Auth:24), (97a9adb2-4918-4370-8360-23bcb53da9fa, Auth:24), (97a9adb2-60cd-4039-a2c2-5f969fd15218, Auth:24), (97a9adb2-693a-4a15-aa45-22372b788ebe, Auth:24), (97a9adb2-6b25-4004-a566-fbbbea4873f0, Auth:24), (97a9adb2-7060-4ada-a419-20966162f003, Auth:24), (97a9adba-3bbe-42b4-893e-da1a43df14d4, Auth:24), (97a9adba-3f1c-4bbf-b986-b0c235af3ca7, Auth:24), (97a9adba-3ff2-4464-9b70-497755780d2b, Auth:24), (97a9adba-4296-43ea-b55b-d9fedfe2aa25, Auth:24), (97a9adba-435e-490d-8286-25169d814f09, Auth:24), (97a9adba-44a5-407f-869e-15f08781f1d9, Auth:24), (97a9adba-4828-489b-a12b-0c09e9a4b4dd, Auth:24), (97a9adba-492d-4706-81c5-4fe2b48b8950, Auth:24), (97a9adba-4b94-4cd1-bb65-2aaeba39e05b, Auth:24), (97a9adba-4cf8-4f48-b59b-863d35085606, Auth:24), (97a9adba-4dfb-4803-bfe3-bdfdd6a4b60b, Auth:24), (97a9adba-4ef1-4f8f-84ef-cde22218f5ec, Auth:24), (97a9adba-641c-4e6d-abef-38e3b72de2c9, Auth:24), (97a9adba-6872-44e6-9814-c5f93417fb3b, Auth:24), (97a9adba-6921-4bee-92e7-5d588a8715f2, Auth:24), (97a9adba-69b7-4133-a0cc-043b449354de, Auth:24), (97a9adba-7c58-4292-b5c2-3312e39bbaad, Auth:24), (97a9adba-80ec-4a65-9c6c-b5e76863d9bd, Auth:24), (97a9adba-81fa-4676-b103-d51b6624c0ff, Auth:24), (97a9adba-82dc-4475-8270-c4aca7d27417, Auth:24), (97a9adba-8417-4a86-9a4b-8391c6c22402, Auth:24), (97a9adca-d898-4a47-aceb-211439793e3f, 0), (97a9adca-d898-4a47-aceb-211439793e3f, 1), (97a9adca-d898-4a47-aceb-211439793e3f, Auth:24), (97a9adca-daf9-459c-af7c-ff18eff2b67e, Auth:24))

### Steps To Reproduce:
Some tags are numeric, some are strings. Column is nvarchar{255). Not sure which part of the system generates numeric tags, but MSSQL is not able to save it. Running Telescope on production mode.

**Comment by driesvints** [comment]
Hi there. Right now, the minimum required database version for MSSQL is 2017. Please upgrade to that and try again: https://laravel.com/docs/9.x/database#introduction

**Comment by beard7** [comment]
I get the same error on my development machine which is running SQL Server Developer 2019. Like the OP,  `tag` column is `nvarchar(255)` so no idea why that specific error is generated.
