### ISSUE TITLE
Avoid editing config/app.php

### ISSUE THREAD

**Issue by thanasisxan** [laravel/telescope#1274]
I would like to suggest that instead of editing the config/app.php for including the TelescopeServiceProvider, to add a configuration that for dev/ local environment only installations, the provider is registered dynamically in AppServiceProvider or something equivalent.

The reason is that the edited config/app.php may be committed accidentally to source control and break production environments, as laravel telescope being only a dev dependency and config/app.php includes its provider anyway.

**Comment by driesvints** [comment]
We suggest to work with the `env()` and env variables so you can set different values for different environments.
