### ISSUE TITLE
I'd like to be able to filter tags by "equal or greater than"

### ISSUE THREAD

**Issue by sts-ryan-holton** [laravel/telescope#1279]
Hi, I'm using Laravel Telescope v4.10.0 inside of Laravel v8.83.25. I've created some custom tags for my request for the `duration` key, but would like to match returned results that are equal or greater than. I've attempted to achieve this by modifying my tag code, but it returns nothing in the `register` method:

```php
Telescope::tag(function (IncomingEntry $entry) {
    return $entry->type === 'request'
                ? ['duration>='.$entry->content['duration']]
                : [];
});
```

**Comment by driesvints** [comment]
Thanks. Right now we have no plans for this but feel free to attempt a PR.
