### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by Hoopex** [laravel/telescope#1285]
- Telescope Version: Latest
- Laravel Version: Latest
- PHP Version: 8.1.10
- Database Driver & Version: MySQL v8

### Description:
Hello, I've installed this package but i got this
![Screenshot 2022-12-19 140707](https://user-images.githubusercontent.com/54420969/208433770-7225f33e-ff50-4a6b-a67b-9587b278f3dc.png)

**Comment by driesvints** [comment]
Works fine for me:

<img width="2213" alt="Screenshot 2022-12-20 at 10 59 01" src="https://user-images.githubusercontent.com/594614/208639327-a26055d0-5959-40d9-bc37-e00cd55f911f.png">
