### ISSUE TITLE
Add support for model keys cast to backed enums in FormatModel

### ISSUE THREAD

**Issue by sidquisaad** [laravel/telescope#1287]
- Telescope Version: 4.10.2
- Laravel Version: 9.x.x
- PHP Version: 8.1.13
- Database Driver & Version:

### Description:
In `Laravel\Telescope\FormatModel.php`, an Eloquent model key can be cast to a backed enum, which would not be able to be cast to a string.

### Steps To Reproduce:

1. Create a model with a non-autoincrement id.
2. Add a cast for `id` to a backed enum in the `$casts` member variable in said model
3. Try inserting a new row of said model into the database using `create` or `updateOrCreate` etc ...

I have submitted a rough fix in a [PR#1286](https://github.com/laravel/telescope/pull/1286), but I'm not too sure that will help as I don't have the full picture.

**Comment by driesvints** [comment]
Thanks. Seems like you already sent in a PR so let's see how it goes. This also seems like a feature request, not a bug.

**Comment by sidquisaad** [comment]
Thank you. It is indeed a bug and not a feature request. Laravel added support for casting model fields to backed enums, and that breaks Telescope. This in my case broke my seeders and halted development (for a while before I dug into the code and patched it locally).

The PR is submitted is just a quick fix I'm using locally.
