### ISSUE TITLE
X-Request-Id Header

### ISSUE THREAD

**Issue by dennisoderwald** [laravel/telescope#129]
It would be useful if Telescope had the option to enable a middleware that sets the ID of the request previously in `X-Request-Id` header.

This makes it easier to analyze errors, especially in productive environments with a large number of requests per second.

**Comment by themsaid** [comment]
Can you explain more?

**Comment by dennisoderwald** [comment]
The telescope stores each operation (requests etc.) under a UUID. The UUID would set the middleware as response header, so that the UUID can be used to find the request faster. Normally you use the X-Request-Id header for this.

**Comment by themsaid** [comment]
We have no plans to support this at the moment. Might be an idea for the future.
