### ISSUE TITLE
Telescope getting HTTP 500 when fetching request details

### ISSUE THREAD

**Issue by TylerOBrien** [laravel/telescope#1294]
- Telescope Version: ^4.9
- Laravel Version: 9.37.0
- PHP Version: 8.1.11
- Database Driver & Version: n/a

### Description:

When trying to view some request details the request sent to the Laravel instance throws this error:

```
GET https://[redacted].com/telescope/telescope-api/requests/98413cba-0c8d-48df-95b7-3a40e0e6bfdb

message | "mb_strtolower(): Argument #1 ($string) must be of type string, array given"
-- | --
exception | "TypeError"
file | "/home/api/releases/1674057319/vendor/laravel/framework/src/Illuminate/Support/Str.php"
line | 507
```

This has something to do with Telescope failing to parse the JSON, because if I look up the db record for one of the request details that Telescope can successfully display then copy that over to a record that Telescope cannot display it will work.

The JSON for the requests that cannot be displayed are well-formed because if I paste all of the JSON into my web browser's dev console it parses correctly without error.

This is the JSON stored in the db that Telescope is failing to parse (with IP addresses and domain names redacted for privacy reasons): https://paste.ofcode.org/jXvLg7g9VzY6K8reDFLzXr

### Steps To Reproduce:

Try to view the request details for a request with the JSON I provided as the content.

**Comment by TylerOBrien** [comment]
I had some time to dig through the stack trace and the problem is this line of code:

https://github.com/laravel/telescope/blob/4.x/src/Avatar.php#L33

This line of code assumes the `email` attribute is a string, which it is not on the API I am working on. The `email` attribute on this API is an object (specifically it's a relationship on the User model).

As a test to confirm this is the issue I changed if-statement on line 25 from this:

```
if (empty($user['email'])) {
    return;
}
```

to this:

```
if (empty($user['email']) || !is_string($user['email'])) {
    return;
}
``

and the error went away and all requests are now loading correctly.

**Comment by TylerOBrien** [comment]
Looks like there's minor issues elsewhere with Telescope assuming that the `email` attribute is a string, though no errors are being caused by that and Telescope remains functional.

Is there a way to pass a function to Telescope that can overwrite the `email` attribute just for Telescope so it's receiving the string value that it expects? Like this for example:

```
Telescope::userAttributes(function ($attributes) {
    return array_merge($attributes, [
        'email' => 'custom_email_override@domain.com',
    ]);
});
```

The Docs only seem to mention a function for overriding how the avatar is being made, but not how the `$user` object is being constructed.

**Comment by driesvints** [comment]
You can register a custom callback to handle it:

```php
Avatar::register(function ($usedId, $email) {

});
```
