### ISSUE TITLE
Logo style

### ISSUE THREAD

**Issue by uzdeveloper1** [laravel/telescope#1297]
- Telescope Version: 4.13.0
- Laravel Version: 9.50.1
- PHP Version: 8.2.0
- Database Driver & Version: pgsql 15

### Description:
![screencapture-tender-loc-telescope-models-2023-02-02-17_24_24](https://user-images.githubusercontent.com/65232715/216324204-491e69e8-a1ba-40bb-9928-0224dd8f88d8.png)

**Comment by uzdeveloper1** [comment]
![Screenshot 2023-02-02 at 17 25 45 (2)](https://user-images.githubusercontent.com/65232715/216324749-381c4965-3531-491e-9684-9aabf8b1c974.png)

**Comment by uzdeveloper1** [comment]
Cach remove after update to version 4.13.0

**Comment by PieterCappelle** [comment]
I had the same exact problem today. Took me some time to find the solution :-)
`php artisan view:clear`
