### ISSUE TITLE
Empty (but not null) TELESCOPE_PATH and/or HORIZON_PATH disables recording.

### ISSUE THREAD

**Issue by kylearch** [laravel/telescope#1300]
- Telescope Version: 4.13.0
- Laravel Version: 9.5.2
- PHP Version: 8.2.1
- Database Driver & Version: mysql 8.0.31

### Description:
An empty (but not `NULL`) value in _either_ `config('telescope.path')` or `config('horizon.path')` incorrectly disables all Telescope recording. The lines [here](https://github.com/laravel/telescope/blob/4.x/src/Telescope.php#L235) and [here](https://github.com/laravel/telescope/blob/4.x/src/Telescope.php#L239-L241) add the plain wildcard `'*'` to the collection of unapproved URIs when either config value is defined as an empty string.

#### Use Case
I want to host Telescope and Horizon at `telescope.example.com/` and `horizon.example.com/`, respectively. The explicit `null` checks in [Telescope::requestIsToApprovedUri](https://github.com/laravel/telescope/blob/4.x/src/Telescope.php#L246-L267) make this impossible, even though the configuration supports the dashboard(s) loading with those settings.

### Steps To Reproduce:
1. Install Telescope.
2. Create file `config/horizon.php` with the content: `<?php return ['path' => '']; `
3. Notice no recording happens at any application URIs.

**Comment by driesvints** [comment]
We could look at a PR that supports this use case 👍

**Comment by RomainMazB** [comment]
@driesvints would you consider re-opening this issue?

It still occurs 2 years after a 4 modified lines PR by @kafaa-dev was closed by Taylor and the use case is common: any developer who want to host horizon or telescope on a subdomain will face it.

I think my personal experience of this issue answer the "why aren't there more people crying about it?".

I started to host telescope and horizon on the main domain or the app: `domain.com/telescope` and `domain.com/horizon`.
It worked like a charm for months, then the project grown up and I wanted the things to be more distinct. I created the subdomains `horizon.domain.com` and `telescope.domain.com` and configured the two packages to reflect the changes:
```env
TELESCOPE_DOMAIN=telescope.domain.com
TELESCOPE_PATH=
HORIZON_DOMAIN=horizon.domain.com
HORIZON_PATH=
```
And here the things just stopped to work as they should but never I thought this would come from Telescope. Indeed I was more like "Probably telescope can't handle other subdomain requests" or "I should have a problem in my routes files"...

After a couple of hours of facing a wall "just to change the URL look", I just gave up with this _basic and common_ yet custom configuration and I rollbacked to the basic previous URLs for weeks before trying to dig deeper into this today.

Today, it took to me almost 1 hour to understand that was an issue from Telescope and a lot of `dd`s inside telescope vendors file to understand "why the hell `Telescope::isRecording()` returns false?"

I think a lot of people face this issue but they just gave up and stay with the dummy `/telescope` and `/horizon` paths.
It's just the fact that a PR was created, and to me it looks really simple to read it and see that there is no cons that would justify the PR to not be merged.
