### ISSUE TITLE
Uncaught Error: Class "Brick\Math\BigInteger"

### ISSUE THREAD

**Issue by tahirmahm123** [laravel/telescope#1302]
- Telescope Version: 4.13
- Laravel Version: 10.x-dev
- PHP Version: 8.1
- Database Driver & Version: MySQL 5.7.37

### Description:
Laravel Project was working fine. I just enabled telescope and Application Crashed.

### Stack Trace
Uncaught Error: Class "Brick\Math\BigInteger" not found in /app/vendor/ramsey/uuid/src/Math/BrickMathCalculator.php:117 Stack trace:
#0 /app/vendor/ramsey/uuid/src/Converter/Number/GenericNumberConverter.php(55): Ramsey\Uuid\Math\BrickMathCalculator->toBase()
#1 /app/vendor/ramsey/uuid/src/Generator/CombGenerator.php(90): Ramsey\Uuid\Converter\Number\GenericNumberConverter->toHex()
#2 /app/vendor/ramsey/uuid/src/UuidFactory.php(360): Ramsey\Uuid\Generator\CombGenerator->generate()
#3 /app/vendor/laravel/framework/src/Illuminate/Support/Str.php(1265): Ramsey\Uuid\UuidFactory->uuid4()
#4 /app/vendor/laravel/telescope/src/IncomingEntry.php(75): Illuminate\Support\Str::orderedUuid()
#5 /app/vendor/laravel/telescope/src/IncomingEntry.php(92): Laravel\Telescope\IncomingEntry->__construct()
#6 /app/vendor/laravel/telescope/src/Watchers/LogWatcher.php(40): Laravel\Telescope\IncomingEntry::make()
#7 /app/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(421): Laravel\Telescope\Watchers\LogWatcher->recordLog()
#8 /app/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(249): Illuminate\Events\Dispatcher->Illuminate\Events\{closure}()
#9 /app/vendor/laravel/framework/src/Illuminate/Log/Logger.php(245): Illuminate\Events\Dispatcher->dispatch()
#10 /app/vendor/laravel/framework/src/Illuminate/Log/Logger.php(186): Illuminate\Log\Logger->fireLogEvent()
#11 /app/vendor/laravel/framework/src/Illuminate/Log/Logger.php(106): Illuminate\Log\Logger->writeLog()
#12 /app/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(105): Illuminate\Log\Logger->warning()
#13 /app/vendor/laravel/framework/src/Illuminate/Support/helpers.php(423): Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}()
#14 /app/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(109): with()
#15 /app/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(70): Illuminate\Foundation\Bootstrap\HandleExceptions->handleDeprecationError()
#16 /app/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(250): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#17 /app/vendor/brick/math/src/BigInteger.php(22): Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}()
#18 /app/vendor/composer/ClassLoader.php(122): unknown()
#19 /app/vendor/composer/ClassLoader.php(443): Composer\Autoload\ClassLoader::Composer\Autoload\{closure}()
#20 /app/vendor/ramsey/uuid/src/Math/BrickMathCalculator.php(117): Composer\Autoload\ClassLoader->loadClass()
#21 /app/vendor/ramsey/uuid/src/Converter/Number/GenericNumberConverter.php(55): Ramsey\Uuid\Math\BrickMathCalculator->toBase()
#22 /app/vendor/ramsey/uuid/src/Generator/CombGenerator.php(90): Ramsey\Uuid\Converter\Number\GenericNumberConverter->toHex()
#23 /app/vendor/ramsey/uuid/src/UuidFactory.php(360): Ramsey\Uuid\Generator\CombGenerator->generate()
#24 /app/vendor/laravel/framework/src/Illuminate/Support/Str.php(1265): Ramsey\Uuid\UuidFactory->uuid4()
#25 /app/vendor/laravel/telescope/src/IncomingEntry.php(75): Illuminate\Support\Str::orderedUuid()
#26 /app/vendor/laravel/telescope/src/IncomingExceptionEntry.php(27): Laravel\Telescope\IncomingEntry->__construct()
#27 /app/vendor/laravel/telescope/src/IncomingEntry.php(92): Laravel\Telescope\IncomingExceptionEntry->__construct()
#28 /app/vendor/laravel/telescope/src/Watchers/ExceptionWatcher.php(54): Laravel\Telescope\IncomingEntry::make()
#29 /app/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(421): Laravel\Telescope\Watchers\ExceptionWatcher->recordException()
#30 /app/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(249): Illuminate\Events\Dispatcher->Illuminate\Events\{closure}()
#31 /app/vendor/laravel/framework/src/Illuminate/Log/Logger.php(245): Illuminate\Events\Dispatcher->dispatch()
#32 /app/vendor/laravel/framework/src/Illuminate/Log/Logger.php(186): Illuminate\Log\Logger->fireLogEvent()
#33 /app/vendor/laravel/framework/src/Illuminate/Log/Logger.php(94): Illuminate\Log\Logger->writeLog()
#34 /app/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(645): Illuminate\Log\Logger->error()
#35 /app/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(274): Illuminate\Log\LogManager->error()
#36 /app/app/Exceptions/Handler.php(43): Illuminate\Foundation\Exceptions\Handler->report()
#37 /app/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(182): App\Exceptions\Handler->report()
#38 /app/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(250): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException()
#39 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}()
#40 {main} thrown

**Comment by driesvints** [comment]
Telescope v4 works just fine for me on Laravel v10. Most likely, you've not updated all your dependencies.
