### ISSUE TITLE
Logs Watcher - Deprecated Messages

### ISSUE THREAD

**Issue by CheshireC4t** [laravel/telescope#1311]
- Telescope Version: 4.13.2
- Laravel Version: 9.52.0
- PHP Version: 8.2.2
- Database Driver & Version: n/a

### Description:
Laravel Telescope is logging deprecated warning messages in the Logs Watcher, even though I have "error_reporting = ~E_DEPRECATED" in php.ini file. I also have "LOG_DEPRECATIONS_CHANNEL" set to 'null' in config/logging.php.

Because of this, I get hundreds of deprecated messages in my logs watcher every page load because some third party libraries haven't yet updated to php 8.2. This makes Telescope unusable.

### Steps To Reproduce:
1) Have a 3rd party package that uses a method that's deprecated.
2) Call that method multiple times per page load.
3) See Watcher Log filled with tons of spam.

### Example Error using 3rd Party Library TwigBridge:
Creation of dynamic property TwigBridge\Extension\Laravel\Dump::$cloner **is deprecated** in \vendor\rcrowe\twigbridge\src\Extension\Laravel\Dump.php on line 33

**Comment by nunomaduro** [comment]
You can now specify the log level: https://github.com/laravel/telescope/pull/1312.
