### ISSUE TITLE
Telescope’s header svg log get too bigger.

### ISSUE THREAD

**Issue by y-nakashima-sailboat** [laravel/telescope#1313]
- Telescope Version: 4.8.3
- Laravel Version: 9.39.0
- PHP Version: 8.1.14
- Database Driver & Version:MySQL 8.0.28

- Mac Os: Big Sur 11.6.4
- Google Chrome 109.0.5414.119（Official Build） （x86_64）

### Description:
Telescope’s header svg log get too bigger.
Does anyone know why?

<img width="1528" alt="スクリーンショット 2023-02-22 13 52 24" src="https://user-images.githubusercontent.com/41831250/220527271-0b291df1-eca0-48e4-9325-b6c02ee0f7bd.png">

**Comment by driesvints** [comment]
Clear your views
