### ISSUE TITLE
Highlighting duplicate queries from the database

### ISSUE THREAD

**Issue by andrey-helldar** [laravel/telescope#1326]
Now the list of requests shows only the number of duplicate requests, and in order to find which ones are duplicated, you have to manually compare them.

I suggest highlighting entries containing duplicate requests.

#### Current view
![image](https://user-images.githubusercontent.com/10347617/225940126-d6f14347-b2a7-4d13-b085-c0f83f0a1bad.png)

#### Suggest view
![image](https://user-images.githubusercontent.com/10347617/225939954-c0bd9c42-f134-44d5-936d-ca26abd49e44.png)

**Comment by driesvints** [comment]
Feel free to attempt a PR 👍

**Comment by driesvints** [comment]
@andrey-helldar I don't review prs myself, taylor does. Feel free to attempt whatever you prefer.
