### ISSUE TITLE
When the path is changed, the Dump page is not refreshed.

### ISSUE THREAD

**Issue by ismailcaakir** [laravel/telescope#133]
Laravel Version 5.7.10

Screenshot
https://prnt.sc/l9w3hj

And the same issue applies within this page
/monitored-tags

**Comment by ismailcaakir** [comment]
And the same issue applies within this page 
/monitored-tags

**Comment by themsaid** [comment]
fixed in the next release.

**Comment by ismailcaakir** [comment]
Sorry, I haven't seen it yet.These lines were not updated.

https://github.com/laravel/telescope/blob/master/resources/js/screens/dumps/index.vue#L39
https://github.com/laravel/telescope/blob/master/resources/js/screens/monitoring/index.vue#L24
https://github.com/laravel/telescope/blob/master/resources/js/screens/monitoring/index.vue#L59
