### ISSUE TITLE
Details of the telescope entry always fetching

### ISSUE THREAD

**Issue by ThePatrykOOO** [laravel/telescope#1333]
- Telescope Version: 4.14
- Laravel Version: 10.6
- PHP Version: 8.1
- Database Driver & Version: Mysql

### Description:

I installed telescope from laravel documentation. But I have problem with showing details of request or query. Data from API was loaded but not showing.
<img width="1716" alt="Screenshot 2023-04-07 at 09 51 49" src="https://user-images.githubusercontent.com/22714417/230567635-21d1e3f6-977b-4eb4-b6d9-1e4c67159794.png">

### Steps To Reproduce:
Go to telescope http://localhost/telescope/requests
Click showing detail of request

**Comment by driesvints** [comment]
Seems to work fine for me:

<img width="1569" alt="Screenshot 2023-04-07 at 11 36 13" src="https://user-images.githubusercontent.com/594614/230585462-eadb6b30-7ac2-40df-bf61-9759f517a4f7.png">

Please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)
