### ISSUE TITLE
Allow some commands to run also when not runningInConsole

### ISSUE THREAD

**Issue by mariopro** [laravel/telescope#1334]
Allow some commands to run also when not runningInConsole to run also via UI.

My proposal is to make a small change in the `TelescopeServiceProvider` method `registerCommands()`. The current version does not allow, for instance, a call via `Artisan::call('telescope:clear');` and optionally leave the `telescope:install` and `telescope:publish` for the console only.

```
/**
 * Register the package's commands.
 *
 * @return void
 */
protected function registerCommands()
{
	if($this->app->runningInConsole()) {
		$this->commands([
			Console\InstallCommand::class,
			Console\PublishCommand::class,
		]);
	}
	
	$this->commands([
		Console\ClearCommand::class,
		Console\PauseCommand::class,
		Console\PruneCommand::class,
		Console\ResumeCommand::class,
	]);
}

**Comment by driesvints** [comment]
I think we used to have this but changed them to run in console. Feel free to propose this through a PR 👍
