### ISSUE TITLE
Frontend Errors Watcher

### ISSUE THREAD

**Issue by mshamaseen** [laravel/telescope#1343]
For me, Telescope is essential in every project, but every time I need to append frontend error watcher to it, by sending JS errors to backend and report them on the backend:

// frontend
`window.onerror = function( message, url, line, column, error ) {
  // send information to backend
};`

// backend
`report(FrontendException())`

Then I can also monitor frontend errors on production.

of course, this will send errors to the exceptions tab, which makes it hard to distinguish between backend errors and frontend errors.

I wonder if that can be added to Telescope as a feature? it would be very helpful!

**Comment by driesvints** [comment]
Thanks for your request. Right now, I'm afraid we don't have any plans for this, sorry.

**Comment by mshamaseen** [comment]
> Thanks for your request. Right now, I'm afraid we don't have any plans for this, sorry.

I can work on it myself if it can be merged?
