### ISSUE TITLE
Backslashes issue in Query Details

### ISSUE THREAD

**Issue by Sairahcaz** [laravel/telescope#1345]
### Telescope Version

4.9

### Laravel Version

8.75

### PHP Version

8.1

### Database Driver & Version

Server-Version: 8.0.32 - MySQL Community Server - GPL

### Description

I know that Laravel 8 is EOL, but I'm pretty sure this issue also exists in further versions.

I don't even know if this could be considered as a bug...
But I thought I just report it anyways, cause it's a bit cumbersome and confusing.

As I tried to debug a relation from tenant to setting model and enabled telescope, I saw the following select-statement was executed:

![image](https://user-images.githubusercontent.com/7384870/236233031-9ba32727-8433-420f-93f6-8868db146cb3.png)

No when you copy this select-statement and paste it into your mysql client it gives you no results. That was really confusing me, until I  learned that I need to add double backslashes here to get a proper result: 
```mysql
select
  *
from
  `settings`
where
  `settings`.`model_type` = 'App\\Models\\Tenant'
  and `settings`.`model_id` = 3
  and `settings`.`model_id` is not null
  and `settings`.`deleted_at` is null
```

As I said I don't know if this could be considered as a bug or issue, but it's though not really what you exepect!

### Steps To Reproduce

When telescope is enabled, just run a query within your Laravel app, which contains backslashes...

**Comment by driesvints** [comment]
Hi @Sairahcaz. This indeed isn't ideal.. but like you said I don't think we can qualify this as a bug. The snippet that's shown really is just a representation of the query. I'm not sure those are intended to be run on an engine directly. Ideally for this to work, some changes might need to be done on the `sql-formatter` library that we use under the hood.
