### ISSUE TITLE
Undefined property: `Illuminate\Http\Client\Response::$transferStats`

### ISSUE THREAD

**Issue by pionl** [laravel/telescope#1359]
### Telescope Version

4.14.4

### Laravel Version

9.24.0

### PHP Version

8.1.20

### Description

When using older version of Laravel the HTTP client watcher raises exception `Undefined property: Illuminate\Http\Client\Response::$transferStats` due the fact that the property is not defined in the Response class. This is the [code on v9.24.0](https://github.com/laravel/framework/blob/v9.24.0/src/Illuminate/Http/Client/Response.php)

As the composer.json does not restrict Laravel 9.X version it should be probably "detected" (property_exists)? The bug is caused by this addition. [v4.14.3](https://github.com/laravel/telescope/releases/tag/v4.14.3). 

There are functions in Response class that tries to access `transferStats` but there are not used in my cases. (like `effectiveUri`).

We have downgraded to `v4.14.2` and we are planning to upgrade to L9.50.

I can make PR if desired :)

Thank you!

### Steps To Reproduce

- use older version of laravel 9.24.0
- run http request via Laravel Client

**Comment by driesvints** [comment]
Thanks! I've sent in a fix for this: https://github.com/laravel/telescope/pull/1360
