### ISSUE TITLE
The Mix manifest does not exist error

### ISSUE THREAD

**Issue by ckissi** [laravel/telescope#136]
I'm using different directory structure for Laravel.

everything related to laravel except the public folder is located in the "laravel" folder so:

/laravel/app
/laravel/bootstrap
/laravel/config
.....
/public

I'm getting the following error:

`The Mix manifest does not exist. (View: /Users/crazyjack/Sites/test/laravel/vendor/laravel/telescope/resources/views/layout.blade.php)`

I've checked the mix-manifest.json  in public folder and its there with the following content:

```
{
    "/js/app.js": "/js/app.js",
    "/css/app.css": "/css/app.css",
    "/js/vendor.js": "/js/vendor.js",
    "/js/manifest.js": "/js/manifest.js"
}
```

**Comment by ForzaSFerrari** [comment]
Did you use this command `php artisan vendor:publish --tag=telescope-assets --force` ?

**Comment by ckissi** [comment]
Seems that command is necessary for update only but you gave me an idea and I've found assets in the original public folder under /laravel/ directory so I've just copied them to my public folder outside of "laravel" folder and it works now. Thanks!

**Comment by davidjtgriffiths** [comment]
I've got the same problem but copying across the assets doesn't fix it for me.
Any ideas?

**Comment by M165437** [comment]
Anyone having this problem, also try `echo "" | sudo -S service php7.1-fpm reload`. Solved it for me.

**Comment by Fenweldryn** [comment]
having the same issue.
Did npm install, then npm run dev. Did not solve.
Tried php artisan vendor:publish --tag=telescope-assets (also with --force), no help.

**Comment by vintprox** [comment]
IMO last longing option is to set `path.public` for whole application through provider. I found a cleaner solution [here](https://stackoverflow.com/a/47518119/2396907):
```
// app/Providers/AppServiceProvider.php

...
	public function boot()
	{
...
		$this->app->bind('path.public', function() {
			return base_path() . '/../xn--o1aat.xn--p1ai/forum';
		});
...
	}
...
```

**Comment by hackernewbie** [comment]
> IMO last longing option is to set `path.public` for whole application through provider. I found a cleaner solution [here](https://stackoverflow.com/a/47518119/2396907):
> 
> ```
> // app/Providers/AppServiceProvider.php
> 
> ...
> 	public function boot()
> 	{
> ...
> 		$this->app->bind('path.public', function() {
> 			return base_path() . '/../public';
> 		});
> ...
> 	}
> ...
> ```
> 
> `/../public` part is relative to laravel directory.
> 
> You can prettify this one with some environment variable (set via `.env`) to make it machine-agnostic.

This did the job for me!

**Comment by alkrauss48** [comment]
For those in a boat like me where you're trying to programatically install telescope in an environment where TELESCOPE_ENABLED=false must be true, the following helped solve this issue for me:
