### ISSUE TITLE
Bad Method Call

### ISSUE THREAD

**Issue by Rahulkannaujiya** [laravel/telescope#1365]
### Telescope Version

4.1.0

### Laravel Version

10.15.0

### PHP Version

8.2.4

### Description

BadMethodCallException
PHP 8.2.4
10.15.0
Method Illuminate\Foundation\Application::share does not exist.

please help me anyone related this issue 
please answer me  

### Steps To Reproduce

[error.txt](https://github.com/laravel/telescope/files/12169299/error.txt)
php artisan cache:clear

   BadMethodCallException 

  Method Illuminate\Foundation\Application::share does not exist.

  at vendor\laravel\framework\src\Illuminate\Macroable\Traits\Macroable.php:112 
    108▕      */
    109▕     public function __call($method, $parameters)
    110▕     {
    111▕         if (! static::hasMacro($method)) {
  ➜ 112▕             throw new BadMethodCallException(sprintf(
    113▕                 'Method %s::%s does not exist.', static::class, $method
    114▕             ));
    115▕         }
    116▕

  i   Bad Method Call: Did you mean Illuminate\Foundation\Application::isShared() ? 

  1   vendor\maatwebsite\excel\src\Maatwebsite\Excel\ExcelServiceProvider.php:154
      Illuminate\Foundation\Application::__call("share")

  2   vendor\maatwebsite\excel\src\Maatwebsite\Excel\ExcelServiceProvider.php:58
      Maatwebsite\Excel\ExcelServiceProvider::bindClasses()

**Comment by driesvints** [comment]
Seems this is related to the maatwebsite excel package. Please file an issue with them.
