### ISSUE TITLE
Laravel Telescope in localhost

### ISSUE THREAD

**Issue by HidayatLahabu** [laravel/telescope#1371]
I have tried Laravel Telescope for a Laravel project in local development. However, unfortunately, Laravel Telescope seems to only work when I activate the php artisan serve command. Is there a way to make it work using just the localhost? I am using Ubuntu 22.04 with Apache2 and MySQL for my development environment. Any assistance would be greatly appreciated. Thank you.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
