### ISSUE TITLE
NotificationWatcher formatNotifiable TypeError

### ISSUE THREAD

**Issue by yangjisen** [laravel/telescope#1372]
### Telescope Version

4.16.0

### Laravel Version

10.18.0

### PHP Version

8.1.4

### Database Driver & Version

8.0.27

### Description

```php
      $params = [[
            'title' => 'title',
            'text' => 'text',
        ]];

        Notification::send($params, new InvoicePaid($invoice));
```

TypeError: get_class(): Argument #1 ($object) must be of type object, array given

https://github.com/laravel/telescope/blob/b5def3d5c41cc2e9ffee2ddaa18462338833a01e/src/Watchers/NotificationWatcher.php#L67-L80

### Steps To Reproduce

Provide detailed steps to reproduce your issue. If necessary, please provide a GitHub repository to demonstrate your issue using laravel new bug-report --github="--public".

**Comment by nunomaduro** [comment]
Apologies - could you please recreate this issue with a more detailed description? I'm finding it difficult to grasp the issue as described here and how to reproduce it. Sorry!
