### ISSUE TITLE
NotificationWatcher formatNotifiable TypeError

### ISSUE THREAD

**Issue by yangjisen** [laravel/telescope#1375]
### Telescope Version

4.16.0

### Laravel Version

10.18.0

### PHP Version

8.1.4

### Database Driver & Version

8.0.27

### Description

When the incoming $notifiable is an array, the error is: NotificationWatcher formatNotifiable TypeError

https://github.com/laravel/telescope/blob/b5def3d5c41cc2e9ffee2ddaa18462338833a01e/src/Watchers/NotificationWatcher.php#L67-L80

Should an is_array($notifiable) be added before return get_class($notifiable) in the formatNotifiable method?

### Steps To Reproduce

step1: Generating Notifications ``` php artisan make:notification InvoicePaid ```
step2: Using The Notification Facade
```
	$notifiables = [[
		'title' => 'title',
		'text' => 'text',
	]];

	Notification::send($notifiables, new InvoicePaid($invoice));
```

Now use the facade to send messages, and when the incoming parameter $notifiables is an array, the class  ``` NotificationWatcher ``` on method ``` formatNotifiable ``` of the telescope will report an error: "NotificationWatcher formatNotifiable TypeError" when checking the type because $notifiables is not a class but an array, using get_class($notifiable)

**Comment by driesvints** [comment]
I'm not sure what the proper solution here is but would appreciate a PR if you can figure something out, thanks!

**Comment by yangjisen** [comment]
> I'm not sure what the proper solution here is but would appreciate a PR if you can figure something out, thanks!

I made the instanceof judgment, I think we should add some other type judgment, View the Notification facade * @method static void send(\Illuminate\Support\Collection|array|mixed $notifiables, mixed $notification) Supported type, I'm not sure what type formatNotifiable should return in array, but is it now a string

**Comment by driesvints** [comment]
Hi there, right now we don't document the usage of notifications like this. Therefor, I don't think we can consider this as supported, sorry. Please use regular class based notifications, thanks.
