### ISSUE TITLE
there are Tens of thousands pending jobs

### ISSUE THREAD

**Issue by winter-ice** [laravel/telescope#1377]
### Telescope Version

4.16.1

### Laravel Version

10.19.0

### PHP Version

8.2

### Database Driver & Version

MySQL 8.0

### Description

https://github.com/laravel/telescope/commit/9bbfc8f32fc26e2af85e1130ecde6a85859efa4d

I think this PR made new bugs, after updated Telescope, there are Tens of thousands `Laravel\Telescope\Jobs\ProcessPendingUpdates` jobs shows in my `Horizon` panel

### Steps To Reproduce

I'm a rookie, I don't know how to reporduce it.

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
