### ISSUE TITLE
Should not assume User is an Eloquent model

### ISSUE THREAD

**Issue by gjm** [laravel/telescope#138]
In the `IncomingEntry` class Telescope assumes `$user` is an Eloquent model as it calls the `getKey()` method. In my case that is not true and i had to implement a dummy `getKey()` model to make it work.

As i see it, instead of `getKey()`, it should call `getAuthIdentifier()` from the `Authenticatable` contract. That would make more sense as Laravel's auth mechanism relies on this contract.

**Comment by themsaid** [comment]
fixed that, thanks.
