### ISSUE TITLE
Support for Percona XtraDB Cluster with Strict Mode Enabled

### ISSUE THREAD

**Issue by philipkozeny** [laravel/telescope#1380]
[Percona XtraDB Cluster](https://www.percona.com/software/mysql-database/percona-xtradb-cluster) is a widely-used MySQL Galera Cluster solution, recommended for production environments. When operating in its recommended [strict mode](https://docs.percona.com/percona-xtradb-cluster/8.0/strict-mode.html) for production use, the cluster mandates that all tables must have an explicit primary key.

While attempting to run Telescope on a Percona XtraDB Cluster with strict mode enabled, the following error occurs:

```sql 
SQLSTATE[HY000]: General error: 1105 Percona-XtraDB-Cluster prohibits use of DML command on a table (citizen.telescope_entries_tags) without an explicit primary key with pxc_strict_mode = ENFORCING or MASTER (Connection: mysql, SQL: insert into `telescope_entries_tags` (`entry_uuid`, `tag`) values (9a031faf-ad80-454a-9535-4222cc3658e8, slow))
```

**Comment by driesvints** [comment]
I'm sorry but I don't think we can account for this edge case. Since we only have one report so far and the ticket has been open for a while I'm going to close this one.

**Comment by driesvints** [comment]
I'm sorry but no. We are open to PRs however.
