### ISSUE TITLE
Logo Size

### ISSUE THREAD

**Issue by Paulo-Teodoro** [laravel/telescope#1388]
### Telescope Version

4.16.4

### Laravel Version

10.25.0

### PHP Version

8.2

### Description

Logo doesnt apply size.
The <a> element of router-link is not visible in the svg logo.
The icons are not updating as expected.

![logo](https://github.com/laravel/telescope/assets/67804745/dc6f5fad-28b2-4691-be98-bba6dd941024)
![code](https://github.com/laravel/telescope/assets/67804745/15b8d0f3-555f-4acd-a0c0-f39261b942c9)

I've attempted to resolve this by removing telescope and reinstalling without cache
`composer remove laravel/telescope`
`composer require laravel/telescope --no-cache`

Running the telescope commands:
`php artisan telescope:install`
`php artisan telescope:publish`
`php artisan view:cache`

While this approach works with a fresh Laravel installation, it's causing issues with existing projects in production that require an upgrade.

#1297 #1313 with the same problem.

### Steps To Reproduce

Attempt to upgrade a production project with a different version of Telescope:

`composer update laravel/telescope`
`php artisan telescope:publish`
`php artisan view:cache`

**Comment by driesvints** [comment]
This has been reported many times already but without a clear way to reproduce. Right now we don’t believe there’s a big issue here sorry.
