### ISSUE TITLE
Allow ProcessPendingUpdates to be queued on something different than 'default'

### ISSUE THREAD

**Issue by NeurohrByteS** [laravel/telescope#1392]
Currently ProcessPendingUpdates is always queued to the 'default' queue. 
https://github.com/laravel/telescope/blob/3a250a44faa89ba4790ad6207060e90f79f49d1e/src/Telescope.php#L673

It would be great if if this could be configured similar to Scout.
https://laravel.com/docs/10.x/scout#queueing

**Comment by NeurohrByteS** [comment]
Thank you for this great library!

**Comment by driesvints** [comment]
If you could send in a PR we could have a look maybe 👍 

> Thank you for this great library!

Thanks!

**Comment by NeurohrByteS** [comment]
@driesvints As requested: https://github.com/laravel/telescope/pull/1393
