### ISSUE TITLE
Ignore Telescope's own requests

### ISSUE THREAD

**Issue by Fossil01** [laravel/telescope#1398]
### Telescope Version

4.16

### Laravel Version

10

### PHP Version

8.2

### Database Driver & Version

MariaDB 10.10.6

### Description

Ignoring paths in Telescope does not seem to work properly. Or I am doing something wrong.

Whenever I check the Requests page it's littered with requests belonging to Telescope itself every second or so: https://share.cleanshot.com/89qrjwCf

In telescope.php I have tried this but it doesn't do anything:

```php
    'ignore_paths' => [
        'nova-api*',
        '*telescope*',
    ],
```

Any way of achieving this? It's very hard to debug things now since the request keeps getting pushed down in the list every second.

### Steps To Reproduce

```php
    'ignore_paths' => [
        'nova-api*',
        '*telescope*',
    ],
```

**Comment by crynobone** [comment]
Shouldn't it suppose to be `telescope*`?

**Comment by crynobone** [comment]
Hey there,

While this may be a legitimate issue, can you first try posting your problem or question on one of the support channels below? If this issue can be definitively identified as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
