### ISSUE TITLE
 PHP version

### ISSUE THREAD

**Issue by lstables** [laravel/telescope#14]
`[InvalidArgumentException]
  Package laravel/telescope at version  has a PHP requirement incompatible with your PHP version (7.1.14)`

I have PHP 7.1.14 installed using Valet

**Comment by Francismori7** [comment]
7.2+ required.

**Comment by taylorotwell** [comment]
Right now it requires 7.2. although I'm not 100% sure if we are using a 7.2. only feature. Would need to research in the code base.

**Comment by lstables** [comment]
Thanks, maybe the docs need that adding then

**Comment by svenluijten** [comment]
@lstables it's already in [the `composer.json`](https://github.com/laravel/telescope/blob/1.0/composer.json#L21), so you shouldn't even be able to install the package if you're using anything below PHP 7.2.

**Comment by lstables** [comment]
Fair play, I'll upgrade my PHP version later and try again, thanks all :)
