### ISSUE TITLE
Feature: Request Watcher - Add posibility to limit size of view data in response

### ISSUE THREAD

**Issue by milanchymcak** [laravel/telescope#1408]
In the method [**response**](https://github.com/laravel/telescope/blob/4.x/src/Watchers/RequestWatcher.php#L178) inside the Request Watcher, we can limit the size of response by the option size_limit with the use of contentWithinLimits. But that doesn't apply to the view data 

```php
if ($response instanceof IlluminateResponse && $response->getOriginalContent() instanceof View) {
            return [
                'view' => $response->getOriginalContent()->getPath(),
                'data' => $this->extractDataFromView($response->getOriginalContent()),
            ];
        }
```

Will be very helpful if we can use size_limit option or any similar also to the view data. Currently you have to do custom filter inside TelescopeServiceProvider.

**Comment by driesvints** [comment]
Heya, if you could send in a PR then we could look at the code that would make this work. Thanks
