### ISSUE TITLE
Recording automatically resumed after 30 days

### ISSUE THREAD

**Issue by FrancisMawn** [laravel/telescope#1412]
Hi, looking at the pause/resume commands, I noticed that the current behavior will automatically resume the recording after 30 days?

```php
$cache->put('telescope:pause-recording', true, now()->addDays(30));
```

We were looking into using Telescope in a production environment but we would like to have the ability to pause the recording indefinitely so that we only record when necessary.

What was the reasoning behind the 30 days reset and would you guys be opened to make this behavior configurable through an environment variable?

**Comment by driesvints** [comment]
Not yet no. But feel free to attempt a PR 👍 I don't think there's a specific reasoning.

**Comment by FrancisMawn** [comment]
Since the proposed PR was denied, I came up with a dirty workaround. So for those of you looking for a solution here's what I ended up doing:

```php
$schedule
    ->command('telescope:pause')
    ->when(fn () => Cache::get('telescope:pause-recording'))
    ->daily();
```

I scheduled a daily job that re-runs the pause command which essentially reset the cache expiry when Telescope is paused.
