### ISSUE TITLE
Possible Features

### ISSUE THREAD

**Issue by kingeke** [laravel/telescope#1416]
I love telescope!

Here are some features that would be amazing if implemented.

- **Multi filter option**: It'll be a nice feature if we can add more filter queries, like I want to view this authenticated user's request for these certain tags i have or specific routes only, currently we just see all the routes they visited, if we can narrow it down to a specific route for a specific user, and if we can then view next and previous (x) amount of requests from this particular request.
- **Frontend Pagination limit**: If we can increase the pagination limit via the frontend, that'll also help get more requests faster, or we add it as a query param which can be passed at will.

**Comment by driesvints** [comment]
Hi there @kingeke. With features like this, it all depends on the complexity involved. If we could look at a PR we could consider these so feel free to attempt those, thanks.
