### ISSUE TITLE
Consider .env variable APP_URL to requests

### ISSUE THREAD

**Issue by filipedtristao** [laravel/telescope#142]
The application is considering the absolute host as a way to process requests.

For example, in my environment I have the application running on http://localhost/api address, however all requests are made directly to the http://localhost, ignoring the /api that is where my application is.

I have the variable APP_URL pointing to the correct location in my .env, but it does not seem to be used in the telescope.

**Comment by enimiste** [comment]
I think this PR https://github.com/laravel/telescope/pull/94 would fix this issue.

**Comment by marcosfreitas** [comment]
I'm with this issue too.

**Comment by filipedtristao** [comment]
> I think this PR #94 would fix this issue. But not accepted by maintainers.

I don't think so.  In your PR, there is only modifying in a part of the VUE code, but the problem that occurs in my application is general, including in the blade template that loads the JS and CSS codes.

![image](https://user-images.githubusercontent.com/10791793/47470451-31052d80-d7dc-11e8-9c3d-0552272d89f7.png)

**Comment by marcosfreitas** [comment]
@filipedtristao I ignored this problem rewriting the base of Vue request. Well, isn't the best solution but if you like me, want to use, it could resolve while an update appears. 
In the code below **/app** is my laravel base path.
location ^~ /telescope {
        rewrite /telescope/(.*)$ /app/telescope/$1 last;
}

location ^~ /vendor {
        rewrite /vendor/(.*)$ /app/vendor/$1 last;
}

**Comment by filipedtristao** [comment]
@marcosfreitas Good workaround!

However my project runs on apache, so I had to adapt the rule to my environment.

My .htaccess looks like this, where **api-eloverde:** is my laravel base path.

`Options -Indexes

<IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews
    </IfModule>

    RewriteEngine On

	RewriteCond %{REQUEST_URI} (^/telescope)
	RewriteRule ^(.*)$ /api-eloverde/$1?&%{QUERY_STRING} 
	
	RewriteCond %{REQUEST_URI} (^/vendor)
	RewriteRule ^(.*)$ /api-eloverde/$1?&%{QUERY_STRING} [R=301,L,QSA]
	
</IfModule>`

**Comment by themsaid** [comment]
Don't run laravel in a subdirectory. Workaround exist, but we won't be concerned about it in our official packages. Sorry guys.
