### ISSUE TITLE
Hide sensitive information from job details

### ISSUE THREAD

**Issue by FrancisMawn** [laravel/telescope#1422]
Hi, 

I don't know if I'm missing something but Telescope offers the option to obfuscate data for both incoming and out going requests but I don't see any option for data passed to a queued job as parameters... ?

So for example, I want to dispatch a job to create an account asynchronously. The password is hidden from the request payload but looking at the job details, I can see the password in clear text.

**Comment by driesvints** [comment]
Hi @FrancisMawn. This isn't currently possible indeed. But if you want to send in a PR we could have a look at it and what it would meant to get that in. Thanks

**Comment by driesvints** [comment]
Also: more likely it's better to hash/encrypt those values before you send it to your job.

**Comment by FrancisMawn** [comment]
> Also: more likely it's better to hash/encrypt those values before you send it to your job.

Yeah, this is precisely what I was looking into in the meantime...
