### ISSUE TITLE
Load Older Entries not working on Jobs page sometimes

### ISSUE THREAD

**Issue by 9x3l6** [laravel/telescope#1423]
### Telescope Version

4.17.3

### Laravel Version

10.38.2

### PHP Version

8.2.14

### Database Driver & Version

Postgresql

### Description

Sometimes it works, loads a page or few pages, and then a lot of the time it doesn't load any more and gives error. This happens on the Jobs page `/telescope/jobs`

```
app.js?id=613c227dfb4d6e1fc4db1b1a90513610:2 Uncaught TypeError: Cannot read properties of undefined (reading 'content')
    at app.js?id=613c227dfb4d6e1fc4db1b1a90513610:2:567736
    at Be (app.js?id=613c227dfb4d6e1fc4db1b1a90513610:2:320015)
    at Pn.filter (app.js?id=613c227dfb4d6e1fc4db1b1a90513610:2:365680)
    at i (app.js?id=613c227dfb4d6e1fc4db1b1a90513610:2:382248)
    at Ab (app.js?id=613c227dfb4d6e1fc4db1b1a90513610:2:354357)
    at app.js?id=613c227dfb4d6e1fc4db1b1a90513610:2:340110
    at xe (app.js?id=613c227dfb4d6e1fc4db1b1a90513610:2:320452)
    at lp (app.js?id=613c227dfb4d6e1fc4db1b1a90513610:2:340076)
    at Fn.value (app.js?id=613c227dfb4d6e1fc4db1b1a90513610:2:383977)
    at lp (app.js?id=613c227dfb4d6e1fc4db1b1a90513610:2:340067)
```

<img width="1437" alt="Screen Shot 2023-12-26 at 5 28 56 AM" src="https://github.com/laravel/telescope/assets/113054034/984136a8-7759-4b3d-b559-4c6d55809542">

### Steps To Reproduce

Navigate to `Jobs` screen and click Load Older Entries until it doesn't work and check browser console to see error message. Should.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by rmilesson** [comment]
I'm having the same issue although I'm running Laravel 12 and Telescope 5.6.0. The exception occurs at the same location. I press "Load Older Entries", wait a few seconds and then the crash occurs. I can no longer press "Load Older Entries" after a crash has occurred.
