### ISSUE TITLE
Ability to delete data by data type

### ISSUE THREAD

**Issue by leonardofilhogm** [laravel/telescope#1436]
Hello, 
It will be very helpful if we have the capability to choose if we want to delete the whole telescope data or simply or specific tabs (like logs). 

Sometimes i want to keep exceptions on the list while i need to erase logs that become too big.

**Comment by leonardofilhogm** [comment]
I you believe this can be helpful, i can work on it and send a PR.

**Comment by driesvints** [comment]
Heya. Everything depends on the complexity of the PR. Feel free to send it in so we can have a look. Thanks!
