### ISSUE TITLE
Redirect Back to Application Dashboard/Homepage

### ISSUE THREAD

**Issue by zarulizham** [laravel/telescope#1440]
Hi, I believe clicking on the "Laravel Telescope" does the same thing with "Requests" navigation. It is nicer if we have options to redirect back to application dashboard/homepage when click "Laravel Telescope" on the top left.

<img width="392" alt="image" src="https://github.com/laravel/telescope/assets/10229855/506854e6-d497-4814-ade5-bc8c9bb736d7">

**Comment by driesvints** [comment]
No plans for that right now sorry.
