### ISSUE TITLE
[Feature Request] Set timezone for IncomingEntry recorded_at

### ISSUE THREAD

**Issue by WEDeach** [laravel/telescope#1441]
This issue is similar to #330
---
If a server contains multiple time zones, the recorded time will be inconsistent.
Is it possible to add a config to specify the default recording time zone?

---
As a temporary solution, I modified the code here
https://github.com/laravel/telescope/blob/1f47307083d48aa2b8b4caef934609b555c8173e/src/IncomingEntry.php#L77

```php
 $this->recordedAt = now(config('app.timezone')); 
```

Thank you for your consideration

**Comment by driesvints** [comment]
This won't work if the data is also read out at different servers. We suggest to not use the same Telescope setup if you use different timezones on different servers. Ideally the servers have the same timezone.
