### ISSUE TITLE
Call to undefined method Laravel\Telescope\Telescope::ignoreMigrations()

### ISSUE THREAD

**Issue by binaryfire** [laravel/telescope#1442]
### Telescope Version

5.0

### Laravel Version

10.3.3

### PHP Version

8.3

### Database Driver & Version

MySQL 8

### Description

Hi guys. I just updated to v5 and the `ignoreMigrations()` method is gone. Is that a bug or was that an intentional change? Is there a new alternative?

### Steps To Reproduce

N/A

**Comment by crynobone** [comment]
See https://github.com/laravel/telescope/blob/5.x/UPGRADE.md
