### ISSUE TITLE
Migration file is being published with a new timestamp everytime 

### ISSUE THREAD

**Issue by ziarv** [laravel/telescope#1443]
### Telescope Version

5.0.0

### Laravel Version

11.0.6

### PHP Version

8.3.3

### Database Driver & Version

mysql 8.0

### Description

the command publishes a new migration file every time we run `php artisan vendor:publish --tag telescope-migrations`. this causes table already exist error 

### Steps To Reproduce

Fresh Installation of laravel 11. 
and then install the telescope

**Comment by driesvints** [comment]
@ziarv you usually only run this once when installing telescope install. The timestamp changing is a new feature of Laravel to keep these recent.

**Comment by ziarv** [comment]
@driesvints  Thank you for your reply but I found a solution there is config for that update_date_on_publish
