### ISSUE TITLE
Allowed memory size exhausted

### ISSUE THREAD

**Issue by vatsake** [laravel/telescope#1458]
### Telescope Version

5.0

### Laravel Version

11.0

### PHP Version

8.2

### Description

```
Allowed memory size of 268435456 bytes exhausted (tried to allocate 2097160 bytes)
in /var/www/vendor/laravel/telescope/src/Telescope.php line 329
```

What could be the issue here? Wasn't using telescope at the time.

### Steps To Reproduce

No idea

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
