### ISSUE TITLE
Ability to set queue for ProcessPendingUpdates

### ISSUE THREAD

**Issue by ZacharyDuBois** [laravel/telescope#1459]
It would be nice to be able to specify the queue that the `ProcessPendingUpdates` job would be pushed to.

Something like just another static setter like `Telescope::useQueue('low');` into the `TelescopeServiceProvider`.

Issue I am running into is a job batch that could dispatch a few thousand jobs but these keep mixing themselves in causing it to run slower than it would. Since Telescope is a debug tool, it shouldn't impact the performance of what is happening elsewhere (at least IMO).

I might be able to contribute something this weekend.

**Comment by driesvints** [comment]
Hi @ZacharyDuBois. Could you attempt a PR? Then Taylor can review it and see if we can get this in. Thanks!

**Comment by ZacharyDuBois** [comment]
Sure, hopefully I can find some time this weekend to do it. Sadly my employer won't allow me to contribute during the work day.
