### ISSUE TITLE
Manifest.json cause 404 error if file in resources is missing

### ISSUE THREAD

**Issue by nathanaelytj** [laravel/telescope#1463]
### Telescope Version

5.0.2

### Laravel Version

11.4.0

### PHP Version

8.3.4

### Description

When telescope updated dashboard won't open with error like:
`GET http://localhost:5173/resources/sass/styles.scss net::ERR_ABORTED 404 (Not Found)`
`GET http://localhost:5173/resources/js/app.js net::ERR_ABORTED 404 (Not Found)`

This issue seem to be the same issue as laravel/horizon#1416
After reading commit history, this file seems to be the culprit too: `public/build/manifest.json`

### Steps To Reproduce

1. Create new laravel project
2. Install telescope
3. Remove or rename file `resources/js/app.js` and `resources/sass/styles.scss`
4. Open telescope dashboard and this issue will happen

**Comment by driesvints** [comment]
Did you publish the new assets like: https://github.com/laravel/laravel/blob/11.x/composer.json#L39

```
php artisan vendor:publish --tag=laravel-assets --ansi --force
```

**Comment by driesvints** [comment]
Reverted
