### ISSUE TITLE
Avatars are not being displayed in request details

### ISSUE THREAD

**Issue by roger-hermasch** [laravel/telescope#1471]
### Telescope Version

5.x

### Laravel Version

11.x

### PHP Version

8.3

### Database Driver & Version

MySQL on MacOS (silicon)

### Description

Is the Telescope::Avatar functionality still available? It is still the last entry in the official docu (like it has always been for the last couple versions) but my team noticed aren't being displayed anymore. We have a custom function for avatars which is correctly returning the avatar paths in the request->user (opening the avatar link in a new tab works) but it is not being displayed in the telescope web interface. Resetting the function to use Gravatar didn't help either.

Not an important feature but really nice to have and always appreciated :) Thanks for the help!

![grafik](https://github.com/laravel/telescope/assets/55159268/771681ad-bbc8-48b9-b5a5-ded5d2cce660)
![grafik](https://github.com/laravel/telescope/assets/55159268/a107fe4b-3b29-46ca-91cd-aaf68712579b)

### Steps To Reproduce

install laravel, install telescope, create simple request with authenticated user which has a profile image --> no avatar in telescope visible

**Comment by driesvints** [comment]
Hi yes but this also requires a name. It seems your user doesn't have a name?

**Comment by roger-hermasch** [comment]
Sorry if this is too noob - how do I add the name? I have it stored in my database but how can I add it to each request?

**Comment by driesvints** [comment]
It's the `name` property of your user.

**Comment by roger-hermasch** [comment]
Makes sense - **thank you**! Just in case that anyone stumbles upon this:

I added the following code to my User.php model:
```
public function getNameAttribute(): string {
        return trim($this->first_name . ' ' . $this->last_name);
}
```
