### ISSUE TITLE
5.0.3 upgrade app.js SHA-384 integrity issue

### ISSUE THREAD

**Issue by thecankaya** [laravel/telescope#1473]
### Telescope Version

5.0.3

### Laravel Version

11.4.0

### PHP Version

8.2.17

### Database Driver & Version

11.3.2

### Description

Im having below issue after upgrade. Tried cache delete, dump and dumpautoload same in development and production environment.

`Failed to find a valid digest in the 'integrity' attribute for resource 'https://domain/vendor/telescope/app.js' with computed SHA-384 integrity 'qfBKay8U8etFG6p/gU88kGhWOAl5Q6mjmH9nRBzpvim7DO34aaghuKhyypx2nPyo'. The resource has been blocked.`

### Steps To Reproduce

composer update

**Comment by driesvints** [comment]
I don't have the same issue when I upgrade Telescope to the latest version. Please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb) or [InertiaJS Discord](https://discord.gg/inertiajs) for Inertia questions
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)
