### ISSUE TITLE
Preventing migrations from running in Production

### ISSUE THREAD

**Issue by Rydgel** [laravel/telescope#1476]
I'm upgrading from v4 to v5, and it is said that:

> Telescope 5.0 no longer automatically loads migrations from its own migrations directory. Instead, you should run the following command to publish Telescope's migrations to your application:

I'm currently using the local only install like this:

```php
public function register(): void
{
    if ($this->app->environment('local')) {
        $this->app->register(\Laravel\Telescope\TelescopeServiceProvider::class);
        $this->app->register(TelescopeServiceProvider::class);
    }
}
```

If I understand correctly, I am now forced to publish the migrations.
That would make them run on production after a deploy, is there a way around it?

**Comment by driesvints** [comment]
Heya, not at this time I'm afraid. But the above will still prevent Telescope from running in your app on production. Only the migrations will be run.

**Comment by Rydgel** [comment]
thanks for the quick response

**Comment by BobbyBorisov** [comment]
@Rydgel hey what did you end up doing?
