### ISSUE TITLE
SVG icons not loading

### ISSUE THREAD

**Issue by ElvisIsKing666** [laravel/telescope#1480]
### Telescope Version

4.17.6

### Laravel Version

10.38

### PHP Version

8.3.4

### Description

On my local machine running valet, the SVG icons load and work. On my remote machine running a dockerizer setup that SVG icons do not load. 

Also, it appears that the JS element listeners on the Commands, Requests, Logs, etc <span> elements aren't running properly. Initially, I can click on new nav items and the page reloads instantly. But if I click on one that is enabled but the XHR returns an empty list - then the automatic page reloading breaks: when I click on a new nav-item it doesn't automatically load that page - the URL changes, but the XHR fetch for the previous command keeps running until I hit reload. Once I hit reload I can click new nav items until I click one that returns zero items and it breaks again.

The CSS and JS assets are loaded. 

I'm wondering what could be causing that. 

Local machine:
<img width="266" alt="image" src="https://github.com/laravel/telescope/assets/166011086/7f52113a-8c53-4930-93ea-4990f3ba2751">

Remote machine:
<img width="381" alt="image" src="https://github.com/laravel/telescope/assets/166011086/b8ae1eb9-1a5a-40c2-bc48-922fd73149b1">

### Steps To Reproduce

I'm guessing there is something in my specific setup that is interfering - so it's not easy to reproduce. I'm wondering if anyone has an idea how to begin debugging this.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb) or [InertiaJS Discord](https://discord.gg/inertiajs) for Inertia questions
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
