### ISSUE TITLE
Telescope Query Watcher causes new model to have id = 0

### ISSUE THREAD

**Issue by altin-berisha** [laravel/telescope#1482]
### Telescope Version

3.1

### Laravel Version

8.83.27

### PHP Version

8.2.1

### Description

When trying to create a new item on a specific model i'm encountering an issue when i hardcode one of the foreign keys
In my case i have 3 tables, organisations, users and schedules.
User model has a "hasMany" relationship with the Schedule model.

### Steps To Reproduce

In my case 
this is the code to reproduce the error :
`        
$schedule = user()->schedules()->create([
            'organisation_id' => 1,
            'name' => $this->form['name'],
        ]);
dd($schedule)
`
dd results that $schedule has an id = 0

changing the code to 
`
$schedule = user()->schedules()->create([
            'organisation_id' => Organisation::find(1)->id,
            'name' => $this->form['name'],
        ]);
`

also setting TELESCOPE_QUERY_WATCHER to false fixes this.

**Comment by crynobone** [comment]
Hey there,

Unfortunately we don't support this version of the library anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
