### ISSUE TITLE
Batch index view is not searchable

### ISSUE THREAD

**Issue by FrancisMawn** [laravel/telescope#1490]
Hi,

I'm curious to know why the Batch index view does not include the search tag input?

**telescope/resources/js/screens/batches/index.vue**
```js
<index-screen title="Batches" resource="batches" hide-search="true">
```

I can manually set the tag attribute in the querystring but it's a bit inconvenient. Could we enable tag search on this view like most other views?

**Comment by driesvints** [comment]
Hey @FrancisMawn. If you believe it would be beneficial here then we'd appreciate a PR and we could maybe give that a go?
