### ISSUE TITLE
Export Telescope Data

### ISSUE THREAD

**Issue by skdishansachin** [laravel/telescope#1492]
### Summary

Telescope is a great tool for monitoring and debugging Laravel applications. However, it cannot export specific data, which can be a limitation in certain scenarios. It would be cool if they added the ability to export data in CSV or JSON formats.

### Problem Statement
I came across a scenario while using Telescope to monitor an application, where I required specific request data. Since Telescope doesn't provide a way to export this data, I had to retrieve it directly from the database tables instead. It's not ideal to keep all Telescope monitoring data because it can grow huge. Although the prune option is there, it deletes all data, which may not always be suitable for specific requirements.

### Proposed Solution
Introduce data export functionality in Telescope with the capabilities like :

- **Export Options:** Allow exporting data in CSV and JSON formats.
- **Filter-Based Export:** Enable exporting data based on specific filters, such as requests, exceptions, or queries.
- **Date Range Export:** Allow users to specify a date range for the data export.
- **Entity-Specific Export:** Provide options to export data for specific entities within a filter.
- **General Export:** Implement a general export option for overall data.

Thank you!

**Comment by driesvints** [comment]
Thank you for your request. Right now we don't have plans to add this unfortunately. Should we get more requests for this we might consider the acceptation of a PR.
