### ISSUE TITLE
If processing data in a custom command requires querying and operating the database 1000000+ times, Telescope will cause memory overflow

### ISSUE THREAD

**Issue by laterz** [laravel/telescope#1494]
### Telescope Version

5.1.1

### Laravel Version

11.0

### PHP Version

8.2

### Database Driver & Version

8.0

### Description

I have a task that requires querying and operating the database multiple times in the console's database Chunk. If Telescope is turned on, the program will exceed its memory limit and be terminated after running for a while.

In addition to database operations, it is estimated that other watchers may also exceed memory limits if the data volume is large.

Can records be written to the database at a certain amount? Now it seems that the program must be in memory before it can be executed and only written to the database after it is completed

### Steps To Reproduce

see the Description

**Comment by driesvints** [comment]
I don't think we can consider 1000000+ database operations a realistic use case sorry. I believe this is something you should handle in your own code and adapt it to not do that many DB operations in one go. Telescope was not designed to handle this.
