### ISSUE TITLE
Pass event instance to event listeners tag() method

### ISSUE THREAD

**Issue by tonybolzan** [laravel/telescope#1497]
### Telescope Version

5.1.1

### Laravel Version

any

### PHP Version

any

### Database Driver & Version

any

### Description

In Laravel Horizon v5.21.5 - 2023-12-29 - It was possible to add the event to the TAG constructor, but Telescope does not support this method signature.

- https://github.com/laravel/horizon/pull/1361

### Steps To Reproduce

Add `public function tags(MyEvent $event)` to a Listener

**Comment by driesvints** [comment]
Not sure about this one. Welcoming PR's for the thing that you want to achieve 👍

**Comment by tonybolzan** [comment]
Why not?
Laravel Telescope are incompatibilize with Laravel Horizon.

If I add that parameter to `tags` that work in Horizon, the Job fail if Telescope was active, and works if Telescope are disabled, this is because Telescope use the same function for Horizon in a diferent way.

If this project is imcompatible with Horizon, please update the documentation?

**Comment by tonybolzan** [comment]
The error occur on [ExtractTags.php#L102](https://github.com/laravel/telescope/blob/5.x/src/ExtractTags.php#L102)
```
Too few arguments to function #::tags(), 0 passed on line 1 and exactly 1 expected
```
Because it is no longer compatible with Horizon [Tags.php#L84](https://github.com/laravel/horizon/blob/5.x/src/Tags.php#L84) after [PR1361](https://github.com/laravel/horizon/pull/1361)
