### ISSUE TITLE
Add time filter to queries.

### ISSUE THREAD

**Issue by RoboteriaAntigua** [laravel/telescope#1500]
Add a time filter to queries that allows selecting between which hour and which hour. For example: all queries between 5:00 PM and 5:15 PM.

**Comment by driesvints** [comment]
Feel free to attempt a PR for anything you'd like to get into Telescope 👍

**Comment by RoboteriaAntigua** [comment]
thanks, sure i do

**Comment by vatsake** [comment]
@RoboteriaAntigua Did you make a PR?
