### ISSUE TITLE
Telescope Should have a Theme Toggle Button

### ISSUE THREAD

**Issue by hadees-ahmed** [laravel/telescope#1504]
**Issue Description:**
In our development team, we've run into an issue with the way themes are handled in our project. Some developers prefer a light theme, while others prefer a dark theme. However, the current setup only allows us to set one theme on the development branch. This means that if a developer doesn't like the theme that’s currently set, they have to manually switch it every time they work on the project, which gets pretty annoying.

This is frustrating for a lot of us because we have to constantly change the theme back and forth while working. It’s a small thing, but it adds up, especially when you're trying to focus on coding.

**Proposed Solution:**
To solve this, I decided to add a theme toggle button directly in the UI. This button lets each developer choose between light and dark themes based on what they prefer. The choice is saved in the browser, so it sticks even after you close and reopen the project.

As I was building this for our own project, I realized this might be a useful feature for others too, so I thought it would be worth contributing to Laravel Telescope.

**What I Did:**
Added a Button: The button is easy to use and lets you switch between light and dark themes instantly.
Stored the Preference: The theme preference that user will pick will be saved as boolean value in the browser’s local storage, so it’s applied every time user open Telescope even after restarting its browser.

In Dark Mode UI will look Like:
![Screenshot from 2024-08-17 14-40-51](https://github.com/user-attachments/assets/131869fe-00ef-4dd4-9716-e5570cada727)

In Light Mode UI will look Like:
![Screenshot from 2024-08-17 14-45-17](https://github.com/user-attachments/assets/12576fe0-c643-4796-96e1-40a0d948b780)

Default Theme: The button respects whatever default theme is set by the project but lets users change it if they want.

**Why I'm Raising This Issue:**
Before I submit a pull request, I wanted to get feedback from the Laravel team and community. I think this feature could help other developers who are facing the same issue and make working with Telescope a bit more comfortable for everyone. I'd love to hear what you think about this idea. @taylorotwell @driesvints 

Looking forward to your thoughts!

**Comment by driesvints** [comment]
Thanks. Feel free to attempt a PR with whatever you want to add 👍
