### ISSUE TITLE
Telescope Jobs Stuck in Pending Status

### ISSUE THREAD

**Issue by Active-Class** [laravel/telescope#1512]
### Telescope Version

5.2.2

### Laravel Version

10.46

### PHP Version

8.3

### Database Driver & Version

MySQL 8 AWS Aurora 

### Description

When we schedule jobs (`PushNotificationJob`, see below) to run every 5 seconds, majority of the jobs displayed in Telescope remain stuck in the `Pending` status. Please see the screenshot below:

![bmZCk64U](https://github.com/user-attachments/assets/676cfa5a-d7c1-4595-a002-7a8716d8522a)

As shown, there are multiple jobs with the `Pending` status. This screenshot is from a local machine, but the same issue occurs on our server, where all jobs also get stuck in `Pending`.

![image](https://github.com/user-attachments/assets/602cc375-3ab0-49e2-9081-e92b14270454)

This is the code:

```
class Kernel extends ConsoleKernel
{
    protected function schedule(Schedule $schedule)
    {
        $schedule->job(new PushNotificationJob)->everyFiveSeconds();

        $schedule->job(new CheckClassStartedService)->everyMinute();

        $interval = DB::table('settings')->where('key', 'interval')?->value ?? 5;
        $schedule->job(new FirebaseWakeupNotificationService)->cron(StringHelper::cron24($interval));
    }
}
```

Based on the logs and database changes, we know the jobs are executing correctly. However, Telescope does not update the status to `Processed`. Execution of each job takes less than a second.

Our setup includes a Vapor serverless architecture with SQS on AWS.

When we change the frequency of `PushNotificationJob` to run every minute, the problem is resolved.

Any suggestions or solutions? Please let me know if I should provide any further information.

### Steps To Reproduce

No particular instructions.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb) or [InertiaJS Discord](https://discord.gg/inertiajs) for Inertia questions
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by Active-Class** [comment]
Thanks @driesvints for your comment. But I think it is a bug. That is why I've posted my message here. I've also posted it on [StackOverflow](https://stackoverflow.com/questions/78924147/telescope-jobs-stuck-in-pending-status) with no luck.
