### ISSUE TITLE
Soap Request and Response are empty in client-requests Payload and response

### ISSUE THREAD

**Issue by GaneshKandu** [laravel/telescope#1520]
### Telescope Version

^5.0

### Laravel Version

^10.8

### PHP Version

8.2.0

### Description

I am making this soap request, its successful but i am getting empty data in poyload and response

Payload section

```
[
]
```

Response section

```
HTML Response
```
My php code

```php
		$response = Http::withHeaders([
			'Content-Type' => 'application/xml',
			'Ocp-Apim-Subscription-Key' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
		])
		->withBody(
			view('rgi.asia.quote',compact(
				'travel_start_date',
				'travel_end_date'
			))->render()
			,'text/xml'
		)
		->post('http://domain.com/api')->body();

               dd($response);
```

Please check and fix

### Steps To Reproduce

install laravel
install telescope
write code for soap request
make soap request
check request and response in your soap

**Comment by ev-gor** [comment]
This is not a bug. Telescope doesn't recognize and parse XML that SOAP is based on. I'm not sure if we should implement such support, as SOAP is not a very popular protocol

**Comment by crynobone** [comment]
Likes like there low demand for this, however you are still free to submit PR to include such support.
