### ISSUE TITLE
Guzzle calls from vendor packages aren't logging

### ISSUE THREAD

**Issue by emergingdzns** [laravel/telescope#1528]
### Telescope Version

5.2

### Laravel Version

8.83

### PHP Version

8.2

### Description

We are using the Twilio vendor package that uses Guzzle under the hood for making requests from our system to Guzzle. But these calls aren't getting logged into the Telescope system as far as I can tell. I've tried the Guzzle watcher package but it won't install (presumably due to still being on Laravel 8). How can we get these calls logged into Telescope?

### Steps To Reproduce

Install twilio/sdk version 6.6.
Create a call to Twilio using the sdk.
Notice no logging in telescope.

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
