### ISSUE TITLE
UI small issue, 'Batches' tab has extra top margin

### ISSUE THREAD

**Issue by zackAJ** [laravel/telescope#1530]
### Telescope Version

latest

### Laravel Version

latest

### PHP Version

8.3

### Database Driver & Version

/

### Description

![image](https://github.com/user-attachments/assets/10def1fe-0ab7-4741-9dae-05efaeecebb1)

### Steps To Reproduce

stare at the side menu and get triggered by the extra space between Jobs and Batches tabs

**Comment by crynobone** [comment]
Closing this as this seem to be the expected behavior: https://github.com/laravel/telescope/pull/1531#issuecomment-2380656695
