### ISSUE TITLE
[Feature] Encryption at the Rest

### ISSUE THREAD

**Issue by gawsoftpl** [laravel/telescope#1532]
### Telescope Version

4.1.0

### Laravel Version

10.4.1

### PHP Version

8.3

### Description

I would like to add encryption at the rest. Add optional encryption only for 'content' column in Entrymodel). I would find this option useful, if you agree I can make a pull request.

### Steps To Reproduce

Feature, no reproduce

**Comment by crynobone** [comment]
Looks like the PR was rejected
