### ISSUE TITLE
Hiding nested request parameter

### ISSUE THREAD

**Issue by ghost** [laravel/telescope#1534]
### Telescope Version

4.16.2

### Laravel Version

10.48.16

### PHP Version

8.2

### Description

Is it possible to hide sensitive request parameters that are nested two or more levels deep in a request payload? From what I can tell, \Laravel\Telescope\Telescope::hideRequestParameters only accepts a one-dimensional array. However, accepting nested arrays would be beneficial for Livewire apps, where a password (in a login request, for example) might be three levels deep, such as in "components.updates.password". Thanks!

### Steps To Reproduce

N/A

**Comment by Boorinio** [comment]
From what i am seeing it already works!
![image](https://github.com/user-attachments/assets/8cc37d9c-c2fd-455e-831f-25ad31812c1d)

![image](https://github.com/user-attachments/assets/55203626-a103-4afc-9a23-2e5b3061d3cb)

![image](https://github.com/user-attachments/assets/8de2dc9f-cc90-467f-8507-9f34d23daa82)

**Comment by ghost** [comment]
Thanks @Boorinio. How about Telescope's dashboard (requests section), is "another_secret" hidden there as well?

**Comment by crynobone** [comment]
Thanks @Boorinio
