### ISSUE TITLE
Target [Laravel\Telescope\Contracts\EntriesRepository] is not instantiable.

### ISSUE THREAD

**Issue by patake** [laravel/telescope#1538]
### Telescope Version

5.2.3

### Laravel Version

11.28.1

### PHP Version

8.3.2

### Database Driver & Version

8.0.32

### Description

![image](https://github.com/user-attachments/assets/afcf7957-401f-4b4b-b0be-ca254481d2ea)

`[2024-10-19 23:28:43] local.ERROR: Target [Laravel\Telescope\Contracts\EntriesRepository] is not instantiable. {"exception":"[object] (Illuminate\\Contracts\\Container\\BindingResolutionException(code: 0): Target [Laravel\\Telescope\\Contracts\\EntriesRepository] is not instantiable. at /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:1195)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(947): Illuminate\\Container\\Container->notInstantiable()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(815): Illuminate\\Container\\Container->build()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1046): Illuminate\\Container\\Container->resolve()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(751): Illuminate\\Foundation\\Application->resolve()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1028): Illuminate\\Container\\Container->make()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(1559): Illuminate\\Foundation\\Application->make()
#6 /var/www/html/vendor/laravel/telescope/src/ListensForStorageOpportunities.php(65): Illuminate\\Container\\Container->offsetGet()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\\Telescope\\Telescope::Laravel\\Telescope\\{closure}()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(43): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(83): Illuminate\\Container\\Util::unwrapIfClosure()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(690): Illuminate\\Container\\BoundMethod::call()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1420): Illuminate\\Container\\Container->call()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(218): Illuminate\\Foundation\\Application->terminate()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1190): Illuminate\\Foundation\\Http\\Kernel->terminate()
#15 /var/www/html/public/index.php(17): Illuminate\\Foundation\\Application->handleRequest()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/resources/server.php(23): require_once('...')
#17 {main}
"} `

### Steps To Reproduce

Right after running composer require laravel/telescope and every request after, this message appears.

**Comment by crynobone** [comment]
Did you follow the installation guide?

**Comment by ayakaida** [comment]
I had the same issue but upgrading to Laravel version 11.29 from 11.28.1 solved this.

**Comment by crynobone** [comment]
Hey there,

We're closing this issue because it's inactive, already solved, old, or not relevant anymore. Feel free to open up a new issue if you're still experiencing this problem.
