### ISSUE TITLE
Fatal error when deploying to production

### ISSUE THREAD

**Issue by mvdnbrk** [laravel/telescope#154]
Install Telescope
```
composer require laravel/telescope --dev
```

When deploying your app to production you will probably run:
```
composer install --no-dev
```

Which will trigger `php artisan package:discover` and will result in an error:
```
PHP Fatal error:  Class 'Laravel\Telescope\TelescopeApplicationServiceProvider' not found 
in ~/app/Providers/TelescopeServiceProvider.php on line 10
```

`App\Providers\TelescopeServiceProvider::class` is added to `config/app.php` when you run `php artisan install:telescope`. 

But the package is not installed since you are running composer install with the --no-dev flag.

**Comment by browner12** [comment]
I believe the idea is that you run `php artisan telescope:install` on your dev environment, and then commit the newly created provider to your repo.

**Comment by themsaid** [comment]
check @browner12's comment

**Comment by mvdnbrk** [comment]
@themsaid am I missing something?

Running `php artisan telescope:install` adds `App\Providers\TelescopeServiceProvider::class,` to the config/app.php file. And creates the `TelescopeServiceProvider` class in the app/Providers folder:

```
<?php

namespace App\Providers;

use Laravel\Telescope\Telescope;
use Illuminate\Support\Facades\Gate;
use Laravel\Telescope\IncomingEntry;
use Laravel\Telescope\TelescopeApplicationServiceProvider;

class TelescopeServiceProvider extends TelescopeApplicationServiceProvider
{
    ...
```

The service provider requires  Laravel\Telescope\TelescopeApplicationServiceProvider which will not be installed with composer install --no-dev.

**Comment by browner12** [comment]
ahh, i see what you're saying.  yah, that's a thinker

**Comment by mvdnbrk** [comment]
`composer require laravel/telescope` ~~--dev~~ 

:wink:

**Comment by browner12** [comment]
that's the question, though. I'm still confused if this package is intended to be used in Production or not.

**Comment by mvdnbrk** [comment]
I believe this package is mainly for dev purposes but could be used in production as well according to the [post](https://mattstauffer.com/blog/introducing-laravel-telescope/) by Matt Stauffer.

**Comment by johanvanhelden** [comment]
I often compare Telescope to the Debugbar, both are packages that, IMHO, should not be installed on production. If for some reason there is something wrong with the Gate, and you expose Telescope or Debugbar to the outside world, you expose details of your application that should not be public.

So I'd rather see a solution that does not involve installing it as a regular dependency. Maybe this issue could be opened again?

**Comment by matthewhall-ca** [comment]
Agreed with @johanvanhelden this seems like it should be handled like Debugbar or Clockwork, where you can install it as a dev dependency and just have it not active in Production

**Comment by mvdnbrk** [comment]
Agree. Most of the times you will not push Telescope to production.
However, if you would like to have it available in production, you can.

By default you will only have access to the dashboard in a local environment, unless you explicitly give access to to a user with the `gate` method:

```
protected function gate()
{
    Gate::define('viewTelescope', function ($user) {
        return in_array($user->email, [
            'taylor@laravel.com',
        ]);
    });
}
```

**Comment by johanvanhelden** [comment]
@mvdnbrk Sure, but to prevent security issues I'd rather not have it installed on production at all. If a bug slips through and a part of Telescope exposes things that it shouldn't, we've got a problem.

If I can just *not install* Telescope on production, I've got nothing to worry about.

**Comment by mvdnbrk** [comment]
Like @matthewhall-ca mentioned this should be handled like Debugbar.
Just install Telescope with `composer require laravel/telescope --dev` and there should nothing to be worried about when deploying to production. 

`App\Providers\TelescopeServiceProvider::class` should not be added to `config/app.php`.

Like @browner12 mentioned package auto-discovery should handle this?

What about the `public/vendor/telescope` folder?
Shouldn't be there either I guess.

**Comment by browner12** [comment]
I feel like we're running into some chicken/egg problems 🤕 

we do need the vendor assets published and committed, because otherwise your re-deploying them on new clones?

idk anymore.

**Comment by johanvanhelden** [comment]
I'd say Telescope does not need to publish its assets. The (and I am going to use this example again) Debugbar also works fine without having any assets published.

URL: `/_debugbar/assets/stylesheets?v=1534935979`
![screenshot from 2018-10-25 08-51-14](https://user-images.githubusercontent.com/19389981/47481209-2b870200-d833-11e8-8a92-35425dd703f0.png)

**Comment by themsaid** [comment]
Hey everyone, Telescope is meant to be used for dev purposes AND production as well, however using it in production needs to be controlled and secured.

If you don't want to use it in production, just add the package to `extra.laravel.dont-discover` in your composer.json and only register the ServiceProvider if the environment isn't `production`.

```
if ($this->app->environment('local')) {
    $this->app->register(TelescopeServiceProvider::class);
}
```

**Comment by johanvanhelden** [comment]
Alright thanks for clarifying @themsaid , so besides adding this information to the documentation, the only issue left would be the asset handling, right?

**Comment by emielmolenaar** [comment]
Just symlink `vendor/laravel/telescope/public` to `public/vendor/telescope` and add the symlink to git. Same thing I did with Horizon. Solves assets troubles :smiley:

**Comment by johanvanhelden** [comment]
Symlinking feels a bit dirty, because those symlinks will exist on production as well, but will be dead. And I am not sure all OS's support symlinks in the same way. Let's say I commit a symlink on Linux, will it also work for my Windows colleague?

**Comment by emielmolenaar** [comment]
We don't care about Windows, so symlinks are fine here. Guess they won't work on Windows.

What harm could a dead symlink in `public/vendor` do? In this case I rather prefer a dead symlink over pushing these (ultimately unused) assets to production.

**Comment by mvdnbrk** [comment]
A route to `telescope/assets/stylesheets` or similar seems more elegant to me.
That route can take of serving all the necessary assets.
Keeps the `public` folder clean as well.

**Comment by themsaid** [comment]
What's the problem with having the `public/vendor/telescope` file? I don't understand.

**Comment by matthewhall-ca** [comment]
Yeah personally i see no issue with having a `public/vendor/telescope` file, the issue is that if you have something in your require-dev dependencies it shouldn't be breaking a dev-less composer install. 

Like having `symfony/css-selector` and `symfony/dom-crawler` in your require-dev. Application will run fine without them when you do a dev-less install.

**Comment by dindong** [comment]
I required provide in app service provider and added package to dont-auotload as descriped.
If I run `php artisan package:discover` after `composer install --no-dev` I get the following Error:

```
In TelescopeServiceProvider.php line 10:

  Class 'Laravel\Telescope\TelescopeApplicationServiceProvider' not found
```

Am I doing anything wrong?

**Comment by lesterchan** [comment]
@dindong Did you run `composer require laravel/telescope --dev` instead of `composer require laravel/telescope`?

**Comment by dindong** [comment]
@lesterchan Yes I installed it as ah dev dependency, because I dont want it on production.

**Comment by lesterchan** [comment]
@dindong did you put don't discover in composer.json?

```
    "extra": {
        "laravel": {
            "dont-discover": [
                "laravel/telescope"
            ]
        }
    },
```

Then in `AppServiceProvider` `register()` do something like
```
        if ($this->app->environment() === 'local') {
            $this->app->register(\Laravel\Telescope\TelescopeServiceProvider::class);
            $this->app->register(TelescopeServiceProvider::class);
        }
```

**Comment by dindong** [comment]
@lesterchan  I only register this->app->register(TelescopeServiceProvider::class); at the moment.

**Comment by lesterchan** [comment]
@dindong `\Laravel\Telescope\TelescopeServiceProvider::class` is the one that loads all the telescope routes. You need to register that if you are not using auto discover (like me).

**Comment by themsaid** [comment]
Hope this is clear to everyone by now.

**Comment by fylzero** [comment]
I'm having this same issue where php artisan package:discover after composer install --no-dev results in...

```
In TelescopeServiceProvider.php line 10:

  Class 'Laravel\Telescope\TelescopeApplicationServiceProvider' not found
```

I have telescope in don't discover in composer.json...  I can tell you, my problem is that the suggested code in AppServiceProvider...

```
$this->app->isLocal()
```

This does not work.  I expected this value to change when I switch my .env APP_ENV variable.  It does not change correctly.

**Comment by Oluwatobi-beebittech** [comment]
@fylzero This actually worked for me.

**Comment by alielmajdaoui** [comment]
One more step is missing from @themsaid https://github.com/laravel/telescope/issues/154#issuecomment-432938123 is to remove `App\Providers\TelescopeServiceProvider::class` from `providers` array in `config/app.php`

Thanks to https://stackoverflow.com/a/66272295/3632172

**Comment by blondie63** [comment]
the solution for me is this:

in app/Providers/AppServiceProvider.php:
```
        if ($this->app->environment('local') && class_exists(\Laravel\Telescope\TelescopeServiceProvider::class)) {
            $this->app->register(\Laravel\Telescope\TelescopeServiceProvider::class);
        }
```

**Comment by inigopascall** [comment]
Just had this issue on Laravel 11 when deploying to Forge. Probably, like me, y'all didn't read the docs properly...

[As per the docs](https://laravel.com/docs/11.x/telescope#local-only-installation), you need to remove the line from `/bootstrap/providers.php`:

```
return [
    App\Providers\AppServiceProvider::class,
    App\Providers\ObserverServiceProvider::class,
    App\Providers\TelescopeServiceProvider::class, // remove this line
];
```

Works fine for me now 👌

**Comment by rdp77** [comment]
You can change how it registers the telescope provider by changing 2 files

`/bootstrap/providers.php`

```
<?php

$providers = [
    App\Providers\AppServiceProvider::class,
    App\Providers\Filament\AdminPanelProvider::class,
];

if (class_exists(\Laravel\Telescope\TelescopeServiceProvider::class)) {
    $providers[] = App\Providers\TelescopeServiceProvider::class;
}

return $providers;
```

`App\Providers\AppServiceProvider.php`

```
  public function register(): void
    {
        if ($this->app->isLocal() && class_exists(\Laravel\Telescope\TelescopeServiceProvider::class)) {
            $this->app->register(\Laravel\Telescope\TelescopeServiceProvider::class);
            $this->app->register(TelescopeServiceProvider::class);
        }
    }
```

Make sure you install composer with `composer install --no-dev`
You can optimize again with `composer dump-autoload`
