### ISSUE TITLE
Session tab is always empty 

### ISSUE THREAD

**Issue by nemanja-milic** [laravel/telescope#1540]
### Telescope Version

5.2

### Laravel Version

10.10

### PHP Version

8.2

### Description

I am making the rest api laravel and in mine telescope session is always empty i do not know why when i send something to the session.
![image](https://github.com/user-attachments/assets/6d220237-2a8c-4eaa-8c36-58e9bfded843), code i used is down below
`public static function getAllCars()
    {
        $carsStatus = CarStatus::getStatusByOrder();
        $cars = Car::getCarsWithImages(Car::orderByRaw("FIELD(status, $carsStatus)"));

        session(["cars" => $cars]);

        return $cars->getCollection()->transform(function ($car) {
            $car->color = CarStatus::getColor($car->status);
            $car->last_time_updated = $car->updated_at !== $car->created_at ? $car->updated_at : null;
            return $car;
        });
    }`

### Steps To Reproduce

Install the telescope 
Open in the browser 
Make some request to the app
You should see the error

**Comment by crynobone** [comment]
REST API request normally are stateless request, which doesn't use/load session by default, therefore this seem to be expected. You may submit a new bug report with full reproducing code if you believe this is still an issue.
