### ISSUE TITLE
Limit to job watcher data

### ISSUE THREAD

**Issue by kingeke** [laravel/telescope#1545]
### Telescope Version

5.2.5

### Laravel Version

9

### PHP Version

8.2

### Description

Hello, this is more of a question than a bug, is there a way to limit the data stored in sql for jobs? 

I have a job that's chained, the data is massive, thus I get a MySQL has gone away error when telescope tries to save it to the DB, the only work around I could do was to stop recording and start when done, but if there's a way to limit the size and maybe show a bit of it or none at all

### Steps To Reproduce

Chain a large amount of data, like chunking a csv file

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
