### ISSUE TITLE
HTTP Request inside Livewire not being recorded

### ISSUE THREAD

**Issue by zarulizham** [laravel/telescope#1557]
### Telescope Version

4.17.6

### Laravel Version

10.48.20

### PHP Version

8.3.15

### Database Driver & Version

MySQL 9.0.0

### Description

In my Livewire component has Http::get() request. Telescope did not capture the Client Request due to `telescope.ignore_paths` contains `livewire*`. 

After I commented out `livewire*` in ignore_paths, records for Http coming in.

I believe only request URLs contains `livewire*` shall be excluded in Telescope Request (Not Client Request).

### Steps To Reproduce

1. Create Livewire component
2. Make Http::get('https://ipinfo.io/ip') request.
3. Observe Telescope Client Request. No data were recorded.
4. Remove `livewire*` inside config/telescope.php (telescope.ignore_paths).
5. Make Http::get('https://ipinfo.io/ip') request.
6. Observe Telescope Client Request. Data were recorded.

**Comment by crynobone** [comment]
> After I commented out livewire* in ignore_paths, records for Http coming in.

That's the correct behavior to enable Livewire requests to be logged.
