### ISSUE TITLE
Convert the content field type to MEDIUMTEXT

### ISSUE THREAD

**Issue by lionslair** [laravel/telescope#166]
I have an existing project and as soon as I installed telescope I experienced issues.I removed it and made a new branch to test from.

First issue after installing.  The content field in telescope_entries is not long enough for my content.. Changing the field to a longtext worked.

`[2018-10-25 09:30:24] local.ERROR: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'content' at row 1 (SQL: insert into `telescope_entries` (`batch_id`, `content`, `created_at`, `type`, `uuid`) values `

Second. I use UUID fields for ID's throughout my application. It doesn't seem to like it. This one seems to be what breaks some of my queries.

`[2018-10-25 09:43:14] local.ERROR: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`screensavers`.`telescope_entries_tags`, CONSTRAINT `telescope_entries_tags_entry_uuid_foreign` FOREIGN KEY (`entry_uuid`) REFERENCES `telescope_entries` (`uuid`) ON DELETE CASCADE) (SQL: insert into `telescope_entries_tags` (`entry_uuid`, `tag`) values (8c1aa4a0-dbf9-4273-b355-95e8825c5b1c, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a0-dcef-4d3b-9836-ca86f0c0c00f, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a0-dd89-4497-b9ad-72cbd8d34808, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a0-e5ba-4491-88fc-8910591dca09, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a0-e83e-491d-b0d6-d084d216aae3, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a0-ee16-443a-a4c5-b55a6e9767dc, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a1-015e-4bfe-b912-624b8e5c9afe, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a1-045d-4ec5-857c-66266e2a1b8c, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a1-06f2-49a5-b327-e474a866bd58, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a1-0a12-4a12-8b43-9156e7ad9a9a, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a1-1ca6-4a86-818a-3c52d8d79d8e, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a1-286f-40aa-8807-972709f8f78b, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a1-2f8c-40a7-ba4a-d90990a206d8, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a1-353e-4039-97ad-7d4f00bb9ba3, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a1-39f3-4252-bdbc-656ce98fb97c, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a1-3fc6-4f5e-8c55-ec4aec7c5bfa, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a1-447a-40b4-88e6-cf6b0990d8bb, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a1-4e77-42b7-bf0b-4779ddaed04e, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a1-5362-48dc-8847-33bf4960e36d, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a1-59b8-4c01-81d4-1321376e8639, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a1-628f-45f2-9f94-b850ef894b0b, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a1-6a03-4fdb-91be-079177a48134, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a1-826a-4923-bb44-010fda6d29de, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a1-8838-4ecc-aec0-a9b573efcb3e, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a1-8f18-4c81-a64b-7585b7f1ca22, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a1-9f22-4a8a-88db-f0848dd5089b, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a1-ac05-4733-bfe5-22fd19f09181, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a1-bb0c-4c65-9519-f858e750045b, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a1-c0d6-46bd-87f9-2fcb8d726d13, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a1-c849-4969-94d1-90bcf018b209, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a1-cf27-480c-a6d6-38f3fdcf2929, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a1-d4b4-4b0b-a565-50b0a1776017, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a1-dd2e-4d97-adaa-5fc93be3596f, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a1-f968-499a-a8b6-9cd22c2dfc4a, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a2-04d3-4436-835e-670f75f23a40, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a2-1620-415c-9fac-9f6eb8789326, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a2-25df-4414-a34c-9346500e37d1, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a2-306a-48c4-ab18-2d2bc4b1b282, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a2-3bab-4dee-b341-b42a432e7751, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a2-440e-4098-8d7f-2b5d29470675, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a2-50a2-4afa-a0fe-95a9a4c2f27e, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a2-5ce9-4949-8625-d73d0af297d1, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a2-64a4-49df-bcbf-b0be84b7f0dd, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a2-6b5d-4179-9392-d80a32684e9a, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a2-706d-4a4f-9511-da4715f26a30, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a2-765e-4ad2-8244-a380485c8aa5, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a2-8060-4ebe-ac19-88bbdd9d660a, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a2-8e52-4de5-a270-95ed374897c0, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a2-991d-4710-a49b-fbd98f222f47, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a2-b259-403f-b9f7-fa51ddefb2e1, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a2-bab9-4796-b53a-ac72c2a86474, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a2-c3da-4638-b4f4-02f1d773853e, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a2-ca80-47ba-b188-2df4e2035ca5, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a2-d0a1-4391-81d9-0c437dfccaa6, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a2-d8d2-471a-a929-bc4b18f7aa2d, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a2-df0d-4aa0-b748-613a52d5dbbd, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a2-e83e-41c8-b405-e1fa0d42f848, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a2-f42e-4a19-99c8-7dd6380687f0, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a2-fc97-463f-ae16-94e8f3f2250d, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a3-06a0-4375-a336-dd863ca04a48, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a3-0cf4-44f1-9d2c-904fd30d3bf5, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a3-1646-4f4b-8a70-13d94bf72bea, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a3-1bd7-4950-99bd-4311c6bd3853, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a3-2599-40b3-a38f-85d557033878, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a3-2a76-4595-8cf9-521e3269bd11, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a3-3006-407c-b441-1ce2883b0de4, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a3-380e-4e57-acd8-7728dbe8e76c, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a3-3df4-4336-925b-1465cbb32571, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a3-6670-43ba-b049-cb74734ac446, Auth:8948bc49-8968-496b-bd02-93992a06142b)) {"userId":"8948bc49-8968-496b-bd02-93992a06142b","email":"nathan.rzepecki@test.com","exception":"[object] (Illuminate\\Database\\QueryException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`screensavers`.`telescope_entries_tags`, CONSTRAINT `telescope_entries_tags_entry_uuid_foreign` FOREIGN KEY (`entry_uuid`) REFERENCES `telescope_entries` (`uuid`) ON DELETE CASCADE) (SQL: insert into `telescope_entries_tags` (`entry_uuid`, `tag`) values (8c1aa4a0-dbf9-4273-b355-95e8825c5b1c, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a0-dcef-4d3b-9836-ca86f0c0c00f, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a0-dd89-4497-b9ad-72cbd8d34808, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a0-e5ba-4491-88fc-8910591dca09, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a0-e83e-491d-b0d6-d084d216aae3, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a0-ee16-443a-a4c5-b55a6e9767dc, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a1-015e-4bfe-b912-624b8e5c9afe, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a1-045d-4ec5-857c-66266e2a1b8c, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a1-06f2-49a5-b327-e474a866bd58, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a1-0a12-4a12-8b43-9156e7ad9a9a, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a1-1ca6-4a86-818a-3c52d8d79d8e, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a1-286f-40aa-8807-972709f8f78b, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a1-2f8c-40a7-ba4a-d90990a206d8, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a1-353e-4039-97ad-7d4f00bb9ba3, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a1-39f3-4252-bdbc-656ce98fb97c, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a1-3fc6-4f5e-8c55-ec4aec7c5bfa, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a1-447a-40b4-88e6-cf6b0990d8bb, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a1-4e77-42b7-bf0b-4779ddaed04e, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a1-5362-48dc-8847-33bf4960e36d, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a1-59b8-4c01-81d4-1321376e8639, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a1-628f-45f2-9f94-b850ef894b0b, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a1-6a03-4fdb-91be-079177a48134, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a1-826a-4923-bb44-010fda6d29de, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a1-8838-4ecc-aec0-a9b573efcb3e, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a1-8f18-4c81-a64b-7585b7f1ca22, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a1-9f22-4a8a-88db-f0848dd5089b, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a1-ac05-4733-bfe5-22fd19f09181, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a1-bb0c-4c65-9519-f858e750045b, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a1-c0d6-46bd-87f9-2fcb8d726d13, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a1-c849-4969-94d1-90bcf018b209, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a1-cf27-480c-a6d6-38f3fdcf2929, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a1-d4b4-4b0b-a565-50b0a1776017, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a1-dd2e-4d97-adaa-5fc93be3596f, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a1-f968-499a-a8b6-9cd22c2dfc4a, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a2-04d3-4436-835e-670f75f23a40, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a2-1620-415c-9fac-9f6eb8789326, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a2-25df-4414-a34c-9346500e37d1, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a2-306a-48c4-ab18-2d2bc4b1b282, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a2-3bab-4dee-b341-b42a432e7751, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a2-440e-4098-8d7f-2b5d29470675, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a2-50a2-4afa-a0fe-95a9a4c2f27e, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a2-5ce9-4949-8625-d73d0af297d1, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a2-64a4-49df-bcbf-b0be84b7f0dd, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a2-6b5d-4179-9392-d80a32684e9a, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a2-706d-4a4f-9511-da4715f26a30, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a2-765e-4ad2-8244-a380485c8aa5, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a2-8060-4ebe-ac19-88bbdd9d660a, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a2-8e52-4de5-a270-95ed374897c0, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a2-991d-4710-a49b-fbd98f222f47, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a2-b259-403f-b9f7-fa51ddefb2e1, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a2-bab9-4796-b53a-ac72c2a86474, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a2-c3da-4638-b4f4-02f1d773853e, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a2-ca80-47ba-b188-2df4e2035ca5, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a2-d0a1-4391-81d9-0c437dfccaa6, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a2-d8d2-471a-a929-bc4b18f7aa2d, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a2-df0d-4aa0-b748-613a52d5dbbd, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a2-e83e-41c8-b405-e1fa0d42f848, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a2-f42e-4a19-99c8-7dd6380687f0, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a2-fc97-463f-ae16-94e8f3f2250d, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a3-06a0-4375-a336-dd863ca04a48, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a3-0cf4-44f1-9d2c-904fd30d3bf5, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a3-1646-4f4b-8a70-13d94bf72bea, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a3-1bd7-4950-99bd-4311c6bd3853, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a3-2599-40b3-a38f-85d557033878, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a3-2a76-4595-8cf9-521e3269bd11, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a3-3006-407c-b441-1ce2883b0de4, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a3-380e-4e57-acd8-7728dbe8e76c, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a3-3df4-4336-925b-1465cbb32571, Auth:8948bc49-8968-496b-bd02-93992a06142b), (8c1aa4a3-6670-43ba-b049-cb74734ac446, Auth:8948bc49-8968-496b-bd02-93992a06142b)) at /home/vagrant/Code/screensavers/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`screensavers`.`telescope_entries_tags`, CONSTRAINT `telescope_entries_tags_entry_uuid_foreign` FOREIGN KEY (`entry_uuid`) REFERENCES `telescope_entries` (`uuid`) ON DELETE CASCADE) at /home/vagrant/Code/screensavers/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:144, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`screensavers`.`telescope_entries_tags`, CONSTRAINT `telescope_entries_tags_entry_uuid_foreign` FOREIGN KEY (`entry_uuid`) REFERENCES `telescope_entries` (`uuid`) ON DELETE CASCADE) at /home/vagrant/Code/screensavers/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:142)
[stacktrace]
#0 /home/vagrant/Code/screensavers/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('insert into `te...', Array, Object(Closure))
#1 /home/vagrant/Code/screensavers/vendor/laravel/framework/src/Illuminate/Database/Connection.php(459): Illuminate\\Database\\Connection->run('insert into `te...', Array, Object(Closure))
#2 /home/vagrant/Code/screensavers/vendor/laravel/framework/src/Illuminate/Database/Connection.php(411): Illuminate\\Database\\Connection->statement('insert into `te...', Array)
#3 /home/vagrant/Code/screensavers/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2541): Illuminate\\Database\\Connection->insert('insert into `te...', Array)
#4 /home/vagrant/Code/screensavers/vendor/laravel/telescope/src/Storage/DatabaseEntriesRepository.php(163): Illuminate\\Database\\Query\\Builder->insert(Array)
#5 /home/vagrant/Code/screensavers/vendor/laravel/telescope/src/Storage/DatabaseEntriesRepository.php(115): Laravel\\Telescope\\Storage\\DatabaseEntriesRepository->storeTags(Object(Illuminate\\Support\\Collection))
#6 /home/vagrant/Code/screensavers/vendor/laravel/telescope/src/Telescope.php(439): Laravel\\Telescope\\Storage\\DatabaseEntriesRepository->store(Object(Illuminate\\Support\\Collection))
#7 /home/vagrant/Code/screensavers/vendor/laravel/telescope/src/ListensForStorageOpportunities.php(44): Laravel\\Telescope\\Telescope::store(Object(Laravel\\Telescope\\Storage\\DatabaseEntriesRepository))
#8 [internal function]: Laravel\\Telescope\\Telescope::Laravel\\Telescope\\{closure}()
#9 /home/vagrant/Code/screensavers/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Object(Closure), Array)
#10 /home/vagrant/Code/screensavers/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(75): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#11 /home/vagrant/Code/screensavers/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Object(Closure), Object(Closure))
#12 /home/vagrant/Code/screensavers/vendor/laravel/framework/src/Illuminate/Container/Container.php(572): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Object(Closure), Array, NULL)
#13 /home/vagrant/Code/screensavers/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(965): Illuminate\\Container\\Container->call(Object(Closure))
#14 /home/vagrant/Code/screensavers/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(191): Illuminate\\Foundation\\Application->terminate()
#15 /home/vagrant/Code/screensavers/public/index.php(60): Illuminate\\Foundation\\Http\\Kernel->terminate(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\JsonResponse))
#16 {main}
"} `

**Comment by themsaid** [comment]
Most applications won't have this huge amount of data to record per entry, and we don't want to take space that's not needed by default, so feel free to update the field type as you wish.

Regarding the second issue I don't see how is this related to Telescope.

**Comment by lionslair** [comment]
Second issue does not occur without telescope. 

The integrity constraint is on the telescope tables 

.telescope_entries_tags, CONSTRAINT telescope_entries_tags_entry_uuid_foreign FOREIGN KEY (entry_uuid) REFERENCES telescope_entries (uuid) ON DELETE CASCADE)

**Comment by themsaid** [comment]
Yes I know but it does seem to be something special in your app, let’s see if anyone else reports the same issue.

**Comment by haekb** [comment]
I'll +1 to the content field not long enough. Some of our responses are big enough to get truncated by the text length. (We return about 1000 rows at a time, comes out to about 2mb of data per response.) 

We currently have a migration in place to change the column type, but it'd be better if the default was mediumText imo.

**Comment by CyrilMazur** [comment]
+1 content field is not long enough for my app

**Comment by egknight** [comment]
+1 on the content field

**Comment by MatanYed** [comment]
+1 but on `batch_id`
`SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'batch_id' at row 1`

**Comment by mvdnbrk** [comment]
+1 for the content field

**Comment by Scarwolf** [comment]
+1
