### ISSUE TITLE
Acessibilty and Confort on Night Theme

### ISSUE THREAD

**Issue by marcosfreitas** [laravel/telescope#170]
**Guys, just an observation.**
That purple color seems not be the best option to use in night theme (considering people with "normal" color vision), maybe it can be light blue or only night and black. If you don't like this, can I add an extra theme for this purpose? By example, I really have difficult to read the screen using the night theme (and I consider myself having a "normal" color vision), but it still the best option for my eyes.

**Comment by themsaid** [comment]
Well to me if Steve Schoger thinks it's nice I'm happy with it :D

**Comment by taylorotwell** [comment]
Feel free to make a PR with a suggestion for a different color and we can consider it! Thanks
