### ISSUE TITLE
Biginteger issue on Queries

### ISSUE THREAD

**Issue by ForzaSFerrari** [laravel/telescope#171]
If you have biginteger as types in your database, I've found that you may get wrong id's in your query details in Telescope.

Here are some examples of id's. The upper id is the id, you may have in the url. The lower id is the result in Telescope.
```
189656563
189656563

18965656326
18965656326

1896565632644
1896565632644

189656563264489
189656563264489

18965656326448986
18965656326448984

1896565632644898696
1896565632644898800
```
In laravel itself I have no errors.

**Comment by themsaid** [comment]
Wrong ids where? Which part is displaying the wrong IDs? Can you share a screenshot?

**Comment by ForzaSFerrari** [comment]
ID in database: 1898010790473457955
![capture](https://user-images.githubusercontent.com/16107131/47516747-8dbd2280-d886-11e8-8150-cc5c438105ce.PNG)

**Comment by themsaid** [comment]
@ForzaSFerrari can you check the network tab for the preview screen, find the body of the entry and see if the number is correct there, you should see it in the JSON content under the "bindings" key.

**Comment by ForzaSFerrari** [comment]
Chrome/Opera (API): Binding says 1898010790473457955
Chrome/Opera (Network Tab): Binding says 1898010790473458000

Firefox (API and Network Tab): Binding says 1898010790473458000

**Comment by themsaid** [comment]
And the value in the database?

**Comment by ForzaSFerrari** [comment]
value in the database is 1898010790473457955

**Comment by themsaid** [comment]
Can you open a PR with the fix since you can replicate the issue?

**Comment by ForzaSFerrari** [comment]
For me it looks like an issue at the sql formatter package. Not at Laravel Telescope itself.

**Comment by ForzaSFerrari** [comment]
@themsaid what is the right package of this? `highlight.js/lib/languages/sql`
I really believe I get this error through a package and not through Telescope itself.

**Comment by themsaid** [comment]
I can't seem to replicate this issue and there seems to be no one else reporting the same behaviour. I'm going to close this for now.

Please open a PR in case you figured out a way to fix it on your machine so we can verify. 

Also if anyone else is facing the same issue please ping me.

Thanks

**Comment by ForzaSFerrari** [comment]
For me it's an error from an external package, but if I don't get no answer here or via mail by you, I will not research further, because I also have to do other things.

**Comment by billriess** [comment]
I've just hit this issue as well. When dealing with a large ID telescope is decrementing the reported ID by 1 even though the payload is correct. This means the data in telescope cannot be trusted. If casted as a string it works fine.

**Comment by billriess** [comment]
Update #2

I found the issue.
There is a limitation in JS with larger numbers. The max value before integers start having weird behavior is `9007199254740991`. Any number larger than this in JS will start to return the wrong value.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER

I don't know that this would be a bug or not for Telescope. I suppose Telescope could check if the number is larger than this and throw a warning and cast the number as a string.
