### ISSUE TITLE
Database connection configuration is not in current release

### ISSUE THREAD

**Issue by amitavroy** [laravel/telescope#172]
While the latest code on branch 1.0 has the configuration in the constructor to accept custom database connection, the code which is coming from packagist doesn't have the updated code.

Latest code: 
https://github.com/laravel/telescope/blob/1.0/src/Storage/migrations/2018_08_08_100000_create_telescope_entries_table.php

Code from pacakgist:
https://github.com/laravel/telescope/blob/v0.1.2/src/Storage/migrations/2018_08_08_100000_create_telescope_entries_table.php

**Comment by themsaid** [comment]
releasing in a bit.
