### ISSUE TITLE
Disable Telescope during migration

### ISSUE THREAD

**Issue by danrichards** [laravel/telescope#173]
I'm having issues with `Telescope` being active while the app is migrating. I can work-around this, but I feel like Telescope shouldn't be active while the app is migrating. 

We can see it has caused issues with our CI and we have to work-around this scenario.

<img width="1408" alt="screen shot 2018-10-25 at 10 40 01 am" src="https://user-images.githubusercontent.com/470255/47508694-9429ab00-d842-11e8-89e4-68176b2d609f.png">

If you don't agree, please let me know, I'll close ticket.

**Comment by danrichards** [comment]
A bit more context here, the CI us booting up the app and migrating the whole database, model creation is generating Telescope events, which fail because those tables to not exist yet.

I think the simplest work-around would be to make the telescope migrations publishable, then I can pre-date them so they fire before the other migrations. 

Another method would be that the migration process could be detected, and Telescope could be disabled at run-time. But some people may wish to have telescope active incase a migration fails, it could be useful, so the first suggestion may be better.

**Comment by okaufmann** [comment]
I had the exact same Error with Forge. Solved it by manually temporarily disable Telescope during the migration. This was very hacky indeed.

May it be possible to use `Telescope::stopRecording()` and `Telescope::startRecording()` in https://github.com/laravel/telescope/blob/1.0/src/Storage/migrations/2018_08_08_100000_create_telescope_entries_table.php ? (Can't test it right now)

**Comment by themsaid** [comment]
Some people might want Telescope to record the migrations, I can see the problem though when telescope tables aren't there yet, this problem can happen in a CI or in a production server if there are things to record before the database migration that adds telescope tables run.

I think this has to be taken care of manually, in CI for example just disable telescope entirely, you don't need it to be running and recording what's going on in the CI.

In production, the first time you install Telescope make sure it's disabled, and then enable it in a commit after the migrations run.

**Comment by michaelnguyen547** [comment]
can you please elaborate how to disable Telescope?

**Comment by okaufmann** [comment]
Check my previous response: https://github.com/laravel/telescope/issues/173#issuecomment-433103456

**Comment by okaufmann** [comment]
You may want to listen for 'php artisan migrate` or 'php artisan migrate --force' and disable Telescope just for running migrations.

You could listen for the `CommandStarting` event in your `EventServiceProvider` and then stop recording for certain commands:
```
class EventServiceProvider extends ServiceProvider
{
    /**
     * The event listener mappings for the application.
     *
     * @var array
     */
    protected $listen = [
        \Illuminate\Console\Events\CommandStarting::class => [
            App\Listeners\CommandStartingListener::class
        ]
    ];

    // ...

}
```

```php
<?php

namespace App\Listeners;

use Illuminate\Console\Events\CommandStarting;
use Laravel\Telescope\Telescope;

class CommandStartingListener
{
    /**
     * Handle the event.
     *
     * @param  object $event
     * @return void
     */
    public function handle(CommandStarting $event)
    {
        if ($event->command === 'migrate' || starts_with($event->command, 'migrate ')) {
            Telescope::stopRecording();
        }
    }
}

```

**Comment by paras-malhotra** [comment]
I haven't encountered this issue during migrations. But seeding certainly slows down due to Telescope. In fact, I've encountered out of memory errors during the database seeds. Solved it for now using `Telescope::stopRecording()` and `Telescope::startRecording()` at the start and end of the `DatabaseSeeder` class

**Comment by paras-malhotra** [comment]
I found that a better solution would be to add the commands (e.g. migrate, db:seed, etc.) in an `ignoreCommands` array in `config/telescope.php`.

**Comment by okaufmann** [comment]
This is the better solution indeed. Didn't noticed this configuration 😇

**Comment by danrichards** [comment]
@okaufmann I didn't even realize there was a general event for when a command fires. This is a great solution.

**Comment by danrichards** [comment]
@paras-malhotra Also a great solution

**Comment by themsaid** [comment]
recommended solution is: https://github.com/laravel/telescope/issues/173#issuecomment-433734464

**Comment by jlsjonas** [comment]
If you want to keep logs for those actions; execute `php artisan migrate --path=vendor/laravel/telescope/src/Storage/migrations/` before executing your other migrations
