### ISSUE TITLE
[Feature Request] App Identifier in config for logging multiple apps, etc.

### ISSUE THREAD

**Issue by rufhausen** [laravel/telescope#177]
Since multiple applications (or a single load-balanced app) can feed into the same telescope database, it would be nice if, in the config, you could set some kind of searchable/filterable identifier (tag?) in order to identify the app instance the entry pertains to.
Thanks.

**Comment by tillkruss** [comment]
If no name is configured, this should default to `gethostname()`.

**Comment by deleugpn** [comment]
This is beautiful. Hope somebody can pick this up.

**Comment by themsaid** [comment]
Every entry has the host name stored with it, you can find it in the preview section.

**Comment by rufhausen** [comment]
> Would be nice to be able to set a .env parameter like TELESCOPE_IDENTIFIER=webserver or TELESCOPE_IDENTIFIER=API
> 
> This way you will be able to generate overview and see what app it is instead of searching for a url. Console commands wont use a url, queues, etc.

The .env var wouldn't work well when using something like Envoyer.io that shares the .env file between all the servers within a project.

**Comment by Donny5300** [comment]
> > Would be nice to be able to set a .env parameter like TELESCOPE_IDENTIFIER=webserver or TELESCOPE_IDENTIFIER=API
> > This way you will be able to generate overview and see what app it is instead of searching for a url. Console commands wont use a url, queues, etc.
> 
> The .env var wouldn't work well when using something like Envoyer.io that shares the .env file between all the servers within a project.

That means that you will lose all flexibility for your application when you use Envoyer? I cant imagine that you cant have a API, Queue, Console Commands or any other type of application with a different .env file... 

Anyway, I added it with a PR #226

**Comment by rufhausen** [comment]
You are correct. You can have separate .env files per server. However, envoyer offers the convenience of sharing one and maintaning it via the envoyer UI, which makes it way easier to maintain when u have multiple app servers and worker servers using the same codebase.

**Comment by themsaid** [comment]
As I shared in a previous comment, the hostname is recorded on every single entry. In the preview screen you can find which host this entry was recorded from.

**Comment by deleugpn** [comment]
@themsaid I don't think that's as powerful. I can have multiple Docker Containres running the same hostname behind a load balancer. An environment variable would be so much more powerful as it would allow the developer to choose whatever strategy they want.

- Everything logging with the same name.
- Each microservice with a different name;
- Each container of each microservice with a different name;
- All Web Containers with the same name, but all background (artisan, schedule) containers with different names.

Or even a mix of strategies e.g. a few related microservices with one name and a few others with another name.

**Comment by themsaid** [comment]
@deleugpn feel free to open a PR
