### ISSUE TITLE
Authorization fails

### ISSUE THREAD

**Issue by eossa** [laravel/telescope#178]
I change the gate method in TelescopeServiceProvider:

```
Gate::define('viewTelescope', function ($user) {
    return in_array($user->username, [
        '1234567890',
    ]);
});
```

Instead of use the email attribute I use the username attribute for login, however in production returns a 403 response when I am logged with the user with that username.

**Comment by fridzema** [comment]
By default the laravel users table uses the `name` column for username, do you have changed this?
Have you tried to access before changing it?

**Comment by themsaid** [comment]
That's something in your code, you'll need to look deeper.

**Comment by eossa** [comment]
I found the trouble, I had not register the **TelescopeServiceProvider** in my *config/app.php*.

**Comment by struyfv** [comment]
Hi, I have the same issue and I registered the TelescopeServiceProvider.

My code:

```
protected function gate()
    {
//        dd('test');
        Gate::define('viewTelescope', function ($user) {
            dd($user);
            return in_array($user->email, [
                'email'
            ]);
        });
    }
```
When I uncomment dd('test'); I see it, but the code never stops at dd($user);

Any idea?

**Comment by baekerIT** [comment]
Hi,

i’ve a solution, but don’t have the time to look now. This evening I  will look through my current project, where the problem has caused.

**Comment by struyfv** [comment]
I found out why it didn't work. I didn't use the default 'web' guard for auth.

**Comment by luqmanrom** [comment]
@baekerIT I don't think you need to remove `Authorize::class`. The only time it will allow only locals if your Telescope auth callback is not defined. If your TelescopeServiceProvider is properly defined, the callback and the viewTelescope gate will be defined there. 


Make sure these things:

1. Include `TelescopeServiceProvider` in `config/telescope.php`
2. Clear the config cache - `php artisan config:clear`
3. Clear the compiled files - `php artisan clear-compiled`

Hope it works

**Comment by swilla** [comment]
I was fighting with this for a while, and what I needed to do was remove `laravel\telescope` from the `dont-discover` list in composer.json, then all the conditional loading describe in the documentation worked as expected.

**Comment by mateo2181** [comment]
How can I include TelescopeServiceProvider in config/telescope.php?

**Comment by fridzema** [comment]
@mateo2181 you must include it in `config/app.php`

**Comment by mateo2181** [comment]
Yes, I did it and works. Thanks!

**Comment by MutedFaith** [comment]
> I've got following Solution for reach Telescope in Production:
> 
> Remove the Authorize::class from Telescope Middleware in config/telescope.php
> 
> The Authorize Middleware restricts any access to telescope except local

This approach will give users access to telescope whether authenticated or not. It's not advisable to do this.
