### ISSUE TITLE
Illuminate\Database\QueryException - Deadlock 

### ISSUE THREAD

**Issue by michaelnguyen547** [laravel/telescope#180]
Sentry.io caught this (Horizon https://github.com/laravel/horizon/issues/412) - I have no ideas if Horizon or Telescope causes this

horizon.stats.index
SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction (SQL: insert into telescope_entries (batch_id, content, created_at, type, uuid) values (8c1bafb1-0d89-48c3-a828-1fe95669c19f, {"type":"hit","key":"1qXuDwVKWrhXcgNzyq4rVlC5aB6t9y0xbBxZB07D","value":"a:5:{s:6:"_token";s:40:"j8ohwNnI04jxDH9L0DSgnmrxX22lnzhI4T5VcIHq";s:9:"_previous";a:1:{s:3:"url";s:37:"http://localhost/horizon/api/workload";}s:22:"PHPDEBUGBAR_STACK_DATA";a:0:{}s:6:"_flash";a:2:{s:3:"old";a:0:{}s:3:"new";a:0:{}}s:52:"login_admin_59ba36addc2b2f9401580f014c7f58ea4e30989d";i:2;}","hostname":"homestead"}, 2018-10-25 22:09:55, cache, 8c1bafb0-9cca-4007-b765-92c75ddf2dc4), (8c1bafb1-0d89-48c3-a828-1fe95669c19f, {"uri":"horizon/api/stats","method":"GET","headers":{"cookie":"XSRF-TOKEN=eyJpdiI6InhNVUFIekYrYkRoRVg0eXFTQWkzQXc9PSIsInZhbHVlIjoiMWRZN0Myc25TQUdaN1wvZVFmc3FIbjRjU2RMUjBRaWZhNHpOUHN2VlgwYWI2YWxZTlFjdTExd1ZjUVhWVTZja0kiLCJtYWMiOiJlNmRmNzg

horizon.masters.index

SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction (SQL: delete from telescope_entries where type = command and sequence not in (select sequence from (select sequence from telescope_entries where type = command order by sequence desc limit 100) as entries_temp))

**Comment by PandaTheSlayer** [comment]
Same

**Comment by fridzema** [comment]
Also had this a lot of times for random models

**Comment by necenzurat** [comment]
Same issue when TELESCOPE_LIMIT was 10000 or 100.

**Comment by umerabbas** [comment]
Same Issue

**Comment by paras-malhotra** [comment]
Now that pruning is removed from the core package, is this still an issue with `dev-master`?

**Comment by michaelnguyen547** [comment]
> Now that pruning is removed from the core package, is this still an issue with `dev-master`?

I am updating to v0.1.5 and still have deadlock issue

**Comment by paras-malhotra** [comment]
You can always `composer require laravel/telescope:^1.0` at your own risk since it hasn't been released yet.

**Comment by michaelnguyen547** [comment]
> You can always `composer require laravel/telescope:^1.0` at your own risk since it hasn't been released yet.

- The requested package laravel/telescope ^1.0 is satisfiable by laravel/telescope[1.0.x-dev] but these conflict with your requirements or minimum-stability.

I tried `composer require laravel/telescope=1.0.x-dev` which give me the `dev-master cb05ac7` not the 1.0 branch

**Comment by paras-malhotra** [comment]
You need to set `"minimum-stability": "dev"` in your `composer.json`

**Comment by michaelnguyen547** [comment]
> You need to set `"minimum-stability": "dev"` in your `composer.json`

did that, but composer still loads the `dev-master db05ac7`, not 1.0 branch

**Comment by paras-malhotra** [comment]
Try now with the new v0.1.6 release

**Comment by michaelnguyen547** [comment]
using v0.1.6 atm, so far no more deadlock, i keep checking it for the next few days

**Comment by themsaid** [comment]
Thanks everyone.
