### ISSUE TITLE
1 application, multiple servers

### ISSUE THREAD

**Issue by Donny5300** [laravel/telescope#181]
I would love to start with the fact that this is really great, thank you!

Im running into an issue and I think that there are more people on that. When you have one application running on multiple servers which have different meanings (1 server for console commands, 1 for the queue, 1 for the web app, etc. etc.) its hard to track on which server something happend. Is there a solution or "nice to know" for this issue?

Small thing: working with subdomains might cause some confusion cause you need 1 or 2 clicks extra to figure out the domain.

**Comment by tillkruss** [comment]
Duplicate of #177.

**Comment by Donny5300** [comment]
My bad, couldnt find anything about it!
