### ISSUE TITLE
Mobile App - usage

### ISSUE THREAD

**Issue by pavankumarkatakam** [laravel/telescope#183]
Hi @taylorotwell and contributors of this package, I'm very excited to see and use this package it really helpful for debugging, is scheduler is working as configured, list of jobs pipeline and many more. Actually, I have thought of to build like this package and but not able to do. But I'm now thinking to build a mobile app (Android and iOS) for this package which will become handier for exceptions, requests etc. I have also seen the code for all watchers it is very flexible and can also register for our own watchers I think. 

Before building the app I would like to know the opinion of yours and other Laravel users as well. And if anybody interested to help me in designing the screens.

**Comment by pavankumarkatakam** [comment]
Below are my current work on this
![1 applications](https://user-images.githubusercontent.com/6078669/48313397-ee1bc600-e5e1-11e8-8d7f-9465f875dca6.jpeg)
![2 menu1](https://user-images.githubusercontent.com/6078669/48313398-eeb45c80-e5e1-11e8-9ba6-e7deb9a725ec.jpeg)
![3 menu2](https://user-images.githubusercontent.com/6078669/48313399-eeb45c80-e5e1-11e8-890f-d8f4f2ef0d12.jpeg)
![4 monitoring](https://user-images.githubusercontent.com/6078669/48313400-eeb45c80-e5e1-11e8-8470-9be1dd011cd3.jpeg)
![5 tag_form](https://user-images.githubusercontent.com/6078669/48313401-ef4cf300-e5e1-11e8-96f5-961a4f68e0b7.jpeg)
![6 tag_delete](https://user-images.githubusercontent.com/6078669/48313402-ef4cf300-e5e1-11e8-9bf2-9a1be110cbf9.jpeg)
![7 requests](https://user-images.githubusercontent.com/6078669/48313403-efe58980-e5e1-11e8-9e06-d8e5bd837938.jpeg)
![8 request_details](https://user-images.githubusercontent.com/6078669/48313404-efe58980-e5e1-11e8-93bf-77f81d908a72.jpeg)

**Comment by pavankumarkatakam** [comment]
To achieve this fully, the UI and backend code should be decoupled at few places like  the config "path" is directly binded in blade to javascript, that needs to be also an API.
`\Laravel\Telescope\Telescope::scriptVariables()`

**Comment by paras-malhotra** [comment]
The screens look really nice, awesome job so far @pavankumarkatakam 👏

**Comment by pavankumarkatakam** [comment]
Thank @paras-malhotra

**Comment by themsaid** [comment]
Hey @pavankumarkatakam great work!

Telescope routes are protected from outside access using an auth guard, currently session authentication is the default so I'm not sure how a mobile app will read from Telescope internal API.

The api was built to be used inside Telescope dashboard not the outside world :)

I'm closing this for now since it's not really related to Telescope.

If you want to continue building your app I suggest that you create a package that reads from Telescope database and expose an API the mobile app can read.

**Comment by paras-malhotra** [comment]
@themsaid just a thought - users who want to use the app can always replace the `Authorize` middleware in the `config/nova.php` file with the mobile app package's middleware that may support multiple guards. That way, the app may be able to read from the Telescope internal API.

**Comment by pavankumarkatakam** [comment]
@themsaid , I thought the authentication for only API projects (no session) (only JSON no blade)(using the login settings like Header name, how token generate etc) is in your roadmap. If  it is not then even the telescope web interface will not work in production for API projects. Is that right?
