### ISSUE TITLE
Overflow in tables

### ISSUE THREAD

**Issue by SimoneStefani** [laravel/telescope#184]
**Actual result:** long path strings (for example in Requests section) cause some columns to overflow the table layout.

**Expected result:** strings shouldn't cause columns overflow no matter how long they are. Maybe a solution can be to truncate them and/or adding ellipsis? Probably this is not enough:
https://github.com/laravel/telescope/blob/f9ee91ef63d3e139e0e4941e546014955b5f81c9/resources/js/screens/requests/index.vue#L29

**Screenshot of the issue:**
![screenshot 2018-10-26 at 09 07 25](https://user-images.githubusercontent.com/13915504/47550365-4de65180-d8ff-11e8-8941-b4b8ef9545a5.png)

**Comment by themsaid** [comment]
fixed

**Comment by SimoneStefani** [comment]
Thanks a lot!

**Comment by rolandstarke** [comment]
The table is a little bit to wide for me.
![to_wide](https://user-images.githubusercontent.com/5196813/52520345-db5c7000-2c68-11e9-959d-d29722a120b4.png)

What do you think about a css solution? (works fine in Chrome, Edge, FF)

```css
{
    max-width: 1px;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
}
```


![css_ellipsis](https://user-images.githubusercontent.com/5196813/52520570-dac4d900-2c6a-11e9-980e-0c7150b7c353.png)
