### ISSUE TITLE
Events not tracked when fired via tinker

### ISSUE THREAD

**Issue by mrmonat** [laravel/telescope#189]
I have some custom events, and if I trigger them via Laravel Tinker, the events don't show up in telescope.

**Comment by themsaid** [comment]
Please share steps to replicate, I can't replicate it.

**Comment by mrmonat** [comment]
All I did was 

`php artisan make:event TestEvent`

`php artisan tinker`

`event(new App\Events\TestEvent())`

but then no new event appeared in Telescope

**Comment by minhajul** [comment]
In my cases:

`  $user = \App\User::find(1);
    event(new \App\Events\TestEvent($user));`

This event firing is not tracking by telescope. But when I am returning something after firing an event
like this

`  $user = \App\User::find(1);
    event(new \App\Events\TestEvent($user));
    return view('welcome');`

is perfectly working.

**Comment by Donovan-H** [comment]
@themsaid where you able to replicate with those steps?

**Comment by paras-malhotra** [comment]
I can confirm that no entries are logged on Tinker (except a command type entry). Not sure why this happens as all other commands seem to work. Something to do with the Psy Shell maybe? @themsaid @deleugpn thoughts?

**Comment by themsaid** [comment]
It’s because the app never terminates, Telescope stores the entries when the app terminates or a worker loop is over. So it won’t work with Tinker.

**Comment by paras-malhotra** [comment]
Makes sense, I think we can then make a note in the docs and close this issue.

**Comment by trideout** [comment]
If you `return false` in tinker before exiting it should exit correctly.

**Comment by themsaid** [comment]
Check https://github.com/laravel/telescope/issues/189#issuecomment-436055512

**Comment by Dartanjan** [comment]
Not sure if this helps anyone, but after I did
```
app()->terminate()
```
in Tinker, I was able to see the SQL log in Telescope that I wasn't seeing with `return false` or such.
