### ISSUE TITLE
High database usage in telescope.

### ISSUE THREAD

**Issue by einnar82** [laravel/telescope#212]
Hello, 

Thank you for the wonderful package. I noticed that laravel telescope saves all application transactions to the database. My question was if we continue to used it and push it into production, does the database usage may higher because of laravel telescope activities?

**Comment by silyont** [comment]
Telescope is developed for debugging. You won't debug on production. Moreover, keeping Telescope on production might lead to more security issue such as exposing the requests to the server. If you want to track the relevant data, I suggest you write your own log.

**Comment by deleugpn** [comment]
I plan on using Telescope on production 24/7. I think the database problem can be mitigated by having a dedicated database only for Telescope and worst case scenario Telescope can just push to a queue and be processed on the background.
Writing your own log has a much higher chance of being vulnerable to known security issues than a well established open source project.
I'm not using Telescope on production yet due to its maturity (still on beta) and I'm working on bringing a decent test suite to the project to help it reach the necessary maturity for me to take advantage of its power on production systems.

**Comment by paras-malhotra** [comment]
> Telescope is developed for debugging. You won't debug on production.

I don't think that's the intent of Laravel Telescope. If you read any of [Matt's blog](https://mattstauffer.com/blog/introducing-laravel-telescope/) or [@themsaid's video](https://www.twitch.tv/videos/324620558) or even [the code](https://github.com/laravel/telescope/blob/ad91b6805c90d35bb3538b252897347021731948/stubs/TelescopeServiceProvider.stub#L26), all of them mention the possibility of using Laravel Telescope in production.

**Comment by silyont** [comment]
> > Telescope is developed for debugging. You won't debug on production.
> 
> I don't think that's the intent of Laravel Telescope. If you read [Matt's blog](https://mattstauffer.com/blog/introducing-laravel-telescope/) or listen to [@themsaid's video](https://www.twitch.tv/videos/324620558) or even take a look at [the code](https://github.com/laravel/telescope/blob/ad91b6805c90d35bb3538b252897347021731948/stubs/TelescopeServiceProvider.stub#L26), all of them mention the possibility of using Laravel Telescope in production.

Yes, maybe I misunderstood the target of Laravel Telescope.

**Comment by paras-malhotra** [comment]
#235 may address this issue I think

**Comment by jonJKF** [comment]
I feel like a lot of the way Telescope is architected would work well with Redis lists, I see in the config there are options for the storage but haven't yet seen any documentation yet to suggest alternatives to the default "database" storage method. Currently getting lots of database traffic and deadlock issues with the default driver even in a low traffic staging environment so I'm sure an alternative storage location would be preferred.

**Comment by themsaid** [comment]
Hey guys,

I will personally use Telescope for production, however I wouldn't record everything, just things I need to look at, for example if a specific user is having an issue I'll just monitor requests coming from this user.

If you plan to record everything then yes the database storage driver isn't the best solution, we're open to new driver implementations that would make more sense.
