### ISSUE TITLE
Queries Sorting By Duration

### ISSUE THREAD

**Issue by HDVinnie** [laravel/telescope#213]
### Issue Type
- [x] Feature Idea

Would be nice to be able to sort queries by duration to be able to see which queries are taking the longest to perform.

**Comment by pavankumarkatakam** [comment]
At present all entries including query also is sorting by `sequence` column this is hardcoded for Database Repository. But sequence number is not showing in the frontend part. I think showing the sequence number will also be useful. To achieve sorting with time which is actually a json field in content column EloquentQueryOptions needs to be changed.

**Comment by themsaid** [comment]
Slow queries are tagged under `slow`, you can search with this tag and it'll show you all the slow queries.
