### ISSUE TITLE
Doesn't work with oracle database

### ISSUE THREAD

**Issue by azzozhsn** [laravel/telescope#214]
Hello,

It seems there is an issue with storing big text with oracle, I'm not sure is it a Telescope's problem or EntriesRepository's. The error message looks like this:

> [2018-10-28 07:42:42] local.ERROR: oci_bind_by_name(): Invalid variable used for bind (SQL: insert into "TELESCOPE_ENTRIES" ("BATCH_ID", "CONTENT", "CREATED_AT", "TYPE", "UUID") select 8c20827f-62c0-4928-aa68-eb69e2de7c81, {"name":"modules.assistance.register","payload":[{"class":"Nwidart\\Modules\\Laravel\\Module","properties":[]}],"listeners":[],"broadcast":false,"hostname":"azzozhsn.local"}, 2018-10-28 07:42:42, event, 8c20827f-0bab-46e9-bf8d-04039b59396b from dual union all select 8c20827f-62c0-4928-aa68-eb69e2de7c81, {"name":"modules.attendance.register","payload":[{"class":"Nwidart\\Modules\\Laravel\\Module","properties":[]}],"listeners":[],"broadcast":false,"hostname":"azzozhsn.local"}, 2018-10-28 07:42:42, event, 8c20827f-0c5c-4f87-a40a-0befd2375a04 from dual union all select 8c20827f-62c0-4928-aa68-eb69e2de7c81, {"name":"modules.auth.register","payload":[{"class":"Nwidart\\Modules\\Laravel\\Module","properties":[]}],"listeners":[],"broadcast":false,"hostname":"azzozhsn.local"}, 2018-10-28 07:42:42, event, 8c20827f-0c82-4926-8cfd-b2dabd3ed377 from dual union all select 8c20827f-62c0-4928-aa68-eb69e2de7c81, {"name":"modules.dashboard.register","payload":[{"class":"Nwidart\\Modules\\Laravel\\Module","properties":[]}],"listeners":[],"broadcast":false,"hostname":"azzozhsn.local"}, 2018-10-28 07:42:42, event, 8c20827f-0ca5-4a44-a59d-ad4cfb1e553b from dual union all select 8c20827f-62c0-4928-aa68-eb69e2de7c81, {"name":"modules.processes.register","payload":[{"class":"Nwidart\\Modules\\Laravel\\Module","properties":[]}],"listeners":[],"broadcast":false,"hostname":"azzozhsn.local"}, 2018-10-28 07:42:42, event, 8c20827f-0cc6-460f-bf0a-c4fb4df6d89f from dual union all select 8c20827f-62c0-4928-aa68-eb69e2de7c81, {"name":"modules.vacations.register","payload":[{"class":"Nwidart\\Modules\\Laravel\\Module","properties":[]}],"listeners":[],"broadcast":false,"hostname":"azzozhsn.local"}, 2018-10-28 07:42:42, event, 8c20827f-0cf4-4d20-af02-f7f109d2fb66 from dual union all select 8c20827f-62c0-4928-aa68-eb69e2de7c81, {"name":"modules.visitors.register","payload":[{"class":"Nwidart\\Modules\\Laravel\\Module","properties":[]}],"listeners":[],"broadcast":false,"hostname":"azzozhsn.local"}, 2018-10-28 07:42:42, event, 8c20827f-0d17-4222-acf4-eb7e046ca23d from dual union all select 8c20827f-62c0-4928-aa68-eb69e2de7c81, {"name":"modules.assistance.boot","payload":[{"class":"Nwidart\\Modules\\Laravel\\Module","properties":[]}],"listeners":[],"broadcast":false,"hostname":"azzozhsn.local"}, 2018-10-28 07:42:42, event, 8c20827f-0ecc-4443-9d06-4a7e05360156 from dual union all select 8c20827f-62c0-4928-aa68-eb69e2de7c81, {"name":"modules.attendance.boot","payload":[{"class":"Nwidart\\Modules\\Laravel\\Module","properties":[]}],"listeners":[],"broadcast":false,"hostname":"azzozhsn.local"}, 2018-10-28 07:42:42, event, 8c20827f-0ee1-4e17-a24b-0d70c19f5f36 from dual union all select 8c20827f-62c0-4928-aa68-eb69e2de7c81, {"name":"modules.auth.boot","payload":[{"class":"Nwidart\\Modules\\Laravel\\Module","properties":[]}],"listeners":[],"broadcast":false,"hostname":"azzozhsn.local"}, 2018-10-28 07:42:42, event, 8c20827f-0ef1-43ef-8e62-ad20cff5fbb8 from dual union all select 8c20827f-62c0-4928-aa68-eb69e2de7c81, {"name":"modules.dashboard.boot","payload":[{"class":"Nwidart\\Modules\\Laravel\\Module","properties":[]}],"listeners":[],"broadcast":false,"hostname":"azzozhsn.local"}, 2018-10-28 07:42:42, event, 8c20827f-0f01-490d-8c66-326270c807f0 from dual union all select 8c20827f-62c0-4928-aa68-eb69e2de7c81, {"name":"modules.processes.boot","payload":[{"class":"Nwidart\\Modules\\Laravel\\Module","properties":[]}],"listeners":[],"broadcast":false,"hostname":"azzozhsn.local"}, 2018-10-28 07:42:42, event, 8c20827f-0f14-4679-ab86-95a0532b5a6d from dual union all select 8c20827f-62c0-4928-aa68-eb69e2de7c81, {"name":"modules.vacations.boot","payload":[{"class":"Nwidart\\Modules\\Laravel\\Module","properties":[]}],"listeners":[],"broadcast":false,"hostname":"azzozhsn.local"}, 2018-10-28 07:42:42, event, 8c20827f-0f28-492f-b853-c7b7720580b3 from dual union all select 8c20827f-62c0-4928-aa68-eb69e2de7c81, {"name":"modules.visitors.boot","payload":[{"class":"Nwidart\\Modules\\Laravel\\Module","properties":[]}],"listeners":[],"broadcast":false,"hostname":"azzozhsn.local"}, 2018-10-28 07:42:42, event, 8c20827f-0f36-40d8-8344-36492ccfc024 from dual union all select 8c20827f-62c0-4928-aa68-eb69e2de7c81, {"uri":"\/","method":"GET","headers":{"cache-control":"max-age=0","upgrade-insecure-requests":"1","cookie":"XSRF-TOKEN=eyJpdiI6IktkNWlYWWI0clRrdXU3WlE4TVNlMkE9PSIsInZhbHVlIjoiVGJHclhPYnBXclhIMDdyNWQra3NIaDlsYnByQlI3aForOTRFRmFkTWFERHUxUmlrb3lUVFhmdmlzVGpYMllxMCIsIm1hYyI6IjgxYTA3ZTkyNTY4Yzk0NWY5MjUzYmE0ZDcwNGU5MGU5Njc3ZTZmZDE3NGViZWY3YWQ1MDAzOTc1ZWY1N2RmM2EifQ%3D%3D; laravel_session=eyJpdiI6ImdvT2ZVVXBzbUc2NVdqMkp1ZHNIMGc9PSIsInZhbHVlIjoieU1EamNueGRnamNFWFpVNTRYa1Uyd1dFTVVQdkNON2tnT2N4Tmx1cmVSU1czcUs3UDFGQjRYVnJvUFFzMnE2XC8iLCJtYWMiOiIyZjk1Y2FjMDM3MWFjNmNkNTVhYjE3OWNmZDA2NzUwZGQzZWM5OThhMmM0MGRlYjk4MDkxYWNiMTJkYzFhYTEyIn0%3D","connection":"keep-alive","dnt":"1","referer":"http:\/\/eimarah.test\/api\/vacations\/requests\/qarar\/2015990","accept-encoding":"gzip, deflate","accept-language":"en-US,en;q=0.5","accept":"text\/html,application\/xhtml+xml,application\/xml;q=0.9,*\/*;q=0.8","user-agent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10.13; rv:63.0) Gecko\/20100101 Firefox\/63.0","host":"eimarah.test","content-length":"","content-type":""},"payload":[],"session":{"_token":"efM9RoVB9sgywxawi9lGbxOtSbpbmUKrxYwrHTXt","_previous":{"url":"http:\/\/eimarah.test"},"PHPDEBUGBAR_STACK_DATA":[],"_flash":{"old":[],"new":[]}},"response_status":200,"response":"HTML Response","hostname":"azzozhsn.local"}, 2018-10-28 07:42:42, request, 8c20827f-521d-4532-a155-97a5a4a55d89 from dual ) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 0): oci_bind_by_name(): Invalid variable used for bind (SQL: insert into \"TELESCOPE_ENTRIES\" (\"BATCH_ID\", \"CONTENT\", \"CREATED_AT\", \"TYPE\", \"UUID\") select 8c20827f-62c0-4928-aa68-eb69e2de7c81, {\"name\":\"modules.assistance.register\",\"payload\":[{\"class\":\"Nwidart\\\\Modules\\\\Laravel\\\\Module\",\"properties\":[]}],\"listeners\":[],\"broadcast\":false,\"hostname\":\"azzozhsn.local\"}, 2018-10-28 07:42:42, event, 8c20827f-0bab-46e9-bf8d-04039b59396b from dual union all select 8c20827f-62c0-4928-aa68-eb69e2de7c81, {\"name\":\"modules.attendance.register\",\"payload\":[{\"class\":\"Nwidart\\\\Modules\\\\Laravel\\\\Module\",\"properties\":[]}],\"listeners\":[],\"broadcast\":false,\"hostname\":\"azzozhsn.local\"}, 2018-10-28 07:42:42, event, 8c20827f-0c5c-4f87-a40a-0befd2375a04 from dual union all select 8c20827f-62c0-4928-aa68-eb69e2de7c81, {\"name\":\"modules.auth.register\",\"payload\":[{\"class\":\"Nwidart\\\\Modules\\\\Laravel\\\\Module\",\"properties\":[]}],\"listeners\":[],\"broadcast\":false,\"hostname\":\"azzozhsn.local\"}, 2018-10-28 07:42:42, event, 8c20827f-0c82-4926-8cfd-b2dabd3ed377 from dual union all select 8c20827f-62c0-4928-aa68-eb69e2de7c81, {\"name\":\"modules.dashboard.register\",\"payload\":[{\"class\":\"Nwidart\\\\Modules\\\\Laravel\\\\Module\",\"properties\":[]}],\"listeners\":[],\"broadcast\":false,\"hostname\":\"azzozhsn.local\"}, 2018-10-28 07:42:42, event, 8c20827f-0ca5-4a44-a59d-ad4cfb1e553b from dual union all select 8c20827f-62c0-4928-aa68-eb69e2de7c81, {\"name\":\"modules.processes.register\",\"payload\":[{\"class\":\"Nwidart\\\\Modules\\\\Laravel\\\\Module\",\"properties\":[]}],\"listeners\":[],\"broadcast\":false,\"hostname\":\"azzozhsn.local\"}, 2018-10-28 07:42:42, event, 8c20827f-0cc6-460f-bf0a-c4fb4df6d89f from dual union all select 8c20827f-62c0-4928-aa68-eb69e2de7c81, {\"name\":\"modules.vacations.register\",\"payload\":[{\"class\":\"Nwidart\\\\Modules\\\\Laravel\\\\Module\",\"properties\":[]}],\"listeners\":[],\"broadcast\":false,\"hostname\":\"azzozhsn.local\"}, 2018-10-28 07:42:42, event, 8c20827f-0cf4-4d20-af02-f7f109d2fb66 from dual union all select 8c20827f-62c0-4928-aa68-eb69e2de7c81, {\"name\":\"modules.visitors.register\",\"payload\":[{\"class\":\"Nwidart\\\\Modules\\\\Laravel\\\\Module\",\"properties\":[]}],\"listeners\":[],\"broadcast\":false,\"hostname\":\"azzozhsn.local\"}, 2018-10-28 07:42:42, event, 8c20827f-0d17-4222-acf4-eb7e046ca23d from dual union all select 8c20827f-62c0-4928-aa68-eb69e2de7c81, {\"name\":\"modules.assistance.boot\",\"payload\":[{\"class\":\"Nwidart\\\\Modules\\\\Laravel\\\\Module\",\"properties\":[]}],\"listeners\":[],\"broadcast\":false,\"hostname\":\"azzozhsn.local\"}, 2018-10-28 07:42:42, event, 8c20827f-0ecc-4443-9d06-4a7e05360156 from dual union all select 8c20827f-62c0-4928-aa68-eb69e2de7c81, {\"name\":\"modules.attendance.boot\",\"payload\":[{\"class\":\"Nwidart\\\\Modules\\\\Laravel\\\\Module\",\"properties\":[]}],\"listeners\":[],\"broadcast\":false,\"hostname\":\"azzozhsn.local\"}, 2018-10-28 07:42:42, event, 8c20827f-0ee1-4e17-a24b-0d70c19f5f36 from dual union all select 8c20827f-62c0-4928-aa68-eb69e2de7c81, {\"name\":\"modules.auth.boot\",\"payload\":[{\"class\":\"Nwidart\\\\Modules\\\\Laravel\\\\Module\",\"properties\":[]}],\"listeners\":[],\"broadcast\":false,\"hostname\":\"azzozhsn.local\"}, 2018-10-28 07:42:42, event, 8c20827f-0ef1-43ef-8e62-ad20cff5fbb8 from dual union all select 8c20827f-62c0-4928-aa68-eb69e2de7c81, {\"name\":\"modules.dashboard.boot\",\"payload\":[{\"class\":\"Nwidart\\\\Modules\\\\Laravel\\\\Module\",\"properties\":[]}],\"listeners\":[],\"broadcast\":false,\"hostname\":\"azzozhsn.local\"}, 2018-10-28 07:42:42, event, 8c20827f-0f01-490d-8c66-326270c807f0 from dual union all select 8c20827f-62c0-4928-aa68-eb69e2de7c81, {\"name\":\"modules.processes.boot\",\"payload\":[{\"class\":\"Nwidart\\\\Modules\\\\Laravel\\\\Module\",\"properties\":[]}],\"listeners\":[],\"broadcast\":false,\"hostname\":\"azzozhsn.local\"}, 2018-10-28 07:42:42, event, 8c20827f-0f14-4679-ab86-95a0532b5a6d from dual union all select 8c20827f-62c0-4928-aa68-eb69e2de7c81, {\"name\":\"modules.vacations.boot\",\"payload\":[{\"class\":\"Nwidart\\\\Modules\\\\Laravel\\\\Module\",\"properties\":[]}],\"listeners\":[],\"broadcast\":false,\"hostname\":\"azzozhsn.local\"}, 2018-10-28 07:42:42, event, 8c20827f-0f28-492f-b853-c7b7720580b3 from dual union all select 8c20827f-62c0-4928-aa68-eb69e2de7c81, {\"name\":\"modules.visitors.boot\",\"payload\":[{\"class\":\"Nwidart\\\\Modules\\\\Laravel\\\\Module\",\"properties\":[]}],\"listeners\":[],\"broadcast\":false,\"hostname\":\"azzozhsn.local\"}, 2018-10-28 07:42:42, event, 8c20827f-0f36-40d8-8344-36492ccfc024 from dual union all select 8c20827f-62c0-4928-aa68-eb69e2de7c81, {\"uri\":\"\\/\",\"method\":\"GET\",\"headers\":{\"cache-control\":\"max-age=0\",\"upgrade-insecure-requests\":\"1\",\"cookie\":\"XSRF-TOKEN=eyJpdiI6IktkNWlYWWI0clRrdXU3WlE4TVNlMkE9PSIsInZhbHVlIjoiVGJHclhPYnBXclhIMDdyNWQra3NIaDlsYnByQlI3aForOTRFRmFkTWFERHUxUmlrb3lUVFhmdmlzVGpYMllxMCIsIm1hYyI6IjgxYTA3ZTkyNTY4Yzk0NWY5MjUzYmE0ZDcwNGU5MGU5Njc3ZTZmZDE3NGViZWY3YWQ1MDAzOTc1ZWY1N2RmM2EifQ%3D%3D; laravel_session=eyJpdiI6ImdvT2ZVVXBzbUc2NVdqMkp1ZHNIMGc9PSIsInZhbHVlIjoieU1EamNueGRnamNFWFpVNTRYa1Uyd1dFTVVQdkNON2tnT2N4Tmx1cmVSU1czcUs3UDFGQjRYVnJvUFFzMnE2XC8iLCJtYWMiOiIyZjk1Y2FjMDM3MWFjNmNkNTVhYjE3OWNmZDA2NzUwZGQzZWM5OThhMmM0MGRlYjk4MDkxYWNiMTJkYzFhYTEyIn0%3D\",\"connection\":\"keep-alive\",\"dnt\":\"1\",\"referer\":\"http:\\/\\/eimarah.test\\/api\\/vacations\\/requests\\/qarar\\/2015990\",\"accept-encoding\":\"gzip, deflate\",\"accept-language\":\"en-US,en;q=0.5\",\"accept\":\"text\\/html,application\\/xhtml+xml,application\\/xml;q=0.9,*\\/*;q=0.8\",\"user-agent\":\"Mozilla\\/5.0 (Macintosh; Intel Mac OS X 10.13; rv:63.0) Gecko\\/20100101 Firefox\\/63.0\",\"host\":\"eimarah.test\",\"content-length\":\"\",\"content-type\":\"\"},\"payload\":[],\"session\":{\"_token\":\"efM9RoVB9sgywxawi9lGbxOtSbpbmUKrxYwrHTXt\",\"_previous\":{\"url\":\"http:\\/\\/eimarah.test\"},\"PHPDEBUGBAR_STACK_DATA\":[],\"_flash\":{\"old\":[],\"new\":[]}},\"response_status\":200,\"response\":\"HTML Response\",\"hostname\":\"azzozhsn.local\"}, 2018-10-28 07:42:42, request, 8c20827f-521d-4532-a155-97a5a4a55d89 from dual ) at /Users/azzozhsn/Sites/eimarah/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, ErrorException(code: 0): oci_bind_by_name(): Invalid variable used for bind at /Users/azzozhsn/Sites/eimarah/vendor/yajra/laravel-pdo-via-oci8/src/Pdo/Oci8/Statement.php:491)
> [stacktrace]
> #0 /Users/azzozhsn/Sites/eimarah/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('insert into \"TE...', Array, Object(Closure))
> #1 /Users/azzozhsn/Sites/eimarah/vendor/laravel/framework/src/Illuminate/Database/Connection.php(459): Illuminate\\Database\\Connection->run('insert into \"TE...', Array, Object(Closure))
> #2 /Users/azzozhsn/Sites/eimarah/vendor/laravel/framework/src/Illuminate/Database/Connection.php(411): Illuminate\\Database\\Connection->statement('insert into \"TE...', Array)
> #3 /Users/azzozhsn/Sites/eimarah/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2541): Illuminate\\Database\\Connection->insert('insert into \"TE...', Array)
> #4 /Users/azzozhsn/Sites/eimarah/vendor/laravel/telescope/src/Storage/DatabaseEntriesRepository.php(117): Illuminate\\Database\\Query\\Builder->insert(Array)
> #5 /Users/azzozhsn/Sites/eimarah/vendor/laravel/telescope/src/Telescope.php(439): Laravel\\Telescope\\Storage\\DatabaseEntriesRepository->store(Object(Illuminate\\Support\\Collection))
> #6 /Users/azzozhsn/Sites/eimarah/vendor/laravel/telescope/src/ListensForStorageOpportunities.php(44): Laravel\\Telescope\\Telescope::store(Object(Laravel\\Telescope\\Storage\\DatabaseEntriesRepository))
> #7 [internal function]: Laravel\\Telescope\\Telescope::Laravel\\Telescope\\{closure}()
> #8 /Users/azzozhsn/Sites/eimarah/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Object(Closure), Array)
> #9 /Users/azzozhsn/Sites/eimarah/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(75): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
> #10 /Users/azzozhsn/Sites/eimarah/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Object(Closure), Object(Closure))
> #11 /Users/azzozhsn/Sites/eimarah/vendor/laravel/framework/src/Illuminate/Container/Container.php(572): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Object(Closure), Array, NULL)
> #12 /Users/azzozhsn/Sites/eimarah/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(965): Illuminate\\Container\\Container->call(Object(Closure))
> #13 /Users/azzozhsn/Sites/eimarah/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(191): Illuminate\\Foundation\\Application->terminate()
> #14 /Users/azzozhsn/Sites/eimarah/public/index.php(60): Illuminate\\Foundation\\Http\\Kernel->terminate(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\Response))
> #15 /Users/azzozhsn/.composer/vendor/laravel/valet/server.php(147): require('/Users/azzozhsn...')
> #16 {main}

**Comment by themsaid** [comment]
Closing the issue since there's no enough information to take it further and it's not reported by anyone else.

Please open a new issue  if you managed to figure out if it's Telescope-related or not.

**Comment by stickeerehan** [comment]
Having the same issue with telescope not working with Oracle. Error and stack trace below:

[2018-12-19 16:32:39] local.ERROR: oci_bind_by_name(): Invalid variable used for bind (SQL: insert into "TELESCOPE_ENTRIES" ("BATCH_ID", "CONTENT", "CREATED_AT", "TYPE", "UUID") values (8c89db33-090d-4266-b820-48986f3cc180, {"command":"list","exit_code":0,"arguments":{"command":"list","namespace":null},"options":{"raw":false,"format":"txt","help":false,"quiet":false,"verbose":false,"version":false,"ansi":false,"no-ansi":false,"no-interaction":false,"env":null},"hostname":"80f97cc23773"}, 2018-12-19 16:32:39, command, 8c89db33-0616-4441-ae1a-4738622c6227)) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 0): oci_bind_by_name(): Invalid variable used for bind (SQL: insert into \"TELESCOPE_ENTRIES\" (\"BATCH_ID\", \"CONTENT\", \"CREATED_AT\", \"TYPE\", \"UUID\") values (8c89db33-090d-4266-b820-48986f3cc180, {\"command\":\"list\",\"exit_code\":0,\"arguments\":{\"command\":\"list\",\"namespace\":null},\"options\":{\"raw\":false,\"format\":\"txt\",\"help\":false,\"quiet\":false,\"verbose\":false,\"version\":false,\"ansi\":false,\"no-ansi\":false,\"no-interaction\":false,\"env\":null},\"hostname\":\"80f97cc23773\"}, 2018-12-19 16:32:39, command, 8c89db33-0616-4441-ae1a-4738622c6227)) at /var/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, ErrorException(code: 0): oci_bind_by_name(): Invalid variable used for bind at /var/www/vendor/yajra/laravel-pdo-via-oci8/src/Pdo/Oci8/Statement.php:491)

[stacktrace]

#0 /var/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('insert into \"TE...', Array, Object(Closure))
#1 /var/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(459): Illuminate\\Database\\Connection->run('insert into \"TE...', Array, Object(Closure))
#2 /var/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(411): Illuminate\\Database\\Connection->statement('insert into \"TE...', Array)
#3 /var/www/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2598): Illuminate\\Database\\Connection->insert('insert into \"TE...', Array)
#4 /var/www/vendor/laravel/telescope/src/Storage/DatabaseEntriesRepository.php(118): Illuminate\\Database\\Query\\Builder->insert(Array)
#5 /var/www/vendor/laravel/telescope/src/Telescope.php(539): Laravel\\Telescope\\Storage\\DatabaseEntriesRepository->store(Object(Illuminate\\Support\\Collection))
#6 /var/www/vendor/laravel/telescope/src/ListensForStorageOpportunities.php(44): Laravel\\Telescope\\Telescope::store(Object(Laravel\\Telescope\\Storage\\DatabaseEntriesRepository))
#7 [internal function]: Laravel\\Telescope\\Telescope::Laravel\\Telescope\\{closure}()
#8 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Object(Closure), Array)
#9 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(75): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#10 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Object(Closure), Object(Closure))
#11 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(572): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Object(Closure), Array, NULL)
#12 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(967): Illuminate\\Container\\Container->call(Object(Closure))
#13 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(149): Illuminate\\Foundation\\Application->terminate()
#14 /var/www/artisan(49): Illuminate\\Foundation\\Console\\Kernel->terminate(Object(Symfony\\Component\\Console\\Input\\ArgvInput), 0)
#15 {main}


Using laravel 5.7.19, yajra/laravel-oci8 5.7.2 and telescope 1.0.10
