### ISSUE TITLE
Large response payloads not monitored

### ISSUE THREAD

**Issue by paras-malhotra** [laravel/telescope#228]
Any request payload that exceeds the max length of the `content` field in the `telescope_entries` table is not monitored at all.

#166 highlights this issue and I think the discussed solution is to change it mediumtext. The current size restriction for mySQL is 64KB and I think there is a strong use case to not log the response beyond that (to prevent bloating of the telescope database/table).

What's more is that if the response payload exceeds the column size, the other watchers aren't able to log either (e.g. the queries aren't logged even though they can perfectly fit the size restriction).

I think this would is would be quite a common case for users of Telescope and IMO, the Telescope storage class should handle this and possibly store a truncated snippet of the response in such cases. Also, if an insertion of an entry fails, the other entries should not be affected.

**Comment by themsaid** [comment]
until we address this, feel free to run a migration to change the column type in your app.

**Comment by themsaid** [comment]
Long responses will be purged now. check https://github.com/laravel/telescope/pull/291 and https://github.com/laravel/telescope/commit/a643fbd505b2359d7cf5a9be25c26589d3e9543a
