### ISSUE TITLE
[Feature Request] Queue storage of Telescope entries

### ISSUE THREAD

**Issue by paras-malhotra** [laravel/telescope#235]
I think it would be awesome if we add an option to queue the storage of Telescope entries. This would be especially useful for using Laravel Telescope in production from a performance standpoint

**Comment by themsaid** [comment]
entries are stored before kernel shutdown and after each worker cycle, I don't see the point in queueing.

**Comment by paras-malhotra** [comment]
I see, that makes sense. Thanks @themsaid!
