### ISSUE TITLE
419 HTTP status code will be overwritten by 500 HTTP status code

### ISSUE THREAD

**Issue by ForzaSFerrari** [laravel/telescope#238]
After I was faced with the #64 error, I now get the same error with the 500 HTTP status code and there is no workaround at the moment.

I get it on an upgraded version of Telescope, but also on a fresh installed version.

**Comment by reachsampath** [comment]
Same here. I also see the below when i run php artisan telescope:prune
In QueryWatcher.php line 78:     
  Undefined index: file  

I just updated to 0.1.14

**Comment by ForzaSFerrari** [comment]
It's fixed.
