### ISSUE TITLE
Base table or view not found: 1146 Table 'homestead.telescope_entries' doesn't exist when trying to composer require the package

### ISSUE THREAD

**Issue by rs-sliske** [laravel/telescope#241]
Looks like this is trying to record the package:discover command before i have had chance to run the migrations. :(

[2018-10-29 15:06:05] local.ERROR: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'homestead.telescope_entries' doesn't exist (SQL: insert into `telescope_entries` (`batch_id`, `content`, `created_at`, `type`, `uuid`) values (8c23240c-60f0-4435-8031-9b393766394a, {"command":"package:discover","exit_code":0,"arguments":{"command":"package:discover"},"options":{"help":false,"quiet":false,"verbose":false,"version":false,"ansi":false,"no-ansi":false,"no-interaction":false,"env":null},"output":"","hostname":"5b3b6f02f219"}, 2018-10-29 15:06:05, command, 8c23240c-6080-402b-92d3-6bc3bf0b3554)) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'homestead.telescope_entries' doesn't exist (SQL: insert into `telescope_entries` (`batch_id`, `content`, `created_at`, `type`, `uuid`) values (8c23240c-60f0-4435-8031-9b393766394a, {\"command\":\"package:discover\",\"exit_code\":0,\"arguments\":{\"command\":\"package:discover\"},\"options\":{\"help\":false,\"quiet\":false,\"verbose\":false,\"version\":false,\"ansi\":false,\"no-ansi\":false,\"no-interaction\":false,\"env\":null},\"output\":\"\",\"hostname\":\"5b3b6f02f219\"}, 2018-10-29 15:06:05, command, 8c23240c-6080-402b-92d3-6bc3bf0b3554)) at /app/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'homestead.telescope_entries' doesn't exist at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:82, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'homestead.telescope_entries' doesn't exist at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:80)
[stacktrace]
#0 /app/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('insert into `te...', Array, Object(Closure))
#1 /app/vendor/laravel/framework/src/Illuminate/Database/Connection.php(459): Illuminate\\Database\\Connection->run('insert into `te...', Array, Object(Closure))
#2 /app/vendor/laravel/framework/src/Illuminate/Database/Connection.php(411): Illuminate\\Database\\Connection->statement('insert into `te...', Array)
#3 /app/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2541): Illuminate\\Database\\Connection->insert('insert into `te...', Array)
#4 /app/vendor/laravel/telescope/src/Storage/DatabaseEntriesRepository.php(117): Illuminate\\Database\\Query\\Builder->insert(Array)
#5 /app/vendor/laravel/telescope/src/Telescope.php(453): Laravel\\Telescope\\Storage\\DatabaseEntriesRepository->store(Object(Illuminate\\Support\\Collection))
#6 /app/vendor/laravel/telescope/src/ListensForStorageOpportunities.php(44): Laravel\\Telescope\\Telescope::store(Object(Laravel\\Telescope\\Storage\\DatabaseEntriesRepository))
#7 [internal function]: Laravel\\Telescope\\Telescope::Laravel\\Telescope\\{closure}()
#8 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Object(Closure), Array)
#9 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(75): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#10 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Object(Closure), Object(Closure))
#11 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(571): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Object(Closure), Array, NULL)
#12 /app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(965): Illuminate\\Container\\Container->call(Object(Closure))
#13 /app/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(149): Illuminate\\Foundation\\Application->terminate()
#14 /app/artisan(54): Illuminate\\Foundation\\Console\\Kernel->terminate(Object(Symfony\\Component\\Console\\Input\\ArgvInput), 0)
#15 {main}
"}

**Comment by CrixuAMG** [comment]
I have the same problem, just cloned an existing repo that had telescope in the composer.json file and ran `composer install`.

```
Illuminate\Database\QueryException {#948
  #sql: "insert into `telescope_entries` (`batch_id`, `content`, `created_at`, `type`, `uuid`) values (?, ?, ?, ?, ?)"
  #bindings: array:5 [
    0 => "8c24b257-9cc8-4566-bb54-a3ac42e8fa31"
    1 => "{"command":"package:discover","exit_code":0,"arguments":{"command":"package:discover"},"options":{"help":false,"quiet":false,"verbose":false,"version":false,"ansi":true,"no-ansi":false,"no-interaction":false,"env":null},"output":"","hostname":"homestead"}"
    2 => "2018-10-30 10:39:47"
    3 => "command"
    4 => Ramsey\Uuid\Uuid {#933
      #codec: Ramsey\Uuid\Codec\TimestampFirstCombCodec {#939
        -builder: Ramsey\Uuid\Builder\DefaultUuidBuilder {#928
          -converter: Ramsey\Uuid\Converter\Number\BigNumberConverter {#930}
        }
      }
      #fields: array:6 [
        "time_low" => "98dd2755"
        "time_mid" => "fb42"
        "time_hi_and_version" => "4c9d"
        "clock_seq_hi_and_reserved" => "be"
        "clock_seq_low" => "f4"
        "node" => "8c24b2579127"
      ]
      #converter: Ramsey\Uuid\Converter\Number\BigNumberConverter {#930}
    }
  ]
  #message: "SQLSTATE[42S02]: Base table or view not found: 1146 Table 'crm_db.telescope_entries' doesn't exist (SQL: insert into `telescope_entries` (`batch_id`, `content`, `created_at`, `type`, `uuid`) values (8c24b257-9cc8-4566-bb54-a3ac42e8fa31, {"command":"package:discover","exit_code":0,"arguments":{"command":"package:discover"},"options":{"help":false,"quiet":false,"verbose":false,"version":false,"ansi":true,"no-ansi":false,"no-interaction":false,"env":null},"output":"","hostname":"homestead"}, 2018-10-30 10:39:47, command, 8c24b257-9127-4c9d-bef4-98dd2755fb42))"
  #code: "42S02"
  #file: "./vendor/laravel/framework/src/Illuminate/Database/Connection.php"
  #line: 664
  -previous: Doctrine\DBAL\Driver\PDOException {#141
    -errorCode: 1146
    -sqlState: "42S02"
    #message: "SQLSTATE[42S02]: Base table or view not found: 1146 Table 'crm_db.telescope_entries' doesn't exist"
    #code: "42S02"
    #file: "./vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php"
    #line: 82
    -previous: PDOException {#947
      #message: "SQLSTATE[42S02]: Base table or view not found: 1146 Table 'crm_db.telescope_entries' doesn't exist"
      #code: "42S02"
      #file: "./vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php"
      #line: 80
      +errorInfo: array:3 [
        0 => "42S02"
        1 => 1146
        2 => "Table 'crm_db.telescope_entries' doesn't exist"
      ]
      trace: {
        ./vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:80 { …}
        ./vendor/laravel/framework/src/Illuminate/Database/Connection.php:452 { …}
        ./vendor/laravel/framework/src/Illuminate/Database/Connection.php:657 { …}
        ./vendor/laravel/framework/src/Illuminate/Database/Connection.php:624 { …}
        ./vendor/laravel/framework/src/Illuminate/Database/Connection.php:459 { …}
        ./vendor/laravel/framework/src/Illuminate/Database/Connection.php:411 { …}
        ./vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2541 { …}
        ./vendor/laravel/telescope/src/Storage/DatabaseEntriesRepository.php:118 { …}
        ./vendor/laravel/telescope/src/Telescope.php:453 { …}
        ./vendor/laravel/telescope/src/ListensForStorageOpportunities.php:44 { …}
        Laravel\Telescope\Telescope::Laravel\Telescope\{closure}() {}
        ./vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29 { …}
        ./vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:75 { …}
        ./vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:31 { …}
        ./vendor/laravel/framework/src/Illuminate/Container/Container.php:572 { …}
        ./vendor/laravel/framework/src/Illuminate/Foundation/Application.php:965 { …}
        ./vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:149 { …}
        ./artisan:51 {
          ›
          › $kernel->terminate($input, $status);
          ›
          arguments: {
            $input: Symfony\Component\Console\Input\ArgvInput {#25 …}
            $status: 0
          }
        }
      }
    }
    +errorInfo: array:3 [
      0 => "42S02"
      1 => 1146
      2 => "Table 'crm_db.telescope_entries' doesn't exist"
    ]
    trace: {
      ./vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:82 { …}
      ./vendor/laravel/framework/src/Illuminate/Database/Connection.php:452 { …}
      ./vendor/laravel/framework/src/Illuminate/Database/Connection.php:657 { …}
      ./vendor/laravel/framework/src/Illuminate/Database/Connection.php:624 { …}
      ./vendor/laravel/framework/src/Illuminate/Database/Connection.php:459 { …}
      ./vendor/laravel/framework/src/Illuminate/Database/Connection.php:411 { …}
      ./vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2541 { …}
      ./vendor/laravel/telescope/src/Storage/DatabaseEntriesRepository.php:118 { …}
      ./vendor/laravel/telescope/src/Telescope.php:453 { …}
      ./vendor/laravel/telescope/src/ListensForStorageOpportunities.php:44 { …}
      Laravel\Telescope\Telescope::Laravel\Telescope\{closure}() {}
      ./vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29 { …}
      ./vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:75 { …}
      ./vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:31 { …}
      ./vendor/laravel/framework/src/Illuminate/Container/Container.php:572 { …}
      ./vendor/laravel/framework/src/Illuminate/Foundation/Application.php:965 { …}
      ./vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:149 { …}
      ./artisan:51 {
        ›
        › $kernel->terminate($input, $status);
        ›
        arguments: {
          $input: Symfony\Component\Console\Input\ArgvInput {#25 …}
          $status: 0
        }
      }
    }
  }
  +errorInfo: array:3 [
    0 => "42S02"
    1 => 1146
    2 => "Table 'crm_db.telescope_entries' doesn't exist"
  ]
  trace: {
    ./vendor/laravel/framework/src/Illuminate/Database/Connection.php:664 { …}
    ./vendor/laravel/framework/src/Illuminate/Database/Connection.php:624 { …}
    ./vendor/laravel/framework/src/Illuminate/Database/Connection.php:459 { …}
    ./vendor/laravel/framework/src/Illuminate/Database/Connection.php:411 { …}
    ./vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2541 { …}
    ./vendor/laravel/telescope/src/Storage/DatabaseEntriesRepository.php:118 { …}
    ./vendor/laravel/telescope/src/Telescope.php:453 { …}
    ./vendor/laravel/telescope/src/ListensForStorageOpportunities.php:44 { …}
    Laravel\Telescope\Telescope::Laravel\Telescope\{closure}() {}
    ./vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29 { …}
    ./vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:75 { …}
    ./vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:31 { …}
    ./vendor/laravel/framework/src/Illuminate/Container/Container.php:572 { …}
    ./vendor/laravel/framework/src/Illuminate/Foundation/Application.php:965 { …}
    ./vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:149 { …}
    ./artisan:51 {
      ›
      › $kernel->terminate($input, $status);
      ›
      arguments: {
        $input: Symfony\Component\Console\Input\ArgvInput {#25 …}
        $status: 0
      }
    }
  }
}
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
```

**Comment by Roemerb** [comment]
I have the same issue. Using Homestead and PostgreSQL. `Table 'homestead.telescope_entries' doesn't exist.` and yes, it definitely does exist. No problems with any other database table. Can access `/telescope` fine but nothing loads thanks to this error

**Comment by bgarrison25** [comment]
is your database actually called "homestead"? Only thing I can think of is that telescope is using your "mysql" connection (in the config) and you are trying to use a different connection. If this is the case, publish the config file and change storage.database.connection to use your other connection.

**Comment by bgarrison25** [comment]
I just noticed that this is supposedly happening on composer require....which leaves me clueless

**Comment by mwiekens** [comment]
I have the same problem but it only happens on `php artisan migrate`. The database is empty and then I try to fill it then . 

___________________________

php artisan migrate -v
Migration table created successfully.
Migrating: 2018_01_01_000000_create_action_events_table
Migrated:  2018_01_01_000000_create_action_events_table
Migrating: 2018_04_26_100713_create_performance_indicators_table
Migrated:  2018_04_26_100713_create_performance_indicators_table
Migrating: 2018_04_26_100714_create_announcements_table

   Illuminate\Database\QueryException  : SQLSTATE[42S02]: Base table or view not found: 1146 Table 'database.telescope_monitoring' doesn't exist (SQL: select `tag` from `telescope_monitoring`)

  at /c/Users/user/workspace/admin/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664
    660|         // If an exception occurs when attempting to run a query, we'll format the error
    661|         // message to include the bindings with SQL, which will make this exception a
    662|         // lot more helpful to the developer instead of just the database's errors.
    663|         catch (Exception $e) {
  > 664|             throw new QueryException(
    665|                 $query, $this->prepareBindings($bindings), $e
    666|             );
    667|         }
    668|

  Exception trace:

  1   Doctrine\DBAL\Driver\PDOException::("SQLSTATE[42S02]: Base table or view not found: 1146 Table 'database.telescope_monitoring' doesn't exist")
      /c/Users/user/workspace/admin/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:82

  2   PDOException::("SQLSTATE[42S02]: Base table or view not found: 1146 Table 'database.telescope_monitoring' doesn't exist")
      /c/Users/user/workspace/admin/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:80

  3   PDO::prepare("select `tag` from `telescope_monitoring`", [])
      /c/Users/user/workspace/admin/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:80

  4   Doctrine\DBAL\Driver\PDOConnection::prepare("select `tag` from `telescope_monitoring`")
      /c/Users/user/workspace/admin/vendor/laravel/framework/src/Illuminate/Database/Connection.php:326

  5   Illuminate\Database\Connection::Illuminate\Database\{closure}("select `tag` from `telescope_monitoring`", [])
      /c/Users/user/workspace/admin/vendor/laravel/framework/src/Illuminate/Database/Connection.php:657

  6   Illuminate\Database\Connection::runQueryCallback("select `tag` from `telescope_monitoring`", [], Object(Closure))
      /c/Users/user/workspace/admin/vendor/laravel/framework/src/Illuminate/Database/Connection.php:624

  7   Illuminate\Database\Connection::run("select `tag` from `telescope_monitoring`", [], Object(Closure))
      /c/Users/user/workspace/admin/vendor/laravel/framework/src/Illuminate/Database/Connection.php:333

  8   Illuminate\Database\Connection::select("select `tag` from `telescope_monitoring`", [])
      /c/Users/user/workspace/admin/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2027

  9   Illuminate\Database\Query\Builder::runSelect()
      /c/Users/user/workspace/admin/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2219

  10  Illuminate\Database\Query\Builder::Illuminate\Database\Query\{closure}()
      /c/Users/user/workspace/admin/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2499

  11  Illuminate\Database\Query\Builder::onceWithColumns(Object(Closure))
      /c/Users/user/workspace/admin/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2221

  12  Illuminate\Database\Query\Builder::pluck("tag")
      /c/Users/user/workspace/admin/vendor/laravel/telescope/src/Storage/DatabaseEntriesRepository.php:249

  13  Laravel\Telescope\Storage\DatabaseEntriesRepository::monitoring()
      /c/Users/user/workspace/admin/vendor/laravel/telescope/src/Storage/DatabaseEntriesRepository.php:236

  14  Laravel\Telescope\Storage\DatabaseEntriesRepository::isMonitoring()
      /c/Users/user/workspace/admin/vendor/laravel/telescope/src/IncomingEntry.php:164

  15  Laravel\Telescope\IncomingEntry::hasMonitoredTag()
      /c/Users/user/workspace/admin/app/Providers/TelescopeServiceProvider.php:29

  16  App\Providers\TelescopeServiceProvider::App\Providers\{closure}(Object(Laravel\Telescope\IncomingEntry))
      /c/Users/user/workspace/admin/vendor/laravel/framework/src/Illuminate/Support/HigherOrderCollectionProxy.php:60

  17  Closure::__invoke(Object(Laravel\Telescope\IncomingEntry))
      /c/Users/user/workspace/admin/vendor/laravel/framework/src/Illuminate/Support/HigherOrderCollectionProxy.php:60

  18  Illuminate\Support\HigherOrderCollectionProxy::Illuminate\Support\{closure}(Object(Closure))
      /c/Users/user/workspace/admin/vendor/laravel/framework/src/Illuminate/Support/Collection.php:442

  19  Illuminate\Support\Collection::every(Object(Closure))
      /c/Users/user/workspace/admin/vendor/laravel/framework/src/Illuminate/Support/HigherOrderCollectionProxy.php:61

  20  Illuminate\Support\HigherOrderCollectionProxy::__call("__invoke")
      /c/Users/user/workspace/admin/vendor/laravel/telescope/src/Telescope.php:206

  21  Laravel\Telescope\Telescope::Laravel\Telescope\{closure}()
      /c/Users/user/workspace/admin/vendor/laravel/telescope/src/Telescope.php:179

  22  call_user_func(Object(Closure))
      /c/Users/user/workspace/admin/vendor/laravel/telescope/src/Telescope.php:179

  23  Laravel\Telescope\Telescope::withoutRecording(Object(Closure))
      /c/Users/user/workspace/admin/vendor/laravel/telescope/src/Telescope.php:209

  24  Laravel\Telescope\Telescope::record("query", Object(Laravel\Telescope\IncomingEntry))
      /c/Users/user/workspace/admin/vendor/laravel/telescope/src/Telescope.php:332

  25  Laravel\Telescope\Telescope::recordQuery(Object(Laravel\Telescope\IncomingEntry))
      /c/Users/user/workspace/admin/vendor/laravel/telescope/src/Watchers/QueryWatcher.php:43

  26  Laravel\Telescope\Watchers\QueryWatcher::recordQuery(Object(Illuminate\Database\Events\QueryExecuted))
      /c/Users/user/workspace/admin/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:360

  27  Illuminate\Events\Dispatcher::Illuminate\Events\{closure}("Illuminate\Database\Events\QueryExecuted")
      /c/Users/user/workspace/admin/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:209

  28  Illuminate\Events\Dispatcher::dispatch("Illuminate\Database\Events\QueryExecuted")
      /c/Users/user/workspace/admin/vendor/laravel/framework/src/Illuminate/Database/Connection.php:826

  29  Illuminate\Database\Connection::event(Object(Illuminate\Database\Events\QueryExecuted))
      /c/Users/user/workspace/admin/vendor/laravel/framework/src/Illuminate/Database/Connection.php:682

  30  Illuminate\Database\Connection::logQuery("create table `announcements` (`id` varchar(255) not null, `user_id` int not null, `body` text not null, `action_text` varchar(255) null, `action_url` text null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'", [])
      /c/Users/user/workspace/admin/vendor/laravel/framework/src/Illuminate/Database/Connection.php:635

  31  Illuminate\Database\Connection::run("create table `announcements` (`id` varchar(255) not null, `user_id` int not null, `body` text not null, `action_text` varchar(255) null, `action_url` text null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'", [], Object(Closure))
      /c/Users/user/workspace/admin/vendor/laravel/framework/src/Illuminate/Database/Connection.php:459

  32  Illuminate\Database\Connection::statement("create table `announcements` (`id` varchar(255) not null, `user_id` int not null, `body` text not null, `action_text` varchar(255) null, `action_url` text null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'")
      /c/Users/user/workspace/admin/vendor/laravel/framework/src/Illuminate/Database/Schema/Blueprint.php:97

  33  Illuminate\Database\Schema\Blueprint::build(Object(Illuminate\Database\MySqlConnection), Object(Illuminate\Database\Schema\Grammars\MySqlGrammar))
      /c/Users/user/workspace/admin/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php:264

  34  Illuminate\Database\Schema\Builder::build(Object(Illuminate\Database\Schema\Blueprint))
      /c/Users/user/workspace/admin/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php:165

  35  Illuminate\Database\Schema\Builder::create("announcements", Object(Closure))
      /c/Users/user/workspace/admin/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:223

  36  Illuminate\Support\Facades\Facade::__callStatic("create")
      /c/Users/user/workspace/admin/database/migrations/2018_04_26_100714_create_announcements_table.php:22

  37  CreateAnnouncementsTable::up()
      /c/Users/user/workspace/admin/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:360

  38  Illuminate\Database\Migrations\Migrator::Illuminate\Database\Migrations\{closure}()
      /c/Users/user/workspace/admin/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:367

  39  Illuminate\Database\Migrations\Migrator::runMigration(Object(CreateAnnouncementsTable), "up")
      /c/Users/user/workspace/admin/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:178

  40  Illuminate\Database\Migrations\Migrator::runUp("/c/Users/user/workspace/admin/database/migrations/2018_04_26_100714_create_announcements_table.php")
      /c/Users/user/workspace/admin/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:147

  41  Illuminate\Database\Migrations\Migrator::runPending([])
      /c/Users/user/workspace/admin/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:96

  42  Illuminate\Database\Migrations\Migrator::run([])
      /c/Users/user/workspace/admin/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php:71

  43  Illuminate\Database\Console\Migrations\MigrateCommand::handle()
      /c/Users/user/workspace/admin/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29

  44  call_user_func_array([])
      /c/Users/user/workspace/admin/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29

  45  Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
      /c/Users/user/workspace/admin/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:87

  46  Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Object(Closure))
      /c/Users/user/workspace/admin/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:31

  47  Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), [])
      /c/Users/user/workspace/admin/vendor/laravel/framework/src/Illuminate/Container/Container.php:572

  48  Illuminate\Container\Container::call()
      /c/Users/user/workspace/admin/vendor/laravel/framework/src/Illuminate/Console/Command.php:183

  49  Illuminate\Console\Command::execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
      /c/Users/user/workspace/admin/vendor/symfony/console/Command/Command.php:255

  50  Symfony\Component\Console\Command\Command::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
      /c/Users/user/workspace/admin/vendor/laravel/framework/src/Illuminate/Console/Command.php:170

  51  Illuminate\Console\Command::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /c/Users/user/workspace/admin/vendor/symfony/console/Application.php:886

  52  Symfony\Component\Console\Application::doRunCommand(Object(Illuminate\Database\Console\Migrations\MigrateCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /c/Users/user/workspace/admin/vendor/symfony/console/Application.php:262

  53  Symfony\Component\Console\Application::doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /c/Users/user/workspace/admin/vendor/symfony/console/Application.php:145

  54  Symfony\Component\Console\Application::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /c/Users/user/workspace/admin/vendor/laravel/framework/src/Illuminate/Console/Application.php:89

  55  Illuminate\Console\Application::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /c/Users/user/workspace/admin/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:122

  56  Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /c/Users/user/workspace/admin/artisan:37

**Comment by bgarrison25** [comment]
for those of you that are having issues with this.....what does your database config file look like? What connection are you using for your database? What connection is telescope being told to use?

**Comment by mwiekens** [comment]
Mysql. I didnt not edit anything in the `config/database.php`. I am only setting DB_HOST, DB_DATABASE, DB_USERNAME, DB_PASSWORD in `.env`.

I did get through the migration after setting the APP_ENV from `staging` to `local`

**Comment by sblawrie** [comment]
I'm having this issue as well, but in my case the table does **not** exist.

Basically, I run `composer install` before `php artisan migrate`, and when composer is done doing its thing, Telescope tries inserting the queries that were run into `telescope_entries`. But because the migration hasn't run yet, it fails.

A _temporary_ fix is to place this in Telescope::filter() in TelescopeServiceProvider:

`if (!Schema::hasTable('telescope_entries')) {
                return false;
   }`

This prevents Telescope from trying to insert into `telescope_entries` if it doesn't exist yet.

**Comment by Roemerb** [comment]
For me the issue simply turned out to be the `telescope.storage.database.connection` config property. Since I've installed Telescope the value of this property has been changed load the `DB_CONNECTION` property from the environment. Telescope runs fine now!

**Comment by themsaid** [comment]
`package:discover` will be ignored by default, Telescope won't try to record it so this should solve the issue.

Please ping me if you're still having the issue after v0.1.9

**Comment by BramRoets** [comment]
@themsaid 

I'm still having this problem. It happens when running `composer install` before any valid database is configured (during circleci testing). No .env file or database exists at the moment. (Unit testing on circleci is done with sqlite in memory)

```
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In Connection.php line 664:
                                                                               
  SQLSTATE[HY000] [2002] Connection refused (SQL: select * from information_s  
  chema.tables where table_schema = gbm and table_name = telescope_monitoring  
  )                                                                            
                                                                               

In PDOConnection.php line 50:
                                             
  SQLSTATE[HY000] [2002] Connection refused  
                                             

In PDOConnection.php line 46:
                                             
  SQLSTATE[HY000] [2002] Connection refused  
                                             

Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1
Exited with code 1
```

**Comment by ohnotnow** [comment]
"Me too" on the CI/docker front.  You can reproduce by just doing  :

```
$ laravel new test-telescope
$ cd test-telescope/
$ composer require laravel/telescope

Using version ^1.0 for laravel/telescope
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
  - Installing moontoast/math (1.1.2): Loading from cache
  - Installing laravel/telescope (v1.0.1): Loading from cache
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

In Connection.php line 664:

  SQLSTATE[HY000] [1049] Unknown database 'homestead' (SQL: select * from inf
  ormation_schema.tables where table_schema = homestead and table_name = tele
  scope_monitoring)

In Connector.php line 70:

  SQLSTATE[HY000] [1049] Unknown database 'homestead'
```

**Comment by vincenzoraco** [comment]
If anyone still has this issue, make sure to run:

`php artisan optimize`
`composer dump-autoload`

**Comment by CrixuAMG** [comment]
@vincenzoraco `php artisan optimize` was removed in Laravel 5.6, so it'll only work in 5.5 or earlier versions of Laravel.

**Comment by vincenzoraco** [comment]
@CrixuAMG I am currently using 5.7 and I can use the optimize command as usual. It does do what it meant to do, like clearing the routing cache. I did tested it making Laravel to cache the routes, added a new route, get the error 404, then run optimize and then get a 200.

I read from here Laravel News https://laravel-news.com/laravel-5-6-removes-artisan-optimize  that it has been removed since 5.6 but I can still use it

**Comment by CrixuAMG** [comment]
@vincenzoraco I haven't tried it since 5.6 came out, just tried it out and confirmed it does still exist in 5.7. My apologies!

**Comment by kevingamaa** [comment]
check out your AuthServiceProvider or some provider that you may usiing to something to make sure you're not usiing any model on it , if you are just comment it and try again  php artisan migrate or composer dump-autoload

**Comment by DevDavido** [comment]
Having the same issue (using L5.8). It helped running `php artisan migrate` first before running `php artisan telescope:install` to make it install without errors.

**Comment by faroutchris** [comment]
I encountered this issue when running `php artisan migrate`.
As far as I can tell, telescope is trying to log cache hits before there was a cache table in my database. I'm unsure of exactly what the issue is, but this was the error message:
```Base` table or view not found: 1146 Table 'betterbets.cache' doesn't exist (SQL: select
   * from `cache` where `key` = betterbets_cachetelescope:dump-watcher limit 1)```

On Laravel 5.8, using the database as a cache driver.

I resolved it by changing `CACHE_DRIVER=file` in `.env`, running the migration and then changing the `CACHE_DRIVER` back to database

Hope that helps someone who's stuck.

**Comment by rainbowhat** [comment]
Nothing to migrate.
Postgress

**Comment by aminraeisi** [comment]
This issue happens also when you setup supervisord to always run your jobs and do `artisan migrate:fresh` (in dev environment). Because there is a chance that right after the tables are dropped, the jobs tables gets checked for new jobs and you get this error in the logs that the table does not exist.

**Comment by kylecmccandless** [comment]
php artisan cache:table
php artisan migrate

fixed it for me
