### ISSUE TITLE
/telescope gives 404

### ISSUE THREAD

**Issue by kylescousin** [laravel/telescope#244]
I can see the route in the route list: GET|HEAD      | telescope/{view?}                                        |                        | Laravel\Telescope\Http\Controllers\HomeController@index 

But when browsing there => 404

I tried clearing route cache, APP_ENV is set to local.

Running nginx/1.15.5 (Ubuntu) and trying website.local/telescope

**Comment by Donny5300** [comment]
Did you defined the gate in your TelescopeServiceProvider that returns a `true` value? 

```
protected function gate()
        {
            Gate::define('viewTelescope', function ($user) {
                return true;
            });
        }
```

**Comment by vesper8** [comment]
I noticed that previously if you had telescope disabled it would still load the route and then show a message saying that telescope was disabled. But that seems to have recently changed and now if telescope is disabled it will also disable the route completely
