### ISSUE TITLE
Call to undefined function Moontoast\Math\bcadd() 

### ISSUE THREAD

**Issue by yushkevichv** [laravel/telescope#25]
Hi!

After install at laradock receive error Call to undefined function Moontoast\Math\bcadd(). 

Requirements at docs doesn't say about it nothing.

**Comment by yushkevichv** [comment]
rebuild and add bcmath resolve my problem. I think, this information should add to docs

**Comment by themsaid** [comment]
moontoast/math already requires ext-bcmath https://github.com/moontoast/math/blob/master/composer.json

**Comment by Zerquix18** [comment]
This problem shows because the extension hasn't been loaded. If it hasn't been installed, you'll get this error while trying to install the Laravel telescope:

```
  Problem 1
    - moontoast/math 1.1.2 requires ext-bcmath * -> the requested PHP extension bcmath is missing from your system.
    - moontoast/math 1.1.1 requires ext-bcmath * -> the requested PHP extension bcmath is missing from your system.
    - moontoast/math 1.1.0 requires ext-bcmath * -> the requested PHP extension bcmath is missing from your system.
    - laravel/telescope v0.1.5 requires moontoast/math ^1.1 -> satisfiable by moontoast/math[1.1.0, 1.1.1, 1.1.2].
    - Installation request for laravel/telescope ^0.1.5 -> satisfiable by laravel/telescope[v0.1.5].
```

You can install ext-bcmath by running

`apt install php7.2-bcmath`

(change 7.2 for your PHP version)

Then you can load it by running

`sudo service apache2 restart`

**Comment by yushkevichv** [comment]
I already solve my problem (https://github.com/laravel/telescope/issues/25#issuecomment-432302285) but requirements and docs for this package not have this info. My Issue was about docs.

**Comment by guyaloni** [comment]
> bcmath

Can you please give more details? I have exactly the same issue but cannot find out how to solve it!

**Comment by guyaloni** [comment]
> rebuild and add bcmath resolve my problem. I think, this information should add to docs



@yushkevichv, Can you please give more details?
I have exactly the same issue but cannot find out how to solve it!

**Comment by yushkevichv** [comment]
@guyaloni try it https://stackoverflow.com/questions/3400362/how-to-install-bcmath-module

I use laradock. It has param. After change need build —no-cache workspace.

**Comment by guyaloni** [comment]
@yushkevichv, should I do it from docker workspace?

**Comment by guyaloni** [comment]
> @guyaloni try it https://stackoverflow.com/questions/3400362/how-to-install-bcmath-module
> 
> I use laradock. It has param. After change need build —no-cache workspace.

@yushkevichv, should I do it from docker workspace?

**Comment by Ostendorf** [comment]
I had the same issue (running **CentOS** with PHP 7.1 from Software Collections).

1. Install `bcmath`
```
yum install rh-php71-php-bcmath
```

2. Install `telescope` (which can now install `moontoast/math` requirement):
```
composer require laravel/telescope --dev
```

3. Then I got the error:
```
Call to undefined function Moontoast\Math\bcadd()
```

4. Because I forgot to reload PHP:
```
systemctl restart rh-php71-php-fpm
```
