### ISSUE TITLE
The Mix manifest does not exist on production

### ISSUE THREAD

**Issue by PatriXsmarT** [laravel/telescope#250]
I developed my project and uploaded it with my host but anytime i visit the URL /telescope , it throw back this error to me 
"The Mix manifest does not exist. (View: /home/patrix5/patrixsmartr/vendor/laravel/telescope/resources/views/layout.blade.php)"
Pls i am confused and i need help as quick as possible.

**Comment by eossa** [comment]
You must exec `php artisan vendor:publish --tag=telescope-assets` in your server.

**Comment by PatriXsmarT** [comment]
still won't work

**Comment by SaphiLC** [comment]
still fails, not all servers allow you to use "public" as the public folder...

**Comment by M165437** [comment]
Anyone having this problem, also try `echo "" | sudo -S service php7.1-fpm reload`. Solved it for me.

**Comment by hackernewbie** [comment]
> You must exec `php artisan vendor:publish --tag=telescope-assets` in your server.

This worked for me!

Thanks!
