### ISSUE TITLE
max_allowed_packet error

### ISSUE THREAD

**Issue by blyleven** [laravel/telescope#259]
Hi there, 

I've got a server crashing all the time because there are a lot of failing queries.

SQLSTATE[08S01]: Communication link failure: 1153 Got a packet bigger than 'max_allowed_packet' bytes (SQL: insert into `telescope_entries` (`batch_id`, `content`, `created_at`, `type`, `uuid`)

These errors are logged to the log files, which will get so big (9GB), it will fill up the entire diskspace of the server. 

Anybody got some helpful info on this one? :-)

**Comment by themsaid** [comment]
You're trying to write a very long entry in your database, this is not Telescope related. I suggest that you only record what you need in production.
