### ISSUE TITLE
Undefined method in `JobWatcher.php`

### ISSUE THREAD

**Issue by browner12** [laravel/telescope#26]
After install when discovering packages, this error pops up:

In JobWatcher.php line 26:
                                                                         
  Call to undefined method Illuminate\Queue\Queue::createPayloadUsing()  

I solved by upgrading my `laravel/framework` from version 5.7.6 to 5.7.10.

Due to this commit in 5.7.7 

https://github.com/laravel/framework/commit/3f68cbe3df82990c69e34309901fcefefdb65c95#diff-49b10598ca52b8a639b383a7e23dcb68

Should we add a requirement of the framework to telescope?

**Comment by Plytas** [comment]
It says in readme that Laravel 5.7+ is required.

**Comment by browner12** [comment]
already sent in a PR to update to 5.7.7+

https://github.com/laravel/telescope/pull/27
