### ISSUE TITLE
[Feature Request] Duration of request

### ISSUE THREAD

**Issue by deviouspk** [laravel/telescope#265]
Hi,
Would it be possible to log and display the time it took to execute a request? This could be very useful.

**Comment by deviouspk** [comment]
On #313 taylor said:
![image](https://user-images.githubusercontent.com/7100315/47967349-a97db100-e05c-11e8-830f-c8ebbb202879.png)

I would love to have it on the index though. There's plenty of place to display it. And i really don't want to click on each request to check the execution time of it.
Can we have a discussion about this?

**Comment by deleugpn** [comment]
I think it would be better to have a configurable index in such a way that each one can choose what to see in their index given each object's context.
That would free the burden of Telescope having to please too many variables.
