### ISSUE TITLE
Documentation improvement

### ISSUE THREAD

**Issue by cosecantt** [laravel/telescope#271]
Mentioning 
````For non-local usage authorization, add App\Providers\TelescopeServiceProvider::class to config/app.php ````
is missing in the documentation.

**Comment by Te7a-Houdini** [comment]
i think it's added when running ```php artisan telescope:install```

**Comment by cosecantt** [comment]
For laravel 5.7 it did not add and did not work until I added it manually.

**Comment by bgarrison25** [comment]
by "did not work" do you mean you couldn't even get to /telescope or that it wasn't recording things?

**Comment by cosecantt** [comment]
By did not work I meant it did not work as expected. When logged in I
visited /telescope and it redirected to 403 unauthorized page. Once I added
above class to the config without any other changes it worked as it
expected.

**Comment by bgarrison25** [comment]
Yeah, I don't know why it didn't add that provider class to config/app.php for you but in the three installs I have done so far it did it automatically. I can't reproduce it myself.

**Comment by robertmylne** [comment]
Didn't add it to the file for me either. Only did when I ran on production server.
