### ISSUE TITLE
Telescope don't have an permission to access on the server

### ISSUE THREAD

**Issue by ronmartdanieljavier** [laravel/telescope#276]
Hi,
Can anyone help me regarding this? I tried to install laravel telescope with our existing project and new laravel project but every time I accessing the telescope dashboard the server always showing the Forbidden page both existing and new laravel project.

I run these command to install the telescope:
-composer require laravel/telescope --dev
-php artisan telescope:install
-php artisan migrate
-php artisan vendor:publish --tag=telescope-assets --force

Did I miss something? Thanks in advance

**Comment by Zerquix18** [comment]
What kind of message does it show? This one?

![image](https://user-images.githubusercontent.com/2019162/47754734-44981480-dc72-11e8-8889-ed0134f9dd72.png)

**Comment by ronmartdanieljavier** [comment]
This one.
<img width="1245" alt="screen shot 2018-10-31 at 9 35 49 am" src="https://user-images.githubusercontent.com/11402104/47754888-751e9380-dcf0-11e8-98d9-79f852968b3c.png">

I only get that error page if I access a different url that is not registered on my laravel routes that why It's so weird only telescope experiencing the permission access

**Comment by ronmartdanieljavier** [comment]
I'm getting "/telescope - No such file or directory" as server error log

**Comment by themsaid** [comment]
Seems like the service provider isn't running and the routes aren't registered. Check your app to see what's special about it.

Continue the discussion on the forums since this repo is for bug reporting only.
