### ISSUE TITLE
Uncaught Error: Call to undefined method Auth::hasUser()

### ISSUE THREAD

**Issue by dmyers** [laravel/telescope#277]
The Auth [Guard contract](https://github.com/laravel/framework/blob/5.7/src/Illuminate/Contracts/Auth/Guard.php) does not require a hasUser() method and so [this line](https://github.com/laravel/telescope/blob/3d66a003ff6eb5af84af56a12924590d92a1f3d9/src/Telescope.php#L201) does not work in all situations. Someone tried to add it to the contract in the laravel/framework, but [the PR](https://github.com/laravel/framework/pull/25629) was rejected.

Thoughts?

**Comment by themsaid** [comment]
switched to use `check()`

**Comment by meysam69** [comment]
I'm going to implement a custom gaurd but I can't understand exacatly what the method `hasUser` suppose to do? can anyone help me with that?
