### ISSUE TITLE
array_key_exists() error

### ISSUE THREAD

**Issue by sciracioglu** [laravel/telescope#283]
**when I use a telescope, I got this error**

array_key_exists(): The first argument should be either a string or an integer {"exception":"[object] (ErrorException(code: 0): array_key_exists(): The first argument should be either a string or an integer at /Users/sc/code/portal/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:315)

**Comment by themsaid** [comment]
please re-open with full stack trace.
