### ISSUE TITLE
Authorization not working for guard except 'web'

### ISSUE THREAD

**Issue by shahvirag** [laravel/telescope#285]
When user is authenticated with guard 'web' telescope gate works properly.
If user is authenticated with guard like 'admin' telescope gate works properly.

**Comment by shahvirag07** [comment]
I have multiple guards in my application 'web', 'api' and 'admin'.
![code1](https://user-images.githubusercontent.com/24240840/47835465-10376c00-ddca-11e8-9f9a-1d94dda20635.png)

For production use of Telescope, If i allow any user belongs to web guards so it works fine. But if I logged in with 'admin' guard than user not authenticated for telescope access. I have already defined user emails in service provider gate method.
