### ISSUE TITLE
Testing fails with RefreshDatabase

### ISSUE THREAD

**Issue by Resin01** [laravel/telescope#286]
After adding telescope all my tests fails when using RefreshDatabase. It seems that the telescope migration is hardcoded to use a certain connection, and therefor does not use my 'testing' connection. I get the following error.
General error: 1 table "telescope_entries" already exists

**Comment by themsaid** [comment]
don't let telescope run in your testing environment, it's unnecessary overhead.

**Comment by Resin01** [comment]
Great. How do I ensure this? I see nothing in the documentation on how to get RefreshDatabase to skip certain migrations

**Comment by Braunson** [comment]
@Resin01 I just had this same issue, you can disable telescope entirely by placing this in your `.env.testing`

```
TELESCOPE_ENABLED=false
```

**Comment by Braunson** [comment]
@TheFrankman Thanks for checking into that. I ended up disabling it for testing as really it's not necessary for phpunit testing anyway.
