### ISSUE TITLE
Telescope not recording anything if APP_ENV isn't local

### ISSUE THREAD

**Issue by bgarrison25** [laravel/telescope#288]
So I set up Telescope on production. I then went into the gate and set it up as normal. I can get to /telescope but there was nothing logged. I tried clearing all my cache etc and still nothing. I then changed my APP_ENV from production to local and now it is logging everything appropriately. 

Let me know if you need anything.

**Comment by hotmeteor** [comment]
Check the `register()` method in your `TelescopeServiceProvider`. It dictates what is recorded in production.

**Comment by bgarrison25** [comment]
I see. So, only exceptions / failed jobs / scheduled tasks / monitored tasks are available on production unless you edit this method. I would recommend adding to this to the documentation along with the part describing the gate method and maybe even specify the different $entry methods that are available and what they relate to.

**Comment by bgarrison25** [comment]
Also a few of the default checks for non-local environments simply return "false" by default at this point...i assume thats because its beta.

**Comment by bgarrison25** [comment]
ahhhhh. I missed that. Very nifty. Still, I know documentation is in its infancy but documenting the different checks would be useful.

**Comment by themsaid** [comment]
docs in the making :) feel free to send PR to the readme though

**Comment by 3bolyfci** [comment]
in .env file you can add  TELESCOPE_KEY = true  
and in telescopeServiceProvider in register method   update  this 
Telescope::filter(function (IncomingEntry $entry) {
            if ( $this->app->isLocal()) {
                return true;
            }
by this 
 Telescope::filter(function (IncomingEntry $entry) {
            if (env('TELESCOPE_KEY', false) | $this->app->isLocal()) {
                return true;
            }

**Comment by IlyasMohetna** [comment]
For new laravel version you might need to update in the App/Providers/TelescopeServiceProvider.php 

In the register() method change this : 

`
public function register(): void
    {
        // Telescope::night();

        $this->hideSensitiveRequestDetails();

        $isLocal = $this->app->environment('local');

        Telescope::filter(function (IncomingEntry $entry) use ($isLocal) {
            return $isLocal ||
                   $entry->isReportableException() ||
                   $entry->isFailedRequest() ||
                   $entry->isFailedJob() ||
                   $entry->isScheduledTask() ||
                   $entry->hasMonitoredTag();
        });
    }
`

To 

public function register(): void
    {
        // Telescope::night();

        if ($this->app->environment('production')) {
           Telescope::start();
        }
        $this->hideSensitiveRequestDetails();

        $isLocal = $this->app->environment('local');

        Telescope::filter(function (IncomingEntry $entry) {
                return $entry->isReportableException() ||
                    $entry->isFailedRequest() ||
                    $entry->isFailedJob() ||
                    $entry->isScheduledTask() ||
                   $entry->hasMonitoredTag();
        });
    }
