### ISSUE TITLE
[Feature request] Filter Requests by verb type

### ISSUE THREAD

**Issue by lsfiege** [laravel/telescope#292]
It would be great to have this functionality :)
Amazing job @themsaid !!!

**Comment by themsaid** [comment]
You can apply tags to the request watcher if you want:

```
Telescope::tag(function($incomingEntry){
    return [...YOUR CUSTOM TAGS HERE...];
});
```

**Comment by lsfiege** [comment]
Actually I was referring to a UI level filter, but this solution is also good :)

**Comment by EdgarSedov** [comment]
Is it currently possible to search by 2 tags simultaneously?

**Comment by yooga0** [comment]
You may combine them with '&':
`Tag1&Tag2`
