### ISSUE TITLE
Migrate fails using different .env

### ISSUE THREAD

**Issue by randompixel** [laravel/telescope#301]
```
$ ./artisan migrate:status
+------+----------------------------------------------------+-------+
| Ran? | Migration                                          | Batch |
+------+----------------------------------------------------+-------+
| Yes  | 2014_10_12_000000_create_users_table               | 1     |
| Yes  | 2018_08_08_100000_create_telescope_entries_table   | 3     |
| Yes  | 2018_08_24_142248_create_user_recent_clients_table | 2     |
+------+----------------------------------------------------+-------+
```
Using migrate locally shows the telescope entries in the migrations, however if I try and run the migration in a different environment (in this case my Azure DB) I get an error.

```
 16:56:09  ...code/app   master ✘ ✹ 
$ ./artisan migrate:status --env=azure

   Illuminate\Database\QueryException  : SQLSTATE[42S02]: Base table or view not found: 1146 Table 'database_name.telescope_monitoring' doesn't exist (SQL: select `tag` from `telescope_monitoring`)
```
And I'm not entirely sure how to get past this point. The `migrate` command gives the same error. Surely the whole purpose of the migrate command is to create this table!

Any help would be really appreciated.

**Comment by randompixel** [comment]
This was fixed by https://github.com/laravel/telescope/issues/173#issuecomment-433734464, setting

```
'ignoreCommands' => [
        'migrate'
    ],
```
in the telescope config. I'm guessing it was trying to log the migration of itself. Not sure if that's still a bug or not?

**Comment by themsaid** [comment]
This is now fixed.
