### ISSUE TITLE
Doesn't work with postgreSQL

### ISSUE THREAD

**Issue by aldozumaran** [laravel/telescope#304]
Hello,
in my .env file i have:
DB_CONNECTION=pgsql
but  when i try to execute php artisan migrate, i have this error
**_MySQL server has gone away_**

```
  PDOException  : SQLSTATE[HY000] [2006] MySQL server has gone away

  at /var/www/html/quasar/qconsole/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:70
    66|         if (class_exists(PDOConnection::class) && ! $this->isPersistentConnection($options)) {
    67|             return new PDOConnection($dsn, $username, $password, $options);
    68|         }
    69| 
  > 70|         return new PDO($dsn, $username, $password, $options);
    71|     }
    72| 
    73|     /**
    74|      * Determine if the connection is persistent.

 Exception trace:

  1   PDO::__construct("mysql:host=***.****.***.****;port=****;dbname=****", "admin", "****", [])
      /var/www/html/quasar/qconsole/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:70

  2   Illuminate\Database\Connectors\Connector::createPdoConnection("mysql:host=***.***.***.***;port=***;dbname=****", "admin", "****", [])
      /var/www/html/quasar/qconsole/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:100


```

**Comment by edersoares** [comment]
Did you clear your config cache?

**Comment by cjonstrup** [comment]
I have same problem using postgresql

 git:(master) ✗ composer require laravel/telescope --dev
Using version ^0.1.6 for laravel/telescope
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
  - Installing moontoast/math (1.1.2): Loading from cache
  - Installing laravel/telescope (v0.1.6): Loading from cache
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
Discovered Package: beyondcode/laravel-dump-server
Discovered Package: fideloper/proxy
Discovered Package: laravel/telescope
Discovered Package: laravel/tinker
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Package manifest generated successfully.
[2018-11-06 21:00:19] local.ERROR: could not find driver (SQL: insert into `telescope_entries` (`batch_id`, `content`, `created_at`, `type`, `uuid`) values (8c33ba9a-7d89-4d6a-a138-f76c07606549, {"command":"package:discover","exit_code":0,"arguments":{"command":"package:discover"},"options":{"help":false,"quiet":false,"verbose":false,"version":false,"ansi":false,"no-ansi":false,"no-interaction":false,"env":null},"output":"","hostname":"localhost.localdomain"}, 2018-11-06 21:00:19, command, 8c33ba9a-7c91-40dd-b580-cc6b089c42ce)) {"exception":"[object] (Illuminate

**Comment by flexgrip** [comment]
Same here. The first migration takes several minutes before it fails with the same error above.

**Comment by flexgrip** [comment]
Not sure anything changed here, but I forgot that this was broken and wanted to try this out again. Everything went smooth. So maybe this was fixed? Was there even a release?

**Comment by aldozumaran** [comment]
yes it works, @edersoares thanks, after php artisan transport:install, 
the cache must be emptied.
