### ISSUE TITLE
[Feature Request] Track the Route/Controller/Trait/Views used in a response

### ISSUE THREAD

**Issue by trideout** [laravel/telescope#314]
Similar to the functionality of the Routes and Views tabs in Laravel Debugbar, I'd love to see support for tracking which route matched for a request as well as the views called in a request and the Endpoint Method that returned the request. Tracking these values would allow me to replace Debugbar/Clockwork with Telescope.
![screenshot from 2018-11-02 12-41-32](https://user-images.githubusercontent.com/3935944/47934333-af2c9880-de9c-11e8-9ce4-64b67d05976d.png)

**Comment by deleugpn** [comment]
This would probably have a significant performance impact  while not being that useful for production. If implemented, I hope it would be togglable so we can disable on production.

**Comment by trideout** [comment]
We wouldn't necessarily need the Reflection that is used by Debugbar, we could simply pull the route endpoint information from Illuminate/Routing/Router. That shouldn't have any more overhead than any other task being performed by Telescope
