### ISSUE TITLE
Data too long for column 'content'

### ISSUE THREAD

**Issue by kundancool** [laravel/telescope#316]
Getting error with content size for column can we change it to longText instead of text

> Illuminate\Database\QueryException
SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'content' at row 565 (SQL: insert into `telescope_entries` (`batch_id`, `content`, `created_at`, `type`, `uuid`)

**Comment by themsaid** [comment]
You can change that in your app of you want, also please make sure you're on your latest version as we started pruning long responses.

**Comment by hcancelik** [comment]
I'm on the latest version and I still get this error.

**Comment by thomasdominic** [comment]
Me too
