### ISSUE TITLE
[Feature Request] No way to filter by batch

### ISSUE THREAD

**Issue by paras-malhotra** [laravel/telescope#318]
To the best of my knowledge, currently there is no way to filter entries by batch. For example, say we need to record all entries for an app lifecycle that result in an exception (e.g. the queries fired, the request, etc.).

`Telescope::filter` only works for filtering individual entries but does not allow filtering entries at a batch level. Is there a way to do this in the existing package? If not, should we add something like `Telescope::filterBatch`? I would be happy to send a PR if this is useful. It's definitely a feature I'd like to have in all my apps using Telescope.

**Comment by themsaid** [comment]
Pr open
