### ISSUE TITLE
RedisWatcher doesn't record entries as the event is not dispatched

### ISSUE THREAD

**Issue by paras-malhotra** [laravel/telescope#321]
By default, events are disabled in `RedisManager` due to this commit: https://github.com/laravel/framework/commit/b14cfc9966572cf7b61e05a433947895cfddef2a

Unless these events are enabled `RedisWatcher` would not work as it listens to the `CommandExecuted` event. That's why it's broken right now.

**Comment by themsaid** [comment]
Yes you have to explicitly enable that in your app if you want laravel to fire events:

```
Redis::enableEvents();
```

**Comment by michaelnguyen547** [comment]
@themsaid where do I put `Redis::enableEnvents()`

**Comment by deleugpn** [comment]
In a Service Provider

**Comment by AfzalH** [comment]
Putting `Redis::enableEnvents()` in ApplicationServiceProvider's boot method breaks Laravel Horizon

**Comment by paras-malhotra** [comment]
@AfzalH could you elaborate how it breaks Horizon? Any errors / stack trace observed?

**Comment by paras-malhotra** [comment]
@AfzalH thanks for the bug report. Could you open a separate issue for this? This sounds like a legit bug.

**Comment by paras-malhotra** [comment]
@AfzalH I meant a separate issue on this repository. This doesn't seem to be an issue with Horizon, looks like a Telescope issue.

**Comment by AfzalH** [comment]
Done [telescope/481](https://github.com/laravel/telescope/issues/481)
