### ISSUE TITLE
Moontoast\Math\BigNumber is required.

### ISSUE THREAD

**Issue by jcqtc** [laravel/telescope#323]
Just cloned the repo and created a vanilla *telescopetest* laravel project, linked the package into the composer.json file and ran `composer install` & `php artisan telescope:install` commands.

It works without the telescope service provider in the app.php config file.

Here's the error:
```
Cannot call Ramsey\Uuid\Converter\Number\DegradedNumberConverter::toHex without support for large integers, since integer is an unsigned 128-bit integer; Moontoast\Math\BigNumber is required.
```

The Telescope entry point for this error is at `C:\laragon\www\telescope\src\IncomingEntry.php` at `Str::orderedUuid()`:

``` php
    /**
     * Create a new incoming entry instance.
     *
     * @param  array  $content
     * @return void
     */
    public function __construct(array $content)
    {
        $this->uuid = Str::orderedUuid();
 
        $this->recordedAt = now();
 
        $this->content = array_merge($content, ['hostname' => gethostname()]);
 
        // $this->tags = ['hostname:'.gethostname()];
    }
```

**Comment by themsaid** [comment]
Please refer to previous issues on the same error for more information.
