### ISSUE TITLE
Support for localization

### ISSUE THREAD

**Issue by jcqtc** [laravel/telescope#329]
I'm working on implementing locales into Telescope, but i'm struggling with the overall architecture of the language files / binding to Vue.

Here's what I plan to do:

- Create a file for each resources (`main.php`, `requests.php`, `jobs.php`...) with related keys.
- Add a `lang` key to the `Telescope::scriptVariables()` method containing all the files / keys.
- Add a `trans(resource, key)` method in the `base.js` file and using it with a computed property (maybe? or method?) in Vue components.

Let's say in `base.js`:
``` javascript
trans(resource, key) {
    return this.Telescope.lang[resource][key];
 },
```
And in `requests/index.vue`:
``` javascript
export default {
    mixins: [
       StylesMixin,
    ],
    methods: {
        trans(key) {
            return this.$root.trans('requests', key);
        },
    },
}
```
So, we would use it like this:
``` vue
<tr slot="table-header">
    <th scope="col">{{ trans('verb') }}</th>
    <th scope="col">{{ trans('path') }}</th>
    <th scope="col">{{ trans('status') }}</th>
    <th scope="col">{{ trans('happened') }}</th>
    <th scope="col"></th>
</tr>
```
This would point to `telescope::requests.verb` on the backend.

How can I enhance this? I think there's a better solution, but I can't find one...

**Comment by andrey-helldar** [comment]
@themsaid, probably, this moment has [`not come`](https://github.com/laravel/telescope/pull/1244) yet 😅
