### ISSUE TITLE
How to handle multiple timezones

### ISSUE THREAD

**Issue by jonagoldman** [laravel/telescope#330]
I see that timezone is set in `layout.blade.php` using `config('app.timezone')`, this results in:
```js
Telescope.timezone = "UTC"
```

But what happens if my app works with multiple timezones?

In a multi tenant app where each tenant have a different timezone, with the database configured in the tenant timezone, and the timezone config is changed at runtime, then it results is something like this:

![image](https://user-images.githubusercontent.com/1297559/47970859-d0d27f00-e058-11e8-8134-7ea185450391.png)

You can see that the "happened" column displays time in UTC, resulting in misleading results, because actually, "5h ago" and "Just now" happened at the same time, but its displayed differently.

What is the recommended way to handle this situation?

Thanks.

**Comment by themsaid** [comment]
I don't think there's a way around this edge case, I'd store all dates and times in UTC and do the conversion on display.

**Comment by jonagoldman** [comment]
Ok, so the best way to go is to work only with UTC in the server and database and do the conversion to local time at each client browser.
Thanks.

**Comment by themsaid** [comment]
Yes, that's what we do in Envoyer for example, we store all in UTC but we show you deployment time based on your local time.
