### ISSUE TITLE
`batch_id` is too long

### ISSUE THREAD

**Issue by MatanYed** [laravel/telescope#332]
SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'batch_id'

v0.1.6
laravel/framework ~5.7.7

**Comment by themsaid** [comment]
batch_id is a regular UUID, with the default migration it shouldn't be a problem. Please check what's wrong with your app or database engine.

**Comment by MatanYed** [comment]
@themsaid I already tried to investigate it with no success
I'm using MySQL 5.7, another laravel app is working just fine on my machine.
What could it be? What should I check?
