### ISSUE TITLE
There are no commands defined in the "telescope" namespace.

### ISSUE THREAD

**Issue by amitsharma8891** [laravel/telescope#336]
Hi,

I try to install "Telescope" withLaravel 5.7.12  but getting following errors:

**There are no commands defined in the "telescope" namespace.**
I also clear the cache

**Comment by gabrieliuga** [comment]
Is this to do with the php_sapi_name return?
Had a similar issue on a cpanel server which reports php_sapi_name as cgi-fcgi
Solution:

bootstrap/app.php
```php
$app = new App\Library\Application(
    realpath(__DIR__.'/../')
);
```

Application.php in app/Library
```php
namespace App\Library;

class Application extends \Illuminate\Foundation\Application
{
    public function runningInConsole()
    {
        return php_sapi_name() == 'cli' || php_sapi_name() == 'phpdbg' || php_sapi_name() == 'cgi-fcgi';
    }
}
```

**Comment by paras-malhotra** [comment]
@amitsharma8891 do you have auto discovery enabled? If not, you'll need to include the `Laravel\Telescope\TelescopeServiceProvider` in your `config/app.php`
