### ISSUE TITLE
Getting Symfony\\Component\\HttpKernel\\Exception\\HttpException

### ISSUE THREAD

**Issue by lsfiege** [laravel/telescope#34]
Hi!
I have tried telescope in a fresh Laravel 5.7 installation and worked like a charm.

But if i try to install it into an recently upgraded laravel app to 5.7.10 i'm getting an Symfony\\Component\\HttpKernel\\Exception\\HttpException

![image](https://user-images.githubusercontent.com/13440507/47375481-bf878b00-d6c6-11e8-88e3-2e0ab05a9b83.png)

Could it be due to a bad update in my application?

**Comment by themsaid** [comment]
@lsfiege could be, you'll need to follow the stack trace until you figure out what's wrong. Closing this since it doesn't seem like an issue in Telescope.

**Comment by lsfiege** [comment]
In fact, it was an error when I partially updated the Http/Kernel.php file. It was my mistake, sorry.
