### ISSUE TITLE
session stored on redis appear in telescope cache tab

### ISSUE THREAD

**Issue by michaelnguyen547** [laravel/telescope#345]
<img width="1013" alt="screen shot 2018-11-06 at 4 00 33 pm" src="https://user-images.githubusercontent.com/436950/48099605-639c2680-e1dd-11e8-8bc0-4f5733fce6c5.png">

is it intended that session in Redis show up under Cache?

**Comment by deleugpn** [comment]
I would think so as it's a cache hit.

**Comment by themsaid** [comment]
Framework keys aren't prefixed so it's hard to omit them. If we start adding prefixes it'll be a major breaking change, so maybe in 5.8 or so.
