### ISSUE TITLE
Connect remotely to lumen?

### ISSUE THREAD

**Issue by mrahmadt** [laravel/telescope#346]
Hello

I'm aware that telescope not compatible with lumen, but I wonder if I can install it in a separate location with Laravel and connect it to lumen somehow?

I think this is a great tool that everyone needs.

if this not possible, can you guide me to some other tool/service that can do the same?

Thanks

**Comment by themsaid** [comment]
It won't be able to record Lumen events, we'll look into making it compatible with lumen soon.

**Comment by mrahmadt** [comment]
When? :)

Do you have like announcement mailing list or something like that (sorry I'm not social networking guy)

**Comment by goodspeed666** [comment]
Hi @themsaid ,

Do you have the schedule for release lumen version ?

Thank you.

**Comment by bkvishe** [comment]
Are you guys planing something for Lumen version ?
