### ISSUE TITLE
Exceptions tab not working

### ISSUE THREAD

**Issue by leoncottell** [laravel/telescope#348]
Click on Exceptions, just get a spinner, no data loads, dev tools show this request :

.../telescope/telescope-api/exceptions?tag=&before=&take=50&family_hash=

Which gives this error :

"message": "Argument 6 passed to Laravel\\Telescope\\EntryResult::__construct() must be of the type array, null given, called in .../app/vendor/laravel/telescope/src/Storage/DatabaseEntriesRepository.php on line 91",
    "exception": "Symfony\\Component\\Debug\\Exception\\FatalThrowableError",
    "file": ".../app/vendor/laravel/telescope/src/EntryResult.php",
    "line": 78,

**Comment by leoncottell** [comment]
I am getting the same behavior & error message on mail tab too when it tries to load : .../telescope/telescope-api/mail?tag=&before=&take=50&family_hash=

**Comment by themsaid** [comment]
https://github.com/laravel/telescope/issues/33
