### ISSUE TITLE
[Feature Request] Load new entries automatically

### ISSUE THREAD

**Issue by leoncottell** [laravel/telescope#349]
When viewing log (and other panels) if there is new info it shows a 'Load New Entries' link, which when clicked loads the new data.  Would be better if this just loaded the new entries without me having to click it

**Comment by Te7a-Houdini** [comment]
![screenshot from 2018-11-07 14-34-57](https://user-images.githubusercontent.com/17250137/48131906-52fdb600-e29a-11e8-9a23-de3e52192354.png)
have you tried to click on ```Auto Load Entries``` button on the top right

**Comment by leoncottell** [comment]
Perfect, that does it, thanks, didn't realise what the buttons were for - there is a UI issue with the buttons though, the on state colour is the same as the hover colour, so when you mouse over it and click to turn off it still looks like it's on until you move the mouse away.
