### ISSUE TITLE
conflict bug for fico7489/laravel-pivot

### ISSUE THREAD

**Issue by leunico** [laravel/telescope#351]
"root":
"message": "Undefined offset: 0"
"exception": "ErrorException"
"file": "/home/vagrant/code/dn_platform/vendor/laravel/telescope/src/Watchers/ModelWatcher.php"
"line": 35
"trace":
0:
"file": "/home/vagrant/code/dn_platform/vendor/laravel/telescope/src/Watchers/ModelWatcher.php"
"line": 35
"function": "handleError"
"class": "Illuminate\Foundation\Bootstrap\HandleExceptions"
"type": "->"
1:
"file": "/home/vagrant/code/dn_platform/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php"
"line": 357
"function": "recordAction"
"class": "Laravel\Telescope\Watchers\ModelWatcher"
"type": "->"
...

**Comment by themsaid** [comment]
issue with zero description.

**Comment by bbashy** [comment]
Getting this as well with same package.

I have the package to be able to watch pivot table attachments events and action things from it.

Stack
```
/var/www/crm/vendor/laravel/telescope/src/Watchers/ModelWatcher.php:36
--
/var/www/crm/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:357
/var/www/crm/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:209
/var/www/crm/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:182
/var/www/crm/vendor/fico7489/laravel-pivot/src/Traits/ExtendFireModelEventTrait.php:37
/var/www/crm/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:733
/var/www/crm/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:644
/var/www/crm/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:591
/var/www/crm/app/Http/Controllers/Admin/UserController.php:182
```

User Model. Trait is added to get this.
```
protected static function boot()
{
    parent::boot();

    static::pivotAttached(function ($model, $relationName, $pivotIds) {
        //
    }
}
```

**Comment by paras-malhotra** [comment]
The issue is that the framework passes the model object in the payload which is wrapped in an array because of this line: https://github.com/laravel/framework/blob/2ffac1635a473a45ff14e138b84f06edd11e76ef/src/Illuminate/Events/Dispatcher.php#L244

The package on the other hand passes an associative array as payload (https://github.com/fico7489/laravel-pivot/blob/41b514e82d8321773f7fade7057582fe1a4e9c64/src/Traits/ExtendFireModelEventTrait.php#L34), so `$data[0]` results in an error.

To be honest, this one is a tough nut to crack without being specific about the package. Possibly using `$data[0] ?? $data['model']` is too specific to the package.

I guess the alternative and best way to solve the issue is to write a custom model watcher that takes care of this.

**Comment by paras-malhotra** [comment]
@bbashy, in the next release, #465 can solve this. Just add this to your Telescope config:

```php
ModelWatcher::class => [
    'enabled' => true,
    'events' => [
        'eloquent.retrieved*', 'eloquent.creating*', 'eloquent.created*', 'eloquent.updating*',
        'eloquent.updated*',  'eloquent.saving*', 'eloquent.saved*', 'eloquent.restoring*', 
        'eloquent.restored*', 'eloquent.deleting*', 'eloquent.deleted*', 'eloquent.forceDeleted*'
    ],
],
```

**Comment by leunico** [comment]
@paras-malhotra  thanks

**Comment by bbashy** [comment]
@paras-malhotra Updated to v1.0.10 and used the events list but it's still erroring for pivots.

**Comment by paras-malhotra** [comment]
@bbashy that's strange. Is it the same stack trace? Can you double check a dump of `config('telescope.watchers')`?

**Comment by bbashy** [comment]
@paras-malhotra Is it because the event is `"event" => "eloquent.created: App\Models\SomeName"` and I'm watching `"eloquent.created*"`? Don't think this will help as I still need to watch this model?

**Comment by paras-malhotra** [comment]
That's strange. I thought the laravel-pivot package only creates additional events but doesn't modify the framework's created event?

**Comment by bbashy** [comment]
That's the event it sends through with the data from the package. I can't exclude it then :(
