### ISSUE TITLE
Issues with Notifications in a Job

### ISSUE THREAD

**Issue by Braunson** [laravel/telescope#353]
I'm running a job via sync but this error keeps happening after installing Laravel Telescope.

It looks like it's caused due to this code to notify a user. I've tried stopping Telescope from recording before the notification is sent and starting it after with the same error below.

#### Possible Cause?

```php
$this->user->notify(new App\Notifications\ListImportComplete($this->list));
```

`$this->user` is an instance of `App\Models\User`. `$this->list` is an instance of another model `App\Models\CallList`. This worked prior to installing Laravel Telescope. Any ideas?

The error happens on the event `"eloquent.created: Laravel\Spark\Notification"` as the `Telescope\src\Watchers\ModelWatcher.php` is calling `$data[0]->getKey()` returns a UUID on the `Laravel\Spark\Notification` class.

#### Stack

```php
{
    "message": "Object of class Ramsey\\Uuid\\Converter\\Number\\BigNumberConverter could not be converted to string",
    "exception": "Symfony\\Component\\Debug\\Exception\\FatalErrorException",
    "file": "/home/vagrant/project/vendor/laravel/telescope/src/Watchers/ModelWatcher.php",
    "line": 35,
    "trace":[]
}
```

**Comment by Braunson** [comment]
Looks like an update to the Laravel\Telescope\Watchers\ModelWatcher's method `recordAction` will resolve this issue, not ideally but it solves the issue for now.

Here's a working updated function:

```php
public function recordAction($event, $data)
    {
        if (! $this->shouldRecord($event)) {
            return;
        }

        if (is_object($data[0]->getKey()) AND $data[0]->getKey() instanceOf \Ramsey\Uuid\Uuid) {
            $key = $data[0]->getKey()->toString();
        } else {
            $key = $data[0]->getKey();
        }
        
        $model = get_class($data[0]).':'.implode('_', (array) $key);

        $changes = $data[0]->getChanges();

        Telescope::recordModelEvent(IncomingEntry::make(array_filter([
            'action' => $this->action($event),
            'model' => $model,
            'changes' => empty($changes) ? null : $changes,
        ]))->tags([$model]));
    }
```

**Comment by CrixuAMG** [comment]
Wouldn't the following be a better replacement?
```
$key = $data[0]->getKey();
if (is_object($key) && $key instanceOf \Ramsey\Uuid\Uuid) {
    $key = $key->toString();
}
```
This reduces the amount of calls to the method `getKey` and simplifies the check.

**Comment by themsaid** [comment]
I can't replicate this issue using Spark + Telescope.

**Comment by paras-malhotra** [comment]
@themsaid I think we cannot rely on `$model->getKey()` returning a string. The signature of the method defines the return type as mixed because it gets the attribute which may have a mutator.

https://github.com/laravel/framework/blob/5d8508f67fbc66938ad15c3dad9dc6ea214b3e28/src/Illuminate/Database/Eloquent/Model.php#L1381-L1389

**Comment by themsaid** [comment]
`getKey` would return string or integer, both can be casted to string. same with UUID, it can be casted to string. So there must be something special about that app.

**Comment by paras-malhotra** [comment]
@themsaid `getKey()` is allowed to return any object (even objects that cannot be typecasted to strings).

**Comment by Braunson** [comment]
@themsaid `getKey` for a `Notification` on a fresh install is returning the UUID Object and throws an error accordingly. Perhaps it's the PHP version I'm using (Forge 7.2), but it's happening on Homestead 7.2 as well. Nothing special on this app, it's a **fresh** install with Spark 7.x.

Here's the Notification which is triggered from a Job on a User object.

```
<?php

namespace App\Notifications\CallList;

use App\Models\CallList;
use Illuminate\Bus\Queueable;
use Illuminate\Notifications\Notification;
use Illuminate\Contracts\Queue\ShouldQueue;
use Laravel\Spark\Notifications\SparkChannel;
use Illuminate\Notifications\Messages\MailMessage;
use Laravel\Spark\Notifications\SparkNotification;

class CallListCSVImportComplete extends Notification
{
    use Queueable;

    protected $list;

    public function __construct(CallList $list)
    {
        $this->list = $list;
    }

    public function via($notifiable)
    {
        return [SparkChannel::class];
    }

    public function toSpark($notifiable)
    {
        return (new SparkNotification)
                ->action('View List', route('lists.show', $this->list))
                ->icon('fa-upload')
                ->body('The call list "' . $this->list->name . '" import has completed!');
    }
}

```

**Comment by noreason** [comment]
Can confirm I'm having the exact same issue. PHP 7.2.10, Spark 7.x, Laravel 5.7

**Comment by themsaid** [comment]
This is now fixed.
