### ISSUE TITLE
Call to undefined method Symfony\Component\HttpFoundation\Response::getOriginalContent()

### ISSUE THREAD

**Issue by hs-moosa** [laravel/telescope#354]
`Symfony\Component\HttpFoundation\Response` dose not have a method called `getOriginalContent` its giving error.
https://github.com/laravel/telescope/blob/0727782798faf00edd2baacb4bc3b26a9f32e70c/src/Watchers/RequestWatcher.php#L115

**Comment by sabid** [comment]
the same error,

**Comment by Fendy5** [comment]
I also encountered this mistake.

**Comment by hs-moosa** [comment]
I guesses the method is expecting `Illuminate\Http\Response` but when you are not using the view it has a normal `Symfony\Component\HttpFoundation\Response`

**Comment by themsaid** [comment]
Fixed by checking if the response is `Illuminate\Http\Response` before trying to get original content.

**Comment by jlsjonas** [comment]
i.e. in e4f5c0dd07970fb73fbf79cfa96316b7f91560cf

@themsaid would you mind closing and/or mentioning issues in the commit messages for easier tracking? thanks :) (it shouldn't cost you more time as you have to open the issue to comment&close otherwise anyway)
