### ISSUE TITLE
Redis tab is always empty

### ISSUE THREAD

**Issue by michaelnguyen547** [laravel/telescope#355]
I do have data saved in Redis, however, Telescope Redis tab is always empty. What should be there?

**Comment by themsaid** [comment]
https://github.com/laravel/telescope/issues/321

**Comment by rickmacgillis** [comment]
I'm reopening this issue, as it seems that even with `Redis::enableEvents();` in `AppServiceProvider`'s `boot()` method, it still stays empty.

The way I have been testing this is to use Redis as the cache driver, and then verify that the cache was used in some way as witnessed by the cache tab having data.

Here's a loom video demoing the issue at hand: https://www.useloom.com/share/c087546105054ffd9efa8cd5bd7e1799

**Comment by nelsonmelecio** [comment]
I just cloned version 2.0.2 (latest as of the writing). The issue on 'Redis' page being empty is still persist...

**Comment by shreyanshpanchal** [comment]
After putting `Redis::enableEvents();` in AppServiceProvider &
Restarting the `supervisor`, Fixed it for me.

**Comment by jarnovanleeuwen** [comment]
This can happen when you are also using Redis as cache driver. See the related issue here: https://github.com/laravel/telescope/issues/622

Workaround is to replace `Redis::enableEvents()` with:

```php
// For previously resolved connections.
foreach (Redis::connections() as $connection) {
    $connection->setEventDispatcher($this->app->make('events'));
}

// For new connections.
Redis::enableEvents();
```

**Comment by jlsjonas** [comment]
Note that your workaround can throw an `Invalid argument supplied for foreach()` if there's no (active?) redis connection yet.
_Simplest_ workaround is implicitly typecasting `Redis::connections()` to an array (prepend with `(array) `)

**Comment by jarnovanleeuwen** [comment]
Ah, I expected an empty array when there are no resolved connections yet. Thanks, I changed it.
