### ISSUE TITLE
SQL Syntax Error

### ISSUE THREAD

**Issue by Diddyy** [laravel/telescope#36]
After following the correct install steps on my current laravel project:

- ```composer require laravel/telescope --dev```
- ```php artisan telescope:install```
- ```php artisan migrate```

I get the following error when running after running the ```migrate``` command:
```➜  hostinhub git:(master) ✗ php artisan migrate
Migrating: 2018_08_08_100000_create_telescope_entries_table

   Illuminate\Database\QueryException  : SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json not null, `created_at` datetime null) default character set utf8mb4 collate' at line 1 (SQL: create table `telescope_entries` (`sequence` bigint unsigned not null auto_increment primary key, `uuid` char(36) not null, `batch_id` char(36) not null, `family_hash` varchar(255) null, `should_display_on_index` tinyint(1) not null default '1', `type` varchar(20) not null, `content` json not null, `created_at` datetime null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')

  at /Users/josh/code/hostinhub/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664
    660|         // If an exception occurs when attempting to run a query, we'll format the error
    661|         // message to include the bindings with SQL, which will make this exception a
    662|         // lot more helpful to the developer instead of just the database's errors.
    663|         catch (Exception $e) {
  > 664|             throw new QueryException(
    665|                 $query, $this->prepareBindings($bindings), $e
    666|             );
    667|         }
    668|

  Exception trace:

  1   PDOException::("SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json not null, `created_at` datetime null) default character set utf8mb4 collate' at line 1")
      /Users/josh/code/hostinhub/vendor/laravel/framework/src/Illuminate/Database/Connection.php:452

  2   PDO::prepare("create table `telescope_entries` (`sequence` bigint unsigned not null auto_increment primary key, `uuid` char(36) not null, `batch_id` char(36) not null, `family_hash` varchar(255) null, `should_display_on_index` tinyint(1) not null default '1', `type` varchar(20) not null, `content` json not null, `created_at` datetime null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'")
      /Users/josh/code/hostinhub/vendor/laravel/framework/src/Illuminate/Database/Connection.php:452

  Please use the argument -v to see more details.
```
I have also noticed that no telescope config file is found in the config directory.

Should it help:
mySQL Version: ```Server version: 10.2.6-MariaDB Homebrew```
PHP Version: ```PHP 7.2.11 (cli) (built: Oct 11 2018 16:24:11) ( NTS )```
NGINX version: ```nginx/1.15.5```

Thanks

**Comment by astr0naugh7** [comment]
I get the exact same error. 

PHP 7.2, XAMPP 3.2.2

**Comment by themsaid** [comment]
That's because MariaDB doesn't have a `json` field type.

**Comment by Diddyy** [comment]
Updating MariaDB to ```Server version: 10.3.10-MariaDB Homebrew``` resolves the issue as the JSON alias was added in MariaDB 10.2.7.

**Comment by themsaid** [comment]
Thanks @Diddyy adding that to the installation docs.

**Comment by astr0naugh7** [comment]
> That's because MariaDB doesn't have a `json` field type.

Okay, thanks for the update, seems like Diddyy found a solution so we'll update this. Thank you!

**Comment by Lunberg88** [comment]
I'm using AMPPS web-server on my mac and still have an error with migration... Any ideas?

**Comment by warrenca** [comment]
For apps that can't simply do a DB upgrade to MySQL v5.7+ or to Mariadb v10.2.7+, you can migrate the telescope to a different database instance.

- I'm using docker in development so I was able to spin up a new MySQL v5.7 easily. Suppose `mysql57` and `3307` is your telescope host and port respectively.
- Create a database named `telescope` in that new MySQL v5.7 server.
- Open `config/telescope.php` and change from `'connection' => env('DB_CONNECTION', 'mysql'),` to `'connection' => env('TELESCOPE_DB_CONNECTION', 'telescope'),`
- Open `config/database.php` and add the `telescope` values in your `connections` array like

```
'connections' => [
...
        'mysql' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],

        'telescope' => [
            'driver'    => 'mysql',
            'host'      => env('TELESCOPE_DB_HOST', 'mysql57'),
            'port'      => env('TELESCOPE_DB_PORT', '3307'),
            'database'  => env('TELESCOPE_DB_DATABASE', 'telescope'),
            'username'  => env('DB_USERNAME', 'forge'),
            'password'  => env('DB_PASSWORD', ''),
            'charset'   => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix'    => '',
            'strict'    => false,
        ],
...
```

- Running `php artisan migrate --database=telescope` will yield to
```
Migration table created successfully.
Migrating: 2018_08_08_100000_create_telescope_entries_table
Migrated:  2018_08_08_100000_create_telescope_entries_table
```

Lastly, if you have different connection values, you can change the env variables `TELESCOPE_DB_CONNECTION`, `TELESCOPE_DB_HOST`, `TELESCOPE_DB_PORT` and `TELESCOPE_DB_DATABASE`.

I find this a good fit if you're running multiple Laravel apps, you can simply point the telescope to a different database without affecting your current database/s. But for now telescope assumes you're using it for one website and you can't differentiate requests coming from different apps.
