### ISSUE TITLE
Authorization not working, backpack

### ISSUE THREAD

**Issue by tmindiashvili1** [laravel/telescope#360]
I use laravel backpack and override Telescope Authorize Middleware class, As shown on the photo. But backpack_auth()->guest(); always true, but I have already logged in.

![test12312](https://user-images.githubusercontent.com/33889365/48263430-8463b680-e43f-11e8-857b-7bee02565791.PNG)

I use backpack guard.

![guard](https://user-images.githubusercontent.com/33889365/48263636-3b603200-e440-11e8-8a59-87d8e4e72767.PNG)

**Comment by tmindiashvili1** [comment]
$user = \Auth::guard('backpack'); user null, but I have already logged in.

![sessionguard](https://user-images.githubusercontent.com/33889365/48266361-9138d800-e448-11e8-9ef2-d48d5e1a92a7.PNG)

**Comment by paras-malhotra** [comment]
This is unrelated to the `laravel/telescope` repo. You should add this issue to the backpack repo.

**Comment by tmindiashvili1** [comment]
default authorization not working too

**Comment by tmindiashvili1** [comment]
> This is unrelated to the `laravel/telescope` repo. You should report this issue to the backpack repo.

default authorization not working too

**Comment by paras-malhotra** [comment]
In that case you can file a separate issue with the code and expected result

**Comment by tmindiashvili1** [comment]
> In that case you can file a separate issue with the code and expected result

![12312dsa](https://user-images.githubusercontent.com/33889365/48270056-7cf9d880-e452-11e8-8b96-325577c60749.PNG)

**Comment by paras-malhotra** [comment]
What is the issue here?

**Comment by tmindiashvili1** [comment]
> What is the issue here?

I authorized other user but laravel telescope show anyway

**Comment by paras-malhotra** [comment]
The default `authorization` method looks like this:

```php
    /**
     * Configure the Telescope authorization services.
     *
     * @return void
     */
    protected function authorization()
    {
        $this->gate();

        Telescope::auth(function ($request) {
            return app()->environment('local') ||
                   Gate::check('viewTelescope', [$request->user()]);
        });
    }
```

You need to override this method in your `TelescopeServiceProvider` and remove `app()->environment('local')` if you only want the Gate check like so:

```php
    /**
     * Configure the Telescope authorization services.
     *
     * @return void
     */
    protected function authorization()
    {
        $this->gate();

        Telescope::auth(function ($request) {
            return Gate::check('viewTelescope', [$request->user()]);
        });
    }
```

**Comment by tmindiashvili1** [comment]
> The default `authorization` method looks like this:
> 
> ```
>     /**
>      * Configure the Telescope authorization services.
>      *
>      * @return void
>      */
>     protected function authorization()
>     {
>         $this->gate();
> 
>         Telescope::auth(function ($request) {
>             return app()->environment('local') ||
>                    Gate::check('viewTelescope', [$request->user()]);
>         });
>     }
> ```
> 
> You need to override this method in your `TelescopeServiceProvider` and remove `app()->environment('local')` if you only want the Gate check like so:
> 
> ```
>     /**
>      * Configure the Telescope authorization services.
>      *
>      * @return void
>      */
>     protected function authorization()
>     {
>         $this->gate();
> 
>         Telescope::auth(function ($request) {
>             return Gate::check('viewTelescope', [$request->user()]);
>         });
>     }
> ```

$request->user() is null, and why ?

**Comment by paras-malhotra** [comment]
Refer https://github.com/laravel/telescope/issues/294#issuecomment-435018272 and https://github.com/laravel/telescope/issues/294#issuecomment-434950639

**Comment by themsaid** [comment]
Can't replicate this, authentication with custom guard is working. and `$request->user('my_guard_name')` returns the logged in user.

**Comment by tmindiashvili1** [comment]
> Can't replicate this, authentication with custom guard is working. and `$request->user('my_guard_name')` returns the logged in user.

null returns ((

**Comment by themsaid** [comment]
closing since it doesn't seem to be Telescope related.

**Comment by meeprakash25** [comment]
$request->user() is null
