### ISSUE TITLE
Disable rendering mailables?

### ISSUE THREAD

**Issue by ohnotnow** [laravel/telescope#364]
Hi,

Just a (yet another!) feature request.  The ability to render the mailables via telescope is great - I love the feature :-). But once in a while bits of various systems send out email that shouldn't be visible to admin users as they have sensitive or confidential/NDA'd information in them.  I'm possibly in a tiny minority here I realise ;-)

In a perfect world I'd like to be able to do something like :
```
public $disableRenderPreview = [
  SomeSensitiveMailable::class,
  SomeOtherMailable::class
];
```
Or maybe :
```
class SomeSensitveMessage extends Mailable
{
...
  public function allowsTelescopePreview()
  {
    // maybe some business logic...
    return false;
  }
}
```
(or something like that)

I've only had a quick scan of the code and there wasn't anything leaping out at me for doing that - I'd be happy to try and work on a PR if anyone else is in the same situation as me and it had some value to the package :-)

Thanks again for Telescope in general - it's very, very appreciated :-)

**Comment by sifex** [comment]
Are your admin users not trusted staff members – just trying to gauge the need for if it needs a separate class or an absolute toggle option instead

**Comment by ohnotnow** [comment]
They are trusted to administer the site - but not necessarily be able to view the contents of every message.  99% of the time it's not a problem - but once in a while you have something (even low-level like 'StaffSalaryReviewMail') which renders out a link to a signed, time-limited URL - it's just not something you want to become available to anyone who has access to telescope.  Some admins _could_ in theory log into the database, hack the code, whatever - and get some kind of access - but that's a lot more of a deliberate 'breach of trust' than just 'click - oh!'.

Aside from the legal/restricted stuff - it just removes a little human 'temptation factor'.

**Comment by sifex** [comment]
Ah ok, would a `Telescope::disableEmailPreviews()` (Or similar setup config parameter) command suffice?

**Comment by ohnotnow** [comment]
If the ::disableEmailPreviews() could take an array of mailable classes that would be perfect.  But disabling them all would do - I'd rather cut them off altogether than let one slip through :-)

**Comment by themsaid** [comment]
I believe you should disable recording mail in production if you don't want you and your team members people to know what emails are sent by the system.

**Comment by ohnotnow** [comment]
Sorry - I should have been clearer.  It's fine (and very useful) for them to know _what_ emails are sent - just not to see the contents :-). At the moment we tend to build dashboard/logs for each app which kind of replicates what Telescope is doing - it would be very nice if we could drop our custom code and unify around Telescope.  No worries if it's not something you want to bring into the core package - I realise we're in an unusual situation :-)

**Comment by themsaid** [comment]
I'm actually thinking of providing the ability to show custom log interfaces inside Telescope. Still not planned but I think it would be useful. Maybe when this is out you can log emails using custom code and display it in Telescope the way you want.

**Comment by ohnotnow** [comment]
Ah - that would be very, very good for us :-). Thanks again for the package - it's already proving itself to us in production :-)
