### ISSUE TITLE
mongodb not support

### ISSUE THREAD

**Issue by zoulux** [laravel/telescope#371]
mongodb not support

**Comment by deleugpn** [comment]
I don't think MongoDB is supported by anything on Laravel?

**Comment by zoulux** [comment]
Then I want to do data migration, which database is appropriate, convenient and fast.

**Comment by themsaid** [comment]
Laravel doesn't support MongoDB out of the box.

**Comment by yuvraj993** [comment]
I have fixed that issue

**Comment by yuvraj993** [comment]
You need to extend **EntryModel** which is in **vendor/laravel/telescope/src/Storage/DatabaseEntriesRepository.php** location of the telescope package and set moloquent connection there.

i.e.

//use Illuminate\Database\Eloquent\Model;
use Moloquent as Model;

class EntryModel extends Model
