### ISSUE TITLE
Queries pagination in request details

### ISSUE THREAD

**Issue by erikgaal** [laravel/telescope#374]
Currently, when there are more than 50 queries in a request, only 50 are shown. In the code below you can see that there is a fallback of 50 entries for a request, but this could be overwritten. It would be nice if there was a way to paginate through all queries for this request.

https://github.com/laravel/telescope/blob/cea78bd64b2b138194e0f59f774a9ff234b345a4/src/Storage/EntryQueryOptions.php#L57-L66

**Comment by themsaid** [comment]
I don't understand what you want.

**Comment by themsaid** [comment]
I see.

Thanks, fixed that :)

**Comment by erikgaal** [comment]
Thanks. :)

**Comment by paras-malhotra** [comment]
https://github.com/laravel/telescope/blob/350a0702aa6304d4d3cac5cbdd38de6b6d8fcfc7/src/Http/Controllers/EntryController.php#L49

@themsaid wont this have a performance impact? I think pagination would be a better option. If not, would be best to stick with 50.

**Comment by spielfigur** [comment]
maybe i missed it, but is it possible to overwrite the limit or paginate through the entries?

<img width="626" alt="image" src="https://user-images.githubusercontent.com/6874264/57397986-38b37f00-71ce-11e9-95e0-50b138614267.png">
