### ISSUE TITLE
how to get latest commits since tagged version with composer?

### ISSUE THREAD

**Issue by vesper8** [laravel/telescope#378]
normally switching to the dev-master gets the latest commits, but I'm seeing an odd behaviour with Telescope

I've tried
```
"laravel/telescope": "1.0.x-dev",
"laravel/telescope": "dev-master",
"laravel/telescope": "^1.0",
```

And all of those result in

```
Installing laravel/telescope (dev-master cb05ac7)
```

Which is an old commit from October 23rd

With 
```
"laravel/telescope": "^0.1.8",
```

I get the latest tagged release, but how can I be on the dev master and get those 24 commits since last tagged release?

**Comment by paras-malhotra** [comment]
Yeah, the master and 1.0 branch have the exact same `branch-alias`. That's what's causing it.

**Comment by themsaid** [comment]
releasing in a bit

**Comment by vesper8** [comment]
@themsaid a new release is always appreciated.. but I feel it should be possible to get the very latest commits at any time, and I think the branches are not setup properly currently as @paras-malhotra mentioned
