### ISSUE TITLE
Could not load assets over http

### ISSUE THREAD

**Issue by phoenixg** [laravel/telescope#388]
The telescope assets were loaded via HTTP protocol by default, so the page cannot function correctly.

<img width="1279" alt="wx20181115-162729 2x" src="https://user-images.githubusercontent.com/990040/48539860-5ffe5300-e8f3-11e8-8bd4-a263bdf464a0.png">

**Comment by themsaid** [comment]
Please check on the forums for help on how to configure your app for ssl.
