### ISSUE TITLE
Error while running migration for telescope...

### ISSUE THREAD

**Issue by Lunberg88** [laravel/telescope#39]
Hi.
I had an error when were tried to install telescope with migration:

`Migrating: 2018_08_08_100000_create_telescope_entries_table

   Illuminate\Database\QueryException  : SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'json not null, `created_at` datetime null) default character set utf8mb4 collate' at line 1 (SQL: create table `telescope_entries` (`sequence` bigint unsigned not null auto_increment primary key, `uuid` char(36) not null, `batch_id` char(36) not null, `family_hash` varchar(191) null, `should_display_on_index` tinyint(1) not null default '1', `type` varchar(20) not null, `content` json not null, `created_at` datetime null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')
`
And once more:
`  1   PDOException::("SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'json not null, `created_at` datetime null) default character set utf8mb4 collate' at line 1")
      /Applications/AMPPS/www/rii_spa/vendor/laravel/framework/src/Illuminate/Database/Connection.php:452

  2   PDO::prepare("create table `telescope_entries` (`sequence` bigint unsigned not null auto_increment primary key, `uuid` char(36) not null, `batch_id` char(36) not null, `family_hash` varchar(191) null, `should_display_on_index` tinyint(1) not null default '1', `type` varchar(20) not null, `content` json not null, `created_at` datetime null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'")
      /Applications/AMPPS/www/rii_spa/vendor/laravel/framework/src/Illuminate/Database/Connection.php:452`

How to solve it?

**Comment by themsaid** [comment]
https://github.com/laravel/telescope/issues/36
