### ISSUE TITLE
[Feature Request] Addition to UI/CSS on Request -> Path

### ISSUE THREAD

**Issue by riyuk** [laravel/telescope#392]
If you're using Telescope to inspect API-Requests the layout breaks if the Request-Path is too long.
This could happen very easily if you do a GET Request with a jwt-Token with `token` as Query-Param.

A simply `word-break: break-all;` on the Request Path `<td>` should fix this.

**Comment by paras-malhotra** [comment]
@riyuk can you attach a screenshot. The URI is truncated to 70 characters, so I'm not sure what's happening there.

**Comment by riyuk** [comment]
@paras-malhotra screenshot attached.
<img width="1242" alt="bildschirmfoto 2018-11-15 um 14 14 42" src="https://user-images.githubusercontent.com/101386/48555256-ef4e3b00-e8e0-11e8-9f36-ad8c8d588135.png">

**Comment by themsaid** [comment]
fixed
