### ISSUE TITLE
Request is not recorded when using ShouldBroadcastNow

### ISSUE THREAD

**Issue by rolandstarke** [laravel/telescope#412]
When I trigger the following event the recording stops for this request.

```php
class Test implements ShouldBroadcastNow
{
//...

class BroadcastTestController extends Controller
{
    public function index(Request $request)
    {
        event(new Test());
        //this request is not recorded
//...
```

I think its because `ShouldBroadcastNow` triggers a `JobProcessed` event. and then the recording is stopped prematurely:

https://github.com/laravel/telescope/blob/81be58678d7d3a966651f2ac784fbdf8724b34b5/src/ListensForStorageOpportunities.php#L90

Related issue:  https://github.com/laravel/telescope/issues/201

**Comment by paras-malhotra** [comment]
This seems to be a bug. @themsaid is there any reason why we need to call `stopRecording` and `startRecording`?

**Comment by themsaid** [comment]
I can't replicate it, when I run a request that fires an event both the request and the event are recorded.

**Comment by rolandstarke** [comment]
I will recheck this evening did you check with `ShouldBroadcastNow`?

**Comment by themsaid** [comment]
I was able to replicate finally and fixed it. thanks :)
