### ISSUE TITLE
Ajax request and links URL are using an absolute root reference

### ISSUE THREAD

**Issue by n0099** [laravel/telescope#414]
When visiting `example.com/laravel/telescope` all the links and ajax requesting will refer to the absolute root path such as `example.com/telescope/requests (links)` or `example.com/telescope/telescope-api/requests?tag=&before=&take=50&family_hash= (ajax)`  which is unreachable.

**Comment by n0099** [comment]
related:
#270 
#293 
PR: #281

**Comment by themsaid** [comment]
don't use laravel in a sub directory.

**Comment by n0099** [comment]
> don't use laravel in a sub directory.

It's not mentioned anywhere in these documents, and laravel itself seems compatible with sub directory url: https://laravel-news.com/subfolder-install

**Comment by themsaid** [comment]
@n0099 I don't believe it is. I've seen tons of issues reported and my conclusion is to always go for a subdomain rather than a subdirectory.

**Comment by GALHP** [comment]
Ran into the same iussue with telescope and laravel app in a subdirectory.

Here is my hacky workaround that for now seems to work for me with some constraints

```
laravel/framework 5.7.28
laravel/telescope 1.2
```

I run the laravel app und `/api` and therefore I have `.htaccess` at html root with rewrites

```
<IfModule mod_rewrite.c>
  RewriteEngine on

  RewriteCond %{REQUEST_URI} ^/telescope
  RewriteRule ^telescope/(.*) /api/telescope/$1 [NC,L]
  RewriteCond %{REQUEST_URI} !^/api
  RewriteCond %{REQUEST_FILENAME} -s [OR]
  RewriteCond %{REQUEST_FILENAME} -l [OR]
  RewriteCond %{REQUEST_FILENAME} -d
  RewriteRule ^.*$ - [NC,L]
  RewriteRule ^(.*) index.html [NC,L]
</IfModule>
```

The additional telescope rules ensure that the ajax requests are correctly handled.
The entry point of telescope is `/api/telescope` or `/telescope`.

Navigating to a telescope category leads to `/telescope/<category>` URLs in the browser. 
The vue router handles all the routing locally and the navigation works as long you refresh the page, than the server will be called this workaround breaks. There it is just a  "hacky" workaround.

But maybe it helps someone anyway.
