### ISSUE TITLE
Telescope is slowing down the application

### ISSUE THREAD

**Issue by m-a-k-o** [laravel/telescope#419]
Hi.

Telescope is slowing down the application. I have changed following code in TelescopeServiceProvider:

```
Telescope::filter(function (IncomingEntry $entry) {
    if ($this->app->environment(['local', 'sbx'])) {
        return true;
    }

    return $entry->isReportableException() ||
         $entry->isFailedJob() ||
         $entry->isScheduledTask() ||
         $entry->hasMonitoredTag();
});
```

TELESCOPE_ENABLED=false
3.12s

TELESCOPE_ENABLED=true
12.67s

I found one interesting difference between telescope behaviour on localhost and hosting.

When I visit same url on localhost and sbx app.

On sbx app in telescope I only see:
![image](https://user-images.githubusercontent.com/6873535/48781952-56069680-ecdd-11e8-8a1e-0bdca377d164.png)
But there should be two requests not only one.

On other side when I visit same url on localhost I see:
![image](https://user-images.githubusercontent.com/6873535/48782000-75052880-ecdd-11e8-855f-ab98ab2f1d5a.png)

First request is same but second is only visible on localhost.

Please if you need more info,logs, ... let me know.

Thank you.

**Comment by themsaid** [comment]
Use Telescope wisely, only record what you need.

**Comment by m-a-k-o** [comment]
But why there is different records in localhost and sbx?

**Comment by themsaid** [comment]
We can't tell :) It's your application and your environment, only you can find an answer to this.

**Comment by m-a-k-o** [comment]
Also when I use out of box configuration without modification what I did to TelescopeServiceProvider result is same. 

I tried only with return $entry->isScheduledTask(); and also it's slowing down the app. That only thing I was needed most.

**Comment by themsaid** [comment]
I have a huge app running in production that Telescope is monitoring and Telescope has no effect on the response time or the time Queued jobs take. That's why I said you are the only one who can dig further to find what's slowing your app :)

**Comment by m-a-k-o** [comment]
Thank you :) I will try to find out why my app is slow with Telescope and I will update the issue ;)

Have a nice day!

**Comment by Tesla2k** [comment]
I hade the same problem telescope was slowing done some request by about 50%. I have very large response and the problem was in the RequestWatcher. The size limit is applied after trying thinks like json_decode and so on which took quite a long time.

I made my own RequestWatcher derived from the original one. The Telescope front end says "This watcher is turned off" but it works fine.

```
use Laravel\Telescope\Watchers\RequestWatcher;
use Symfony\Component\HttpFoundation\Response;


class FastRequestWatcher extends RequestWatcher
{
    /**
     * Format the given response object.
     *
     * @param  \Symfony\Component\HttpFoundation\Response  $response
     * @return array|string
     */
    protected function response(Response $response)
    {
        $content = $response->getContent();
        if (!$this->contentWithinLimits($content))
        {
            return 'Large Response';
        }
        parent::response($response);

    }
}

```
