### ISSUE TITLE
Telescope can throw 1406 Data too long errors.

### ISSUE THREAD

**Issue by Scarwolf** [laravel/telescope#420]
We are using Bugsnag and got 3 errors from Telescope in Production. The problem is: `Illuminate\Database\QueryException SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'content' at row 482 (SQL: insert into `telescope_entries` [....]`. 

The entire query is 234.207 characaters long, I guess it should not be that long? We are using the version from this monday.

**Comment by bonzai** [comment]
#166
