### ISSUE TITLE
Some payload data gets truncated

### ISSUE THREAD

**Issue by jonnywilliamson** [laravel/telescope#427]
I have an application that has a webhook to receive data from Telegram for a bot.

For some reason, a few keys in the payload appear to be truncated when I try to display them on Telescope. It's nearly always the "entities" key and the data isn't very long/large. 

I was wondering if there is a depth limit or similar? Otherwise I would love to be able to see all the key/data that was sent when telegram sends me an update.

Here's an example of a raw request that gets sent to the webhook. Note the "entities" section.

```
POST /webhook HTTP/1.1
Host: mydomain.com
cache-control: no-cache
{
    "update_id": 304312648,
    "message": {
        "message_id": 221569,
        "from": {
            "id": 12345678,
            "is_bot": false,
            "first_name": "Jonathan",
            "last_name": "Williamson",
            "username": "jwilliamson",
            "language_code": "en"
        },
        "chat": {
            "id": 12345678,
            "first_name": "Jonathan",
            "last_name": "Williamson",
            "username": "jwilliamson",
            "type": "private"
        },
        "date": 1542882700,
        "text": "\/flight ei105",
        "entities": [
            {
                "offset": 0,
                "length": 7,
                "type": "bot_command"
            }
        ]
    }
}
```

And here is the exact same request as shown on Telescope.

![image](https://user-images.githubusercontent.com/2513663/48897582-59676280-ee42-11e8-9a6a-df0f2f07e1d3.png)

Any idea why it would truncate just that section?

**Comment by themsaid** [comment]
Fixed that. Releasing in a bit.

**Comment by jonnywilliamson** [comment]
Thank you. I've just upgraded and it is working much better.

Just wondering why you don't close these issues with the commit number?

Telescope is phenomenal, thank you so much for it. 👍
