### ISSUE TITLE
Getting an error from IncomingEntry.php tags function

### ISSUE THREAD

**Issue by johnnoble1990** [laravel/telescope#428]
An api route on one of my projects is being broken after I added Telescope. Error is described below. It is fixed by disabling Telescope, but ideally I would like to be able to use Telescope for my api routes.

Type: Symfony\Component\Debug\Exception\FatalErrorException
File: /vendor/laravel/telescope/src/IncomingEntry.php
Function: tags
Line: 151

Object of class App\Http\Controllers\Api\LeadApiController could not be converted to string

$tags array contains "Auth:1" and $this->tags already contains the above object

**Comment by themsaid** [comment]
Please share the full stack trace.

**Comment by johnnoble1990** [comment]
For the time being this issue has resolved itself. If it comes back I will send the full stack trace.

**Comment by johnnoble1990** [comment]
[
  {
    "function": "__construct",
    "type": "->",
    "class": "Symfony\\Component\\Debug\\Exception\\FatalErrorException",
    "file": "/media/sf_Sites/leads/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php",
    "line": 137,
    "args": []
  },
  {
    "function": "fatalExceptionFromError",
    "type": "->",
    "class": "Illuminate\\Foundation\\Bootstrap\\HandleExceptions",
    "file": "/media/sf_Sites/leads/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php",
    "line": 123,
    "args": []
  },
  {
    "function": "handleShutdown",
    "type": "->",
    "class": "Illuminate\\Foundation\\Bootstrap\\HandleExceptions",
    "file": "/media/sf_Sites/leads/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php",
    "line": 0,
    "args": []
  },
  {
    "function": "array_unique",
    "file": "/media/sf_Sites/leads/vendor/laravel/telescope/src/IncomingEntry.php",
    "line": 151,
    "args": []
  },
  {
    "function": "tags",
    "type": "->",
    "class": "Laravel\\Telescope\\IncomingEntry",
    "file": "/media/sf_Sites/leads/vendor/laravel/telescope/src/Watchers/NotificationWatcher.php",
    "line": 40,
    "args": []
  },
  {
    "function": "recordNotification",
    "type": "->",
    "class": "Laravel\\Telescope\\Watchers\\NotificationWatcher",
    "file": "/media/sf_Sites/leads/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php",
    "line": 360,
    "args": []
  },
  {
    "function": "Illuminate\\Events\\{closure}",
    "type": "->",
    "class": "Illuminate\\Events\\Dispatcher",
    "file": "/media/sf_Sites/leads/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php",
    "line": 209,
    "args": []
  },
  {
    "function": "dispatch",
    "type": "->",
    "class": "Illuminate\\Events\\Dispatcher",
    "file": "/media/sf_Sites/leads/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php",
    "line": 147,
    "args": []
  },
  {
    "function": "sendToNotifiable",
    "type": "->",
    "class": "Illuminate\\Notifications\\NotificationSender",
    "file": "/media/sf_Sites/leads/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php",
    "line": 103,
    "args": []
  },
  {
    "function": "Illuminate\\Notifications\\{closure}",
    "type": "->",
    "class": "Illuminate\\Notifications\\NotificationSender",
    "file": "/media/sf_Sites/leads/vendor/laravel/framework/src/Illuminate/Support/Traits/Localizable.php",
    "line": 19,
    "args": []
  },
  {
    "function": "withLocale",
    "type": "->",
    "class": "Illuminate\\Notifications\\NotificationSender",
    "file": "/media/sf_Sites/leads/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php",
    "line": 105,
    "args": []
  },
  {
    "function": "sendNow",
    "type": "->",
    "class": "Illuminate\\Notifications\\NotificationSender",
    "file": "/media/sf_Sites/leads/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php",
    "line": 77,
    "args": []
  },
  {
    "function": "send",
    "type": "->",
    "class": "Illuminate\\Notifications\\NotificationSender",
    "file": "/media/sf_Sites/leads/vendor/laravel/framework/src/Illuminate/Notifications/ChannelManager.php",
    "line": 42,
    "args": []
  },
  {
    "function": "send",
    "type": "->",
    "class": "Illuminate\\Notifications\\ChannelManager",
    "file": "/media/sf_Sites/leads/vendor/laravel/framework/src/Illuminate/Notifications/RoutesNotifications.php",
    "line": 18,
    "args": []
  },
  {
    "function": "notify",
    "type": "->",
    "class": "App\\Api\\EnquiryMax",
    "file": "/media/sf_Sites/leads/app/Api/EnquiryMax.php",
    "line": 63,
    "args": []
  },
  {
    "function": "leadToEmax",
    "type": "->",
    "class": "App\\Api\\EnquiryMax",
    "file": "/media/sf_Sites/leads/app/Api/EnquiryMax.php",
    "line": 32,
    "args": []
  },
  {
    "function": "sendLeadToEmax",
    "type": "->",
    "class": "App\\Api\\EnquiryMax",
    "file": "/media/sf_Sites/leads/app/Jobs/SendToThirdParty/SendToEmax.php",
    "line": 27,
    "args": []
  },
  {
    "function": "handle",
    "type": "->",
    "class": "App\\Jobs\\SendToThirdParty\\SendToEmax",
    "file": "/media/sf_Sites/leads/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php",
    "line": 29,
    "args": []
  },
  {
    "function": "call_user_func_array:{/media/sf_Sites/leads/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29}",
    "file": "/media/sf_Sites/leads/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php",
    "line": 29,
    "args": []
  },
  {
    "function": "Illuminate\\Container\\{closure}",
    "type": "::",
    "class": "Illuminate\\Container\\BoundMethod",
    "file": "/media/sf_Sites/leads/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php",
    "line": 87,
    "args": []
  },
  {
    "function": "callBoundMethod",
    "type": "::",
    "class": "Illuminate\\Container\\BoundMethod",
    "file": "/media/sf_Sites/leads/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php",
    "line": 31,
    "args": []
  },
  {
    "function": "call",
    "type": "::",
    "class": "Illuminate\\Container\\BoundMethod",
    "file": "/media/sf_Sites/leads/vendor/laravel/framework/src/Illuminate/Container/Container.php",
    "line": 572,
    "args": []
  },
  {
    "function": "call",
    "type": "->",
    "class": "Illuminate\\Foundation\\Application",
    "file": "/media/sf_Sites/leads/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php",
    "line": 94,
    "args": []
  },
  {
    "function": "Illuminate\\Bus\\{closure}",
    "type": "->",
    "class": "Illuminate\\Bus\\Dispatcher",
    "file": "/media/sf_Sites/leads/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
    "line": 116,
    "args": []
  },
  {
    "function": "Illuminate\\Pipeline\\{closure}",
    "type": "->",
    "class": "Illuminate\\Pipeline\\Pipeline",
    "file": "/media/sf_Sites/leads/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
    "line": 104,
    "args": []
  },
  {
    "function": "then",
    "type": "->",
    "class": "Illuminate\\Pipeline\\Pipeline",
    "file": "/media/sf_Sites/leads/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php",
    "line": 98,
    "args": []
  },
  {
    "function": "dispatchNow",
    "type": "->",
    "class": "Illuminate\\Bus\\Dispatcher",
    "file": "/media/sf_Sites/leads/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php",
    "line": 49,
    "args": []
  },
  {
    "function": "call",
    "type": "->",
    "class": "Illuminate\\Queue\\CallQueuedHandler",
    "file": "/media/sf_Sites/leads/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php",
    "line": 83,
    "args": []
  },
  {
    "function": "fire",
    "type": "->",
    "class": "Illuminate\\Queue\\Jobs\\RedisJob",
    "file": "/media/sf_Sites/leads/vendor/laravel/framework/src/Illuminate/Queue/Worker.php",
    "line": 327,
    "args": []
  },
  {
    "function": "process",
    "type": "->",
    "class": "Illuminate\\Queue\\Worker",
    "file": "/media/sf_Sites/leads/vendor/laravel/framework/src/Illuminate/Queue/Worker.php",
    "line": 277,
    "args": []
  },
  {
    "function": "runJob",
    "type": "->",
    "class": "Illuminate\\Queue\\Worker",
    "file": "/media/sf_Sites/leads/vendor/laravel/framework/src/Illuminate/Queue/Worker.php",
    "line": 230,
    "args": []
  },
  {
    "function": "runNextJob",
    "type": "->",
    "class": "Illuminate\\Queue\\Worker",
    "file": "/media/sf_Sites/leads/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php",
    "line": 102,
    "args": []
  },
  {
    "function": "runWorker",
    "type": "->",
    "class": "Illuminate\\Queue\\Console\\WorkCommand",
    "file": "/media/sf_Sites/leads/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php",
    "line": 86,
    "args": []
  },
  {
    "function": "handle",
    "type": "->",
    "class": "Illuminate\\Queue\\Console\\WorkCommand",
    "file": "/media/sf_Sites/leads/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php",
    "line": 29,
    "args": []
  },
  {
    "function": "call_user_func_array:{/media/sf_Sites/leads/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29}",
    "file": "/media/sf_Sites/leads/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php",
    "line": 29,
    "args": []
  },
  {
    "function": "Illuminate\\Container\\{closure}",
    "type": "::",
    "class": "Illuminate\\Container\\BoundMethod",
    "file": "/media/sf_Sites/leads/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php",
    "line": 87,
    "args": []
  },
  {
    "function": "callBoundMethod",
    "type": "::",
    "class": "Illuminate\\Container\\BoundMethod",
    "file": "/media/sf_Sites/leads/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php",
    "line": 31,
    "args": []
  },
  {
    "function": "call",
    "type": "::",
    "class": "Illuminate\\Container\\BoundMethod",
    "file": "/media/sf_Sites/leads/vendor/laravel/framework/src/Illuminate/Container/Container.php",
    "line": 572,
    "args": []
  },
  {
    "function": "call",
    "type": "->",
    "class": "Illuminate\\Foundation\\Application",
    "file": "/media/sf_Sites/leads/vendor/laravel/framework/src/Illuminate/Console/Command.php",
    "line": 183,
    "args": []
  },
  {
    "function": "execute",
    "type": "->",
    "class": "Illuminate\\Queue\\Console\\WorkCommand",
    "file": "/media/sf_Sites/leads/vendor/symfony/console/Command/Command.php",
    "line": 255,
    "args": []
  },
  {
    "function": "run",
    "type": "->",
    "class": "Illuminate\\Queue\\Console\\WorkCommand",
    "file": "/media/sf_Sites/leads/vendor/laravel/framework/src/Illuminate/Console/Command.php",
    "line": 170,
    "args": []
  },
  {
    "function": "run",
    "type": "->",
    "class": "Illuminate\\Queue\\Console\\WorkCommand",
    "file": "/media/sf_Sites/leads/vendor/symfony/console/Application.php",
    "line": 886,
    "args": []
  },
  {
    "function": "doRunCommand",
    "type": "->",
    "class": "Illuminate\\Console\\Application",
    "file": "/media/sf_Sites/leads/vendor/symfony/console/Application.php",
    "line": 262,
    "args": []
  },
  {
    "function": "doRun",
    "type": "->",
    "class": "Illuminate\\Console\\Application",
    "file": "/media/sf_Sites/leads/vendor/symfony/console/Application.php",
    "line": 145,
    "args": []
  },
  {
    "function": "run",
    "type": "->",
    "class": "Illuminate\\Console\\Application",
    "file": "/media/sf_Sites/leads/vendor/laravel/framework/src/Illuminate/Console/Application.php",
    "line": 89,
    "args": []
  },
  {
    "function": "run",
    "type": "->",
    "class": "Illuminate\\Console\\Application",
    "file": "/media/sf_Sites/leads/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php",
    "line": 122,
    "args": []
  },
  {
    "function": "handle",
    "type": "->",
    "class": "App\\Console\\Kernel",
    "file": "/media/sf_Sites/leads/artisan",
    "line": 37,
    "args": []
  },
  {
    "function": "{main}",
    "file": "/media/sf_Sites/leads/artisan",
    "line": 0,
    "args": []
  }
]

**Comment by johnnoble1990** [comment]
I am getting this error again. I have shared the full stack trace above.

**Comment by johnnoble1990** [comment]
There error appears to relate to notifications.

**Comment by themsaid** [comment]
Please upgrade to 1.0.9, if it's not resolved please share the stack trace of the error from the log file not a JSON response.
