### ISSUE TITLE
Displayed timestamp not honoring timezone

### ISSUE THREAD

**Issue by mikeerickson** [laravel/telescope#429]
I see that there are a number of different issues reported on the same subject, but I dont think it has been "fixed" per se

As you can see based on the attached screenshots, the timestamp in the log file is not matching what is displayed (the value in the log file is correct, it is using the value set in `config/app`

Every Telescope entry is displayed with the wrong offset, not just Logs (that is just the easiest way to show what issue I am seeing)

![image](https://user-images.githubusercontent.com/183153/48917272-c5de6380-ee3a-11e8-9104-d017d1f2d4dd.png)

**Comment by michaelnguyen547** [comment]
timezone option in `telescope.php` would be nice

`'timezone' => env('APP_TIMEZONE', 'UTC'),`

**Comment by michaelnguyen547** [comment]
Suddenly, the telescope entries created_at timestamp is incorrect. 

In `.env`, I set `APP_TIMEZONE=UTC`

UTC time is 2018-11-23 3:00:00 AM , telescope saves created_at with 2018-11-23 00:00:00 AM

**Comment by themsaid** [comment]
@michaelnguyen547 what bug?

**Comment by michaelnguyen547** [comment]
> @michaelnguyen547 what bug? It works fine for me. Please share more details.

It works fine on my work machine. I will test on the home machine which gave me the wrong time and updates the ticket after.

**Comment by mikeerickson** [comment]
It is a simple reproduction for me

1. install new laravel app

```bash
$ laravel new laravel-telescope
```

2. install telescope

```bash
$ composer require laravel/telescope
$ php artisan telescope:install
$ php artisan migrate
```

3. configure timezone in `config/app.php`

```
...
    'timezone' => 'America/Los_Angeles',
...
```

4. start server

```bash
...
$ php artisan serve --port=8181
```

5. load site in browser `http://127.0.0.1` default welcome route

6. hit `http://127.0.0.1:8181/telescope`

See log output 

![image](https://user-images.githubusercontent.com/183153/48957215-1d003900-ef0c-11e8-8911-29cf69783339.png)

Review request

![image](https://user-images.githubusercontent.com/183153/48957228-386b4400-ef0c-11e8-9e43-693509a3da5e.png)

You can see that the timestamps are wrong

**Comment by themsaid** [comment]
Telescope needs all dates stored in utc and it will convert it to local time.

**Comment by mikeerickson** [comment]
Further, it affects all timestamp values across tables.  

I want logs to be correct (which they are NOT with UTC)
I want `created_at` and `updated_at` values to be correct (which they are NOT with UTC)

![image](https://user-images.githubusercontent.com/183153/48957541-01962d80-ef0e-11e8-9c28-65522651f014.png)

**Comment by phannaly** [comment]
Same here!. I've checked Vue DevTools, `created_date` is correct but when Vue render templates, it shows the wrong date. Looks like something wrong in `timeAgo` function.

**Comment by phannaly** [comment]
@mikeerickson I just submitted a PR for this. Can you confirm the solution that I provide?

**Comment by themsaid** [comment]
Telescope assumes all dates are stored in utc and it will convert it to browser local time.

**Comment by phannaly** [comment]
Yeah, I think it better for using app timezone, so we can use timezone whatever we want rather than convert to browser local time.

**Comment by andrewgorpenko** [comment]
I can confirm the issue. The entries timestamps are correct in the database, but not in the UI. For instance, the exception happened about 5 minutes ago and it shows me 4 hours ago, moreover, it shows the future date, and AM instead of PM.

**Comment by mikeerickson** [comment]
Curious if this issue is going to be resolved, or closed without a fix?

**Comment by Livijn** [comment]
I think we should display the **server's** time in Telescope. That is how it is done in Horizon. But that (5 minutes ago) is useful. So, just display the created_at raw.

**Comment by terranc** [comment]
Do you have any further conclusions?

**Comment by mikeerickson** [comment]
Seems this issue has gone on stale ears?

**Comment by terranc** [comment]
> Seems this issue has gone on stale ears?

Still, I don't know what the best practice should be.

**Comment by phannaly** [comment]
@mikeerickson @terranc Please check my PR that has been reverted #482. As it's quite long I don't remember what going now.

**Comment by mikeerickson** [comment]
Could the powers that be chime in on this.  @themsaid @taylorotwell 

It would seem that if the value stored as it is in standard Laravel `timestamps` would be a logical common approach.  It has been mentioned that the display is as we wish in Horizons, how about matching these two projects (or even as used in above mentioned `timestamps`)

**Comment by instanttim** [comment]
I spent so much time thinking I was doing something wrong. MySQL defaults to "system" but my research says it internally stores UTC in the database no matter what. It then translates in and out based on the global and session timezones. So my Laravel app is properly handing off a local time with a local tz session, it's showing up properly in the database, the log files, everywhere. My date formatting functions are doing the right thing, it's all great. Except telescope shows the times

**Comment by instanttim** [comment]
To be clear, MYSQL properly understood the session to be -6, so it converted the timezone, somewhere in Telescope I think it did it a second time. Therein lies the problem.

**Comment by themsaid** [comment]
Fixed that in https://github.com/laravel/telescope/commit/41526ac40a1dab0e2219b68029f22e4c5383350e#diff-eecbf42f77d2dce93ddc380434aff268
