### ISSUE TITLE
EntryResult Argument Error

### ISSUE THREAD

**Issue by Lotuashvili** [laravel/telescope#430]
When I try to open cache logs, it throws an error:

`[2018-11-23 01:49:25] local.ERROR: Argument 6 passed to Laravel\Telescope\EntryResult::__construct() must be of the type array, null given, called in /Users/levan/website/vendor/laravel/telescope/src/Storage/DatabaseEntriesRepository.php on line 92 {"userId":1,"email":"l.lotuashvili@gmail.com","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Argument 6 passed to Laravel\\Telescope\\EntryResult::__construct() must be of the type array, null given, called in /Users/levan/website/vendor/laravel/telescope/src/Storage/DatabaseEntriesRepository.php on line 92 at /Users/levan/website/vendor/laravel/telescope/src/EntryResult.php:78)`

PHP Version: 7.1.22
Laravel Version: 5.7.13

**Comment by themsaid** [comment]
Please read the previous issues before posting a new one.
