### ISSUE TITLE
Wrong order of exceptions

### ISSUE THREAD

**Issue by Shifterovich** [laravel/telescope#435]
Same issue as #87 

![screenshot from 2018-11-24 15-33-12](https://user-images.githubusercontent.com/4354706/48969409-6a5cd300-effe-11e8-8b57-beb7caeba84c.png)

It might be relevant to point out that most of these exceptions were triggered using the queue (events, notifications, mailables).

**Comment by themsaid** [comment]
How do I replicate this?

**Comment by Shifterovich** [comment]
It's hard to replicate for me as well, since it's pretty random and seems to only happen with queues.

**Comment by themsaid** [comment]
Closing this for now then since it wasn't reported by other people. Could be a problem with your app.
