### ISSUE TITLE
[Feature Request] Check if there are attachments in emails

### ISSUE THREAD

**Issue by joshuand1990** [laravel/telescope#440]
In the MailWatcher is it really required to have the body and raw, as the attachments would also get stored which might break the API when retrieving the emails. 

Maybe a check if possible to see if there is an attachment, else the full attachment gets saved in the body.

E.g. I have a generated excel workbook that gets generated and attached to the email, in the body field it gets stored in the database, but depending on the size of the database column it will not store correctly.

**Comment by themsaid** [comment]
Are you able to open a PR?

**Comment by themsaid** [comment]
Feel free to open a PR so we can discuss the implementation :)
