### ISSUE TITLE
[Feature Request] When watchers are disabled in config, remove them from the sidebar in the web UI

### ISSUE THREAD

**Issue by ryanmortier** [laravel/telescope#441]
Hi, I ran into this today. I wanted to disable some watchers and did so with the `env()` variable but noticed the sidebar still shows the link/route. I'd open a PR but I don't know enough about Vue to do so.

**Comment by Sparclex** [comment]
I think can be closed:
> No plans to add this.
https://github.com/laravel/telescope/pull/446#issuecomment-442470883

**Comment by ryanmortier** [comment]
So be it.
