### ISSUE TITLE
missing callback in bootedCallbacks

### ISSUE THREAD

**Issue by n588E** [laravel/telescope#448]
Hi, 
I hope somebody can help.
After installing laravel telescope v1.0.6,  #bootedCallbacks is empty in the app service container.

With telescope installed:

![image](https://user-images.githubusercontent.com/28066226/49174315-e5dfbc80-f33d-11e8-9c83-437a2e6c3d8c.png)

Without telescope installed: 

![image](https://user-images.githubusercontent.com/28066226/49175014-8682ac00-f33f-11e8-8902-5b7208cb116b.png)

In map method of RouteServiceProvider I have defined my custom routes that shouldn't be an issue as without telescope it works just fine. 

Probably is worth mentioning that Laravel framework was upgraded from version 5.6 to 5.7 and is not a clean 5.7 installation.

Thanks in advance.

**Comment by themsaid** [comment]
Must be something with your app cause it can't be replicated in a fresh laravel app. Anyone else is having the same issue?

**Comment by themsaid** [comment]
Closing for lack of information and being unable to replicate. Also seems like the issue hasn't been reported by anyone else.
