### ISSUE TITLE
laravel telescope dark version not working

### ISSUE THREAD

**Issue by AManojKiran** [laravel/telescope#453]
i have jsut installed the latest version of telescope and i have uncommented the line
Telescope::night();  inside the TelescopeServiceProvider bit it is still in the light version

**Comment by ludo237** [comment]
Just did this and it's working like a charm 
![image](https://user-images.githubusercontent.com/921500/49216687-f76fa580-f3cb-11e8-9126-9c65f506aceb.png)

**Comment by themsaid** [comment]
works for me too.

**Comment by fridzema** [comment]
@AManojKiran i had this problem to. 
Make sure you register your own `use App\Providers\TelescopeServiceProvider` instead of `use Laravel\Telescope\TelescopeServiceProvider`
