### ISSUE TITLE
[Feature Request] Clear Button

### ISSUE THREAD

**Issue by Sparclex** [laravel/telescope#454]
Thanks for the great tool!

I would appreciate a clear button in the UI, which just runs the telescope:clear command. 

If that would be a welcomed feature, I could do a PR.

**Comment by paras-malhotra** [comment]
We can close this issue. There are no plans to support this.

**Comment by rainbowhat** [comment]
My log file just became 2.6gb, for what? Isn't it better to clear it to limit it to a certain size?

**Comment by tomswinkels** [comment]
Good idea, maybe any can make a PR.

**Comment by rohan7chaudhary** [comment]
Terminal : "**php artisan telescope:clear**" would clear all your telescope logs/entries

**Comment by bendada3** [comment]
+1

**Comment by Hamza-crypto** [comment]
Is there any configuration available to hide this "Delete entries" button. Although it shows alert but I don't want anyone from the allowed persons to clear the entries unexpectedly.

**Comment by rizimore** [comment]
@Hamza-crypto

You can simply copy the layout file from the vendor package to your own views and comment on the hide button

Vendor = vendor/laravel/telescope/resources/views/layout.blade.php
Your Project = resources/views/vendor/telescope/layout.blade.php

![image](https://user-images.githubusercontent.com/31438601/157513297-8d0ac247-a132-4966-9470-d9d8c3733041.png)
