### ISSUE TITLE
[Feature Request] customize which columns are shown (add Duration to Requests list)

### ISSUE THREAD

**Issue by vesper8** [laravel/telescope#455]
I would find it very useful to be able to select which columns are shown by default.

Specifically, I would really find it useful to see the duration column inside the Requests tab (the same way it is shown in the Queries tab)

The Request duration is stored and visible upon clicking on the eye icon but I would prefer to see it in the list to identify slow requests.

**Comment by themsaid** [comment]
No plans to support this at the moment.

**Comment by vedmant** [comment]
Really needs at least database queries count in the requests table
