### ISSUE TITLE
[Feature Request] visually group queries by Request

### ISSUE THREAD

**Issue by vesper8** [laravel/telescope#456]
Currently my requests are executing multiple queries and it is difficult to tell which group of queries are part of which request. It would be nice if the Queries tab had a 'Request ID' column, or if there was another means of clearly identifying a group of queries that ran together

**Comment by themsaid** [comment]
Inside the request preview, there are tabs for related entries (queries, logs, events, etc...) you can browse the queries for that request there. Also open a query and you'll find a link to the request that started it.
