### ISSUE TITLE
Telescope fails to save entries

### ISSUE THREAD

**Issue by deleugpn** [laravel/telescope#459]
I just got an error on production, so I'm reporting it here for now and maybe I can try to work out a PR some other time, if nobody picks it up.

Basically the volume of data accumulated on Telescope Entries could be incredibly large and lead to 

```
[30-Nov-2018 14:08:03 UTC] [2018-11-30 14:08:03] production.ERROR: SQLSTATE[08S01]: Communication link failure: 1153 Got a packet bigger than 'max_allowed_packet' bytes (SQL: insert into `telescope_entries` (`batch_id`, `content`, `created_at`, `type`, `uuid`) values (8c636ec5-a1f2-40d1-9e22-833d3fce79c2,
{
    "status": "pending",
    "connection": "sync",
    "queue": null,
    "name": "App\\Components\\Jobs\\JobStack",
    "tries": null,
    "timeout": null,
    "data": {
        "middlewareStack": [
            "Library\\Authentication\\Console\\Middleware\\TenantDatabaseConnector",
            "App\\Components\\Jobs\\Middleware\\GuzzleInterceptor"
        ],
        "jobs": [
            "App\\Synchronizer\\Jobs\\AccountJob",
            "App\\Synchronizer\\Jobs\\RevenueJob"
        ],
        "tenantId": 3300
    },
    "hostname": "ip-10-40-4-86.eu-west-1.compute.internal"
}
```

Imagine a background process that is inserting too many things into the database and Telescope is just collecting all entries.

At the end, when Telescope tries to send a single insert to the database, it gets this error.
We could work out a strategy to `chunk` the amount of data Telescope is going to send to the database to avoid this. It means sending more than 1 insert query at the end, but it's effective.

**Comment by themsaid** [comment]
Even a single insert can be huge enough to break things, I've seen it.

I keep saying, everyone's app is different so use Telescope in a way that works for you. You may update the networking configuration, PHP memory, database packet size limitations, etc... if that works for you.

By Default Telescope is storing everything, you can change that in your app if you wish and only store what you need.
