### ISSUE TITLE
Requests not shown

### ISSUE THREAD

**Issue by dimsav** [laravel/telescope#463]
Hello,

we face an issue on our production server where the requests entries are not shown in the requests tab.

However, it seems in the database the requests are tracked normally.

Also, when viewing the api calls telescope does, we seem to get some results.

![image 2018-12-02 at 02 16 45](https://user-images.githubusercontent.com/1785686/49339412-08bde980-f63a-11e8-9cd9-98f404507278.png)

Any idea what could I look into to check what is wrong?

Thanks!

**Comment by themsaid** [comment]
Any errors in the browser console?

**Comment by dimsav** [comment]
No errors, in the console.

<img width="1201" alt="image 2018-12-03 at 18 04 30" src="https://user-images.githubusercontent.com/1785686/49385344-e6a19580-f725-11e8-9e42-b174aebaeae5.png">

**Comment by Jimmy-JS** [comment]
It's only in the request screen. on others like exception etc they show the entries on screen. here is the screenshot:
![image](https://user-images.githubusercontent.com/9798426/49491630-92aec200-f887-11e8-87f1-cbaea52d27b6.png)

And the console is clean too.
![image](https://user-images.githubusercontent.com/9798426/49491648-a0644780-f887-11e8-85ee-ca484041011f.png)

And it show entries on other menu like exception:
![image](https://user-images.githubusercontent.com/9798426/49491687-ce498c00-f887-11e8-896e-efc672ad729e.png)

**Comment by Jimmy-JS** [comment]
Yes, I'm already run telescope:publish artisan command

**Comment by themsaid** [comment]
I can't think of an explanation of what you're seeing here and can't replicate it. You'll have to investigate it in your apps since you're the only ones who can replicate it.

**Comment by Mezzair** [comment]
I've had this with two fresh installs today. Same outcome as those people reporting above.

**Comment by themsaid** [comment]
@Mezzair fresh installs on a fresh laravel app works fine for me. Still can't replicate.

**Comment by themsaid** [comment]
Check the Vue component in dev tools, the Root.Index.IndexScreen.entries property should contain some records.

**Comment by ryanmortier** [comment]
Same issue here.

I just deployed an application to production with Laravel Forge and telescope is enabled for production. The only page working for me is `Schedule`. I should be seeing things in `Requests`, `Jobs`, `Commands`, etc. but I'm not.

It worked great when it was running in dev on my Mac.

The `Root.Index.IndexScreen.entries` is an empty array.

**Comment by paras-malhotra** [comment]
The documentation has been updated to explain filters: https://github.com/laravel/docs/pull/4808. I think the majority of the issues are related to filtering in production. This issue, #470, #434, #409, #288, #134 and #76 are all related to the same issue.

@themsaid perhaps we should add a note in the README related to filters for use in production environment?

**Comment by Jimmy-JS** [comment]
@paras-malhotra I think my problem is not in filtering issue. since I already return true inside telescope filter function. and I get request entries on my database (telescope_entries table). and even in network is showing the entries but in vue Root.Index.IndexScreen.entries is just empty array not binded from the XHR Request

**Comment by paras-malhotra** [comment]
@Jimmy-JS yes I understand. Can you add breakpoints on line 118 and 96 of IndexScreen.vue and see what's going on with the entries variable and where `this.entries` is initialized?

**Comment by dimsav** [comment]
Maybe this will help reproduce the problem.

I had the following filter set on production, and this is when the problem started. 

```
Telescope::filter(function (IncomingEntry $entry) {
            if (true || $this->app->isLocal()) {
                return true;
            }
});
```

1.7 Million entries where saved on the telescope_entries table. Only after importing the production db locally, the problem was reproduced on the local environment.

**Comment by themsaid** [comment]
Let's stay focused here please.

This is issue that records exist in the database, they are returned in the XHR request but they don't appear in the UI.

@Jimmy-JS and @dimsav please check Vue dev tools and see the value of `Root.Index.IndexScreen.entries`, is this property empty?

**Comment by Jimmy-JS** [comment]
@themsaid yup it's empty although it was getting entries from XHR request. Here is the screenshot:

**In Vue Dev Tools:**
<img width="1273" alt="screenshot 2018-12-06 at 17 18 02" src="https://user-images.githubusercontent.com/9798426/49577849-ef3ed980-f97a-11e8-8c31-62e69f0a6f88.png">

**In Network:**
<img width="1279" alt="screenshot 2018-12-06 at 17 20 09" src="https://user-images.githubusercontent.com/9798426/49577954-37f69280-f97b-11e8-91c4-0710b3a40e93.png">

**Comment by nakonechny** [comment]
Got the same problem. Requests totally not shown since one heavy request been recorded. Telescope:clear did help but only until that request been recorded again.

Finally I have found out that request's json exceeded the `content` field capacity. Being 'text' it only can store up to 64KB of data. 

Altering it to LONGTEXT and telescope:clear fixed the issue.

**Comment by themsaid** [comment]
I think this can only be fixed by someone who can replicate it. I'll keep the issue open but I really can't think of why it's acting like this with some people and not others.

**Comment by nakonechny** [comment]
> someone who can replicate it.
Everyone. You just insert into telescope_entries with truncated json content (invalid). Then this record gets rejected by DatabaseEntriesRepository::get() line 83. And then 'entries' section of response contains array with keys starting not from 0, but 1 or other number instead. As a result UI completely rejects to display any request from given array. It shows 'just empty space' message.

**Comment by themsaid** [comment]
fixed that in https://github.com/laravel/telescope/commit/364c09fbd9a9fc3cf28a2fb5691661789309fdb4

Thanks @nakonechny for the explanation :)
