### ISSUE TITLE
[Feature Request] Custom watchers and scripts

### ISSUE THREAD

**Issue by paras-malhotra** [laravel/telescope#469]
I just realized that there is no way to add custom watchers to Telescope right now. Even though the backend allows custom watchers, the frontend is restricted.

I think it would be really useful if Telescope allows us to add custom scripts (similar to the way Nova tools work). With this feature, we can not only add custom watchers, but we could also customize the interface and have libraries / packages that can do so much more on the frontend!

**Comment by themsaid** [comment]
I don't think we'll change how the frontend of Telescope is shipped. Currently you can log your custom events and tag them, the LogWatcher will store that and you can search by tag.

I believe in the future we'll look into allowing for custom watchers with more control over the display, however we'll still provided specific display options that you can use for your custom watcher.

**Comment by Namoshek** [comment]
I would like to give this suggestion a +1. For me the use case would be to record outgoing HTTP requests and other custom events. In theory a custom watcher merging most of the recorded data into the current `Requests` section could work, but I don't really like the idea of having ingoing and outgoing requests recorded together.

**Comment by samiles** [comment]
This would be great, to have for example an ElasticSearch watcher. Even better if they could be integrated as community packages - there could be a lot of potential watchers. Hopefully one day...

**Comment by judahnator** [comment]
I would love this. I have some parts of my application that telescope does not record that I would like to monitor. I can build my own watcher, but the frontend would need to work with it as well.

**Comment by jochemgruter** [comment]
I support this idea! Would be very helpful to watch custom application logic.

**Comment by vedmant** [comment]
Yeah, it's very unfortunate that there is no way to add custom watcher. I develop a package that could add useful information to telescope if I could create a custom watcher.

**Comment by Radiergummi** [comment]
Uhm, so, hi from four years in the future! I maintain an [Elasticsearch integration](https://github.com/matchory/elasticsearch) for Laravel and would love to add a Watcher for Elasticsearch queries—but cannot, unfortunately.  
Will this be reconsidered at some point?
