### ISSUE TITLE
Telescope not working on none-local enviroments at all

### ISSUE THREAD

**Issue by shalawani** [laravel/telescope#470]

**Comment by paras-malhotra** [comment]
See https://github.com/laravel/telescope/issues/76#issuecomment-439165858

**Comment by shalawani** [comment]
yes, it seems we should add 
Laravel\Telescope\TelescopeServiceProvider and App\Providers\TelescopeServiceProvider to app.php config file to work fine.

**Comment by shalawani** [comment]
Ok, sorry for inconvenience but I can say that I don't know how to solve it till now
thank you for replying
