### ISSUE TITLE
[1.0.8] JobWatcher Class Causing Issues while Seeding

### ISSUE THREAD

**Issue by brunogaspar** [laravel/telescope#475]
Hey guys

On version 1.0.7 everything was working as expected, however, on version 1.0.8 and with the changes [here](https://github.com/laravel/telescope/pull/457) it started to fail on my end.

The error i'm receiving is `Trying to get property of non-object` `In JobWatcher.php line 27`.

Reason for failing is because on [line 27 of JobWatcher](https://github.com/laravel/telescope/pull/457/files#diff-07bca32437db0c1a8125b8e5afc09817R44) is calling the `recordJob` method and inside the `recordJob` method it performs that Telescope Is Enabled check, which i think should be done way earlier in execution, probably on the `register()` method.

Edit: As a simple reproducible way, i have a `dispatch(new Job())` call being triggered in one of the seeders.

@themsaid Can you please advise?

Thanks!

**Comment by irazasyed** [comment]
Same issue! 

It appears this is happening when the recording is OFF (From the dashboard).
