### ISSUE TITLE
Data too long for column 'content'

### ISSUE THREAD

**Issue by laassseeee** [laravel/telescope#478]
I'm getting `Illuminate\Database\QueryException SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'content' at row 26 (SQL: insert into 'telescope_entries' ('batch_id', 'content', 'created_at', 'type', 'uuid')` when trying to load an index page with some model entries (with encrypted attributes).

Solved it by setting the `content` column type to `MEDIUMTEXT`. Should this be mentioned in the docs?

**Comment by laassseeee** [comment]
I couldn't find a way to publish the Telescope migration files, and make the change there, so I ended up making them directly in the database.

Is there a way to publish the migrations, to make changes like these? The docs or artisan command gives no information afaik.

**Comment by themsaid** [comment]
You may increase the column size or change its type in your database if you want.

**Comment by biopowder** [comment]
@lasseeee 
`php artisan make:migration change_content_field_type_to_telescope_entries_table`

```
class ChangeContentFieldTypeToTelescopeEntriesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        DB::statement('ALTER TABLE `telescope_entries` MODIFY COLUMN `content` MEDIUMTEXT');
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        DB::statement('ALTER TABLE `telescope_entries` MODIFY COLUMN `content` TEXT');
    }
}
```
This approach is not working: `$table->mediumText('content')->change()` it stays in type 'text'
It's not good to do it with statement, but it's at least working.

**Comment by sunscreem** [comment]
I came up against this same issue FWIW

**Comment by tomswinkels** [comment]
Same issue, it is better that Telescope fix that table or strip the content if it is to long.

**Comment by csimpi** [comment]
This is supposed to be a bug, not a closed case... 
Telescope should handle this, we just got crashed server due to this issue with Telescope wich is bad.
The Elastic Beanstalk environment got to be into infinite loop due to:
1. Sending error message about something
2. Telescope is trying to store the error message in the database
3. Due to this bug Telescope can't store it gets Database exception that Telescope is trying to report and store again 
4. Telescope is trying to store the error message in the database ....  ===  step 2. then the loop is kicking in. 

I'm going to disable telescope until this bug has been fixed by the team, I'm not comfortable to changing the database tables of the library.

**Comment by Noogic** [comment]
👍 I've had to disable telescope due to this issue. It's weird to have a successful response and fail in the end because of telescope...

**Comment by FrittenKeeZ** [comment]
We've also encountered this issue.
Why has this just been closed instead of marked as bug?
Either Telescope should publish the migration files so we can fix it, or the field should be changed to `MEDIUMTEXT` right from the beginning.

**Comment by sunscreem** [comment]
I've pinged a tweet to Said in case he wants to re-open this issue:

https://twitter.com/sunscreem/status/1093826649982943233

**Comment by rolandstarke** [comment]
Looks like the column is now `LONGTEXT`: https://github.com/laravel/telescope/commit/4e7663357b1626fcd5c9a5c36417930b02b78718

**Comment by WouterFlorijn** [comment]
@themsaid any update on this? It's still an issue, and like other have said, it should be handled by Telescope, since no matter how large you make the column, there's always an error that's larger.
