### ISSUE TITLE
How to load telescope elegantly in dev environment only?

### ISSUE THREAD

**Issue by phpguru** [laravel/telescope#486]
We are wondering the best way to load Telescope only in development environment. 

If we put laravel/telesope into `require-dev` and install with `composer install --no-dev` the service provider breaks because the library is not found.

```
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
PHP Fatal error:  Class 'Laravel\Telescope\TelescopeApplicationServiceProvider' not found in /home/ubuntu/v1.0.3/app/Providers/TelescopeServiceProvider.php on line 10

In TelescopeServiceProvider.php line 10:

  Class 'Laravel\Telescope\TelescopeApplicationServiceProvider' not found
```

**Comment by themsaid** [comment]
please check the docs https://laravel.com/docs/5.7/telescope#installation

**Comment by rolandstarke** [comment]
One thing to note the docs have a little error

`use Laravel\Telescope\TelescopeServiceProvider::class;`

should probably be

`use Laravel\Telescope\TelescopeServiceProvider;`
