### ISSUE TITLE
PruneCommand pruning issue

### ISSUE THREAD

**Issue by X-Coder264** [laravel/telescope#49]
In the `handle` method the `EntriesRepository` contract is type-hinted, but the only method called on that object is the `prune` method which actually does not even exist on that contract (it's on the `PrunableRepository` contract) so this will lead to issues as soon as someone creates their  `EntriesRepository` contract implementation.

The type-hint on the `handle` method should change to `PrunableRepository` contract, the question is will the `EntriesRepository` contract extend the `PrunableRepository` contract (if the type-hint remains the same) or will the `TelescopeServiceProvider` manually bind the `PrunableRepository` contract to the `DatabaseEntriesRepository` implementation (just like it does currently for the `EntriesRepository` contract).

**Comment by themsaid** [comment]
Thanks, fixed that.

**Comment by X-Coder264** [comment]
@themsaid 

You only changed the type-hint in https://github.com/laravel/telescope/commit/b46ec0fc1ac0aeb87120340ac7ab7ffa0c24d7f7 which now result in this error (as expected) when running the prune command:

`Target [Laravel\Telescope\Contracts\PrunableRepository] is not instantiable.`

**Comment by themsaid** [comment]
I've reverted my changes https://github.com/laravel/telescope/commit/8203efbe43fc79cce0d608af57a5993285a3b1d5 for now
