### ISSUE TITLE
Does not intercept subsequent requests

### ISSUE THREAD

**Issue by google-mac** [laravel/telescope#491]
Our Vue SPA requests are not intercepted by telescope to view details like the regular requests. Perhaps this is not the original intent of Telescope, but I feel that it would be very helpful as many applications are going the SPA route.

I am used to ngrok which has this feature and is very helpful.

I did look over [#463](https://github.com/laravel/telescope/issues/463) though it seems to be for NO requests, so I believe this one is a clean issue.

**Comment by themsaid** [comment]
Please share more details. Are you recording all requests in your configuration? If so, do you mean Telescope is recording some but not the others? Seems like a filter is configured on your side.

**Comment by google-mac** [comment]
Even though I was refreshing Telescope, the requests were not coming in. For some reason, when I changed the TelescopeServiceProvider `register()` method (I just enabled night mode) and refreshed, some of the past requests came through, though only a few out of maybe 15 failed requests that I've been using the developer console to debug.

This is confusing and doesn't really pinpoint the issue- could changing the service provider have triggered such a fix? Perhaps there was a cache bust? I did not make any other changes to the default, which allows all requests when in local environment.

**Comment by themsaid** [comment]
It really sounds like something with your app. Closing the issue then but feel free to ping me if you have any question.

Check the database to see if the desired records are there so you know if it's a display issue or a storage issue in your app.

**Comment by jesseschutt** [comment]
I'm experiencing a similar issue - Telescope is picking up `OPTION` requests from the vue SPA but is not picking up other requests. 

@google-mac - Did you ever find a solution?

**Comment by google-mac** [comment]
@jesseschutt I believe that the records came through once I restarted my Homestead/Vagrant VM. I'm not sure if the timing got misaligned, but that may have fixed it.

If all of your requests are coming in as OPTION, you may be having a CORS issue.. This happens if you are issuing the requests from a different domain as the backend. If that is your issue, try https://github.com/barryvdh/laravel-cors.

**Comment by jesseschutt** [comment]
I've restarted with no luck. The application is running without any CORS issues and I have a CORS package installed.

Telescope will catch all request types to `api.app.com/graphql` but only catches `OPTION` requests to `api.app.com/graphql/teacher`. 

So strange...
