### ISSUE TITLE
telescope over reverse_proxy

### ISSUE THREAD

**Issue by leemmoox** [laravel/telescope#496]
Hello,

Is it possible to somehow implement reverse_proxy to telescope?

There is "path" in config file which is changing vue-route base and laravel route prefix, but to working it correctly I need to split them... 

for example:

Backend url:
http://laravel.example.com/my_application/backend

(but as the laravel app is running over reverse_proxy it see it as http://laravel.example.com/)

Frontend url:
http://laravel.example.com/my_application

so to get access to telescope by default you need to access 
http://laravel.example.com/my_application/backend/telescope

and is working, but telescope api is unaccesible as it is requesting

http://laravel.example.com/telescope/api/...

which is wrong...

in this case I need only reconfigure vue-router base to /my_application/backend/telescope/ to start working, but it changes also laravel routes, which I don't want'...

Temporary sollution which I did is I created another variable prefix and rewrite TelescopeServiceProvider as:
```php
path => "telescope"  //to vue-router
prefix => "my_application/backend/telescope"   //to laravel router
```

changed file src/TelescopeServiceProvider.php:

```php
private function routeConfiguration()
    {
        return [
            'namespace' => 'Laravel\Telescope\Http\Controllers',
            'prefix' => config('telescope.prefix', 'telescope'),
            'middleware' => 'telescope',
        ];
    }
```

but it would be better to use APP_URL as correct URL (not the one detected by laravel as it is wrong)
Thx

**Comment by themsaid** [comment]
I don't understand what you want. Can you please elaborate?

**Comment by leemmoox** [comment]
Hmm,

I just want to implement two separate variables in config file $prefix and $base (instead of $path) and update the code as follow

- the $prefix will be used to add prefix to laravel routes

changes this in file src/TelescopeServiceProvider.php
```php
    private function routeConfiguration()
    {
        return [
            'namespace' => 'Laravel\Telescope\Http\Controllers',
            'prefix' => config('telescope.prefix'),
            'middleware' => 'telescope',
        ];
    }
```
- the $base will be used to change vue router base

```javascript
const router = new VueRouter({
    routes: Routes,
    mode: 'history',
    base: '/' + window.Telescope.base + '/',
});
```

**This is required if you using laravel application in subdirectory over nging reverse proxy**

Thx

**Comment by themsaid** [comment]
Don't install Laravel in a sub directory. Please check the previous discussion on this.

**Comment by Neokyuubi** [comment]
I'm facing the exact same problem as @ChinwalPrasad , please anyone have found a fix or workaround ?

**Comment by erlangparasu** [comment]
https://github.com/laravel/telescope/issues/561
