### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by theupriser** [laravel/telescope#497]
Hello,

I've installed Telescope in my laravel installation and suddenly someday after updating laravel to it's latest version Telescope showed me a blank screen.

See here:
https://laravel.matzz.co/telescope/requests

I can't see what is going wrong. Tried to reinstall several times, including removal of the tables in the database and migration row. But nothing seems to help. The server is running php 7.2.12

**Comment by rivenme** [comment]
same here, after "composer update", telescope shows blank screen

**Comment by paras-malhotra** [comment]
Did you guys run `php artisan telescope:publish`?

**Comment by rivenme** [comment]
Than you paras, that was it. php artisan telescope:publish fixed the blank page.

**Comment by theupriser** [comment]
> Did you guys run `php artisan telescope:publish`?

added it to composer file.. now it should be automatic every update. Thanks!
