### ISSUE TITLE
Installation did not publish config/telescope.php

### ISSUE THREAD

**Issue by jjboostability** [laravel/telescope#50]
First, off, thanks for all the great work you do! I love the Laravel framework!

Now on to the issue. I just installed the repo, but it didn't publish the config/telescope.php file. Just a suggestion to either publish this file by default or include instructions on how to do so in the "Installation and Configuration" section (https://github.com/laravel/telescope#installation--configuration). Maybe include something like this:

`php artisan vendor:publish --tag=telescope-config`

**Comment by themsaid** [comment]
fixed and will release in a bit
