### ISSUE TITLE
Jobs  pending

### ISSUE THREAD

**Issue by Krato** [laravel/telescope#503]
Hello. First thanks @themsaid for this awesome packae. It's amazing! With Horizon and Telescope almost of areas of an application get covered.

I have an app with spark, horizon and telescope with queues running in redis. When I fire a job is working and Telescope and Horizon are showing me the job. The job is firing ok. In Horizon the job is valid, but in Telescope stills as "Pending".

I set `Redis::enableEvents()`, but all jobs still "Pending" 

I forget something?

Thanks!

**Comment by Krato** [comment]
I check the redis log and this is the dump:

```
rpush queues:mail {"displayName":"App\\Jobs\\WelcomeMail","job":"Illuminate\\Queue\\CallQueuedHandler@call","maxTries":null,"timeout":null,"timeoutAt":null,"data":{"commandName":"App\\Jobs\\WelcomeMail","command":"O:20:\"App\\Jobs\\WelcomeMail\":8:{s:7:\"\u0000*\u0000user\";O:45:\"Illuminate\\Contracts\\Database\\ModelIdentifier\":4:{s:5:\"class\";s:8:\"App\\User\";s:2:\"id\";i:1;s:9:\"relations\";a:1:{i:0;s:7:\"website\";}s:10:\"connection\";s:6:\"system\";}s:6:\"\u0000*\u0000job\";N;s:10:\"connection\";N;s:5:\"queue\";s:4:\"mail\";s:15:\"chainConnection\";N;s:10:\"chainQueue\";N;s:5:\"delay\";N;s:7:\"chained\";a:0:{}}"},"telescope_uuid":"8c7d75d2-34ec-4fbc-8ec7-c8e89934042d","id":"11","attempts":0,"type":"job","tags":["App\\User:1"],"pushedAt":1544704755.112363}
```

Yes, there's a telescope_uuid: `8c7d75d2-34ec-4fbc-8ec7-c8e89934042d`

**Comment by themsaid** [comment]
I actually tried Horizon with Telescope and jobs are successfully processed or failed and that reflects on both Horizon and Telescope, so there's something wrong about your app.

**Comment by Krato** [comment]
But what can be? Also, the Notification is not being registered If I sent through the Job, but is being registered when I send standalone.

**Comment by themsaid** [comment]
Seems like your workers aren't recording anything in Telescope.

**Comment by Krato** [comment]
Ok, now is working!

It seems that Telescope not read the job if no ` --sleep=3 --tries=1` is added to `aqrtisan queue`.

I had `artisan queue:work redis`. Now with: `artisan queue:work redis --sleep=3 --tries=1` Telescope record all.

Maybe a bug?

Thanks!

**Comment by themsaid** [comment]
If it's trying forever then a failed job won't get logged.
