### ISSUE TITLE
Hi, your product is brilliant. BUT! Please provide the documentation for extend logic.

### ISSUE THREAD

**Issue by Brigel** [laravel/telescope#505]
### What i need?
I want for you provide documentation/accessibility for extend your module. I need to create several custom pages/tabs for custom data in my project. But now i see how this hard make.
Therefore please, i very ask you, create this functional/docs.  Thats would very help me with my work. And on my oppinion many people would be happy to see such a decision.
Sorry for my English.

**Comment by paras-malhotra** [comment]
@Brigel you can find documentation at the Laravel website [here](https://laravel.com/docs/5.7/telescope). As far as custom tabs/pages are concerned, there is a plan to support custom watchers in the future but it would take some time to come up. See https://github.com/laravel/telescope/issues/469
