### ISSUE TITLE
Jobs are in pending status!

### ISSUE THREAD

**Issue by Rux77** [laravel/telescope#507]
I am using Redis and Horizon to mange my queues..

When I use `php artisan queue:work redis` to process the jobs , the jobs's status in both Horizon and Telescope is successfully changed to `success` status.

On the other hand, when using `php artisan horizon` the jobs are in a `success` status in Horizon, yet Telescope shows these jobs as in a `pending` status!

**Comment by themsaid** [comment]
duplicate of https://github.com/laravel/telescope/issues/503

**Comment by Rux77** [comment]
How to reproduce this issue?

1 - run `php artisan horizon` before dispatching any job..
2 - dispatch a job from Observer or Events listeners..

It seems that Telescope doesn't catch jobs's events probably in this scenario...

**Comment by fridzema** [comment]
Same issue here. 
Horizon says it is finished successfully, but telescope stays pending forever.

**Comment by Rux77** [comment]
@themsaid

is this on your radar?

**Comment by themsaid** [comment]
I can't replicate it no matter what I test, horizon and telescope are running nicely together.

**Comment by Rux77** [comment]
I did a fresh laravel install with the same configuration as my old project ( which has the issue ) and everything is working nicely between horizon and telescope like you said.

I will dig more and see whats happening with my old project.

**Comment by jny986** [comment]
Just incase anyone finds this and is looking for an answer.
I had the same issue with Telescope and AWS/SQS queues and found that the problem was fixed by restarting the queue workers.
