### ISSUE TITLE
Record timestamps are 2 days off

### ISSUE THREAD

**Issue by google-mac** [laravel/telescope#509]
![screen recording 2018-12-17 at 6 06 26 am](https://user-images.githubusercontent.com/17652149/50089410-01164d00-01c3-11e9-9e78-78ffb143a0d3.gif)

My newly created records are being recorded as from 3 days ago. I verified that the DB matches this incorrect date.

**Comment by themsaid** [comment]
If the records are wrong in the database then you need to check your MySQL settings, machine date/time, or environment settings. Closing since it's not a Telescope issue.
