### ISSUE TITLE
Migrating: 2018_08_08_100000_create_telescope_entries_table

### ISSUE THREAD

**Issue by chisumo2016** [laravel/telescope#51]
Migrating: 2018_08_08_100000_create_telescope_entries_table

   Illuminate\Database\QueryException  : SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manua
l that corresponds to your MariaDB server version for the right syntax to use near 'json not null, `created_at` datetime null) default character set u
tf8mb4 collate' at line 1 (SQL: create table `telescope_entries` (`sequence` bigint unsigned not null auto_increment primary key, `uuid` char(36) not
null, `batch_id` char(36) not null, `family_hash` varchar(255) null, `should_display_on_index` tinyint(1) not null default '1', `type` varchar(20) not
 null, `content` json not null, `created_at` datetime null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')

**Comment by lsfiege** [comment]
#36 , you need to upgrade mariadb to 10.2.7+.
