### ISSUE TITLE
Telescope didn't find anything

### ISSUE THREAD

**Issue by michelangelomo** [laravel/telescope#510]
Sometimes when I use Telescope in production environment I didn't see anything.

If I open the Chrome Developer Tools I can see the requests to api with the expected response but the page still show me "We didn't find anything - just empty space."

**Comment by themsaid** [comment]
Can you please make sure you're on latest Telescope version? If so can you please share the response you see in the browser console?

**Comment by paras-malhotra** [comment]
Please see #470, #434, #409, #288, #134 and #76 to solve your issue.

**Comment by michelangelomo** [comment]
Version 1.0.10 is installed (laravel/telescope: '^1.0').

![schermata 2018-12-18 alle 23 12 55](https://user-images.githubusercontent.com/3934987/50186289-b0b20300-031a-11e9-8fa5-176ddec0e99a.png)

**Comment by Rux77** [comment]
Because Telescope use filter by default:
https://laravel.com/docs/5.7/telescope#filtering

comment that code and see what happens

**Comment by themsaid** [comment]
I can't replicate it, you'll need to dig more.

**Comment by michelangelomo** [comment]
@Rux77 
Telescope::filter returns true in production. There is no filters...

**Comment by michelangelomo** [comment]
Now apparently works fine. I don't know how to reproduce it.

**Comment by masihgh** [comment]
i have still this issue in latest version
