### ISSUE TITLE
Multiple applications, one DB

### ISSUE THREAD

**Issue by WendellAdriel** [laravel/telescope#511]
Hello, I work on some applications that share the same DB, but I wanted to each server only see its own records.

Is there any way to make custom tables by app, or tag the records by app?

**Comment by themsaid** [comment]
You can use `Telescope::tag(function(){  ...  })` to add tags to your entries.

**Comment by WendellAdriel** [comment]
Hello @themsaid.
Where can I add that to tag every entry of a particular app?
Is there any examples or API page that I can look into?

**Comment by core45** [comment]
I have the same problem as WendellAdriel - I have 2 separate apps using the same DB. The best would be if I could use 2 separate sets of tables for each if them.

**Comment by The-backend-dev** [comment]
I have the same problem, It's a rather big project with internal external apis and web interfaces using the same DB. We would have liked to use different tables.

**Comment by core45** [comment]
It seems like nobody give a sh... about us unfortunately...

**Comment by hunglyadamo** [comment]
Hi @themsaid.

I also have the same problem. I have 2 laravel applications as follows:
- Admin: this is where I installed the telescope.
- API.
- Same DB
I have tried to mount the storage folders of these 2 apps together. However, the Telescope only displays the data of the admin application, not the API.
Do you have an example of this case?

**Comment by danielrangelsa** [comment]
I Have the same problem. Multi Project and one database.

**Comment by WendellAdriel** [comment]
Hey people, if the tags can help you, I added this to the TelescopeServiceProvider register method:

```php
Telescope::tag(function () {
    return [config('app.name')];
});
```

**Comment by hunglyadamo** [comment]
> Hey people, if the tags can help you, I added this to the `TelescopeServiceProvider` `register` method:
> 
> ```
> Telescope::tag(function () {
>     return [config('app.name')];
> });
> ```

Thank you, Its work.
required: 2 application need to same storage folder, and install telescope in both of app.
