### ISSUE TITLE
Wrong links when website is not under root folder

### ISSUE THREAD

**Issue by biopowder** [laravel/telescope#512]
My wesite path is: http://localhost/xxx/public/

In telescope.php config I haven't changed path='telescope';
I am able to access http://localhost/xxx/public/telescope, but all my links are href to http://localhost/telescope/something_from_menu. But if I change path='xxx/public/telescope' I am not able to access http://localhost/xxx/public/telescope

**Comment by themsaid** [comment]
Please check the previous issue reports. Don't use laravel in a sub directory.

**Comment by biopowder** [comment]
Ok, I found how can I manage all my projects.

Guys, if you have several projects on your windows machine (and if you are using xampp), then just add to `xampp\conf\extra\httpd-vhosts.conf` and restart apache.

```
<VirtualHost *:80>
    DocumentRoot "C:/xampp/htdocs/your_site_name/public"
    ServerName your_site_name
</VirtualHost>
```

Your site will be accessible http://your_site_name, and telescope will work fine ;)
