### ISSUE TITLE
Dump() working in Http/Controllers folder but not in contained sub directory

### ISSUE THREAD

**Issue by ashniazi** [laravel/telescope#518]
So interesting thing i noticed. My app has an Admincp directory within the `Http/Controllers` directory.
When I use the dump() function in a controller located within `App/Http/Controllers` it dumps and logs it in telescope perfectly. However if i dump anything in a controller located within `Http/Controllers/Admincp/` - telescope does not log the dump.

My Controllers within the Admincp directory defines the namespace to be `Http/Controllers/Admincp/` and it also uses `Http\Controllers\Controller`.

Any idea why Telescope doesn't log it.

Using php 7.2.5, laravel 5.7.19, and telescope 1.0.10

**Comment by themsaid** [comment]
Please use the forums for questions.
