### ISSUE TITLE
composer.json required laravel

### ISSUE THREAD

**Issue by TBlindaruk** [laravel/telescope#52]
Hi,

Why `required` section on  `composer.json` required only next:
```
    "require": {
        "php": "^7.1.3",
        "ext-json": "*",
        "moontoast/math": "^1.1",
        "symfony/var-dumper": "^4.1"
    },
```

Why is not contains `laravel/framework` dependency?

**Comment by themsaid** [comment]
There's a PR suggesting adding the used illuminate components: https://github.com/laravel/telescope/pull/45
