### ISSUE TITLE
Non-descriptive Gate index items

### ISSUE THREAD

**Issue by dillingham** [laravel/telescope#520]
![before](https://user-images.githubusercontent.com/29180903/50407308-95277c00-07a2-11e9-9ec9-618a6b156223.png)

The parameters are the models in this case
Would be SUPER useful to see with the file. 
Gives some context as to what is happening.

![after](https://user-images.githubusercontent.com/29180903/50407328-0a934c80-07a3-11e9-8bd3-83944aa6ef4e.png)

**Comment by themsaid** [comment]
Feel free to open a PR.
