### ISSUE TITLE
See complete queries

### ISSUE THREAD

**Issue by thomasdominic** [laravel/telescope#523]
In the queries table, we have the complete query in the title of the link attribute, but in the detail of a query, we do not have the complete query, but only its schema. It would be interesting to have it for example to copy / paste. 

Currently, I'm using the chrome inspector

**Comment by themsaid** [comment]
Some queries are too big to display in the table, you'll have to click on the entry to see the full query in the preview screen.

**Comment by thomasdominic** [comment]
ah I see, it's with mongodb the problem 
![2018-12-28_18h53_00](https://user-images.githubusercontent.com/17202290/50523708-ebadf680-0ad1-11e9-831d-3c0e8054d4a0.png)
![2018-12-28_18h51_33](https://user-images.githubusercontent.com/17202290/50523711-eea8e700-0ad1-11e9-8bfc-e2a33a0aa001.png)
