### ISSUE TITLE
Ignore migrations

### ISSUE THREAD

**Issue by rennokki** [laravel/telescope#525]
Passport has a feature called `ignoreMigrations` that allows you to un-register the automatic migration of Passport's tables to be able to change them the way you need it.

We need something like this on telescope. I'm working with MongoDB and this knocks me off.

**Comment by mattias-persson** [comment]
This feature seems to be documented but not yet released. Following the docs currently gives `Undefined method: ignoreMigrations`.  Any thoughts on when it might be released @themsaid?

**Comment by themsaid** [comment]
Hey everyone, v1.0.11 was released since this morning. Please pull it down and let us know if you have any comments.

**Comment by mattias-persson** [comment]
@taylorotwell @themsaid Seems to be working with the latest release, thanks a ton guys! 🔥
