### ISSUE TITLE
Not working when run with xampp

### ISSUE THREAD

**Issue by shanmuga3** [laravel/telescope#526]
I am using XAMPP to run laravel project. all request goes through http://localhost/telescope. so it return 404 error.how to solve this?.It working fine when using php artisan serve
![screenshot from 2019-01-04 14-46-29](https://user-images.githubusercontent.com/38732797/50680938-92911600-102f-11e9-8336-1f89c762f1ca.png)

**Comment by themsaid** [comment]
Please check the previous issue reports. It won't work for subdirectories, switch to something like Homestead or Docker.
