### ISSUE TITLE
MySQL error max_allowed_packet_error blocks Job Queues

### ISSUE THREAD

**Issue by Lloople** [laravel/telescope#527]
I'm experiencing the problem exposed here #259 but in job queues.

The problem is that when this error happens, the next job is not fired. The queue remains active but it does not fire the next job. Also, the error is not logged anywhere unless you use the `sync` driver on your Queues.

**Comment by themsaid** [comment]
You have to watch out what you record using Telescope, only record what you need.

**Comment by Lloople** [comment]
I know that.

The issue is the queue being stuck, not the recording. I cannot disable all jobs recording either.

**Comment by Lloople** [comment]
Will Redis solve this issue?

Telescope will fail either way because of MySQL error, but I’m happy if the queue continue with the next job instead of not starting the next one.

**Comment by themsaid** [comment]
I haven't seen any similar problems with redis or sqs, Telescope is recording thousands of entries since it was released and never had the queue stuck even if Telescope errored.

**Comment by Lloople** [comment]
I’ll try to extend the redis driver the same way I did with the MySQL to add the client_id then and see if that works. Thanks.

I’ll post this in Laravel repository if I get more info about what is the queue doing 👍
