### ISSUE TITLE
Empty page when accessing telescope

### ISSUE THREAD

**Issue by gjm** [laravel/telescope#528]
When I access telescope I always get an empty page. As the screenshot shows, there are no javascript errors. There are also no errors on the log file. 

I'm running Laravel 5.7 on PHP 7.2.

Here is the HTML source of the empty page:  [telescope_source.txt](https://github.com/laravel/telescope/files/2745858/telescope_source.txt)

Is there anything I can do to help debug this situation?

![telescope](https://user-images.githubusercontent.com/77360/50976825-d6c95e00-14e8-11e9-8f1d-2580d1d6fd88.png)

**Comment by ybaruchel** [comment]
Hi @gjm,

Can you please add more info on reproducing the bug?

**Comment by gjm** [comment]
Hi.

I think it probably was related to a telescope upgrade. I recreated
telescope's tables and republished assets and it seems to be working
fine now.

For me, it's OK to close the issue.

Best regards

Gonçalo Marrafa
