### ISSUE TITLE
Always returns 403 in production

### ISSUE THREAD

**Issue by robertmylne** [laravel/telescope#532]
Won't work for me in production no matter what:

```
    'middleware' => [
        'web',
//        Authorize::class,
    ],
```
```
    public function register()
    {
        // Telescope::night();

        $this->hideSensitiveRequestDetails();

//        Telescope::filter(function (IncomingEntry $entry) {
//            if ($this->app->isLocal()) {
//                return true;
//            }
//
//            return $entry->isReportableException() ||
//                   $entry->isFailedJob() ||
//                   $entry->isScheduledTask() ||
//                   $entry->hasMonitoredTag();
//        });
    }
```
```
    protected function gate()
    {
        Gate::define('viewTelescope', function ($user) {
            return true;
        });
    }
```
```
    protected function authorization()
    {
        $this->gate();

        Telescope::auth(function ($request) {
            return true;
        });
    }

```
```
APP_ENV=local // changed from production to see if that worked
TELESCOPE_ENABLED=true
```

In production always gives me 403, thought the database entries are all being created.

**Comment by robertmylne** [comment]
Running the command `php artisan config:cache` fixed the issue.

**Comment by robertmylne** [comment]
Interestingly when I toggle `TELESCOPE_ENABLED=false` between true and false on my Laravel forge instance it won't change it unless I run `composer dumpautoload && php artisan config:cache`

**Comment by KeithBush** [comment]
That is because `php artisan config:cache` caches the results of all of your config files into one file and no longer reads your .env file.  Great for production but you have to remember to rebuild the cache or clear it yourself. https://laravel.com/docs/5.7/configuration#configuration-caching

**Comment by robertmylne** [comment]
Still, it should be noted in the documentation that this is required when pushing and existing site to production.

**Comment by mabasic** [comment]
I am having the exact same issue, but for me it doesn't work even with `config:cache`.

I have tried clearing the cache manually from `bootstrap/cache` and from `storage/framework`.

**Comment by phuclh** [comment]
I have the same problem, it always returns a 403 error even I set the Gate::define returns true and config cache was cleared. Any solution for that?

**Comment by RuanHerculano** [comment]
I have the same problem.

**Comment by mabasic** [comment]
@phuclh @RuanHerculano I have managed to get it working. I've updated to the latest release `2.0.6` and double checked my user email. Now it works. I can swear that before it would not work no matter what.

I have a different issue now and that is that in production it does not collect any data, but I can log in.

**Comment by core45** [comment]
Have the same problem. Whatever I do it gives me 403.
Laravel 6.9.0, Telescope 2.1

**Comment by wwwroth** [comment]
My Telescope instane was working on prod (with custom IP whitelisting) with Laravel 5.8 but once I upgraded to 7.0 it started returning a 403. Here's my gate..

``` php
       Gate::define('viewTelescope', function ($user = null) {
            if (! in_array(request()->ip(), explode(',', config('nova.ipWhiteList')))) {
                abort(403);
            }
            return true;
        });```

**Comment by ludovic-coder** [comment]
Same here! Why is it closed without any solution?

**Comment by browner12** [comment]
It is probably closed because this is most likely a userland error, and the Github issues are only for bugs in the package itself.

The recommendation would be to move this discussion to another medium (Slack, StackOverflow, etc) and try and debug the problem there.  If that is unsuccessful and you are able to determine this is **actually** a bug in the package itself, then come back here and explain the bug.

**Comment by dalmarcolucas** [comment]
If you are using another guard that's not the default "web", you have to change it in the "config/auth" file:

` 'defaults' => [
        'guard' => 'admin',
        'passwords' => 'users',
    ],`

It was my problem, I'm using a custom "admin" guard, and laravel telescope has no option to specific change the guard, so I had to put the "admin" guard as default.

**Comment by haoxi911** [comment]
My scenario is I used a 3rd party library `Bouncer` which managed Laravel authorizations. So the `Gate` in Telescope's provider doesn't really work.

**Comment by moiz-conceptlz** [comment]
Does anyone know how to get Telescope working with Catalyst Sentinal? (https://cartalyst.com/manual/sentinel/4.x)

Using Laravel 6.18 and Sentinal v4

**Comment by haoyuqi** [comment]
If you don't use Laravel authorization, modify `function ($user)` to `function ($user = null)`
```php
protected function gate()
    {
        Gate::define('viewTelescope', function ($user = null) {
            /*return in_array($user->email, [
                //
            ]);*/
            return true;
        });
    }
```

**Comment by moiz-conceptlz** [comment]
> If you don't use Laravel authorization, modify `function ($user)` to `function ($user = null)`
> 
> ```
> protected function gate()
>     {
>         Gate::define('viewTelescope', function ($user = null) {
>             /*return in_array($user->email, [
>                 //
>             ]);*/
>             return true;
>         });
>     }
> ```

This is great, but this makes telescope open in a production environment too which is not great. 

How can the gate function be integrated with the user object of another auth library - specifically https://cartalyst.com/manual/sentinel/4.x?

**Comment by haoyuqi** [comment]
> > If you don't use Laravel authorization, modify `function ($user)` to `function ($user = null)`
> > ```
> > protected function gate()
> >     {
> >         Gate::define('viewTelescope', function ($user = null) {
> >             /*return in_array($user->email, [
> >                 //
> >             ]);*/
> >             return true;
> >         });
> >     }
> > ```
> 
> This is great, but this makes telescope open in a production environment too which is not great.
> 
> How can the gate function be integrated with the user object of another auth library - specifically https://cartalyst.com/manual/sentinel/4.x?

`return true` just an example, you can customize the validation

**Comment by moiz-conceptlz** [comment]
> > > If you don't use Laravel authorization, modify `function ($user)` to `function ($user = null)`
> > > ```
> > > protected function gate()
> > >     {
> > >         Gate::define('viewTelescope', function ($user = null) {
> > >             /*return in_array($user->email, [
> > >                 //
> > >             ]);*/
> > >             return true;
> > >         });
> > >     }
> > > ```
> > 
> > 
> > This is great, but this makes telescope open in a production environment too which is not great.
> > How can the gate function be integrated with the user object of another auth library - specifically https://cartalyst.com/manual/sentinel/4.x?
> 
> `return true` just an example, you can customize the validation

Thanks for this - I was able to get Telescope working with Sentinal!

**Comment by moiz-conceptlz** [comment]
Thanks for this @haoyuqi  - I was able to get Telescope working with Sentinal!

**Comment by driesvints** [comment]
Hey everyone,

I'm locking this issue because it either has gone off-topic, become a dumping ground for things which shouldn't be in an issue tracker or is just too old. Please try to discuss things further on one of the below channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
