### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by tormjens** [laravel/telescope#533]
The documentation refers to the "Migration Customization", but this was committed 5 days ago. 

![screenshot 2019-01-16 at 10 04 06](https://user-images.githubusercontent.com/3974889/51238008-1f17ce80-1976-11e9-979e-0f6e1ad5da8d.png)

There are 15 commits since the last release, and migration customization is in there. ;)

**Comment by themsaid** [comment]
Tagging in a few minutes :)

**Comment by rfussien** [comment]
Hi,
Did I miss something or 1.0.10 is stil the last release ?
