### ISSUE TITLE
BUG: Database migration creating table without a primary key

### ISSUE THREAD

**Issue by tomswinkels** [laravel/telescope#534]
I have created the database with `php artisan migrate` and not all the tables has some primary key.

`SQLSTATE[HY000]: General error: 1105 Percona-XtraDB-Cluster prohibits use of DML command on a table (prepr_api.telescope_entries_tags) without an explicit primary key with pxc_strict_mode = ENFORCING or MASTER (SQL: insert into `telescope_entries_tags` (`entry_uuid`, `tag`) values (8cc397bb-ea30-42b3-8705-00f6eefb169d, failed))`

**Comment by themsaid** [comment]
What is the database engine?

**Comment by rs-sliske** [comment]
i believe percona is a mysql fork

**Comment by tomswinkels** [comment]
Yeah we use percona.

**Comment by tomswinkels** [comment]
@ybaruchel why do you have close that branch?

**Comment by ybaruchel** [comment]
@tomswinkels Because I accidentally added a primary key to the wrong table and it broke the build.. I didn’t had time to fix it so I closed the PR

**Comment by Elycin** [comment]
Bump to this.

My workplace is interested in using telescope for diagnostic reasons and we're having this current issue with our percona cluster. Would love to see this implemented.
