### ISSUE TITLE
Setting a custom asset_url causes telescope css & js to 404

### ISSUE THREAD

**Issue by jim0thy** [laravel/telescope#539]
Setting a custom `asset_url` causes Telescope to look for `app.css` & `app.js` at the updated asset url, instead of its own asset folder.

Example:
Setting `asset_url => 'cdn.example.com'` causes Telescope to look for its files here:
`https://cdn.example.com/vendor/telescope/app.css`
`https://cdn.example.com/vendor/telescope/app.js`

Removing the custom `asset_url` fixes the problem.

**Comment by rolandstarke** [comment]
Isn't that the expected behavior? You would need make the `/vendor` folder accessible from your cdn as well.

**Comment by jakewtaylor** [comment]
This is a problem I'm from suffering from too. I'm using a service provider to adapt the asset URL based on the domain being used - which works fine for my use case, but breaks Telescope.

I'm currently working around the issue by not updating the asset URL if the current request path starts with 'telescope', but that's going to cause issues if someone creates a page with a slug that starts with 'telescope', so it's not an ideal solution.

Any work arounds?

**Comment by metrixinfo** [comment]
In .env I use ASSET_URL=/assets for local development.  Seems to work just fine.

On staging and production ASSET_URL are defined using the CDN.
ie. ASSET_URL=https://cdn.mycompany.com/assets

Telescope now looks for it's JS and CSS under /assets/vendor: 

My Work around is simply creating a symbolic link to /public/vendor in /public.

````
cd public/assets && ln -s ../vendor vendor
````

**Comment by felyx** [comment]
Our problem is similar to yours, we have an older project where we had to move the content of the public folder to the app root thus telescope is looking for the assets in approot/vendor/telescope which is obviously not good but I do not see an easy solution for this. Maybe a setting where you could specify where the assets are located would be a possible solution for everyone?

**Comment by hengkydev** [comment]
same to me i working with 3 stage , development, staging then prod. 
on development stage the main url is dev.domain.com/projectname.
so is not started with domain name but with url path when i try to access telescope 
asset url and api url is not working properly

**Comment by taylorotwell** [comment]
The original issue's behavior is expected. Telescope's assets would need to be available there.

**Comment by MtDalPizzol** [comment]
> The original issue's behavior is expected. Telescope's assets would need to be available there.

IMO, this should not be the expected behavior.  Telescope should provide an option to set it's asset_url.

For example: I'm using a webpack-dev-server to serve my assets during development directly from memory. This server has it's on URL, which I'm using as the ASSET_URL on my .env file and will not be served from laravel's `public` directory.

So, Telescope can't use ASSET_URL as it's own asset_url.

@jakewtaylor solution is simple, but I think this is simple enough to be provided out of the box.

**Comment by xwiz** [comment]
The response to this is kind of shocking. It's the same laravel that allows changing the asset_uri in env out of the box but telescope is not compatible with that out of the box?
