### ISSUE TITLE
Feature: Added log channel as prefix in log or a channel col

### ISSUE THREAD

**Issue by tomswinkels** [laravel/telescope#544]
I have create difference log channels for my project.

Every job has an own channel so that one log had only data from one job.

Now in telescope i see all that logs but now are the logs all the same.

Maybe its a idea to set the channel name as prefix, or add a col in the table. 

`Log::channel('PlaneQueueJob')->info('Exists',(array)$plane);`

**Situation on this moment**
<img width="1144" alt="image" src="https://user-images.githubusercontent.com/9036151/51891140-75d1cf00-239e-11e9-8fc9-f1e7131af212.png">

**One idea**
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/9036151/51891217-a87bc780-239e-11e9-98b2-adaaf8690c78.png">

**One idea (maybe this is better)**
<img width="1178" alt="image" src="https://user-images.githubusercontent.com/9036151/51891324-04465080-239f-11e9-94ae-d4f366c5ba6b.png">

**Comment by themsaid** [comment]
Feel free to open a PR :)
