### ISSUE TITLE
BUG: Telescope not recording all routes

### ISSUE THREAD

**Issue by Livijn** [laravel/telescope#545]
I am using Laravel Forge and have provisioned servers: db, loadbalancer, app.

When using the app locally and on the staging server, all routes are recorded. However, on the production site some routes are excluded. It is not intentional and I am using this to record the data:

    Telescope::filter(function (IncomingEntry $entry) {
            return true;
        });

I have disabled all app servers but one so I know it isn't an issue with maybe one server not connecting to the same database, etc.

There are at least 2 named routes that won't get recorded. What is causing this?

**Comment by themsaid** [comment]
I think you are the only person who can answer this :) Telescope is working fine for me and it doesn't seem that other people are facing the same issue.

Please ping me if you reach something.

**Comment by Livijn** [comment]
The reason for this seems to be that some routes have too much data for telescope to log.
