### ISSUE TITLE
Timezone is off if not set to UTC

### ISSUE THREAD

**Issue by viirre** [laravel/telescope#55]
If I set another timezone other than `UTC` in my `config/app.php` file (eg `Europe/Stockholm`), all entries are reported as they happened with an offset (depending on the timezone defined). It appears as if you *must* have `UTC` in  `config/app.php` to get the correct time reported.

**Comment by vesper8** [comment]
noticed that as well, my timezone is america/new york and things that happened just now are marked as having happened 4 hours ago

**Comment by piotrgulbis** [comment]
confirming this. Have Europe/Vienna set in app.php and it's marking as happened two hours ago.

**Comment by themsaid** [comment]
So in the database, what timezone are the entries stored in? The one set in config/app?

**Comment by johanvanhelden** [comment]
Chiming in here. @themsaid the database entries are stored in the proper timezone.

Entries are stored as `2018-10-23 21:35:17` and that is also the current time. (Europe/Amsterdam)
However, the interface shows `2h ago`

**Comment by viirre** [comment]
They are stored correctly as per the one specified in config/app

**Comment by themsaid** [comment]
@virre I think that's an easy fix, will have to look into it tomorrow though :)

**Comment by viirre** [comment]
Super! 👍

**Comment by Mecit** [comment]
Are you sure this is actually fixed? I've just installed Telescope and my timezone in config/app.php is set to 'Europe/Istanbul' (that's GMT+3) and for a request made at **14:35**, the request details page says it was made at **5:35 PM (3h ago)**.

**Comment by johanvanhelden** [comment]
Are you sure you installed the latest version? It has been released in 0.1.2.

**Comment by themsaid** [comment]
@Mecit make sure you're on latest telescope and re-publish the assets.

**Comment by ybaruchel** [comment]
@Mecit 
As @themsaid said, you'll have to republish the assets

**Comment by Mecit** [comment]
Thanks @ybaruchel and @themsaid. Seems the package was still in v0.1.1 when I installed it, indeed. Updating and re-publishing the assets solved the issue.

**Comment by hailwood** [comment]
Note to anyone who comes across this issue, republishes and still finds it doesn't work?
Try using the `--force` flag :)

**Comment by yordivd** [comment]
I'm on version v1.2 and still facing this issue. Have republished and force republished.
The entry in my database table has the correct datetime.
for example 2019-10-25 09:44:00 is in my database entry
but in telescope it shows 2019-10-25 11:44:00s (5s ago)..
My timezone in app config is set to Europe/Brussels and is working fine in my application.

**Comment by viirre** [comment]
Can confirm that the actual displayed date (when viewing a single request) is wrong. See screenshot below for a request made at 10:06 local time (the one i config/app.php). The outputted "ago" is correct though.

![Screen Shot 2019-10-25 at 10 06 21 AM](https://user-images.githubusercontent.com/697468/67554307-65713980-f70f-11e9-9815-5d86ac48add0.png)
