### ISSUE TITLE
Log from commands don't seeing in log of Telescope

### ISSUE THREAD

**Issue by tomswinkels** [laravel/telescope#550]
When we use Log::info('INFO'); i an command we don't see that back in Telescope log.

**Comment by rolandstarke** [comment]
I just tested with the default console route and could see the log in telescope.

```php
Artisan::command('inspire', function () {
    Log::info('INFO');
    $this->comment(Inspiring::quote());
})->describe('Display an inspiring quote');
```

![screenshot_2019-02-09 command details - telescope 1](https://user-images.githubusercontent.com/5196813/52522821-c85a9780-2c8a-11e9-89e7-dd302a9ef0d5.png)

**Comment by tomswinkels** [comment]
Hmmm..

This is my case:

I tun a deamon

`php /home/project/current/artisan command:Connection af8946a1-74a7-4968-9f6a-ffa93cbea808`

In the connection file i do

`Log::info('info');`

And in the storage log file i see that log info but not in Telescope.

**Comment by rolandstarke** [comment]
Reading the source it makes sense that you don't see any data, as the entries are only flushed to db at specific times:

https://github.com/laravel/telescope/blob/329850eb72d6f524e343416df201c0c7aacde23b/src/ListensForStorageOpportunities.php#L20-L31

**Comment by tomswinkels** [comment]
Stupid you have right. The command is an open process that never close that's the reason.

I go try to add the Telescope::store :)
