### ISSUE TITLE
Argument 6 passed to Laravel\Telescope\EntryResult::__construct() must be of the type array, integer given

### ISSUE THREAD

**Issue by WouterFlorijn** [laravel/telescope#552]
> Argument 6 passed to Laravel\Telescope\EntryResult::__construct() must be of the type array, integer given, called in /project/vendor/laravel/telescope/src/Storage/DatabaseEntriesRepository.php on line 91

This exception is thrown server-side when I open the Exceptions tab in Telescope.

Argument 6 is the content. Indeed, when I check out the database, there is an entry with `content` equal to `0`. So the problem seems to be that this entry was created in the first place.

**MySQL results**

```bash
MariaDB [project]> select * from telescope_entries where CHAR_LENGTH(content) < 10;
+----------+--------------------------------------+--------------------------------------+----------------------------------+-------------------------+-----------+---------+---------------------+
| sequence | uuid                                 | batch_id                             | family_hash                      | should_display_on_index | type      | content | created_at          |
+----------+--------------------------------------+--------------------------------------+----------------------------------+-------------------------+-----------+---------+---------------------+
|     1814 | 8cea7fc4-b00e-4963-aef3-987dd8819265 | 8cea7fc4-b109-4390-a4a5-778d263fde29 | 153494610558b9ea647e61a1483041fe |                       1 | exception | 0       | 2019-02-05 18:32:18 |
+----------+--------------------------------------+--------------------------------------+----------------------------------+-------------------------+-----------+---------+---------------------+
```

**Comment by rolandstarke** [comment]
I have that rows with content 0 too.

I could reliably reproduce it with the following code:



```php
<?php

namespace App\Http\Controllers;

class IndexController extends Controller
{
    public function index()
    {

        function asdf($longString){
            //$longString will will be stored 
            //as all params in the stacktrace are stored
            throw new \Exception('asdasd');
        }

        $string = base64_decode('gA==');
        asdf($string);

        return view('index');
    }
}
```




Originally I stumbled over it when handling uploaded files in jobs, the failed job diapered and also the logs you do in the job.


A solution would maybe be, not storing all the params in the stack trace? They are not diplayed anywhere. especially having large strings, and passing them around makes the stacktrace and therefore the content column enormous.

**Comment by themsaid** [comment]
check:

- https://github.com/laravel/telescope/issues/430
- https://github.com/laravel/telescope/issues/33

**Comment by rolandstarke** [comment]
The sipping of bad rows works well. Changing the column type to LONGTEXT did solve the issue in the above example.

**Comment by themsaid** [comment]
Thanks for sharing, the problem is exposed when we try to store a huge JSON object in a MySQL column that wouldn't handle the size.

**Comment by rolandstarke** [comment]
Ah sry, i forgot the "not" in my last message. So i still have 0s in the db.

They are comming from:

https://github.com/laravel/telescope/blob/d7a3ca4338b1a1527b8d19a5d62015a468f8ca56/src/Storage/DatabaseEntriesRepository.php#L118

A more simple way to reproduce it is just:

```
Log::info('test' . base64_decode('gA=='));
```
The output from `json_last_error()` gives `JSON_ERROR_UTF8`.

**Comment by m1guelpf** [comment]
@themsaid any updates on this?

**Comment by ikramulmustafa** [comment]
any update on this how to fix it?
