### ISSUE TITLE
"array_key_exists(): The first argument should be either a string or an integer"

### ISSUE THREAD

**Issue by dev** [laravel/telescope#554]
Hello,
We have a model which is using composite keys. We never had any problems using the composite keys (we use a trait in order to be able to use composite keys in Laravel), but since we are using Telescope, we get an error when trying to insert a new row in a table using composite keys.

For example:
`ItemLang::create(['id'=>1,'languagecode'=>'NL','title'=>'Hallo']);`
Returns the error:
`array_key_exists(): The first argument should be either a string or an integer`
at 
`/var/www/vhosts/master.62.git/laravel/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:315
`

```306     public function getAttribute($key)

307     {

308         if (! $key) {

309             return;

310         }

311 

312         // If the attribute exists in the attribute array or has a "get" mutator we will

313         // get the attribute's value. Otherwise, we will proceed as if the developers

314         // are asking for a relationship's value. This covers both types of values.

315         if (array_key_exists($key, $this->attributes) ||

316             $this->hasGetMutator($key)) {

317             return $this->getAttributeValue($key);

318         }

319 

320         // Here we will determine if the model base class itself contains this given key

321         // since we don't want to treat any of those methods as relationships because

322         // they are all intended as helper methods and none of these are relations.

323         if (method_exists(self::class, $key)) {

324             return;

325         }
```

**Comment by themsaid** [comment]
Can you please share the full stack trace?

**Comment by kenwilliams5** [comment]
I'm having the same problem. My tests fail if the telescope model watcher is enabled. Here is what I get when the model watcher is enabled:

`90) Tests\Unit\UserTest::a_user_can_determine_if_another_user_is_in_one_of_their_groups
ErrorException: array_key_exists(): The first argument should be either a string or an integer

/var/www/html/dev.test/public_html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:315
/var/www/html/dev.test/public_html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:1388
/var/www/html/dev.test/public_html/vendor/laravel/telescope/src/FormatModel.php:18
/var/www/html/dev.test/public_html/vendor/laravel/telescope/src/Watchers/ModelWatcher.php:36
/var/www/html/dev.test/public_html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:357
/var/www/html/dev.test/public_html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:209
/var/www/html/dev.test/public_html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasEvents.php:162
/var/www/html/dev.test/public_html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:809
/var/www/html/dev.test/public_html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:651
/var/www/html/dev.test/public_html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:793
/var/www/html/dev.test/public_html/vendor/laravel/framework/src/Illuminate/Support/helpers.php:1027
/var/www/html/dev.test/public_html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:794
/var/www/html/dev.test/public_html/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php:23
/var/www/html/dev.test/public_html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:1610
/var/www/html/dev.test/public_html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:1622
/var/www/html/dev.test/public_html/app/User.php:67
/var/www/html/dev.test/public_html/tests/Unit/UserTest.php:187
`

All of my tests pass if the model watcher is not enabled.

**Comment by sgasser** [comment]
I think you don't have the ```getKey()``` function in your [HasCompositePrimaryKey trait](https://github.com/mopo922/LaravelTreats/blob/master/src/Model/Traits/HasCompositePrimaryKey.php#L25)


```php
    public function getKey()
    {
        $attributes = [];
        foreach ($this->getKeyName() as $key) {
            $attributes[$key] = $this->getAttribute($key);
        }

        return $attributes;
    }
```

**Comment by kenwilliams5** [comment]
That's it!! Thank you!

**Comment by ChinwalPrasad** [comment]
@sgasser Can you elaborate your solution? Where does the method getKey() go ? Thanks a lot :)

**Comment by sgasser** [comment]
@ChinwalPrasad you should add this trait to your model: https://github.com/mopo922/LaravelTreats/blob/master/src/Model/Traits/HasCompositePrimaryKey.php

**Comment by jmediatechnology** [comment]
I had the same problem, but I wasn't in the laravel/telescope environment. 
I want to write an answer for people who experience the same problem. 
 
The warning: "Warning: array_key_exists(): The first argument should be either a string or an integer" is really a php problem, it occurs when the first argument that is given to array_key_exists() is not a string or integer. 

You can reproduce this problem like this: 

```
ini_set('display_errors', '1');
ini_set('display_startup_errors', '1');
error_reporting(E_ALL);

function getStr(){
    return 0;
}

$str = getStr(); // $str = integer 0
$key = substr($str, 0, -2); // $key = boolean false
$arr = array('John');

// Supplying a boolean as first argument will cause a warning.
// The reason for this is because $key contains a boolean false. 
// A boolean false is not an integer or string, that's why php triggers a warning. 
if(array_key_exists($key, $arr)){
    echo 'It exists';
}
```

How can this Warning sneak into the code?
In this example the key that is supplied to array_key_exists is coupled to the result of the substr function. The function substr normally gives a string, but if substr fails then it gives a boolean false. 
So, when substr fails, then array_key_exists will recieve a boolean false which causes the warning. 

Similar situations cause the problem.

**Comment by weblooter** [comment]
Had the same problem. The factory created but did not save the model.
Primary - string.
Trace looked like this:

```
Illuminate\Database\Eloquent\Model->hasChanges()
Illuminate\Database\Eloquent\Model->isDirty()
Illuminate\Database\Eloquent\Model->updateTimestamps()
Illuminate\Database\Eloquent\Model->performInsert()
Illuminate\Database\Eloquent\Model->save()
```
And then I realized that I didn't use timestamps, but I forgot to declare `public $timestamps = false` in the model;
After the declare, it worked

```
class ComplaintType extends Model
{
    use HasFactory;

    protected $primaryKey = 'code';
    public $incrementing = false;
    protected $keyType = 'string';
    public $timestamps = false;

    protected $table = 'site_complaint_types';

    protected $casts = [
        'code' => 'string',
        'sort' => 'int',
        'title' => 'string',
    ];

    protected $fillable = [
        'code',
        'sort',
        'title',
    ];

    public function complaints() {
        return $this->belongsToMany(Complaint::class);
    }
}
```
