### ISSUE TITLE
TelescopeServiceProvider not registered

### ISSUE THREAD

**Issue by rolandstarke** [laravel/telescope#555]
After running `php artisan telescope:install` the `App\Providers\TelescopeServiceProvider::class` is not registered in the `config/app.php` file.

The problem is that my config has `\n` lineendings and the `str_replace` is searching for `PHP_EOL` (`\r\n` on windows).

In my case it could be solved by not searching for `PHP_EOL`:

https://github.com/laravel/telescope/blob/7b91bd857e9441150c834047193c224e2e48c287/src/Console/InstallCommand.php#L63-L67

Working version:
```php
        file_put_contents(config_path('app.php'), str_replace(
            "{$namespace}\\Providers\EventServiceProvider::class,",
            "{$namespace}\\Providers\EventServiceProvider::class,".PHP_EOL."        {$namespace}\Providers\TelescopeServiceProvider::class,",
            $appConfig
        ));
```

Related: https://github.com/laravel/telescope/issues/178, https://github.com/laravel/telescope/issues/271, https://github.com/laravel/telescope/issues/500

**Comment by themsaid** [comment]
It just assumes the convention is used, if you format your config file in a different way you can always manually add the service provider.

**Comment by rolandstarke** [comment]
Wouldn't it be better to solve the problem instead of closing it? You already got 3 other issues because of it. 

idk the convention... use `\n` everywhere?

then the fix could also be 

```
        file_put_contents(config_path('app.php'), str_replace(
            "{$namespace}\\Providers\EventServiceProvider::class,",
            "{$namespace}\\Providers\EventServiceProvider::class,"."\n"."        {$namespace}\Providers\TelescopeServiceProvider::class,",
            $appConfig
        ));
```

**Comment by flick36** [comment]
Indeed is a problem on windows, a shame they just decide to close it instead of solving it
