### ISSUE TITLE
Telescope is logging SocialiteWasCalled everytime the schduler is being run

### ISSUE THREAD

**Issue by Livijn** [laravel/telescope#559]
I am using `Laravel Socialite` and as the title suggests, Telescope logs one entry of `SocialiteProviders\Manager\SocialiteWasCalled` every minute.

Is this supposed to happen? It seems strange. Right now I have to filter out that event like this: 

    Telescope::filter(function (IncomingEntry $entry) {
        if ($entry->type == 'event' && $entry->content['name'] ?? '' == SocialiteWasCalled::class) {
            return false;
        }
    
        // blabla
    });

**Comment by themsaid** [comment]
Telescope records everything, it's your call to filter out what you don't need :)
