### ISSUE TITLE
Frontend failing when laravel is installed in a subdirectory

### ISSUE THREAD

**Issue by rasmus0201** [laravel/telescope#561]
So I'm developing an app and recently installed Telescope. It works pretty smooth, but once i deploy to my test environment which is located in a subdomain (`v2`) and go to /telescope, it loads but every assets doesn't get loaded. 

I think it's because `Telescope.path` doesn't take the `APP_URL` into consideration which could be ex. `https://domain.com/v2` which is my case.

Summary:
Local environment: (`http://domain.localhost/admin/telescope`) - this works perfectly. I altered the telescope config path to be `admin/telescope`.

Testing environment: (`http://domain.tld/v2/admin/telescope`) - this does not work because the base laravel installation is at `http://domain.tld/v2`. Altered the telescope config path to be `admin/telescope`.

**Comment by dvdmarchetti** [comment]
Hi, you might try overriding the url in the layout for telescope in your testing environment.

Here's a workaround:

1. Follow the official documentation to install Telescope.
2. After the database migration, create a file in: ```resources/views/vendor/telescope/layout.blade.php```
3. Copy the contents from the original layout file from the vendor folder, located at: `vendor/laravel/telescope/resources/views/layout.blade.php` and paste it into the previously created file.
4. At the bottom of your new layout file, add a line just after the Telescope global configuration object creation to override the property `window.Telescope.path` like this:
```html
<script>
    window.Telescope = @json($telescopeScriptVariables);
    // Just paste your telescope address, but remove the domain part
    // In your case it would be: 'v2/telescope'
    window.Telescope.path = 'path/to/telescope';
</script>
```

I don't know if there's a better way to do it, but it worked for me.
I hope this helps with your issue. Let me know!

**Comment by themsaid** [comment]
We don't support installing Laravel in a sub directory, sorry.

**Comment by tundak** [comment]
What about larvael 7.x ? this don't have blade file for telescope while project have blade files.

**Comment by driesvints** [comment]
@tundak we probably will never support Laravel in a subdirectory, sorry.

**Comment by Temepest74** [comment]
@driesvints why is this the case? How would someone develop an app with this package on local env? Without some weird workaround

**Comment by driesvints** [comment]
@Temepest74 Laravel in a subdirectory exposes your app outside your web directory and risks exposing code and environment secrets that way.

**Comment by Temepest74** [comment]
> @Temepest74 Laravel in a subdirectory exposes your app outside your web directory and risks exposing code and environment secrets that way.

Yes, but why don't you allow it only in local development (app_debug=true) or something like that?

**Comment by driesvints** [comment]
@Temepest74 doesn't makes sense to us to have a different behavior locally.

**Comment by deniscsz** [comment]
@driesvints  There are cases where the Laravel is in the web root folder of the server but the server where Laravel lives is behind a reverse proxy.

My example: here we have 3 different applications and two of them are Laravel apps. Also we have a SSO in our main domain (www.mycompany.com). Our reverse proxy (nginx) takes the traffic of www.mycompany.com/my-laravel-app and send to Laravel application under the hood.

In this case we need all the links rebuilt with the subfolder path to make the frontend of telescope runs well with the proxy. A config or env can drive this behaviour to make all the links works as expected. Are you open to check/accept some change like this in a PR? I'm able to work on something like this but if there is no chance to be accept, I won't do it.

**Comment by erlangparasu** [comment]
@deniscsz agree. in my case, i  need something like setGlobalPrefix('my/custom/path') :)

**Comment by luanmm** [comment]
> We don't support installing Laravel in a sub directory, sorry.

This is a very simplistic thought.

In my scenario, Laravel isn't **installed** in a sub-directory, for instance, but it is not **accessible** from domain's "root level" either. Like others here already said, the structure is a little bit more complex than a simple case of a website or single app system.

To solve without creating new layout files, like proposed before, here are my "workaround" customizing configs:

```php
    // config/app.php

    'url' => env('APP_URL', 'https://yourdomain.com/your/app/path'),

    'asset_url' => env('APP_URL', 'https://yourdomain.com/your/app/path'),


    // config/telescope.php

    'path' => env('TELESCOPE_PATH', trim(parse_url(env('APP_URL', '/'), PHP_URL_PATH) . '/telescope', '/')),
```

**Comment by luanmm** [comment]
Thanks, @binarweb.

There is no clear reason to not push this into the library code.

Laravel, unfortunately, seems to be, currently, less "open" than .NET, which is ironic.

**Comment by mnwalker** [comment]
Such a simple fix and config('app.url') is a standard laravel setting.

I can understand the security aspect of not wanting live laravel sites in subfolders, but...

1. Laravel itself does work fine in a subfolder (even if less secure...they dont have a not-supported policy)
2. For local dev sites it is a common practice, rather than creating virtualhosts for every new project
3. Telescope itself supports "Local Only Installation"
4. The fix is 5 lines of code without any adverse effects

Suggestion to the team, apply this fix and combine it with a warning if try to run production site in a subfolder.

**Comment by luanmm** [comment]
In my scenario, the app is not in a subfolder, but is accessible from a subpath. Those things are different. Thinking URLs as directory/subdirectory exclusively is too dumb that I refuse to believe that is the logic considered here.

BTW, what are the security concerns regarding this issue?

**Comment by mnwalker** [comment]
> BTW, what are the security concerns regarding this issue?

In my case I access via
http://localhost/project1/public
This has security issues as I can also access http://localhost/project1/.env or http://localhost/project1/.git/config which could expose sensitive info and credentials.
Bad on a live site, perfectly fine on a local machine where I also have http://localhost/project2 and http://localhost/project3 without the hassel of setting up virtualhosts for each project.

Your usecase is a good example where https://example.com/subpath maps to the public folder of your laravel install and https://example.com maps to a different system, so laravel root folder not exposed.
No security issues there and a good reason for telescope to implement support for the standard laravel setting config('app.url')

**Comment by luanmm** [comment]
> In my case I access via http://localhost/project1/public This has security issues as I can also access http://localhost/project1/.env or http://localhost/project1/.git/config which could expose sensitive info and credentials. Bad on a live site, perfectly fine on a local machine where I also have http://localhost/project2 and http://localhost/project3 without the hassel of setting up virtualhosts for each project.

In this kind of structure, I couldn't agree more with the idea of restricting somehow the access (to not "public" folders/files) on production websites.

But, even considering this, I don't think is responsability of Telescope to make these rules nor the team here to make these decisions, because this is limiting Laravel itself. If someday things changes to another direction, Telescope should be patched just because it couldn't be designed to support this in a more dynamic way - which seems just a non-logic way to think software architecture.

> Your usecase is a good example where https://example.com/subpath maps to the public folder of your laravel install and https://example.com maps to a different system, so laravel root folder not exposed. No security issues there and a good reason for telescope to implement support for the standard laravel setting config('app.url')

In this scenario, which is my case, there is absolutely no statement to justify "hardcoding" rules like this. This is really very stressing, because the community already tried to contribute in a way that would make this more flexible and the maintainers tried to put this in a way that considered that "Laravel does not support scenarios like this" - which is the same as declaring that Laravel is a very limited framework, if it cannot support this kind of common topology.

**Comment by mindriven** [comment]
Solution mentioned above still works (Laravel 11.35), but why the heck is this not supported out of the box, if the solution is so simple and well known?

> For those using Laravel 10, the solution from [@dvdmarchetti](https://github.com/dvdmarchetti) no longer works. Change the 4th step to this:
> 
> <script>
>     window.Telescope = @json($telescopeScriptVariables);
> 
>     @php
>         $url = parse_url(config('app.url'));
>     @endphp
> 
>     window.Telescope.basePath = "{{ $url['path'] }}/telescope";
>     window.Telescope.path = "{{ ltrim($url['path'], '/') }}/telescope";
> </script>

**Comment by bizvid** [comment]
After the latest update, the solutions mentioned above stopped working. I have Laravel in a subdirectory on my development server, the telescope is not available at all in the final environment. After the update, the dashboard displays but it does not load data. There are incorrect URLs in the sidebar on the left, pointing to the main domain instead of the subdirectory.

**Comment by adilupu7** [comment]
Any solution for the latest version of Telescope ? None of the above are working anymore

**Comment by mcanti** [comment]
> After the latest update, the solutions mentioned above stopped working. I have Laravel in a subdirectory on my development server, the telescope is not available at all in the final environment. After the update, the dashboard displays but it does not load data. There are incorrect URLs in the sidebar on the left, pointing to the main domain instead of the subdirectory.

same for me

**Comment by adilupu7** [comment]
The only not recommended workaround I could find was to add the hardcoded path in the vendor/laravel/telescope/resources/js/app.js file

`window.Telescope.basePath = '/your-desired-path/' + window.Telescope.path;`
