### ISSUE TITLE
CacheWatcher incompatible with 5.8

### ISSUE THREAD

**Issue by arcdigital** [laravel/telescope#563]
I'm getting this exception in my 5.8 app:
`Undefined property: Illuminate\Cache\Events\KeyWritten::$minutes`
Looks like it's happening in `src/Watchers/CacheWatcher.php`
```
        Telescope::recordCache(IncomingEntry::make([
            'type' => 'set',
            'key' => $event->key,
            'value' => $event->value,
            'expiration' => $event->minutes,
        ]));
```

This seems to be because of the switch from minutes to seconds in 5.8.

**Comment by arcdigital** [comment]
(looks like this is fixed in the 2.0 branch, but that isn't officially released yet)

**Comment by themsaid** [comment]
Releasing today 👍

**Comment by bebignet** [comment]
I have just installed Telescope and get this exception
`Undefined property: Illuminate\Cache\Events\KeyWritten::$seconds`

Laravel 5.7

**Comment by jonnywilliamson** [comment]
@bebignet https://github.com/laravel/telescope/issues/568#issuecomment-469876528

**Comment by NazmusShakib** [comment]
> I have just installed Telescope and get this exception
> `Undefined property: Illuminate\Cache\Events\KeyWritten::$seconds`
> 
> Laravel 5.7

Make sure to use Telescope 2.0 on Laravel 5.8, or Telescope 1.0 on Laravel 5.7. So you have to change your "laravel/telescope" version
