### ISSUE TITLE
Plain Text Mails are not displayed correctly

### ISSUE THREAD

**Issue by adwinying** [laravel/telescope#565]
Plain text mails are displayed without line breaks in Telescope, although line breaks are properly displayed in MailHog and other Email clients.

**Comment by themsaid** [comment]
Please share a screenshot.

**Comment by adwinying** [comment]
## Telescope

![telescope](https://user-images.githubusercontent.com/6265936/53726350-2147d500-3eb1-11e9-917a-490eeef1ac59.png)

## Mailhog

![mailhog](https://user-images.githubusercontent.com/6265936/53726143-b7c7c680-3eb0-11e9-8b2a-782ea787000a.png)

**Comment by themsaid** [comment]
How do you send that email?

**Comment by adwinying** [comment]
Using Mailable class:
```php
public function build()
{
        return $this
            ->from($email)
            ->subject($subject)
            ->text('mail.created');
            ->with(['body' => $body]);
}
```

In `created.blade.php`:

```php
{{ $body }}
```

**Comment by themsaid** [comment]
Yes what's in the body? It doesn't seem to have any formatting information.

**Comment by adwinying** [comment]
`$body` is just a string containing `\n` escape codes.

**Comment by taylorotwell** [comment]
I can confirm this.

**Comment by themsaid** [comment]
We display the email view in an IFrame, because text emails has no formatting information the iframe was just printing some text without styling and that's why it looked odd.

Added a wrapping div around the mail preview.
