### ISSUE TITLE
how to limit request

### ISSUE THREAD

**Issue by softyaco** [laravel/telescope#566]
hi i have tow questions 
first is how to limit the request and job and command for just last 10 times and delete everything else 
just save the last 10 of everything and delete the old one thanks

**Comment by HPWebdeveloper** [comment]
This is not exactly what you want but maybe useful:

There is a concept of Data Pruning [here](https://laravel.com/docs/5.8/telescope)
$schedule->command('telescope:prune')->daily();
$schedule->command('telescope:prune --hours=48')->daily();

**Comment by themsaid** [comment]
Check @HPWebdeveloper answer.

Also you can write your own console command to prune telescope entires to a certain size.
