### ISSUE TITLE
Query doesn't show the '@' sign

### ISSUE THREAD

**Issue by weiwenhao** [laravel/telescope#569]
expect:
![image](https://user-images.githubusercontent.com/24819514/53556837-a4022480-3b7f-11e9-92f5-3a543c3231d3.png)

actually:
![image](https://user-images.githubusercontent.com/24819514/53556817-9cdb1680-3b7f-11e9-9817-4ec7884f5bdb.png)

**Comment by themsaid** [comment]
I'm afraid that's a no-fix. Feel free to try if you want, I'd definitely merge a PR that takes care of it.
