### ISSUE TITLE
Search requests by status

### ISSUE THREAD

**Issue by oad-dwarf** [laravel/telescope#571]
A common usecase for us is to investigate requests with particular HTTP status codes, primarily 422 and 500.

So it would be very nice if Telescope automatically added tags so the status is searchable, for example  `Status:422`.

**Comment by themsaid** [comment]
I think tagging with the response status is not a bad idea, feel free to open a PR.

**Comment by oad-dwarf** [comment]
Thanks @themsaid, but apparently I don't have permission to push a branch, so I cannot open a PR.

But the code is simple:

```patch
diff --git a/src/Telescope.php b/src/Telescope.php
index 2d89c8d..af8e6a2 100644
--- a/src/Telescope.php
+++ b/src/Telescope.php
@@ -434,6 +434,7 @@ class Telescope
      */
     public static function recordRequest(IncomingEntry $entry)
     {
+        $entry->tags[] = 'Status:' . $entry->content['response_status'];
         static::record(EntryType::REQUEST, $entry);
     }


```

**Comment by oad-dwarf** [comment]
@themsaid The code snippet works, I have tested it locally 👍

**Comment by wotta** [comment]
What is the status on this issue?
I would love to see this functionality in Telescope.

So I opened a PR with this functionality in it.
See PR #641.

**Comment by mchaabane** [comment]
You can add this tag in your TelescopeServiceProvider class : register() 

```
        // Add Telescope tag status
        Telescope::tag(function (IncomingEntry $entry) {
            if ($entry->type === 'request') {
                return ['status:'.$entry->content['response_status']];
            }
            return [];
        });
```
