### ISSUE TITLE
Argument 7 passed EntryResult must be an instance of Carbon\CarbonInterface

### ISSUE THREAD

**Issue by AsemAlalami** [laravel/telescope#578]
Argument 7 passed to Laravel\Telescope\EntryResult::__construct() must be an instance of Carbon\CarbonInterface, instance of Illuminate\Support\Carbon given

only replace `CarbonInterface` with `Carbon` it's work fine !!

**Comment by themsaid** [comment]
Make sure you're using Telescope 2.0 on Laravel 5.8

**Comment by themsaid** [comment]
I made the requirement  lose in v2.0.2, give it a try.
