### ISSUE TITLE
Nesting level too deep - recursive dependency?

### ISSUE THREAD

**Issue by muhammadmahindar** [laravel/telescope#580]
Facing this issue when using laravel notification and dispatching a notification. In the ExtractTags.php line 159 if I pass null and true arguments to unique function it works fine though

**Laravel Version:** 5.7.*
**Telescope Version:** 1.*

![image](https://user-images.githubusercontent.com/21039068/53954005-bbe52580-40f6-11e9-85e8-77d3c409129a.png)

**Comment by sherryt400** [comment]
Having same problem while using `$user->notify()`

**Comment by taylorotwell** [comment]
I'm not sure this is a Telescope problem?
