### ISSUE TITLE
Syntax highlighted json looks bad on Ubuntu due to missing fonts

### ISSUE THREAD

**Issue by pdewit** [laravel/telescope#581]
Hey!

My development environment is Ubuntu 18.04, and I just noticed the syntax highlighting is being rendered in Times New Roman because the fonts in the font-family for `.vjs__tree` don't exist in Ubuntu:

`font-family: Monaco,Menlo,Consolas,Bitstream Vera Sans Mono;`

It would probably be good to add monospace as a fallback :)

![image](https://user-images.githubusercontent.com/488574/53955569-aad9eb80-40d9-11e9-9bc3-87010a98c72c.png)

Thanks!

**Comment by themsaid** [comment]
Feel free to open a PR :)
