### ISSUE TITLE
The issue on 'Redis' page being empty still persist...

### ISSUE THREAD

**Issue by nelsonmelecio** [laravel/telescope#585]
I just cloned version 2.0.2 (latest as of the writing). The issue on 'Redis' page being empty still persist...

_Originally posted by @nelsonmelecio in https://github.com/laravel/telescope/issues/355#issuecomment-471311276_

**Comment by talvbansal** [comment]
I'm still seeing the same empty redis page on `2.0.4`. with  `\Illuminate\Support\Facades\Redis::enableEvents();` in the boot method of my AppServiceProvider.

**Comment by taylorotwell** [comment]
Duplicate issue.
