### ISSUE TITLE
Jobs telescope entry not getting created when queue driver not 'sync'

### ISSUE THREAD

**Issue by rameezcubet** [laravel/telescope#593]
I was working with the laravel queues and found this confusing bug.

1. My job contains few DB actions and at the end send a mail.
2. If I set 'QUEUE_CONNECTION' to 'sync', all is working well and recorded in the laravel-telescope, but when I change this to 'redis' or 'database', no job entry is created in the telescope. At the same time, I can see the mail in telescope which is sent via Job.
I have attached a screencast gif to get a better understanding

![job](https://user-images.githubusercontent.com/41043647/54750959-6aad5980-4bff-11e9-9e17-1cdadf1c3a6f.gif)

**Comment by themsaid** [comment]
I can't replicate this, a job is added as `pending` when it's first dispatched and then status changes when I run the actual worker.

**Comment by rameezcubet** [comment]
Too many people have been reporting the same problem, somehow it is working when I pushed to the production server but still not working in the local machine. best I can do to help you debug is provide a TeamViewer or AnyDesk session.

**Comment by CitizenBeta** [comment]
I'm running into this issue on the latest. Was there a solution?

**Comment by dev-mo-ali** [comment]
i have the same issue

**Comment by dev-mo-ali** [comment]
i noticed it Telescope doesn't record jobs when I am using dispatchafterresponse()
but is it working with dispatch()
