### ISSUE TITLE
Entries only get stored when application terminates properly

### ISSUE THREAD

**Issue by benignant** [laravel/telescope#596]
Telescope only persists entries when the application terminates properly. But being able to view entries when there's been an error would be very helpful. For example, logs are most important when there's been an error, but with the way Telescope currently works, no log entries are stored in that case (instead you need to comb through the log file).

Telescope would be vastly more useful if it utilized `register_shutdown_function` instead.

**Comment by themsaid** [comment]
Can you open a PR with the suggested change?

**Comment by benignant** [comment]
I'll give it a shot.

**Comment by benignant** [comment]
I've confirmed that this can be done. However there is a trade-off. If an uncatchable error (e.g., memory exhausted) occurs while storing entries in the shutdown function, PHP will exit immediately (there will be no indication of what happened). This will make the following situation difficult to debug for those developing Telescope itself:

1. The app exits improperly (so the `terminating` event is not fired)
2. An uncatchable error occurs while storing entries in the fallback shutdown function

Is this acceptable? It will make Telescope more reliable for users but harder to debug for developers _of_ Telescope (in this rare case).

**Comment by benignant** [comment]
Ping @themsaid (in case you missed my last comment).

**Comment by barryvdh** [comment]
As far as I can tell, Telescope runs on 'normal' errors, eg. a 500 error which throws an Exception. What cases would benefit from this?

**Comment by benignant** [comment]
> As far as I can tell, Telescope runs on 'normal' errors, eg. a 500 error which throws an Exception. What cases would benefit from this?

Telescope does not persist entries in the following cases:

- `exit` (or `die`) is called
- A fatal uncatchable error occurs (e.g., memory exhausted)

In these scenarios (and possibly some others), the `terminating` event is not fired and therefore Telescope does not persist entries (Telescope hooks into that event).

Even with a shutdown function, there would still be some cases where Telescope would not get a chance to run (this is not a complete list):

- `exit` (or `die`) is called in in an earlier shutdown function
- An uncaught error occurs in an earlier shutdown function
- The process is killed

**Comment by barryvdh** [comment]
Yes sure, but there is no good reason that your code would call `die()` or `exit()`, is there? In the case of memory exhaustion/killing the process, would it still be possible to persist the entries at all?

**Comment by benignant** [comment]
The first list enumerates scenarios where a shutdown function would allow the entries to be stored and the second list enumerates scenarios where the shutdown function solution would not help.

Laravel uses `die` and `exit` when dealing with queues and for debugging with `dd()`.

**Comment by barryvdh** [comment]
Yeah the 1 thing I encounter with this, is that `dd()` doesn't work.  `dd()` captures the output but still dies, so you just get a blank screen.
Not sure what the best way to handle this is, maybe we could detect if `dd()` is called instead of `dump()`?

**Comment by barryvdh** [comment]
Here is an example that would just echo the `dumps` when the application terminated incorrectly, eg. with `dd()`

```php
        // When we die without storing the entries, show the dumps (eg. for `dd()`)
        register_shutdown_function(function() {
            foreach (Telescope::$entriesQueue as $entry) {
                if ($entry instanceof IncomingDumpEntry) {
                    echo $entry->content['dump'];
                }
            }
        });
```

**Comment by benignant** [comment]
In what case does `dd()` not work?

**Comment by barryvdh** [comment]
In case you're watching for dumps (eg dump screen open). Then it's just an empty screen with nothing registered.

**Comment by benignant** [comment]
If I understand correctly, the case you're referring to is the one I opened this issue about. If so, how does the shutdown function you posted help? The issue is that Telescope is not persisting the dump entry, not that `dd()` isn't working. It seems like the code you posted would just duplicate what was already output by `dd()`. What I was proposing was adding something like the following to [`ListensForStorageOpportunities`](https://github.com/laravel/telescope/blob/f17782db5ea36dd45074d9e53c72096249a88a19/src/ListensForStorageOpportunities.php):

```php
register_shutdown_function(function () use ($app) {
    static::store($app[EntriesRepository::class]);
});
```

**Comment by barryvdh** [comment]
Yeah it still doesn't persist, but the dump watcher swallows the output from the dumps, so dd() will just empty otherwise.
If you want to store the entries you can store them indeed, but still, it should be unusual for normal applications and not sure if this is abusing the shutdown or appropriate.

**Comment by benignant** [comment]
Oh, I see what you mean now. I didn't realize the dump watcher prevents dumps from displaying. I think a shutdown function would make Telescope more useful. Not just for `dd()` but also for other cases. I've found Telescope to be fairly unreliable and I think improper application termination is the cause. Another option would be to have a setting for development environments which would make Telescope store entries as soon as they are recorded. This would have a performance penalty, but I think it might be worth it for development environments where debugging with Telescope is more common.

**Comment by barryvdh** [comment]
That could work but there are some issues with that that need to be resolved then. For example, no queries can be run during the query listener and the batch ID needs to be maintained to keep relationships.

**Comment by benignant** [comment]
What do you mean by "no queries can be run during the query listener"? As for the batch ID, it seems like having a different batch ID each time entries are stored was by design, so we'd have to find out how the maintainers want it to work.

It seems like the shutdown function would be simpler (and more performant).

**Comment by barryvdh** [comment]
I mean because of this: https://github.com/laravel/telescope/issues/289

**Comment by benignant** [comment]
We can pick and choose which entry types to store immediately.

**Comment by barryvdh** [comment]
A work around for `dd()` is to not die, but to throw an HttpResponse:

```php
if (!function_exists('ddd')) {
    function ddd(...$vars)
    {
        foreach ($vars as $v) {
            VarDumper::dump($v);
        }

        $response = new \Illuminate\Http\Response('', 500);

        throw new \Illuminate\Http\Exceptions\HttpResponseException($response);
    }
}
```
