### ISSUE TITLE
Importing Telescope makes every route fail apart from /telescope

### ISSUE THREAD

**Issue by kevinc-cogapp** [laravel/telescope#599]
- Telescope Version: 2.0.2
- Laravel Version: 5.8.7
- PHP Version: 7.3.3
- Database Driver & Version:

### Description:
Importing Telescope into my project, made all of my routes get a HTTP Error 500 from the browser. The telescope endpoint is accessible but not other route in the project is working.

Running laravel valet 2.0.24 on a Linux box.

### Steps To Reproduce:
-  `laravel new <project>`
- `composer require laravel/telescope`
- `php artisan telescope:install`
- Navigate to `project.test` -> 500 error
- Navigate to `project.test/telescope` -> it works.

Am I missing something? Thanks for all your work with this.

**Comment by themsaid** [comment]
You'll need to debug more as it seems like something is wrong with your application. Check the details of the exception being thrown and you'll be able to understand what's wrong.

**Comment by HRW5** [comment]
I also had the same thing happen!

- Telescope Version: 2.0.*
- Laravel Version: 5.8.*
- PHP Version: 7.3.*
- Docker Image: php:7.3-apache

After tailing /var/log/apache2/error.log it appeared that I was missing the PHP bcmath extension.

Once the extension was installed, everything worked!

**Comment by sanderlissenburg** [comment]
Thnx @HRW5, solved the problem for me.
