### ISSUE TITLE
Wrong cache TTL description after Laravel 5.8 changes

### ISSUE THREAD

**Issue by ibrunotome** [laravel/telescope#600]
- Telescope Version: 2.0.2
- Laravel Version: 5.8.8
- PHP Version: 7.2.16
- Database Driver & Version: PostgreSQL 10.6

### Description:

If I set a cache this way: `Cache::remember($cacheKey, 15, function ()` after Laravel v5.8, I spect that the TTL is using seconds instead of minutes, but in telescope this is displaying in minutes.

<img width="452" alt="Screen Shot 2019-03-27 at 10 56 40" src="https://user-images.githubusercontent.com/4256471/55081647-02d39480-507f-11e9-8215-5f6a180b8ef8.png">

### Steps To Reproduce:

Set a cache in laravel, look for the expiration in the cache section in telescope.

**Comment by themsaid** [comment]
Make sure you are using the latest package assets.

**Comment by ibrunotome** [comment]
@themsaid I installed telescope today, version v2.0.2 so the package assets are the most recent possible. Do you even tried to make the steps to reproduce?

**Comment by themsaid** [comment]
I've just released v2.0.3 with new compiled assets, please pull it and check.

**Comment by ibrunotome** [comment]
It worked, thanks.

**Comment by ibrunotome** [comment]
@themsaid this latest version breaks almost all my tests:

`[2019-03-27 21:16:43] testing.ERROR: Undefined property: Illuminate\Cache\Events\KeyWritten::$minutes {"exception":"[object] (ErrorException(code: 0): Undefined property: Illuminate\\Cache\\Events\\KeyWritten::$minutes at /app/vendor/laravel/telescope/src/Watchers/CacheWatcher.php:83)
`

It could be resolved adding a coalesce `?? null` to the CacheWatcher, method recordKeyWritten.
