### ISSUE TITLE
Undefined property: Illuminate\Cache\Events\KeyWritten::$minutes

### ISSUE THREAD

**Issue by RicardoRamirezR** [laravel/telescope#601]
- Telescope Version: v2.0.3
- Laravel Version: v5.8.8
- PHP Version: 7.3.3
- Database Driver & Version: MariaDB 10.3.8

### Description:

After a `composer update` I got this message randomly

### Steps To Reproduce:

No clue, sorry
![Captura de pantalla 2019-03-27 a la(s) 9 48 28 p  m](https://user-images.githubusercontent.com/6526545/55126330-b8800100-50da-11e9-9bf3-f318ccf865ee.png)

Locaion: `laravel/telescope/src/Watchers/CacheWatcher.php:83`
```php
79         Telescope::recordCache(IncomingEntry::make([
80             'type' => 'set',
81             'key' => $event->key,
82             'value' => $event->value,
83             'expiration' => $event->seconds ?? $event->minutes,
84         ]));
85     }
```

produced by `cache()->forever($cacheKey, $current_alert)` on my code

Last 4 lines of the Stacktrace:
/var/www/noah.club/releases/728/vendor/sentry/sentry/src/ErrorHandler.php:194
/var/www/noah.club/releases/728/vendor/laravel/telescope/src/Watchers/CacheWatcher.php:83
/var/www/noah.club/releases/728/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:347
/var/www/noah.club/releases/728/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:196

**Comment by themsaid** [comment]
v2.0.4 was released with a fix.
