### ISSUE TITLE
Connection refused from remote Redis server (Homestead v8.2.0)

### ISSUE THREAD

**Issue by ralphmoran** [laravel/telescope#606]
Hi, 

A few minutes ago I installed Telescope on Homestead v8.2.0 and this is the error that I'm encountering. 

Everything else is working and I can execute `pa` commands if I connect toward my VM via SSH but when it comes to using `pa` (php artisan) commands from my host, this is what I get. I know that this is Redis and doesn't let me have an external connection but it was working with no issues before Telescope installation.

Now, if I go back on my Git history to the last stable version, I'm still getting this issue.

Any idea?

<img width="664" alt="Screen Shot 2019-04-02 at 11 20 09 AM" src="https://user-images.githubusercontent.com/5456155/55428234-84bf3400-553d-11e9-8147-4c15b155f5b5.png">

**Comment by gcshri** [comment]
Quite new to telescope - so this might be invalid or wrong info.

Bypassed this problem on a local install by changing the CACHE_DRIVER value in the .env to "file"

**Comment by danilopolani** [comment]
Can you post your Homestead configuration (`Homestead.yaml`)? Also, try to access to Redis with `redis-cli -h 192.168.10.10` from your terminal, if this doesn't work maybe Redis is not running on Homestead.

**Comment by Kovbo** [comment]
I believe it is not a telescope issue. Actually, this is how Homestead works. Homestead runs inside a virtual machine (vagrant). Redis runs inside this virtual machine. And you cannot connect to vagrant machine via terminal.

The same rule applies to databases without Redis. You cannot use standard port 3306 and run commands like `php artisan migrate` through IDE terminal. You have to either use 33060 port, or connect via ssh into vagrant.
