### ISSUE TITLE
Redis pipeline commands doesn't show in redis tab

### ISSUE THREAD

**Issue by mhndev** [laravel/telescope#607]
- Telescope Version: 1.1
- Laravel Version: 5.8.9
- PHP Version: 7.3.3

when you use Redis Pipeline, In telescope redis tab , you can't find queries.

**Comment by driesvints** [comment]
Is this issue also present on Telescope 2.x?

**Comment by themsaid** [comment]
pipeline and transaction commands are ignored since we have no way of knowing the underlaying commands that run inside the pipeline or transaction. Please feel free to open a PR if you find a way.
