### ISSUE TITLE
Multidomain issue

### ISSUE THREAD

**Issue by hardikdangar** [laravel/telescope#609]
- Telescope Version: 1.2
- Laravel Version: 5.7
- PHP Version: 7.1
- Database Driver & Version: mariadb 10.3

### Description:
I have two laravel instances and both use same database. for example a.com and b.com both are running same version of laravel with same database. I installed telescope in both instances but it only shows entries of 1 instance ( the one which installs first). I could not find anything in Database related to this. is it bug? Or thats how it supposed to work ?

### Steps To Reproduce:
install telescope in two seperate laravel installations with same db. it will only show one instance entries.

**Comment by taylorotwell** [comment]
I don't think that's going to work. They need separate databases.

**Comment by deleugpn** [comment]
I run Telescope on multiple Laravel microservices and it works fine. The microservices themselves don't share database, but we have a `monitoring` database exclusively for Telescope which is configured in all applications.
