### ISSUE TITLE
Dump is not working

### ISSUE THREAD

**Issue by eleftrik** [laravel/telescope#611]
- Telescope Version: 2.0.4
- Laravel Version: 5.8.9
- PHP Version: 7.2.16

### Description:

`dump()` is not working. I'm not seeing anything in the dump section in Telescope.

### Steps To Reproduce:

See https://github.com/laravel/telescope/issues/487#issuecomment-479425001

Commenting the return statement in the DumpWatcher class seems to do the trick, but it's only a work-around.

Thank you

**Comment by danilopolani** [comment]
What if you try to increment this value to like `60`? https://github.com/laravel/telescope/blob/2.0/src/Http/Controllers/DumpController.php#L40

(I don't know what's about that, I think a delayer (?), but I don't know why only Dump has it)

**Comment by eleftrik** [comment]
@danilopolani Thanks for your suggestion.
I tried to increment the value as suggested by you, but it doesn't work.

But when I changed `CACHE_DRIVER` from `array` to `file`, dumps started working!
Am I missing anything important?
I didn't read anywhere in the Telescope documentation that cache can't be set to `array`. Moreover, `array` is the default value and Telescope is meant to be used in develop environment only.

**Comment by fgilio** [comment]
I have this problem too and it also starts working when I comment out this lines https://github.com/laravel/telescope/blob/2.0/src/Watchers/DumpWatcher.php#L43-L45
Anything else I can try?

**Comment by Pezhvak** [comment]
here's a quick question (So i don't open another issue).

dump is working fine when i have a return on my controller. but if i use dd() nothing shows up. anybody having the same issue? am i missing something? btw (artisan dump-server) works fine.

** ps: i'm not using them both at once

**Comment by barryvdh** [comment]
Dump checks if a cache entry exists. This is set by the DumpWatcher, for 4 seconds (and it refreshes as long as the page is open). If you set your cache driver to 'array', it will not be persisted so will never be logged.

**Comment by eleftrik** [comment]
> Dump checks if a cache entry exists. This is set by the DumpWatcher, for 4 seconds (and it refreshes as long as the page is open). If you set your cache driver to 'array', it will not be persisted so will never be logged.

@barryvdh I understand your point, but when in `develop` who's using a value different than `array`?

**Comment by fgilio** [comment]
Hmm this is weird, I almost never use array as a cache driver as I always want to have an environment as close to production as possible. But will pay attention to it in the future.
I guess this should be added to the Telescope docs.

**Comment by barryvdh** [comment]
So two things would make this easier:
 1. Show an error when the Array driver is used, to show that Dump cannot be used like this.
 2. Specify a cache driver in the Telescope config (with fallback to the default cache), so you can use `file` for Telescope, but still work with `array` in the rest of your files.

For now I've created a PR to mention this: https://github.com/laravel/docs/pull/5365

**Comment by barryvdh** [comment]
Also added a PR to show an error on the Dump screen: https://github.com/laravel/telescope/pull/683

**Comment by fgilio** [comment]
Thank you very much Barry!
