### ISSUE TITLE
Telescope Migration Comes With A Wrong Timestamp

### ISSUE THREAD

**Issue by winni4eva** [laravel/telescope#616]
- Telescope Version: ^2.0
- Laravel Version: 5.8.*
- PHP Version: 7.2.15
- Database Driver & Version: mysql 5.7.25

### Description:
Telescope migrations comes with a fixed timestamp not the current timestamp

### Steps To Reproduce:
1. run command : php artisan vendor:publish --tag=telescope-migrations
2. you should get a migration with file name 2018_08_08_100000_create_telescope_entries_table.php

**Comment by rs-sliske** [comment]
this is pretty standard for package migrations

**Comment by winni4eva** [comment]
> this is pretty standard for package migrations

I am yet to create a laravel package that requires migrations, I guess I will take your word for it but it looks weird at first. Thanks
