### ISSUE TITLE
Blank Page In Telescope with custom env

### ISSUE THREAD

**Issue by jcfariadias** [laravel/telescope#617]
- Telescope Version: 1.2
- Laravel Version: 5.7.28
- PHP Version: 7.1.2
- Database Driver & Version: MySQL 5.7

### Description:
Unfortunately, that's all I can say. Just an empty page, with no console or request errors.

![Captura de ecrã 2019-04-22, às 17 35 30](https://user-images.githubusercontent.com/2012680/56511873-9fc20a00-6525-11e9-9716-f9688f43e008.png)

Did read every related issue here, published assets, cleared caches and composer autoloader.

DB is effectively has entries in telescope_entries table

![Captura de ecrã 2019-04-22, às 17 38 13](https://user-images.githubusercontent.com/2012680/56511897-b8322480-6525-11e9-810c-3c4dc46e8fcb.png)

### Steps To Reproduce:

Did everything by Laravel's documentation

I'm getting out of ideas. Could you please help ?

**Comment by filipedtristao** [comment]
In which url are you running the project? Because it only works when run direct from the server root.

https://github.com/laravel/telescope/issues/142

**Comment by jcfariadias** [comment]
@filipedtristao it's running on server root. 
Something like - www.example.com/telescope

**Comment by filipedtristao** [comment]
@jcfariadias And laravel.log, did it generate any errors when you access the page?

**Comment by lvitali** [comment]
@jcfariadias I had a similar issue and the problem was the laravel-page-speed package config. Adding 'telescope/*' in the skip section solved the problem for me. Do you have this package installed?

**Comment by jcfariadias** [comment]
> @jcfariadias I had a similar issue and the problem was the laravel-page-speed package config. Adding 'telescope/*' in the skip section solved the problem for me. Do you have this package installed?

That was it! Thank you very much.

I guess this is a problem with that package, but should be mentioned so if anybody has this kind of problem again
