### ISSUE TITLE
Display Slashes in Path

### ISSUE THREAD

**Issue by riyuk** [laravel/telescope#619]
- Telescope Version: 2.0.4
- Laravel Version: 5.8.13
- PHP Version: 7.2.11

### Description:
Can we display the Slashes properly in the view?

### Steps To Reproduce:
![telescope](https://user-images.githubusercontent.com/101386/56752323-47d70d80-6788-11e9-9617-90aa78cec881.png)

**Comment by danilopolani** [comment]
Imho this is the correct behaviour, I mean `foo` and `test` in the **Path** are URL encoded because they are query string params, but then in the **Payload** you can see them as data. Maybe it would be nice an icon to see the Path decoded, but still...

**Comment by riyuk** [comment]
Well. Yes ... and no. In the Overview it also get's displayed encoded, which is kinda hard to read if you got some path's in there.

**Comment by sudip-das** [comment]
In the example, /api/foo is showing the slashes. So, the desired behavior should be /api/foo?bar=baz/foo....

**Comment by themsaid** [comment]
No plans to change this, that's URL query and we display it as is. If you want a more tidy preview you'll need to check the Payload section.
