### ISSUE TITLE
Keeps scanning

### ISSUE THREAD

**Issue by striderxfossility** [laravel/telescope#621]
- Telescope Version: "laravel/telescope": "^2.0"
- Laravel Version: "laravel/framework": "5.8.*",
- PHP Version: Remote: 7.2.17 , local: 7.2.11
- Database Driver & Version: Remote: mysql v. 5.5.62, local: sqlite

### Description:

I am having this problem that the scanning keeps running, on localhost it works fine, but on my actual website it keeps scanning with the js error

Uncaught (in promise) Error: Request failed with status code 500
at LYNF.p.exports (app.js?id=)
at Rn+g.p.exports (app.js?id=)
at XMLHttpRequest.A.(anonymous function) (https://www.***/vendor/telescope/app.js?id=***)

**Comment by danilopolani** [comment]
Could you take a look to Laravel error logs? You can find them in `storage/logs/`, there should be a 500 error somewhere

**Comment by striderxfossility** [comment]
Here is the error, (installed sentry yesterday)

https://sentry.io/share/issue/3e045f621ea14b2a97a31e0b505e5a7c/

**Comment by danilopolani** [comment]
That's weird, because it can't find this file: https://github.com/laravel/telescope/blob/2.0/src/Storage/EntryQueryOptions.php

Can you try to run `composer update laravel/telescope` on your production website? It seems it didn't downloaded all the files

**Comment by striderxfossility** [comment]
I did the update, now it gives the following error

https://sentry.io/share/issue/24a65866cdc1405b84e78d82f4a6fb77/

**Comment by danilopolani** [comment]
Mmhh, could you manually check if the file `vendor/laravel/telescope/src/Storage/EntryQueryOptions.php` exists? If it does, can you try to run `composer dump-autoload` from `vendor/laravel/telescope` folder? This is not a recommended operation, you should never do this, but I don't have any other idea

**Comment by striderxfossility** [comment]
The EntryQueryOptions.php didn't exists.

well, thats indeed wierd, the issue is fixed, i copied the whole map from local to remote, now it works (didn't do dump-autoload)

**Comment by danilopolani** [comment]
That's still weird, but I think it's something related to "your" composer and not to Laravel itself. Glad it's solved!

**Comment by rupeszh** [comment]
Solution to the problem for me is adding telescope in VerifyCsrfToken middleware.i:e
protected $except = [
        'telescope/*'
    ];

**Comment by sternenvogel** [comment]
For me, the **telescope tables were missing** in the database. 
Just running `php artisan migrate` solved the problem.
