### ISSUE TITLE
Redis events cannot be enabled when using Redis as cache driver

### ISSUE THREAD

**Issue by jarnovanleeuwen** [laravel/telescope#622]
- Telescope Version: 2.0.4
- Laravel Version: 5.8.15
- PHP Version: 7.2.15
- Database Driver & Version: Redis 5

### Description:
The documentation suggests adding `Redis::enableEvents()` to the `boot` method of `AppServiceProvider` to enable collecting Redis events. However, at least when using auto-discovery, `TelescopeServiceProvider` is booted earlier than `AppServiceProvider` and invokes the cache at least when registering the `DumpWatcher` (see https://github.com/laravel/telescope/issues/620). Now, when Redis is used as cache driver the Redis connection will be resolved at this point already and will get configured without events.

Possibly related issues: https://github.com/laravel/telescope/issues/607, https://github.com/laravel/telescope/issues/585, https://github.com/laravel/telescope/issues/355

### Steps To Reproduce:
- Install Telescope using auto discovery.
- Set `CACHE_DRIVER` to `redis`
- Enable events using `Redis::enableEvents()`
- Run `Cache::put('foo', 'bar', 300);`
- The Redis page in Telescope remains empty.

### Workaround:
Replace `Redis::enableEvents()` with:

```php
// For previously resolved connections.
foreach ((array) Redis::connections() as $connection) {
    $connection->setEventDispatcher($this->app->make('events'));
}

// For new connections.
Redis::enableEvents();
```

**Comment by fgilio** [comment]
I'm too experiencing this issue and the workaround worked fine, thanks @jarnovanleeuwen

**Comment by taylorotwell** [comment]
I was able to recreate this bug and confirm it.

**Comment by azaricstefan** [comment]
Just to confirm, Workaround helped in my case too.

**Comment by themsaid** [comment]
fixed in https://github.com/laravel/telescope/pull/789
