### ISSUE TITLE
App url Mismatch

### ISSUE THREAD

**Issue by ManojKiranA** [laravel/telescope#624]
- Telescope Version: 2.0.4
- Laravel Version: 5.8.14
- PHP Version: 7.1.28
- Database Driver & Version: 10.1.39-MariaDB - MariaDB Server

### Description:

I have moved  my app to the application to the Seperate directory

For Example 

`mydomain.com/myapp`

So all the application files will be in `myapp`

Now while accessing 

`mydomain.com/myapp/telescope` is working fine

But if i have clicked some menus such as commands 

its directing me to `mydomain.com/telescope/commands`

i have Changed  the APP_URL=mydomain.com/myapp

But its still the same

**Comment by drekinov** [comment]
They stated multiple times that they dont run laravel in sub folders.

That is why symfony with symfony profiler is still better.
It works next to symfony not only if symfony is top level project.

Sorry i am really mad that kind of decisions are ruled by couple people and are pass to community as law similar to dictatorships over the world. If it is possible to run laravel in sub folder then all of it supported components should fit that.
If you dont support that then make laravel framework and lumen to throw exceptions if run in subfolder that subfolder projects are not support. That should a big enough noise to revert that decision or switch framework.

**Comment by ManojKiranA** [comment]
but rest of the application is running perfectly @drekinov

**Comment by themsaid** [comment]
Not supported I'm afraid.
