### ISSUE TITLE
Anyway to show IP address in Request details?

### ISSUE THREAD

**Issue by Ir00man** [laravel/telescope#629]
Now we don't have such an information like IP address on Request Details card.
In some cases it's useful to know from where request was made.
Hope it will be easy to implement. Thx.

**Comment by themsaid** [comment]
Feel free to open a PR. Thanks!

**Comment by vedmant** [comment]
Yeah, would be really helpful.

**Comment by JonathanPort** [comment]
Any idea on how you would do this @themsaid ?  I'd like to do this but don't know where to start. I'm assuming it's pulling in the default Laravel request object but how would you extend this?

**Comment by Ir00man** [comment]
@JonathanPort I think you should look at similar PR https://github.com/laravel/telescope/pull/312/files
