### ISSUE TITLE
Not satisfied by log viewer

### ISSUE THREAD

**Issue by sadhakbj** [laravel/telescope#631]
I have been a great fan of Laravel Log viewer (https://github.com/rap2hpoutre/laravel-log-viewer), by the release of Telescope I abandoned laravel log viewer in my new project and thought to implement Laravel telescope to manage viewing the logs.

I basically log the exceptions:
``` 
 try {
         //code
        } catch (\Exception $exception) {
            logger()->error($exception);
            //code
        }
``` 
I get the following output in telescope:

![image](https://user-images.githubusercontent.com/5828622/57843052-56e03700-77ed-11e9-97c7-6a51e048bd6e.png)

Laravel log viewer behaves in a different way than the Telescope behaves. Can we expect some improvements ?

**Comment by themsaid** [comment]
You can open a PR with your suggestion. thanks
