### ISSUE TITLE
Not picking up artisan daemon database queries?

### ISSUE THREAD

**Issue by Vimiso** [laravel/telescope#632]
- Telescope Version: ^2.0
- Laravel Version: 5.8.*
- PHP Version: 7.2.12
- Database Driver & Version: 8.0.13

If I run a custom artisan command, that loops indefinitely, Telescope does not log any of its database queries. It will, however, detect exceptions, but not `Log::info()`.

After having a quick look through the code, I can see that the command needs to return with a exit code, in order for stuff to happen - yet exceptions are still picked up?

Was I wrong to think Telescope can detect things everywhere, and in any scenario? Or just for simple page requests... which all work.

Thanks!

**Comment by themsaid** [comment]
You'll need to manually run `Telescope::store()` so that Telescope can store what's in memory.
