### ISSUE TITLE
Filtering tables and tags, unclear as to how they work.

### ISSUE THREAD

**Issue by Vimiso** [laravel/telescope#633]
There's not much information on how tags work. Every time I try and search something, I get no results.

My intuition is to just search for keywords, within columns, for each table. i.e. in requests, search 200 for status code.

Any guidance here?

**Comment by themsaid** [comment]
You can filter results by tags, but if the item isn't tagged with the tage you want then no results will appear.

Make sure you check what tags are available or add your own using `Telescope::tags`
