### ISSUE TITLE
Installing telescope breaks horizon

### ISSUE THREAD

**Issue by michaeljhopkins** [laravel/telescope#635]
- Telescope Version: 2.0.4
- Laravel Version: 5.8.5
- PHP Version: 7.2
- Database Driver & Version: Mysql 5.7.26

### Description:

Installing telescope causes the horizon dashboard to be inaccessible due to a new 403 page/view being displayed

### Steps To Reproduce:

I currently have horizon installed and running in a project. It is accessed at `/horizon`. Horizon is protected via the following code in `HorizonServiceProvider` 

```
public function boot() {
    Horizon::auth(function ($request) {
        return Auth::check();
    }
}
```

Installing Telescope causes this page to return a 403 forbidden page (The view looks to be rendered with a new telescope view). Going to `/telescope` does work and the rest of the telescope package also works as expected. "Horizon" as a queue running, also continues to work. It is the GUI that does not work

**Comment by themsaid** [comment]
I have Telescope and Horizon both installed and working fine, you'll need to debug that in your project.

**Comment by leo-unglaub** [comment]
@michaeljhopkins I have the exact same issue you are describing above. Did you come up with a solution for it?
