### ISSUE TITLE
Unable to remove laravel/telescope

### ISSUE THREAD

**Issue by Ruitjes** [laravel/telescope#639]
- Telescope Version: 2.0.4
- Laravel Version: 5.8.18
- PHP Version: 7.2.11

### Description:
I'm unable to remove Telescope.
I've tried already multiply methods which I found on stackoverflow and github.
But no matter what I do I keep getting an error.

### Steps To Reproduce:
`composer remove  laravel/telescope`

Error:
![image](https://user-images.githubusercontent.com/26769441/58475913-909b3100-814f-11e9-9f3b-aabdc1771fa2.png)

**Comment by rogerad** [comment]
i just did it 5 minutes ago 
comment this line first   
//  App\Providers\TelescopeServiceProvider::class,
     then it removes perfectly

**Comment by themsaid** [comment]
The exception you see explains the issue, remove `TelescopeServiceProvider`.

**Comment by Ruitjes** [comment]
Already tried it , but for some reason it still wasn't working.
I just got back to an older commit where I never installed telescope.
