### ISSUE TITLE
Requests is empty and keeps firing XHR request

### ISSUE THREAD

**Issue by jason-migz** [laravel/telescope#640]
- Telescope Version: ^2.0
- Laravel Version: 5.8
- PHP Version: 7.2
- Database Driver & Version: mysql 8.0

### Description:
I use laravel telescope on laravel fresh install and i am using docker for development i have image: "webdevops/php-apache-dev:7.2" and "mysql", when i tried to access laravel telescope no request is shown.

### Steps To Reproduce:
1.) install fresh laravel 5.8 and run factory('App\User') in tinker for seeding data
2.) composer require laravel/telescope,run php artisan telescope:install,php artisan migrate,php artisan telescope:publish
3.) go to terminal project directory, run `sudo docker ps`
4.) get the container id of apache container
5.) run `sudo docker inspect {docker container id}`
6.) get the ip_address of the container
7.) run `sudo docker exec -it {docker container id}`
8.) cd into var/www/htdocs(this is where my laravel project lives inside docker container)
9.) run `php artisan serve --host={ip_address of apache container}`
10.) go to browser hit url http://{ip_address of apache container}:{port in artisan serve}
11.) login user and refresh page
12.) open another tab for laravel telescope http://{ip_address of apache container}:{port in artisan serve}/telescope
13.) no request shown, and if i check into console no error detected and in network xhr request keeps firing even i am not reloading the page with this Request URL: http://172.21.0.3:8002/telescope/telescope-api/requests?tag=&take=1&family_hash=

### network Tab in Browser
![Screenshot from 2019-05-29 10-00-13](https://user-images.githubusercontent.com/21366028/58536986-7f702400-8224-11e9-9535-72e7603f1ca5.png)
### Terminal inside Docker apache image
![Screenshot from 2019-05-29 10-00-56](https://user-images.githubusercontent.com/21366028/58536990-8008ba80-8224-11e9-8b31-c99e4034bf44.png)
### docker-compose.yml
![Screenshot from 2019-05-29 15-17-45](https://user-images.githubusercontent.com/21366028/58537256-1e951b80-8225-11e9-99d9-67ffdcbf6df2.png)

**Comment by themsaid** [comment]
This doesn't seem to be an issue with Telescope itself, check your environment.
