### ISSUE TITLE
Call to undefined method Laravel\Telescope\Telescope::tags()

### ISSUE THREAD

**Issue by olivM** [laravel/telescope#645]
- Telescope Version: 2.0.4
- Laravel Version: 5.8.19
- PHP Version: 7.3.8
- Database Driver & Version: mysql

### Description:

error when trying to add tags

`Call to undefined method Laravel\Telescope\Telescope::tags()`

### Steps To Reproduce:

laravel new test
cd test
composer require laravel/telescope
php artisan telescope:install
php artisan migrate

add to register() in TelescopeServiceProvider.php

`       Telescope::tags(function (IncomingEntry $entry) {
            if ($entry->type === 'request') {
                return ['status:'.$entry->content['response_status']];
            }
            return [];
        });`

go to /telescope/requests

**Comment by themsaid** [comment]
It's `Telescope::tag()`

**Comment by olivM** [comment]
ok thanks for having the doc fixed :)
