### ISSUE TITLE
How to correctly use with envoyer?

### ISSUE THREAD

**Issue by amacsmith** [laravel/telescope#654]
Hello,

First off, this has been a really cool tool to use!

I have deployed it locally and it works great. I am wanting to use this in our non-local environments. So I have updated the gate function to allow specific user emails to access the telescope route. However, when I deployed to our dev server environments utilizing envoyer. I keep seeing that nothing appears in any of the categories except exceptions. 

The error I see seems to be related to debugbar by barry and in our non-local environments this is just a dev requirement in our composer.json files. 

Here is the example of the error:

![image](https://user-images.githubusercontent.com/25642759/60053189-3d13f880-96a5-11e9-9112-ef8478f98606.png)

I am not sure why the injectDebugbar middleware is being used because it is only dev requirement and why is it causing this issue. Basically, no matter what route a user goes to it is reported back in that way. Here is the error message tied to that stack trace.

![image](https://user-images.githubusercontent.com/25642759/60053282-751b3b80-96a5-11e9-906d-fd8bf0e2683c.png)

Thank you in advance for any help or reason as to why this is happening. 

Cheers!

**Comment by amacsmith** [comment]
I have managed to get the other categories filling with info but only when I change to APP_ENV to local. However I am still repeatedly seeing this error.

**Comment by taylorotwell** [comment]
See the Telescope::filter callback in your service provider.
