### ISSUE TITLE
[Feature request] Telescope pause/resume artisan command

### ISSUE THREAD

**Issue by rmundel** [laravel/telescope#655]
Hi!

I was thinking that maybe some artisan commands to reflect the pause/resume feature from the Web UI could be useful.
I just encountered a situation where it would be nice to have the ability to pause telecope != business hours and resume otherwise.
Maybe:
php artisan telescope:pause or stop
php artisan telescope:resume or start

Thanks!

**Comment by ManojKiranA** [comment]
looking pretty good to me

**Comment by taylorotwell** [comment]
This is not a bug report so I am closing for now.
