### ISSUE TITLE
Wrong job status and datas

### ISSUE THREAD

**Issue by L3o-pold** [laravel/telescope#66]
This job was not pending but is done and datas should be more detailed.

<img width="1030" alt="screen" src="https://user-images.githubusercontent.com/4710495/47388078-8c1e1e00-d711-11e8-85b0-75d58bc98e8d.png">

**Comment by themsaid** [comment]
issue is not clear, you'll need to dig into it and present more information.

**Comment by okaufmann** [comment]
> This job was not pending but is done
I think he means that the Job was queue and completed successfully. But the Status field does not get updated. 

I have noticed this behavior as well but can't not provide more information as I am still looking into this 🤷

**Comment by themsaid** [comment]
can't seem to replicate :|

**Comment by L3o-pold** [comment]
@themsaid Restart the worker seems to solve the issue

**Comment by marianvlad** [comment]
@L3o-pold use `artisan horizon:terminate` if you use Horizon

**Comment by digitalbridge** [comment]
Terminate horizon doesn't fix the issue, my job status is always showing "pending". 

It seems the issue is related to supervisor? If I manually run **php artisan queue:work**, it's working.
