### ISSUE TITLE
Controller action string formatting

### ISSUE THREAD

**Issue by diogogomeswww** [laravel/telescope#660]
![image](https://user-images.githubusercontent.com/11543163/60396126-67e2ce80-9b35-11e9-8110-deac3f69f3de.png)

Right now the Controller action string is formatted as:

`Class@method`

And my suggestion is that it would be formatted as:

`Class::method`

It could be a configurable option: `class_method_separator`

The reason is to to make it quicker finding that action on my IDE (I'm using PHPStorm).
`Class@method` won't work but `Class::method` works.

I can make a PR for it but please let me know what you think of it first.

**Comment by Lelectrolux** [comment]
I'm 99% sure the `Class@method` works in sublime text (and I think Atom too) which is what a good deal of the laravel maintainers use primarily.

Currently it also "matches" the default way to do routing.

While I don't care about both of those reasons (I'm using mostly PHPStorm like you, and like to use the `[Controller::class, 'index']` format in my routes), I'd say it still is a more reasonable default than the `::`

**Comment by diogogomeswww** [comment]
I'm going to proposed to the Laravel plugin for PHPStorm to enable finding the methods with the Class@method formatting, since this is the standard in Laravel everywhere.
