### ISSUE TITLE
Telescope still records Query even the QueryWatcher is set to disabled

### ISSUE THREAD

**Issue by michaelnguyen547** [laravel/telescope#669]
- Telescope Version: 2.0.5
- Laravel Version: 5.8.28
- PHP Version: 7.2
- Database Driver & Version: mysql 5.7

### Description:
I set the QueryWatcher enabled to false, but Telescope is still recording `query` type records. There is no `TELESCOPE_QUERY_WATCHER` value in .env

```
<?php

use Laravel\Telescope\Watchers;
use Laravel\Telescope\Http\Middleware\Authorize;

return [
    'path' => 'telescope',

'watchers' => [
// more watcher settings here....
        Watchers\QueryWatcher::class => [
            'enabled' => env('TELESCOPE_QUERY_WATCHER', false),
            'slow' => 100,
        ],

    ],
```
### Steps To Reproduce:

Install telescope, and set QueryWatcher default to false

**Comment by taylorotwell** [comment]
Can't recreate. Doesn't record query and it is noted as being turned off:

<img width="992" alt="image" src="https://user-images.githubusercontent.com/463230/70353483-14d31d00-1833-11ea-8494-de0b52aae3cc.png">

**Comment by samfrjn11** [comment]
Did you find a way to fix this?
I'm having the same behaviour...
Telescope@4.6
Laravel@8.12

![image](https://user-images.githubusercontent.com/13766544/135079772-3a82d1dd-f4de-4488-9028-e568c280f949.png)
