### ISSUE TITLE
Custom UserProvider fails to be registered/found on php artisan config:cache

### ISSUE THREAD

**Issue by turbo124** [laravel/telescope#67]
Adding telescope to an existing project where I have a CustomUserProvider which is registered in my AuthServiceProvider.

When I hit php artisan config:cache I get the following:

$php artisan config:cache
Configuration cache cleared!

In CreatesUserProviders.php line 42:
                                                        
  Authentication user provider [users] is not defined.

**Comment by turbo124** [comment]
In AuthServiceProvider I have:

    public function boot()
    {

        Auth::provider('users', function ($app, array $config) {
            return new MultiDatabaseUserProvider($app['hash'], $config['model']);
        });

    }


Stacktrace of artisan command

php artisan config:cache


[stacktrace]
#0 vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php(121): Illuminate\\Auth\\AuthManager->createUserProvider('users')
#1 vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php(94): Illuminate\\Auth\\AuthManager->createSessionDriver('user', Array)
#2 vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php(68): Illuminate\\Auth\\AuthManager->resolve('user')
#3 vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php(292): Illuminate\\Auth\\AuthManager->guard()
#4 vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(223): Illuminate\\Auth\\AuthManager->__call('hasUser', Array)
#5 vendor/laravel/telescope/src/Telescope.php(199): Illuminate\\Support\\Facades\\Facade::__callStatic('hasUser', Array)
#6 vendor/laravel/telescope/src/Telescope.php(275): Laravel\\Telescope\\Telescope::record('exception', Object(Laravel\\Telescope\\IncomingExceptionEntry))
#7 vendor/laravel/telescope/src/Watchers/ExceptionWatcher.php(46): Laravel\\Telescope\\Telescope::recordException(Object(Laravel\\Telescope\\IncomingExceptionEntry))
#8 vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(360): Laravel\\Telescope\\Watchers\\ExceptionWatcher->recordException(Object(Illuminate\\Log\\Events\\MessageLogged))
#9 vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(209): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}('Illuminate\\\\Log\\\\...', Array)
#10 vendor/laravel/framework/src/Illuminate/Log/Logger.php(210): Illuminate\\Events\\Dispatcher->dispatch('Illuminate\\\\Log\\\\...')
#11 vendor/laravel/framework/src/Illuminate/Log/Logger.php(174): Illuminate\\Log\\Logger->fireLogEvent('error', 'Authentication ...', Array)
#12 vendor/laravel/framework/src/Illuminate/Log/Logger.php(87): Illuminate\\Log\\Logger->writeLog('error', 'Authentication ...', Array)
#13 vendor/laravel/framework/src/Illuminate/Log/LogManager.php(488): Illuminate\\Log\\Logger->error('Authentication ...', Array)
#14 vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(114): Illuminate\\Log\\LogManager->error('Authentication ...', Array)
#15 app/Exceptions/Handler.php(38): Illuminate\\Foundation\\Exceptions\\Handler->report(Object(InvalidArgumentException))
#16 vendor/nunomaduro/collision/src/Adapters/Laravel/ExceptionHandler.php(60): App\\Exceptions\\Handler->report(Object(InvalidArgumentException))
#17 vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(353): NunoMaduro\\Collision\\Adapters\\Laravel\\ExceptionHandler->report(Object(InvalidArgumentException))
#18 vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(124): Illuminate\\Foundation\\Console\\Kernel->reportException(Object(InvalidArgumentException))
#19 artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#20 {main}
"}

**Comment by themsaid** [comment]
That seems like an issue in your app, please let us know if it's something related to Telescope.

**Comment by thijsvdanker** [comment]
I have the same issue.
Might not be something caused by Telescope, but the error goes away when removing Telescope.

**Comment by antongorodezkiy** [comment]
I have the same issue with custom auth provider and laravel 8.77.1 and telescope 4.6.9. Before installing telescope the app was working fine with custom auth provider for the ~5 months.
