### ISSUE TITLE
direct Artisan::call() commands not getting logged 

### ISSUE THREAD

**Issue by nikhilbaby2000** [laravel/telescope#671]
- Telescope Version: 2.0.*
- Laravel Version: 5.8.*
- PHP Version: 7.2.14
- Database Driver & Version: MySql v5.6

### Description:
Direct artisan command call via `Artisan::call()` method is not being logged by Telescope.
But `exec("php artisan command:signature")` is being logged.

In my case, I was writing a nova package to dispatch commands from nova panel. 
Once an Ajax call is being made from Nova, the Controller call was calling the command using `Artisan::call()` method/Facade. This was not being captured by Telescope. I guess some barrier got by-passed (where telescope is monitoring)

### Steps To Reproduce:
Try calling an artisan command, say: `php artisan optimize` from another code (say, a controller).

**Not Logged** if called like: `Artisan::call('optimize');` 
**Logged** if called like: `exec('php artisan optimize');`

Please look into it. Thanks

**Comment by taylorotwell** [comment]
Can't recreate. Logs fine for me:

<img width="968" alt="image" src="https://user-images.githubusercontent.com/463230/70353418-ec4b2300-1832-11ea-84a6-45e6d7bc7909.png">
