### ISSUE TITLE
Telescope showing local.ERROR: $documents is empty {"exception":"[object] (MongoDB\Exception\InvalidArgumentException(code: 0):

### ISSUE THREAD

**Issue by NaseebaNasi** [laravel/telescope#672]
- Telescope Version:"^2.0"
- Laravel Version: 5.8.
- PHP Version: 7.2.20
- Database Driver & Version:mongodb version:- ^3.4

Telescope shows "We couldn't find anything" error while loading telescope/requests. I get this empty page instead of my api listing. I'm using mongodb.
The console is showing this 
`{"entries":[],"status":"enabled"}`
laravel log is showing 

> 
local.ERROR: $documents is empty {"exception":"[object] (MongoDB\Exception\InvalidArgumentException(code: 0):
How can I fix it?

**Comment by nekrovinnei** [comment]
Hello, I have got same problem. Did you find any solution?? I can see records In DB  but on telescope dashboard is nothing. {"entries":[],"status":"enabled"}

**Comment by Messhias** [comment]
+1, I'm facing the same issue with mongodb, unfortunately right now telescope isn't fully support MongoDB.


My solution was to remove the telescope from package.json and work without it (it's increasing a lot my logs folder).

**Comment by yousifnimah** [comment]
Follow these steps and it will work:

1- Find the file  `vendor/laravel/telescope/src/Storage/EntryModel.php`

2- Add `use Jenssegers\Mongodb\Eloquent\Model as Moloquent;`

3- Extend the **EntryModel** class by **Moloquent** instead of **Model** 
Like this `class EntryModel extends Moloquent{`

4- Comment the statement `$query->where('should_display_on_index', true);` the line 170

And it will work :)

**Comment by Messhias** [comment]
> Follow the steps below:
> 
> 1- Find the file `vendor/laravel/telescope/src/Storage/EntryModel.php`
> 
> 2- Add `use Jenssegers\Mongodb\Eloquent\Model as Moloquent;`
> 
> 3- Extend the **EntryModel** class by **Moloquent** instead of **Model**
> Like this `class EntryModel extends Moloquent{`
> 
> 4- Comment the statement `$query->where('should_display_on_index', true);` at the line 170
> 
> And it will work :)

Yes, I did that and worked fine, but anyway this isn't a permanent solution because it'll be necessary to add it to every project that we're using MongoDB.

Maybe use abstract models could be a solution?

**Comment by yousifnimah** [comment]
When I got time I will provide a workaround which can be executed outside the vendor directory

**Comment by taylorotwell** [comment]
Telescope doesn't support MongoDB.
