### ISSUE TITLE
[Feature Request] A way to add tags as a package

### ISSUE THREAD

**Issue by stancl** [laravel/telescope#673]
Right now, `Telescope::tag()` sets the callback that returns the user-specified tags.

https://github.com/laravel/telescope/blob/d7a3ca4338b1a1527b8d19a5d62015a468f8ca56/src/Telescope.php#L521-L532

This doesn't allow packages to easily set tags, because they would override the user-specified tags.

An example of when a package would want to set a tag is multi-tenancy. I'd like my package to set a tag with the tenant id for each request.

It might be possible to set tags from a package using something like this:

```php
$original_callback = Telescope::tagUsing;

Telescope::tag(function (IncomingEntry $entry) {
    if ($entry->type === 'request') {
        $tags = ['status:'.$entry->content['response_status']];
    } else {
        $tags = [];
    }

    return array_merge($original_callback($entry), $tags);
});
```

but it would be nice to have a less hacky way of setting multiple tag-creating callbacks.

**Comment by stancl** [comment]
If this feature request gets approved, I can submit a PR for the master branch as this would be a breaking change.

**Comment by taylorotwell** [comment]
This was resolved via PR.
