### ISSUE TITLE
[Feature Request] Link Exception with Source

### ISSUE THREAD

**Issue by dbpolito** [laravel/telescope#675]
On production, when exception happens it doesn't have any link to Source (Request, Job, Command, Schedule).

Would be great if we could save them in case of failure and link from the Exception panel.

**Comment by barryvdh** [comment]
It would be useful to add at least the Request info, but filtering now happens based on just the IncomingEntry. In that case it would need to be determined if the batch contains anything that needs to be logged.

**Comment by barryvdh** [comment]
You can adjust the Filter method in your ServiceProvider to record Request entries when the status is 500. This way, when an Exception occurs, the Request will be added/linked also:

```php
Telescope::filter(function (IncomingEntry $entry) {
	if ($this->app->isLocal()) {
		return true;
	}


	return $entry->isReportableException() ||
		   $entry->isFailedJob() ||
 		   ($entry->type === EntryType::REQUEST && ($entry->content['response_status'] ?? null) === 500) ||
		   $entry->isScheduledTask() ||
		   $entry->hasMonitoredTag();
});
```

Perhaps it would be useful to add this by default?

**Comment by barryvdh** [comment]
See https://github.com/laravel/telescope/pull/685

**Comment by dbpolito** [comment]
Yes, great PR, hopefully this gets merged but i will definitely adjust my apps with this. Thank you!

**Comment by barryvdh** [comment]
It's merged (not tagged yet), so this can be closed?

**Comment by dbpolito** [comment]
Yep, thank you
