### ISSUE TITLE
[Bug Report] failed and processed jobs are not recorded if there was no pending job recorded

### ISSUE THREAD

**Issue by christophmayrhofer** [laravel/telescope#690]
- Telescope Version: 2.0
- Laravel Version: 5.8
- PHP Version: 7.2
- Database Driver & Version: mysql

### Description:
As far as I can tell, failed and processed job entries are treated as updates to an existing job entry (```DatabaseEntriesRepository->update()```). This assumes that there is already an entry in the DB (that should be created when the job is dispatched).

However, there may not be a an entry for the pending job in the DB (e.g. if telescope was disabled when the job was dispatched). A solution could be to create a new job entry if there is no existing pending job found.

I also never get an IncomingEntry passed to ``` Telescope::filterBatch ``` for failed jobs. Therefore the ```$entry->isFailedJob()``` filter will never return true.

### Steps To Reproduce:
Disable telescope
Dispatch job
Enable telescope
Process job (php artisan queue:work)
--> The job (regardless if failed or processed) does not show up in telescope.

**Comment by taylorotwell** [comment]
We likely won't fix this as it would be a major change to how Telescope works. It is simply a limitation that if Telescope is not enabled when the job is dispatched it will not show up.
