### ISSUE TITLE
[Testing] How to get IncomingRequest for testing purposes?

### ISSUE THREAD

**Issue by stancl** [laravel/telescope#691]
I want to test that a request has specific tags. How do I do that?

**Comment by barryvdh** [comment]
You could set the `afterRecording` perhaps? It doesn't give you the entry itself (not sure why not though), but you can get it from the entries queue (static property)

**Comment by stancl** [comment]
On second thought, for my use case it might be better to just make a request and check the `telescope_entries_tags` table.
