### ISSUE TITLE
Telescope 403s in Vapor Install

### ISSUE THREAD

**Issue by narrative1st** [laravel/telescope#693]
Brand new install of everything.

Vapor staging server with default basic setting gives 403 error

**Comment by narrative1st** [comment]
Brand new everything. Telescope works fine at home. Vapor staging server gives 403 error

**Comment by Stokoe0990** [comment]
I also have an instance of Telescope running in an app on AWS, deployed by Vapor.

With the `'sqs'` part of the config copied out of the latest laravel/laravel repo's `config/queue.php`, I've been able to get queue jobs pushed to the SQS service in Amazon, but the jobs never get processed.

Not only that, but there is nothing in telescope. Almost like it's not monitoring anything.

**Comment by themsaid** [comment]
Just tested Telescope on a fresh Vapor Project and it seems to be working fine.

**Comment by Stokoe0990** [comment]
Forgot to come back and update this but I also have a working installation of Telescope in an app running in AWS through Vapor.

**Comment by narrative1st** [comment]
Twas a simple matter of adding my email to array in the TelescopeServiceProvider.

**Comment by ellisio** [comment]
@themsaid This seems to be broken at a different level now.

```
Building project...
==> Copying Application Files
==> Harmonizing Configuration Files
==> Setting Build Environment
==> Executing Build Commands
==> Running Command: composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - moontoast/math 1.1.2 requires ext-bcmath * -> the requested PHP extension bcmath is missing from your system.
    - moontoast/math 1.1.2 requires ext-bcmath * -> the requested PHP extension bcmath is missing from your system.
    - Installation request for moontoast/math 1.1.2 -> satisfiable by moontoast/math[1.1.2].

```

It seems `laravel/telescope@2.1` depends on `moontoast/math`.

I'm currently rolling my own ARN file to install bcmath.

**Comment by ellisio** [comment]
I digress. This is apparently due to CircleCI's `php-node` image.
