### ISSUE TITLE
Artisan::call('migrate:fresh --seed') wouldnt migrate telescope tables

### ISSUE THREAD

**Issue by foremtehan** [laravel/telescope#713]
- Telescope Version: 2.0.6
- Laravel Version: 6.0
- PHP Version: 7.3
- Database Driver & Version: Mysql 8.0

When i execute ```php artisan migrate:fresh --seed``` on my git bash it migrate both laravel and telescope tables, But on artisan call it wouldnt :

```php
Route::get('fresh', function (){
    Artisan::call('migrate:fresh --seed');
});
```

**Comment by lionslair** [comment]
This is because you have TELESCOPE_ENABLED=false in your env right?

**Comment by foremtehan** [comment]
@lionslair i have it on my phpunit.xml :
```<env name="TELESCOPE_ENABLED" value="false"/>```

By uncommenting this my test suit become 4x slower that normal

**Comment by lionslair** [comment]
I have it set false in my .env files. I only turn it on when needed. With the changes to the service provider the migrations are no longer available when the value is false. However the commands are still registered, So the scheduled prune task still runs even though the tables do not exist.

**Comment by simonezampinistud** [comment]
Same error, and TELESCOPE_ENABLED is true everywhere.

**Comment by taylorotwell** [comment]
We only make migrations available when actually running in the CLI. To make them available on even web requests would be a performance hit. You could work around this by using Symfony Process to actually run a real CLI process to run php artisan migrate:fresh...

<img width="679" alt="image" src="https://user-images.githubusercontent.com/463230/70353096-35e73e00-1832-11ea-8b01-fdba2a633136.png">

**Comment by MohammedElattar** [comment]
// routes/api.php

$process = Process::run('php "../artisan" migrate:fresh --seed');
   return $process->successful();

works for me
