### ISSUE TITLE
Insert Query not showing under respective Request (e.g. function storeData)

### ISSUE THREAD

**Issue by sharma-pankaj-tech** [laravel/telescope#718]
We have facing isssue when saving data as a new record then under request section insert query not showing but in query tab it's showing.
I don't know why this is happening where in model we using simple save method.

code for creating new record: 

$instance = new self();
foreach($record as $key => $val) {
   $instance->$key = $val;
 }
$instance->save()

please suggest what the issue behind this.

Thanks

**Comment by taylorotwell** [comment]
Can't recreate this:

<img width="990" alt="image" src="https://user-images.githubusercontent.com/463230/70352879-c1ac9a80-1831-11ea-85ca-3cc8ee196f3d.png">
