### ISSUE TITLE
Telescope resumes recording after JobProcessing event

### ISSUE THREAD

**Issue by erikgaal** [laravel/telescope#719]
- Telescope Version: 2.1
- Laravel Version: 6.0.0
- PHP Version: 7.3.8
- Database Driver & Version: sqlite

Hi there,

In order to speed up some seeds we've added `Telescope::stopRecording()` at the beginning of the commands/seeds. This should prevent Telescope from recording, however, the seeders are still _slower_, and consuming _more memory_ compared to having Telescope disabled. This didn't seem right, so I started inspecting with the debugger.

What I found out, was that Telescope was still recording queries event though I had set it to stop recording. Using call tracing I found out that `Laravel\Telescope\Watchers\QueryWatcher::recordQuery` was still being called and using significant time. Fast forward to the debugger, and I found out that Telescope was somehow enabled again. A model in our seeder was dispatching a job that was executed synchronously. This triggered the following event listener in Telescope, which set Telescope to start recording again.

https://github.com/laravel/telescope/blob/d9c5c53d3a0c60dcd4ef3777884d0cf368eb3e6f/src/ListensForStorageOpportunities.php#L56-L60

I do not think this behaviour is how it should work. It seems a bit odd that even though I tell Telescope to stop recording, due to a listener it starts recording again.

I've set up an example repository in a new Laravel project that shows the bug at https://github.com/erikgaal/telescope-recording-bug-example. I've also added a test that confirms the wrong behaviour.

https://github.com/erikgaal/telescope-recording-bug-example/blob/7d0812e2bbb4e63b9ae090282b0d4edda9519fd8/tests/Unit/ExampleTest.php#L17-L28

**Comment by ristlin** [comment]
I've run into a similar issue that eventually breaks tests as the watcher exhausts the allotted memory. 

I personally don't see a need to have Telescope active during tests, so I've added the following to my phpunit.xml

`<env name="TELESCOPE_ENABLED" value="false"/>`

**Comment by nolanpro** [comment]
Thanks for this. If anyone was wondering why telescope was logging its own events, it might be your middleware is firing a sync event, as was our case. Then logging doesn't get turned off when the telescope page loads. The PR should fix it.

**Comment by rovansteen** [comment]
@themsaid any plans to cut a new release that includes the fix for this? (#720)

**Comment by taylorotwell** [comment]
Looks like this was fixed by a PR and has since been released.

**Comment by erikgaal** [comment]
Thanks for the release!
