### ISSUE TITLE
 php artisan telescope:install InvalidArgumentException

### ISSUE THREAD

**Issue by dmlang** [laravel/telescope#722]
- Telescope Version: ^2.1
- Laravel Version: 6
- PHP Version: 7.3.8
- Database Driver & Version: Mysql 8.0.13

### Description:
When installing telescope a InvalidArgumentException in vendor/ramsey/uuid/src/Generator/CombGenerator.php:63 occurs. 

### Steps To Reproduce:
try to install telescope to a  laravel 6 app

**Comment by furai** [comment]
I see it's closed, I'm getting similar issue, did you find out why was it happening?

**Comment by barryvdh** [comment]
This was fixed in the latest Laravel release.
