### ISSUE TITLE
Telescope reports "This watcher is turned off." when using an alternative watcher to the default

### ISSUE THREAD

**Issue by Cheezykins** [laravel/telescope#724]
- Telescope Version: 2.1
- Laravel Version: 5.8.35
- PHP Version: 7.3.8
- Database Driver & Version: MySQL 5.7.27

### Description:

I have extended the request watcher to add handling for XML as our API is XML-RPC based. The new watcher works fine and handles requests, but the heading shows a big red error "This watcher is turned off."

![image](https://user-images.githubusercontent.com/11211889/64426580-d5b3f500-d0a6-11e9-8994-b59f83171332.png)

Is there a way to make it not show that?

### Steps To Reproduce:

Extend the Request Watcher.
Add the new Request Watcher to config/telescope.php in place of the existing one.
View the telescope UI.

**Comment by Cheezykins** [comment]
To clarify, everything about the UI works flawlessly. Requests still show as they happen and it all works nicely. It just has that error at the top for no reason.

**Comment by jaycom** [comment]
I have the same issue.
I just change the "Watchers\RequestWatcher::class" to my customer RequestWatcher class in the telescope.php config file

**Comment by upklio** [comment]
Same issue.

**Comment by themsaid** [comment]
That's because the actual Telescope watcher is disabled and you're using your own watcher. The error message is not wrong in this case.

To work around this we'll need to override the watcher using the container in one of your service providers, that way Telescope will use your extension but still have the watcher name correct.

**Comment by andresilva96** [comment]
What I did before the return array from config/telescope.php

```$requestWatcher = strpos(request()->getRequestUri(), '/telescope') !== false ? Watchers\RequestWatcher::class : App\Watchers\RequestWatcher::class;```

Then when call watcher:

```
$requestWatcher => [
    'enabled' => env('TELESCOPE_REQUEST_WATCHER', true),
    'size_limit' => env('TELESCOPE_RESPONSE_SIZE_LIMIT', 64),
    'ignore_http_methods' => [],
    'ignore_status_codes' => [],
],
```

**Comment by adamczykpiotr** [comment]
In order not to have this error, the easiest option is to bind custom watcher class in TelescopeServiceProvider:

`$this->app->bind(RequestWatcher::class, <your class>::class);`

**Comment by tranvanhieu01012002** [comment]
@andrersilva96  yes, this is work  but we should keep ```key: Watchers\RequestWatcher::class ``` in config/telescope.php 
```
        Watchers\RequestWatcher::class => [
            'enabled' => env('TELESCOPE_REQUEST_WATCHER', true),
            'size_limit' => env('TELESCOPE_RESPONSE_SIZE_LIMIT', 64),
            'ignore_http_methods' => [],
            'ignore_status_codes' => [],
             //...other custom setting
```
