### ISSUE TITLE
Don't try to log exceptions when throwing exceptions while trying to log exceptions

### ISSUE THREAD

**Issue by ethanransdellrarebird** [laravel/telescope#725]
If Telescope is tracking exceptions and encounters an error when recording them (e.g. if the telescope_entries table is gone or corrupt), it causes recursive explosion. Suggest having a fallback for this scenario.

**Comment by themsaid** [comment]
Storage exceptions are already handled. How can I replicate your issue?

**Comment by ethanransdellrarebird** [comment]
In my example, the `telescope_entries` table had been dropped.

**Comment by themsaid** [comment]
I can't seem to replicate this and it's not being reported by anyone else so I'm going to close the issue.

Please open a new issue with clear steps of replication.
