### ISSUE TITLE
null displayed as empty string

### ISSUE THREAD

**Issue by tillkruss** [laravel/telescope#726]
- Telescope Version: 2.0
- Laravel Version: 6.0
- PHP Version: 7.3

### Description:

I'm executing an increment on a pivot model:

```php
$participant->increment('unread', 1, ['archived_at' => null]);
```

Telescope shows this query:

```sql
update
  "conversations_companies_map"
set
  "unread" = "unread" + 1,
  "archived_at" = '',
  "updated_at" = '2019-09-06 22:16:15'
where
  "id" = 2386
```

Could it be possible that Telescope is displaying `null` as `''` by chance?

**Comment by barryvdh** [comment]
Which version exactly? You say 2.0 but 2.1 is the latest, which includes https://github.com/laravel/telescope/pull/706

**Comment by tillkruss** [comment]
Sorry, 2.1

**Comment by barryvdh** [comment]
See https://github.com/laravel/telescope/pull/727

**Comment by tillkruss** [comment]
You’re the best! ❤️
