### ISSUE TITLE
Hide php-auth-pw header 

### ISSUE THREAD

**Issue by vedmant** [laravel/telescope#730]
I see that it hides "authorization" header already, but it's showing simple HTTP auth header "php-auth-pw" where plain password can be seen, which I think can be a security concert.

**Comment by ManojKiranA** [comment]
You can hide it by adding the headers in `hideSensitiveRequestDetails` of `TelescopeServiceProvider`

https://github.com/laravel/telescope/blob/2.0/stubs/TelescopeServiceProvider.stub#L41

**Comment by vedmant** [comment]
@ManojKiranA Sure I can, but why then Authorization header is filtered by default? I think this is security issue and this kind of headers have to be hidden by default.

**Comment by barryvdh** [comment]
Why not make a PR then?

**Comment by vedmant** [comment]
@barryvdh Great idea, I'll add it.

**Comment by billmn** [comment]
@vedmant could you close this issue?
