### ISSUE TITLE
app\Providers\TelescopeServiceProviders.php has not been added to project file

### ISSUE THREAD

**Issue by tanjiya** [laravel/telescope#734]
I have tried to install telescope according to <a href="https://laracasts.com/series/laravel-from-scratch-2018/episodes/28">Jeffrey</a>'s video.

I am using the latest version of laravel. I have installed according to the <a href="https://laravel.com/docs/6.0/telescope">laravel documentation</a> for installing as dev.

But, don't find the **app\Providers\TelescopeServiceProviders.php** in app\providers folder.

Need to mention:
--I have used **use Laravel\Telescope\TelescopeServiceProvider** namespace in AppServiceProvider.php

**Comment by tanjiya** [comment]
I have removed telescope using **composer remove laravel/telescope** and removed TelescopeServiceProvider manually from AppServiceProvider. And installed using the following step. and it works!

**composer require laravel/telescope --dev
php artisan telescope:install
php artisan migrate
php artisan telescope:publish**

**Comment by lk77** [comment]
Hello,

if you use laravel 6.x there is some issues in the installation process,
you need to copy the files manually or wait for a fix.

**Comment by taylorotwell** [comment]
I am able to install Telescope correctly on the latest release of Laravel 6.
