### ISSUE TITLE
Auto Theme

### ISSUE THREAD

**Issue by zgosalvez** [laravel/telescope#739]
The new Ignition package has a 'light', 'dark', and 'auto' themes. Can we also have a similar option to set the theme for Telescope to be 'auto' instead of just setting it to 'night' manually?

**Comment by barryvdh** [comment]
In your TelescopeServiceProvider:
```php
if (now()->hour >= 20 || now()->hour < 7) {
      Telescope::night();
}
```

**Comment by zgosalvez** [comment]
Your solution is dependent on server time instead of the client's. I'm referring to having the theme set automatically through the OS/browser.

```js
this.mediaQuery.addEventListener('change', e => {
  this.detectedTheme = e.matches ? 'dark' : 'light';
});
```
Source: https://github.com/facade/ignition/blob/18b86fc5e39ed8656e499f21c9fd33507c83df6f/resources/js/components/Stack/Snippet.vue#L97

**Comment by JackWH** [comment]
@zgosalvez As Telescope's theme is set in the backend, media queries won't work until someone updates the Telescope frontend to support this.

In the mean time, you can try something like I did in `TelescopeServiceProvider` — it's still specific to the server's location, but at least adjusts dynamically throughout the year:

```php
        $sunTimes = date_sun_info(time(), 51.507375, -0.126815);

        if (now()->timestamp > $sunTimes['sunset'] && now()->timestamp < $sunTimes['sunrise']) {
            Telescope::night();
        }
```

Replace the second and third parameters of `date_sun_info()` with you or your user's local latitude/longitude, and Telescope will go dark once the sun sets in your location :)

**Comment by taylorotwell** [comment]
There is no bug report here.

**Comment by joowdx** [comment]
Hi. I created a pull request for this #1118 .
