### ISSUE TITLE
Log telescope

### ISSUE THREAD

**Issue by valeriy-efimov** [laravel/telescope#741]
- Telescope Version: 2.1.0
- Laravel Version: 6.0.0
- PHP Version: 7.3 x64
- Database Driver & Version: Mysql 5.7 x64
 
### Description:
Hello. I use laravel 6 and telescope 2.1 when i try Log::debug('debug');in console command. Telescope show log only when command stop working. Is it possible to immediately display the log?

```
 try {
            while (true) {
... some code 
Log::debug('debug');
}
} catch (\Exception $e) {
           
       }
```

In storage/logs records are present but in telescope nope. "Auto load entries" button it ennable.

if i change command to

```
try {
            while (true) {
... some code 
Log::debug('debug');
break;
}
} catch (\Exception $e) {
           
        }
```

they add log to telescope

While command is working in a telescope, nothing is added for some reason.

### Steps To Reproduce:
>php artisan run_command

**Comment by Warz** [comment]
> Is it possible to immediately display the log?

Yes, you can flush the entries like this:

`\Laravel\Telescope\Telescope::store(app(\Laravel\Telescope\Contracts\EntriesRepository::class));`

Then your log will appear in telescope, even if your program has not finished running. 

Example:
```
while (true) {
	Log::debug('debug');
	\Laravel\Telescope\Telescope::store(app(
		\Laravel\Telescope\Contracts\EntriesRepository::class)
	);
}
```
