### ISSUE TITLE
Disable Gravatar or allow third-party services

### ISSUE THREAD

**Issue by RichardDern** [laravel/telescope#742]
It would be nice to add a configuration entry to disable gravatar, if it doesn't already exists (I didn't see it in the docs)

Possible use-cases and concerns:

- Offline servers
- Privacy (I don't use Gravatar at all, so I don't want my email address to be sent to them with everything that implies in terms of security and privacy)

Another possibility would be to allow customising avatar's URL, so we can use third-party/self-hosted avatar-hosting services.

**Comment by michael-schaefer-eu** [comment]
Hey +1 for the config switch.

I could find out that it sends only a hash of the email address, but anyway they get your IP and they do track the user!

```
gravatarUrl() {
    if (this.entry.content.user.email) {
        const md5 = require('md5')
        return 'https://www.gravatar.com/avatar/' + md5(this.entry.content.user.email.toLowerCase()) + '?s=200'
    }
}
```

**Comment by derekmd** [comment]
@taylorotwell @driesvints This issue can be closed now `Telescope::avatar()` is available.
