### ISSUE TITLE
Add queries filter

### ISSUE THREAD

**Issue by info170** [laravel/telescope#744]
In Queries it will be cool to add filter to show only "insert" or "update" queries. Now it is too difficult to find some rare query between many "select".

**Comment by diogogomeswww** [comment]
I was just to proposed this feature.

Use case for me is:
I trigger some action (endpoint, command,...) and want to quickly know what changed in the DB.

I was thinking in doing a simple UI dropdown filter on the Queries tab, that would allow to select multiple options: select, insert, update.

Happy to do the PR if you like the idea.

**Comment by taylorotwell** [comment]
This is not a bug report.
