### ISSUE TITLE
Laravel Telescope: With Laravel as API

### ISSUE THREAD

**Issue by margaritacoco** [laravel/telescope#754]
In my local environment, i've been using Telescope to debug the Laravel API and also monitor the platform which uses NuxtJS as a frontend.

For production, i'm using the same URL for both(Frontend and Backend).

The problem I encounter, is that Laravel Telescope will not work.
--
**Local env. setup**
Platform url: www.domain.com
Laravel url: www.domain.com/api
Telescope URL(changed in the telescope.php file): www.domain.com/api/telescope

THIS WORKS. 100%.

**Online(Production) env. setup**
Platform url: www.domain.com
Laravel url: www.domain.com/api
Telescope URL(changed in the telescope.php file): www.domain.com/api/telescope

THIS DOESN'T.

Result:
<img width="1680" alt="Capture d’écran, le 2019-10-22 à 13 25 46" src="https://user-images.githubusercontent.com/53951978/67312523-77649980-f4cf-11e9-98ae-97aa5fefc980.png">

Is there something i'm missing?
*the authentification is set to false, so it's not the issue.

**Comment by tisuchi** [comment]
@margaritacoco 

Laravel Telescope is for local development. It will help you to make your application better before launching to production. 
> Telescope makes a wonderful companion to your local Laravel development environment.

Ref: https://laravel.com/docs/6.x/telescope

**Comment by margaritacoco** [comment]
> @margaritacoco
> 
> Laravel Telescope is for local development. It will help you to make your application better before launching to production.
> 
> > Telescope makes a wonderful companion to your local Laravel development environment.
> 
> Ref: https://laravel.com/docs/6.x/telescope
> 
> But if you are still interested to enable telescope in the production, you need to make sure the following things-
> 
> **config/telescope.php:**
> 'enabled' => env('TELESCOPE_ENABLED', true)

This might be a stupid question then, but other than Sentry, how would you go about debugging or monitoring your Laravel application in production?

Thank you for replying!

**Comment by margaritacoco** [comment]
**Solution**

Host your API on a subdomain also. This bypasses the problem, while keeping your api intact.

**Comment by marensas** [comment]
> **Solution**
> 
> Host your API on a subdomain also. This bypasses the problem, while keeping your api intact.

It's not possible to host a second level subdomain on "https" protocol i.e.: https://api.subproject.project.com

https://serverfault.com/questions/104160/wildcard-ssl-certificate-for-second-level-subdomain

**Comment by shehrozafzal** [comment]
I've been facing this issue in my Laravel (API backend) & React (frontend) app using vite bundling.
This is my proxyOptions in vite 

```
const proxyOptions = {
  target: `http://127.0.0.1:8000`,
  changeOrigin: false,
  secure: true,
  ws: false,
};
```
add these two lines in proxy object

```
server: {
    host: "localhost",
    port: process.env.FRONTEND_PORT,
    hmr: hmrConfig,
    proxy: {
      "^/(\\?.*)?$": proxyOptions,
      "^/api(/|(\\?.*)?$)": proxyOptions,
      "^/telescope(/|(\\?.*)?$)": proxyOptions,
      "^/vendor/telescope(/|(\\?.*)?$)": proxyOptions,
    },
  },
```

this fixed the issue for me without using `/api/telescope` method.
