### ISSUE TITLE
Sentry doesn't work with Telescope enabled

### ISSUE THREAD

**Issue by raulsh** [laravel/telescope#755]
- Telescope Version: 2.1
- Laravel Version: 5.8
- PHP Version: 7.2
- Database Driver & Version: MySQL

### Description:

I can't use Sentry with Telescope enabled because Telescope is catching the exception messages

**Comment by ahinkle** [comment]
I (and I'm sure many others) have both Sentry and Telescope enabled and I'm able to see both, Sentry, and Telescope errors.

I would double-check your environment. If you need additional help give us a shout on the Laravel[Discord](https://discordapp.com/invite/mPZNm7A) channel.

**Comment by ahinkle** [comment]
I (and I'm sure many others) have both Sentry and Telescope enabled and I'm able to see both, Sentry, and Telescope errors.

I would double-check your environment. If you need additional help give us a shout on the Laravel [Discord](https://discordapp.com/invite/mPZNm7A) channel.
