### ISSUE TITLE
Telescope Performance measure and duration on Requests list

### ISSUE THREAD

**Issue by LonnyX** [laravel/telescope#767]
It will be nice if Telescope give the total duration on Requests list. 
And why not a more performance section like the symfony profiler?

What do you think?

**Comment by barryvdh** [comment]
I created a concept for this in https://github.com/laravel/telescope/pull/698 but it was rejected and suggested to use Blackfire. So I thing it might be out of scope.

**Comment by LonnyX** [comment]
Ah ok, I understand Taylor
