### ISSUE TITLE
Telescope ignores the "ignore_commands" setting

### ISSUE THREAD

**Issue by ludo237** [laravel/telescope#768]
- Telescope Version: 2.1
- Laravel Version: 5.8.x
- PHP Version: 7.3.x
- Database Driver & Version: MariaDB 10.4

### Description:
Telescope keeps logging the horizon:snapshot command regardless of the `ignore commands` key inside `telescope.php` config file

### Steps To Reproduce:

Write this inside `config/telescope.php`
```php
"ignore_commands" => [ "horizon:snapshot"],
```
I've also tried `horizon:*` and `horizon*` same issue. Telescope will log the schedule command inside `schedule` page

![Annotation 2019-11-05 094913](https://user-images.githubusercontent.com/921500/68192396-28c3fe80-ffa9-11e9-9562-336e3faa8f03.jpg)

This is a problem because then the schedule page gets filled with this command and I can't see other commands.

### Current Fix:

Remove the snapshot command from `Kernel.php`

**Comment by ludo237** [comment]
### Update

I think that the problem is that the `ScheduleWatcher` doesn't have a way to add additional filters to the `recordCommand` function.

In other words `ScheduleWatcher` should leverage the `$options` attribute to check if there are commands to ignore

Correct me if I'm wrong here.

**Comment by themsaid** [comment]
The ignores list filters the commands that you run on your console not ones running by the scheduler.

However, if you want to filter any record you can do that in your TelescopeServiceProvider by calling Telescope::filter() and return false for that record type.
