### ISSUE TITLE
Show 'Duration' for Jobs and Commands

### ISSUE THREAD

**Issue by HPWebdeveloper** [laravel/telescope#769]
First of all, I appreciate all of your efforts!

For **Requests** tab there are some columns:

Verb | Path | Status | **Duration** | Happened
-- | -- | -- | -- | --

While for **Commands** I see only

Command | Exit Code | Happened
-- | -- | --

and If I want to see the **Duration** of each command I have to check the **Command Details** page. Which shows the duration of that command totally (sum of all queries) and also details of each query.

Also the **Jobs** has only these columns:

Job | Status | Happened
-- | -- | --

I think **Duration** (total duration of each job or command) should be added to the columns of Jobs and Commands too.

Best Regards,

**Comment by taylorotwell** [comment]
This is not a bug report.
