### ISSUE TITLE
Test failing when telescope enabled

### ISSUE THREAD

**Issue by InfoSecRavindra** [laravel/telescope#770]
- Telescope Version:2.1
- Laravel Version: 6.5.0
- PHP Version:7.2.24-0ubuntu0.18.04.1
- Database Driver & Version:

### Description:
If telescope is enabled then running unit test is throwing errors,
I didn't write any tests, i just ran default test

`./vendor/phpunit/phpunit/phpunit`

[log.txt](https://github.com/laravel/telescope/files/3834459/log.txt)

### Steps To Reproduce:
type `./vendor/phpunit/phpunit/phpunit` in terminal and it will show errors.

Setting `TELESCOPE_ENABLED=false` in .env and running tests works.

**Comment by PatrickSJ** [comment]
Also take note of an alternative provided by @gordonhung at https://github.com/laravel/telescope/issues/347#issuecomment-549037255 regarding the use of `App::environment['local']` instead of `$this->app->isLocal()` in TelescopeServiceProvider.php to resolve this issue.

**Comment by InfoSecRavindra** [comment]
Okay, Thank you, it solved the problem.

**Comment by bentran** [comment]
I rip my hair out for days because of this error. Disabling Telescope fixed.

**Comment by da-mask** [comment]
I believe you can disable telescope when running tests in phpunit.xml like so:
`   <server name="TELESCOPE_ENABLED" value="false" />`

**Comment by quyle92** [comment]
when running migration for unit test, you have to specify the` --env` flag for telescope to be ignored:
`php artisan migrate --env=testing`
