### ISSUE TITLE
n+1 queries are not being displayed

### ISSUE THREAD

**Issue by gauravmak** [laravel/telescope#774]
- Telescope Version: latest
- Laravel Version: latest
- PHP Version: latest
- Database Driver & Version: MySQL latest

### Description:
If the page is causing the n+1 query issue, all the queries are not being displayed in the Telescope screen.

We added Laravel Telescope and Laravel Debugbar in the sample to compare the results and here are the screenshots.
![Laravel](https://user-images.githubusercontent.com/11887260/68925829-09e41a00-07aa-11ea-9e22-ebb5e1e98fd7.png)
![Queries - Telescope](https://user-images.githubusercontent.com/11887260/68925830-0a7cb080-07aa-11ea-8fe0-abb15dce4c7f.png)

### Steps To Reproduce:
Here is the sample repository to check the code: https://github.com/freshbitsweb/query-debug-test

**Comment by gauravmak** [comment]
Mainly 2 files to be checked: 
https://github.com/freshbitsweb/query-debug-test/blob/master/app/Http/Controllers/DebugController.php

https://github.com/freshbitsweb/query-debug-test/blob/master/resources/views/users.blade.php

**Comment by barryvdh** [comment]
This should be fixed with #773 
Can you verify that?

**Comment by gauravmak** [comment]
Yes, it does @barryvdh :)

**Comment by gauravmak** [comment]
Closing as the PR is merged.
