### ISSUE TITLE
Dashboard Authorization instructions don't allow running on Production

### ISSUE THREAD

**Issue by Patabugen** [laravel/telescope#780]
- Telescope Version: 2.1
- Laravel Version: 6
- PHP Version: 7.3
- Database Driver & Version:

### Description:
I've followed the instructions for enabling the Telescope Dashboard on non-local environments - however it does not appear to be working as described in the documentation.

https://laravel.com/docs/6.x/telescope#dashboard-authorization

### Steps To Reproduce:
Install Telescope as per the instructions.
Modify `App\Providers\TelescopeServiceProvider::gate` to the following:

```
    /**
     * Register the Telescope gate.
     *
     * This gate determines who can access Telescope in non-local environments.
     *
     * @return void
     */
    protected function gate()
    {
        Gate::define('viewTelescope', function ($user) {
            return true; // EXAMPLE ONLY. DO NOT DO THIS IN A REAL PROJECT.
        });
    }
```

This shoud allow access to everybody on non-local environments - however when I try and load `/telescope` on I get a 403 error.

Either the documentation is incorrect/incomplete, or there's a bug somewhere.

**Comment by tomswinkels** [comment]
I have the same problem, this is my workaround:

Remove the gate function and add the next function:

```
    protected function authorization()
    {
        if (config('myconfig.vpn_address') && in_array(config('myconfig.vpn_address'), [data_get($_SERVER, 'HTTP_X_FORWARDED_FOR'), data_get($_SERVER, 'REMOTE_ADDR')])) {
            Telescope::auth(function ($request) {
                return true;
            });
        }
    }
```

**Comment by std-matthew** [comment]
In the ```config/app.php``` add ```App\Providers\TelescopeServiceProvider``` in the ```$providers``` array

```
'providers' => [
  ...
  App\Providers\TelescopeServiceProvider::class,
  ...
]
```

Then you will be able to modify the gate function
