### ISSUE TITLE
NotificationWatcher

### ISSUE THREAD

**Issue by Essam34ML** [laravel/telescope#782]
- Telescope Version: 2.1
- Laravel Version: 5.8
- PHP Version: 7.1.3
- Database Driver & Version: MySQL

### Description:
I can't disable NotificationWatcher, i have added `TELESCOPE_NOTIFICATION_WATCHER=false
` in env, but it is still working.

**Comment by taylorotwell** [comment]
Can't recreate:

<img width="1191" alt="image" src="https://user-images.githubusercontent.com/463230/70352282-6c23be00-1830-11ea-9bb4-cda2f756ecb2.png">

**Comment by taylorotwell** [comment]
Make sure your configuration is not cached.

**Comment by Essam34ML** [comment]
Thank you
