### ISSUE TITLE
Display which queries are duplicated

### ISSUE THREAD

**Issue by MatanYadaev** [laravel/telescope#786]
It's great that now Telescope is displaying count of the duplicated queries.

**The next step, in my opinion, is to display which of the queries are duplicated.**

I have lots of queries that being done in each request/job, and they all are very long, it's a bit hard to say which of these are duplicate.
It would be nice to have some indicatior on each query that representing a "duplicated query", or maybe a filter button that on click displays only the duplicated queries.

**Comment by driesvints** [comment]
Same as https://github.com/laravel/telescope/issues/603 I think.

**Comment by themsaid** [comment]
Indeed a duplicate. Feel free to open a PR.
