### ISSUE TITLE
Support for logging on production

### ISSUE THREAD

**Issue by cuartas15** [laravel/telescope#788]
So basically my TelescopeServiceProvider file comes with the default function

> 
    public function register()
    {
    $this->hideSensitiveRequestDetails();

    Telescope::filter(function (IncomingEntry $entry) {
        if ($this->app->isLocal()) {
            return true;
        }

        return $entry->isReportableException() ||
            $entry->isFailedJob() ||
            $entry->isScheduledTask() ||
            $entry->hasMonitoredTag();
    });
    }

And this is fine, but I also want to register logs from Log::error, Log::info, etc, which this filter is not doing.
I really couldn't find which $entry function do I have to add to achieve this in the documentation or maybe this isn't supported.

**Comment by themsaid** [comment]
You can check the $entry of type `log` and check the `level` to determine if the entry should be logged or not.

**Comment by cuartas15** [comment]
but does Telescope::tag replaces Telescope::filter? or can they both coexist? because I don't want to get rid of the default filter behaviour.
