### ISSUE TITLE
Make ignoring Nova requests optional

### ISSUE THREAD

**Issue by 60days** [laravel/telescope#792]
Hi,

I'd like to use Telescope to debug my Nova app but I noticed all nova requests are automatically used in the ignore list in "handlingApprovedRequest()" in Telescope.php

There may be a way to do this easily already, but I'm relatively new to both PHP and laravel. I tried extending Telescope class in my own code but am getting some pretty inscrutable error logs (part of the reason I want to use telescope!)

Would it be possible to move these entries (or even the entire list) to the default userland telescope.php config file, so the user is free to delete or keep them as needed?

**Comment by driesvints** [comment]
Leaving this to @themsaid

**Comment by timcv** [comment]
Hi,

I have the same problem.

Here is a link to the commit:

https://github.com/laravel/telescope/commit/40959f3c72e82244b89c8594acc07ba07170ca8d#diff-deecd2e5f86cd9955088f4026ca3d452

I would be very thankfull if you could make that optional.

/Tim

**Comment by timcv** [comment]
If you need to have it mandatory, i think it would be much better to change it to:
```
'nova-api/scripts/*',
'nova-api/styles/*',
```
That would avoid the allot of unnecessary request without disabling real api calls.
/Tim

**Comment by royduin** [comment]
Or make it configurable? I'd like to debug my custom Laravel Nova stuff like tools and fields with Laravel Telescope, that's currently not possible because.

**Comment by kusab85** [comment]
Yes, @royduin is right. Catching nova-api requests should be definitively configurable.

**Comment by tylerwiegand** [comment]
I think this may be related to something I ran into after updating Telescope from 2.1 to 2.1.3... I have a nova action that sends a notification and I can't get it to record in Telescope anymore. It was working logging as expected previous to the update.

I created a route to hit in the regular Laravel side and it creates an entry in Telescope just fine -- same exact test in a Nova action and it doesn't create an entry. I downgraded to Telescope 2.1 in the meantime, but I spent a stupid amount of time trying to figure out what the heck was going on.

Hope this helps someone...

**Comment by kusab85** [comment]
@tylerwiegand: There is a function in src/Telescope.php named handlingApprovedRequest where filter for nova-api requests is hard coded. This filter should configurable via config/telescope.php

**Comment by 60days** [comment]
#799 I feel like discussion has gotten a bit circular, so I've added a very minimal PR of making ignoring nova paths configurable. 

There may be more fine-grained control needed, or a method that better matches the project's general philosophy about user config, but for now this is the change that would help me!

**Comment by themsaid** [comment]
Closing since @60days  solution was merged.

**Comment by telkins** [comment]
@60days solution was merged on December 23rd and the latest release (2.1.4) was eight days ago. 
 According to `composer info`, I have version 2.1.4 locally, but when I look for @60days solution, I don't find anything.  I find the hard-coded Nova "ignore" in `Laravel\Telescope\Telescope` and nothing added in the config file.

Am I missing something?  Should I be more patient?

If it's released, which it seems like it should be, then perhaps someone can help me figure out what I'm missing or doing wrong.  If it's not released, then does anyone know when we might be able to expect it?

Thanks...!  :-)

**Comment by themsaid** [comment]
It was merged to master, will be available on the next major release.

**Comment by telkins** [comment]
@themsaid Thx for the info/update...!  :-)
