### ISSUE TITLE
ReflectionException on a wildcard event listener

### ISSUE THREAD

**Issue by riasvdv** [laravel/telescope#793]
- Telescope Version: 2.1.1
- Laravel Version: 6.7.0
- PHP Version: 7.4

### Description:

When Telescope is used in conjunction with our laravel-event-sourcing package, the ViewWatcher causes a ReflectionException (https://github.com/spatie/laravel-event-sourcing/issues/39)

The issue happens on this line https://github.com/laravel/telescope/blob/2.0/src/Watchers/ViewWatcher.php#L123

### Steps To Reproduce:

- New Laravel project
- composer require both laravel/telescope and spatie/laravel-event-sourcing
- Watch the welcome view throw an exception

**Comment by barryvdh** [comment]
I've had a similar issue reported when using Laravel Debugbar together with Telescope. Introduced with https://github.com/laravel/telescope/pull/766 so maybe @arjanwestdorp could take a look?

**Comment by arjanwestdorp** [comment]
@barryvdh sure will have a look now
