### ISSUE TITLE
Log catched exceptions

### ISSUE THREAD

**Issue by SamirMokiem** [laravel/telescope#795]
This package is amazing and helped my team and i very much!

But there is one downside we currently have. We try to create our code as good as possible to handle/catch exceptions. But i noticed that caught exception don't show up in telescope. When searching to find a sollution to also log caught exceptions i found out there is a php function that logs the exception IF the code is in de catch block. However this is not a good sollution in a large code base

Now my request is if it is possible to have telescope show the caught exception as a normal exception in the exceptions tab. This will reduce the clutter when trying to find the page/request this exception occured and shows. Or log it in the background

Thanks!

**Comment by themsaid** [comment]
use `report($e)` in your catch blocks.

```
catch(Exception $e){
    report($e);

    // handle here
}
```

**Comment by SamirMokiem** [comment]
So that is what i mean, this is not a good sollution and now that means i have to add that to all the catch functions. Can't this be implemented in telescope?

**Comment by nokios** [comment]
No. Telescope is user-land PHP. It is not possible for you to have an exception caught, do something with it while preventing it from bubbling up further, and expect some other part of the application to catch it.  It's just not technically possible w/o modifying core PHP code.

**Comment by amosmos** [comment]
@nokios I agree with you but do note that it is indeed gets logged in such cases... I think that means it can also be reported no?

Unless the log is a default in PHP or something and not part of telescope.

Thanks,
Amos
