### ISSUE TITLE
/telescope/views scans forever

### ISSUE THREAD

**Issue by jordonbaade** [laravel/telescope#796]
- Telescope Version: 2.1.2
- Laravel Version: 6.8.0
- PHP Version: 7.3.12
- Database Driver & Version: MySQL 8.0.18

### Description:

/telescope/views scans forever - looks likes data is being pulled properly - no console errors

![image](https://user-images.githubusercontent.com/840932/71034290-17f9c300-20e7-11ea-99ad-def310c3228d.png)

### Steps To Reproduce:

Install Laravel
Install Telescope
Check /telescope/views - it's fine with no results
Visit website home page
Check /telescope/views - scans forever

**Comment by driesvints** [comment]
@barryvdh do you have any thoughts on this?

**Comment by driesvints** [comment]
@jordonbaade did you republish your assets as described in the updating section of the docs? https://laravel.com/docs/6.x/telescope#installation

**Comment by barryvdh** [comment]
I see the issue, but not really sure why it's happening. It looks the same as other screens.

**Comment by barryvdh** [comment]
I think it's because `composers` is not always in the data. It will fail there. From #766

**Comment by barryvdh** [comment]
Should be fixed with https://github.com/laravel/telescope/pull/797

**Comment by driesvints** [comment]
Thanks @barryvdh!

**Comment by jordonbaade** [comment]
Thanks guys :)
