### ISSUE TITLE
Add search by time range

### ISSUE THREAD

**Issue by emargareten** [laravel/telescope#798]
It would be nice to add `startDate` and `endDate` to query options and filter them against `created_at`.

examples:

![image](https://user-images.githubusercontent.com/46111162/71326134-8c0be080-24c4-11ea-9412-b4402e58abf6.png)
---
![image](https://user-images.githubusercontent.com/46111162/71325958-4b12cc80-24c2-11ea-8097-ba03446d1b1c.png)
---
![image](https://user-images.githubusercontent.com/46111162/71325942-14d54d00-24c2-11ea-88e6-ef8e1a0c5919.png)

**Comment by emargareten** [comment]
Moved to laravel/ideas

**Comment by yordivd** [comment]
searching requests by time range would be a huuuge improvement! +1

**Comment by azaricstefan** [comment]
Agreed, this would help a lot when investigating some cases.

**Comment by wwwroth** [comment]
I've wanted this feature for awhile so I've begun a fork/branch for it. I've implemented the UI using `v-calendar`. Any help is more than welcome :)

https://github.com/wwwroth/telescope/commit/a704fb314eb36059f839580082a19b49f41cae23

**Comment by driesvints** [comment]
@wwwroth that's already looking pretty cool 👍

**Comment by azaricstefan** [comment]
I love it! @wwwroth

**Comment by emargareten** [comment]
@wwwroth Are you adding a timepicker as well?

**Comment by driesvints** [comment]
Unfortunately Taylor rejected the PR which means we won't be able to make this happen in Telescope, sorry folks.

Thanks for your work @wwwroth.

**Comment by azaricstefan** [comment]
@driesvints it's just for now. 
I would interpret this as we can merge this in the future when it's improved further. 

> "Unfortunately, I'm going to delay merging this code for now."

**Comment by wwwroth** [comment]
@azaricstefan It was thrown together rather quickly. If @taylorotwell gave the thumbs up to a more robust solution, I'll work on it further or you can help out. I'm not sure if he just doesn't want to take Telescope in that direction.

**Comment by azaricstefan** [comment]
It won't be an issue to make this feature more robust, I can help out here too @wwwroth, question is if this feature fits in Telescope roadmap and plans. @driesvints and @taylorotwell could answer that.

**Comment by henrypham299** [comment]
@azaricstefan @taylorotwell 

Do we have a plan to add this feature to Telescope?

**Comment by greyvugrin** [comment]
Was searching for this exact feature today, it's become a pain point for us to dig into any requests without being able to jump to a time range. The logs fill up pretty quickly on prod so unless an issue just happened browsing takes a while.

Hoping that it can be included. If there's more work to do on the PR side to get it accepted, maybe others can pick up the torch and tackle feedback.

**Comment by LWlook** [comment]
Wow such a feature would really help! @driesvints

**Comment by Mikael-R** [comment]
Do we have a plan to add this feature to Telescope?

**Comment by forwardcodetechstudio** [comment]
Still expecting something in this line as its tough to filter requests. Doesn't make any sense to keep loading more when I want to see logs generated 24 hours ago.

**Comment by arabi-lian** [comment]
@wwwroth  A package this big, and it doesn't even have a time filter!
