### ISSUE TITLE
Hydrated models count

### ISSUE THREAD

**Issue by AlinIonut** [laravel/telescope#800]
I see that debug bar has a nice future, hydrated models, witch count how many eloquent models are build in memory. It is very important for performance measure. I think it would be a nice future in telescope, and help a lot of people to debug memory usage and build faster apps.

**Comment by themsaid** [comment]
IMO displaying the requests that ran is enough, recording the retrieved model event can be very noisy for little gain.

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue and we'll re-open this issue.

**Comment by dansullivan86** [comment]
Any chance this can be reopened since Jonathan Reinink has been pushing it recently in his talks and on [Twitter](https://twitter.com/reinink/status/1235564575396777984?s=20) ?

**Comment by driesvints** [comment]
@dansullivan86 yep. Feel free to send in a pr!

**Comment by mathieutu** [comment]
Yeah, interessed by this metric too.

**Comment by driesvints** [comment]
Gonna close this as this isn't something we're gonna pursue ourselves but anyone's free to attempt a pr if they want.
