### ISSUE TITLE
Memory limit exceeded on Heroku test runner

### ISSUE THREAD

**Issue by eithed** [laravel/telescope#805]
- Telescope Version: 2.1.3
- Laravel Version: 6.9.0
- PHP Version: 7.3.11

### Description:

After installing Telescope, test runner on Heroku started giving me this error:

```
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 8192 bytes) in /app/vendor/laravel/telescope/src/Watchers/FetchesStackTrace.php on line 16
```

during the test-setup script that seeds the database (the seeder isn't that heavy, but it does a couple of things :D it surely doesn't exceed memory limit on my local, even when setting memory limit to 64M).

When investigating the issue on Heroku I tried adding

```
<env name="TELESCOPE_ENABLED" value="false"/>
```

to my `phpunit.xml`, but it didn't have any effect. Only preventing discovery via `composer.json`:

```
"extra": {
        "laravel": {
            "dont-discover": [
                "laravel/telescope"
            ]
        }
    },
```

and adding:

```
        if (!$this->app->runningUnitTests()) {
            $this->app->register(TelescopeServiceProvider::class);
        }
```

to my `AppServiceProvider::register` did the trick.

While I'm fine with preventing package discovery, I'd think that setting TELESCOPE_ENABLED flag should be enough to prevent Telescope.

---

As far as I'm aware of, installing Telescope, creating a seeder that is resource heavy and running it on Heroku test runner is enough to replicate the issue, however I'm unable to replicate it at this moment.

**Comment by zaratedev** [comment]
@eithed 
I have the same problem in my local environment, you solved the problem. 🤔
