### ISSUE TITLE
Package abandoned

### ISSUE THREAD

**Issue by shahvirag** [laravel/telescope#807]
- Telescope Version: ^2.1
- Laravel Version: ^6.0
- PHP Version: 7.2.0

### Description:
Package moontoast/math is abandoned, you should avoid using it. Use brick/math instead.

**Comment by RSpeekenbrink** [comment]
``Moontoast/Math`` is required by telescope to support large integers while making UUIDs. Thereby Ramsey/UUID should support an alternative package first. Made an issue, will be looking into making a PR later: https://github.com/ramsey/uuid/issues/286

**Comment by shahvirag** [comment]
[ramsey/uuid](https://github.com/ramsey/uuid/releases) 4.0 is available now.
