### ISSUE TITLE
Unable to run migrations on App Engine from endpoint

### ISSUE THREAD

**Issue by JasonTheAdams** [laravel/telescope#811]
- Telescope Version: 2.1.3
- Laravel Version: 6.5.2
- PHP Version: 7.2
- Database Driver & Version: MySQL 5.7

### Description:
We're running our application Google App Engine and I'd like to use Telescope in our development environment. One challenge with App Engine is that, because it's a "serverless" solution, there's no way to run anything from a console. The simple reason is that you don't have any kind of dedicated server that's yours — servers spin up and down as needed. As such, migrations (and other console commands) run accomplished by setting up an endpoint that fires the command, such as `/artisan/migrate`.

This leads me to my problem. When Telescope determines whether or not to include the migrations it checks `$this->app->runningInConsole()`. Hmm. In our case it's _not_ running the console and never will be. This becomes a blocker in running the Telescope migrations. A workaround could be to use the `APP_RUNNING_IN_CONSOLE` env variable, but I'm reluctant to use that as the application really isn't running in the console.

I'm happy to make a PR for this. Could we add a `TELESCOPE_INCLUDE_MIGRATIONS` env variable to forego the console check? Or perhaps add a `telescope:migrate` console command to explicitly run the migrations?

Open to ideas!

### Steps To Reproduce:
1. Create an endpoint that runs `php artisan migrate:fresh` and echos the command output
2. Manually hit the endpoint
3. Notice the Telescope migrations are not included

**Comment by driesvints** [comment]
Leaving this to @themsaid to reply.

**Comment by themsaid** [comment]
I don't have experience with App Engine. What do you think should change so it works for you?

**Comment by JasonTheAdams** [comment]
@themsaid In short, it's the `$this->app->runningInConsole` line that's problematic. Is this just intended to be a sort of optimization? I don't really understand it's intent.

I've provided a couple of options above. In short, either that line needs to be removed or there needs to be a way of bypassing it. Just imagine trying to run the migrations from an endpoint rather than the console — that's the exact scenario needed for App Engine (and any other serverless solution).

**Comment by driesvints** [comment]
We won't be supporting App Engine atm, sorry. If you can make changes in a non breakable way you're free to send in a PR. Thanks.
