### ISSUE TITLE
Knowing how many queries were run on the views

### ISSUE THREAD

**Issue by diogogomeswww** [laravel/telescope#813]
This would allow to know how many queries were run on a view an eventually detect n+1 query issues. 

Example:
![image](https://user-images.githubusercontent.com/11543163/72762458-8b578e80-3bd7-11ea-9725-596847a64445.png)

Adding a summary text and on each row adding an icon with tooltip to know which query run on the view.

I'm happy to do a PR.

**Comment by driesvints** [comment]
There's https://github.com/laravel/telescope/issues/774. Don't these appear for you in the queries tab?

**Comment by diogogomeswww** [comment]
Well that's not exactly the same thing.
So imagine an app, with many relations between models, many views being loaded. 
And one or more relations are not being eager loaded on the backend.
So we probably are running queries on the views.

Right now we don't have an easy way to find those queries.

What about this summary: 
![image](https://user-images.githubusercontent.com/11543163/72886739-42e8bf80-3d02-11ea-8681-056c1899debe.png)

I'm just counting the number of queries that were run on each file/line.

I can immediately see that I'm running 10 queries on the same view/line.

**Comment by themsaid** [comment]
Wouldn't all these queries appear each in a row? I think that's enough for you to realize a problem exists.

**Comment by diogogomeswww** [comment]
No, the file/line is not showed on each row.
I need to open each query to see the file/line.

So if I have 100 queries, I will need to open each one to find it.
And I will not know how many queries were run on the same place.

What about making that info just a tooltip? The cons of this, will be that we wouldn't be able to copy the path.
Or a toggle visibility icon?
And just showing the duplicated (count > 1).

**Comment by themsaid** [comment]
Using ` x of which are duplicated` you can easily identify the request has a problem and with a quick look you can find which query is causing issues. It seems very easy to spot to me.

**Comment by diogogomeswww** [comment]
Well it's not very easy to spot when you have 100+ queries on a request.
Even more when those queries are long and are truncated.
At least for me its not easy to find the problem.

Feel free to close it if you don't find it useful.
Thanks

**Comment by themsaid** [comment]
I think I'll close this for since there doesn't seem to be support from others regarding the feature.
