### ISSUE TITLE
Telescope Polling/Duplication even when screen not in view

### ISSUE THREAD

**Issue by RTippin** [laravel/telescope#814]
- Telescope Version: 2.1.0
- Laravel Version: 6.12.0
- PHP Version: 7.3.11
- Database Driver & Version: MySQL 8.0.15

### Description:
The background polling request will sometimes continue for a screen that is no longer in view, and even duplicate multiple times depending how many times you click to different tabs.

### Steps To Reproduce:
Once in telescope, open the network console and wait to change which screen/tab you are viewing in telescope until you see the polling request fire off. It seems if I am able to switch screens before the request finishes, the interval for that screen is never reset and continues on. 

Here is a screenshot showing me in the Logs screen, after previously going from Schedule screen, Commands screen, then back to logs screen. Logs poll is now duplicating, and the Commands and Schedule polls still fire off

![image](https://user-images.githubusercontent.com/3917769/73105868-08c91a80-3ec8-11ea-8de7-e7a2912fb4cf.png)

**Comment by driesvints** [comment]
I suspect this is to allow those views to be easily switched to without having them to re-render every single time you navigate to them. But I'm gonna let @themsaid confirm.

**Comment by RTippin** [comment]
The main reason I feel this to be unintended behavior is due to the fact if you go to a tab and leave, and go back multiple times, the interval poll for that tab will duplicate multiple times over. Thus, I could be on the Request tab, but the poll [ /telescope-api/requests?tag=&before=&take=50&family_hash= ] will fire off multiple of the same instead of one per 3 seconds.

**Comment by themsaid** [comment]
I can't replicate this. When I move away from a tab the interval is destroyed and I don't see any requests for this tab coming.
