### ISSUE TITLE
Switch to new moontoast/math package

### ISSUE THREAD

**Issue by buismaarten** [laravel/telescope#815]
When I install Laravel Telescope I get the following warning:
`Package moontoast/math is abandoned, you should avoid using it. Use brick/math instead.`

**Comment by driesvints** [comment]
Feel free to send in a PR.

**Comment by klimov-paul** [comment]
Note that "laravel/telescope" itself does not use "moontoast/math" directly - it is used by "ramsey/uuid", which is required by "laravel/framework" for UUID generation.

In "ramsey/uuid" "moontoast/math" is an optional requirement, that is why it is added to "require" composer section of "laravel/telescope".

At the present state "ramsey/uuid" has already switched to "brick/math", but this changeset is available only as alpha version:
https://packagist.org/packages/ramsey/uuid#4.0.0-alpha1

This issue will stay on hold until "ramsey/uuid" stable "4.x" release.

**Comment by driesvints** [comment]
@klimov-paul correct. This probably needs to go to the next version branch.

**Comment by klimov-paul** [comment]
Not necessary.
Since "brick/math" is going to become a required part of "ramsey/uuid" instead of recommended, you may replace `"moontoast/math": "^1.1"` with `"ramsey/uuid: ^4.0"` once it is released.
It should not cause any BC break.

**Comment by driesvints** [comment]
@klimov-paul current version of Telescope allows for Laravel 5.8 & 6.x while we plan to require a minimum of ramsey/uuid ^4.0 in Laravel 7.

**Comment by klimov-paul** [comment]
Indeed.
Since Laravel requires `"ramsey/uuid": "^3.7"` my suggestion will not help.
Still I would consider to `"ramsey/uuid": "^4.0"` and Framework 6.x minor version instead of waiting until 7.0. But it is your call.

**Comment by driesvints** [comment]
Hmm, that may be possible yeah. I quickly went through https://github.com/ramsey/uuid#upgrading-from-3x-to-4x but I can't immediately see breaking changes for us.

**Comment by lomotech** [comment]
Any update about this? Since laravel 7.3 can using `ramsey/uuid:4.0` already or did we have any issue that I'm missing.

**Comment by driesvints** [comment]
@lomotech we're open to prs.

**Comment by driesvints** [comment]
This will be fixed when we eventually release Telescope v4.

**Comment by Oluwatobilobaoke** [comment]
hello @driesvints  have you fixed the issue because I'm still receiving the error

**Comment by driesvints** [comment]
No plans atm yet. It's just a warning so ignore it for now.
