### ISSUE TITLE
How can I custom auth guard in Telescope?

### ISSUE THREAD

**Issue by zhouzishu** [laravel/telescope#816]
I have different guards in my Laravel project: `web` , `admin`, `api.` . But I can't use authorization for Telescope except `web` guard.

I think it'd better work with custom guard in config `telescope`, just like laravel nova, right?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by danielpetrica** [comment]
Hi @zhouzishu did you get an answer somewhere else? I need the same guard change for one of my project but can't find anything else on google. Thank you and sorry for resurrecting this issue after so much time.
