### ISSUE TITLE
Custom Notifications are always marked as Queued

### ISSUE THREAD

**Issue by nikkuang** [laravel/telescope#823]
- Telescope Version: 2.1.5
- Laravel Version: 6.14.0
- PHP Version: 7.3.12
- Database Driver & Version: MySQL 5.7.28

### Description:
When using a custom [channel](https://github.com/laravel-notification-channels/fcm). The notification are always marked as Queued, even though it was processed or it failed.

![image](https://user-images.githubusercontent.com/6487764/73812672-9ede3880-4818-11ea-90d6-7dd2050b8cc2.png)

As you can see in the jobs menu, it was marked as `failed` or `processed`

![image](https://user-images.githubusercontent.com/6487764/73812357-76a20a00-4817-11ea-9706-c9b8bf6f70a1.png)

### Steps To Reproduce:

Install the custom notification package from [laravel-notification-channels/fcm](https://github.com/laravel-notification-channels/fcm), and follow the installation instruction.

Once set up, try sending a notification using the this channel with the `notify` method

`$user->notify(new MessageSent());`

**Comment by themsaid** [comment]
"Queued" means the notification was queued. It implements `ShouldQueue`
