### ISSUE TITLE
RequestWatcher front-end JSON.Parse exception when responses contain "invalid" json.

### ISSUE THREAD

**Issue by Calytic** [laravel/telescope#826]
- Telescope Version: 2.1.5
- Laravel Version: 5.8.36
- PHP Version: 7.2.24

### Description:

We have several json endpoints that can include json with escaped quotations or even HTML characters.

```json
{
     "variable": "some \"text\""
}
```
When inspecting the "Requests" section of the Telescope front-end after such a request, the request list does not load or update automatically.

In the javascript console there is the following message..
`TypeError: n.data.entries is undefined`

When inspecting the request, (e.g. `http://localhost/telescope/telescope-api/requests?tag=&before=&take=50&family_hash=`) the following message is printed..
`SyntaxError: JSON.parse: bad escaped character at line 1 column 73360 of the JSON data`

### Steps To Reproduce:

1. Install laravel
2. Install telescope
3. Disable the default telescope service filter to log all requests
4. Create a route `/test.json`
5. Create a controller action which return a json response that includes "invalid" json (mentioned above)
6. Visit `/test.json` route
7. Visit requests section of the telescope front-end

**Comment by themsaid** [comment]
I can't replicate your issue. If the JSON is invalid we show `HTML RESPONSE`.

**Comment by Calytic** [comment]
When I inspect my raw query output from the test url, say for example it has an escaped character (e.g. backslash or quotations)...

```json
{
     "variable": "some <br \/>&quote;text&quote;"
}
```

This is considered valid JSON by laravel and outputs valid JSON to the browser.

When I inspect the `request.content.response` as recorded by telescope for the same request, I see something like this..

```json
{
     "variable": "some <br \>\"text\""
}
```

The response is being recorded as valid JSON, but the JSON being recorded is not valid JSON.  It appears to be url decoded before being converted back into JSON but I'm not entirely sure.

Hope this helps.

**Comment by driesvints** [comment]
I couldn't reproduce this either with the above steps I'm afraid. Please provide a test repo that reproduces the problem. Please commit your custom changes separate from the base Laravel installation.
