### ISSUE TITLE
Add Metrics Dashboard

### ISSUE THREAD

**Issue by ManojKiranA** [laravel/telescope#827]
Add Dashboard metrics based on the Telescope Entries.

For Example 
1. No of Requests
2. No of Queries
and Much more.

Recently i came up with a package which almost does the same except the metrics dashboard

https://github.com/sarfraznawaz2005/meter

![image](https://user-images.githubusercontent.com/30294553/74002775-459c1380-4996-11ea-8c9f-fe209dd0eba8.png)

And if possible there must be option to add new cards in Dashboard

such as
```

function cards(){
TotalQueriesLastHour::class,
TotalRequestsLastHour::class,
//all classes
}

maybe 

class TotalQueriesLastHour implements TelescopeDashboardCard{
//all props and functon
}
```

**Comment by ryangjchandler** [comment]
I love this idea. Would be happy to work on this too, I'm running a custom solution at the moment on a project but would be great if I could use Telescope too.

**Comment by ctstimjackson** [comment]
I think this would be a great addition to Telescope as well. Maybe things like:

- Top 25 routes
- Number of exceptions (unresolved/resolved)
- A filter for queries that are above the 'slow' threshold
- A similar filter/threshold for request response time

**Comment by mohitpawar10** [comment]
We can take https://sentry.io/ reference.

**Comment by azaricstefan** [comment]
This is a great idea, I would love to see this in telescope!

**Comment by deviouspk** [comment]
Would love to see this in telescope aswell!

**Comment by driesvints** [comment]
Hey all. Thank you for your enthusiasm but please abstain from posting comments that you'd like to see this in Telescope. Instead, please help out by discussing how we'd implement this practical or by sending in a PR.

**Comment by driesvints** [comment]
Hey all. This definitely is a good idea and something we'd like to see in Telescope. However, since we won't be working on this ourselves any time soon I'm closing this. We'd still appreciate a PR if anyone's willing to work on this.
