### ISSUE TITLE
Developing in Docker but cache connection required during package discovery process

### ISSUE THREAD

**Issue by danvim** [laravel/telescope#828]
- Telescope Version: 2.1.3
- Laravel Version: 6.9.0
- PHP Version: 7.4

### Description:

This issue has been raised before #620. But the resolution was really a work around at that point. I wanted to bring the issue forth once more.

I'm using Docker Compose **as a development and production environment**. And previously, "Disabling telescope for builds seems a reasonable solution." does not work in my case.

My Docker Compose file includes the following:

- Laravel application built using a `Dockerfile` that includes `compose install`
- DB
- Redis, exposing internal endpoint `my_redis:6379`
- Nginx

The problem arises when a new developer tries to clone the project, setup the development environment and build everything fresh. During Docker's build process, Telescope tries to connect to the endpoint `my_redis:6379`, which isn't up yet, thus fails to build. So, Docker Compose cannot up any containers, (including Redis).

I wanted Telescope to work in my local development environment in Docker Compose. My current mitigation method is to add `--no-scripts` to `composer install` during my Docker build, and instead, run `composer dumpautoload` when the container starts.

For my case, it doesn't make sense to disable Telescope. My current mitigation method has a slow container start time. Is there anyway this problem can be fixed one way or another?

I've made a StackOverflow issue a while ago: https://stackoverflow.com/questions/59810019/dockerfile-build-laravel-trying-to-connect-to-redis-service-yet-to-up **My example `docker-compose.yml` is here.**

### Steps To Reproduce:

1. Setup Docker Compose file and add the Laravel service built with a custom `Dockerfile` that includes `compose install`. Add Redis service with name `my_redis`.
2. Require Telescope in the Laravel application.
3. Setup to use Redis in `.env` for cache/queue/etc, and setup `REDIS_HOST` to be the Docker Compose service endpoint, e.g. `my_redis`
4. Enable Telescope.
5. Run `docker-compose build` in this fresh project.

**Comment by kohlerdominik** [comment]
- Telescope Version: 3.2.0
- Laravel Version: 7.2.0
- PHP Version: 7.3

We can confirm a similar issue. That the cache connection is required is a big drawback for using Telescope.

### In addition to the initial description
It’s not possible to run any command, not even `artisan help`, without having the redis instance up and running.
Especially, it’s not possible to run `artisan package:discover`, which is automatically triggered by `composer install`. 

### The issue in our use case
Beside of the initial raised issue description, there is an additional use case: If a builder container is used, based on [hub.docker.com/_/composer](https://hub.docker.com/_/composer) for example, it’s usually not the case to have the redis dependency set up nor to have ext-redis installed (except if it’s added in a custom build, which just increases container overhead without actual benefit).

#### Steps to reproduce
1.	Clone a fresh Laravel installation `git clone https://github.com/laravel/laravel.git`
2.	Add laravel as required `"laravel/telescope": "^3.1",` → `composer.json`
3.	Run the original composer container to install dependencies: 
`docker run --rm --interactive --tty --volume $PWD:/app composer install --ignore-platform-reqs`

**Comment by driesvints** [comment]
Hello everyone. Since a majority of developers aren't experiencing this particularly issue it's hard to focus our attention to solving this (more so because we're not using Docker ourselves). If you want to get Telescope to work better with Docker we're welcoming prs. Thanks for raising this.

**Comment by Eldair** [comment]
Same issue here
In short, the package is attempting to connect to redis during package discovery process and on some (maybe every) artisan command (basically I can not use artisan tinker unless there is a redis server running while telescope is enabled)

**Comment by killgt** [comment]
It's just not a docker problem, you can have the issue anywhere where you don't have a redis service running. The problem it's the discover will touch the cache, you can fix this by settings the .env with:

`CACHE_DRIVER=file`

I'm doing this in a step before running composer install and resetting it after all artisan commands run.

**Comment by lopezdonaque** [comment]
Same error here.
The problem is due to the DumpWatcher.
Disabling it will fix the error.
I think it should not be executed during the package:discover.

`
        if (! $this->cache->get('telescope:dump-watcher')) {
            return;
        }
`

`
Watchers\DumpWatcher::class => env('TELESCOPE_DUMP_WATCHER', false),
`

**Comment by danvim** [comment]
> 
> 
> It's just not a docker problem, you can have the issue anywhere where you don't have a redis service running. The problem it's the discover will touch the cache, you can fix this by settings the .env with:
> 
> `CACHE_DRIVER=file`
> 
> I'm doing this in a step before running composer install and resetting it after all artisan commands run.

I would argue it is normally not an issue since nobody would realistically run telescope without their cache instance running. Therefore, my aim of this issue was to ask for a feature to turn off connection requirement (with or without a special option) during package discovery.

**Comment by screw** [comment]
> Same error here. The problem is due to the DumpWatcher. Disabling it will fix the error. I think it should not be executed during the package:discover.
> 
> `if (! $this->cache->get('telescope:dump-watcher')) { return; }`
> 
> `Watchers\DumpWatcher::class => env('TELESCOPE_DUMP_WATCHER', false),`

Where do you put this code?

**Comment by jaketoolson** [comment]
> > Same error here. The problem is due to the DumpWatcher. Disabling it will fix the error. I think it should not be executed during the package:discover.
> > `if (! $this->cache->get('telescope:dump-watcher')) { return; }`
> > `Watchers\DumpWatcher::class => env('TELESCOPE_DUMP_WATCHER', false),`
> 
> Where do you put this code?

This goes in your `telescope` config file.

**Comment by jaketoolson** [comment]
@screw - This goes in your `telescope` config file.

**Comment by NilLlisterri** [comment]
In our case, the best solution has also been disabling the dump watcher in the telescope config file (`config/telescope.php`), as we were filtering those entries anyway.

```
Watchers\DumpWatcher::class => [
    'enabled' => env('TELESCOPE_DUMP_WATCHER', false),
    'always' => env('TELESCOPE_DUMP_WATCHER_ALWAYS', false),
],
```
