### ISSUE TITLE
Array to String conversion IncomingEntry.php

### ISSUE THREAD

**Issue by vdbMark** [laravel/telescope#833]
- Telescope Version: 2.1.^
- Laravel Version: 6.9.0
- PHP Version: 7.4.0
- Database Driver & Version:
MariaDB

Migration causes an Array to String conversion.
I have the following migration which is working fine up until the second insert.
![image](https://user-images.githubusercontent.com/52448924/75048196-6bfa9c80-54c8-11ea-8e6b-ad28fea35ff5.png)

![image](https://user-images.githubusercontent.com/52448924/75048250-7fa60300-54c8-11ea-87ab-ceeca7727383.png)

Stacktrace:
![image](https://user-images.githubusercontent.com/52448924/75048381-b54aec00-54c8-11ea-957d-f7a004c84b9b.png)

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by developers-at-vandyckbrown** [comment]
Hey!

i've updated the package and am currently running v3.0.0.
I'll try to find some more information, i didn't see this problem on my staging or local development environment, could it be something with php 7.4? (my other environments run in 7.2)

**Comment by vdbMark** [comment]
Hey!

i've updated the package and am currently running v3.0.0.
I'll try to find some more information, i didn't see this problem on my staging or local development environment, could it be something with php 7.4? (my other environments run in 7.2)

**Comment by driesvints** [comment]
@vdbMark I can run Telescope just fine on PHP 7.4

**Comment by vdbMark** [comment]
So i went to see what values caused the error:
![image](https://user-images.githubusercontent.com/52448924/75140932-2cae9480-56f0-11ea-9c27-c050209cfbd5.png)

Something is giving a 2d array instead of a model 
![image](https://user-images.githubusercontent.com/52448924/75140889-16083d80-56f0-11ea-9d48-4b756ccbae11.png)

**Comment by zkang93** [comment]
If you are using stancl/tenant package, please comment out 
Stancl\Tenancy\Features\TelescopeTags::class in config/tenancy.php under features array.

**Comment by vdbMark** [comment]
We are not using tenancy. I ended up removing this piece of code which solved the problem for now
