### ISSUE TITLE
Validation errors shown as HTTP 302

### ISSUE THREAD

**Issue by buismaarten** [laravel/telescope#834]
- Telescope Version: 3.0.0
- Laravel Version: 6.16.0
- PHP Version: 7.4.1
- Database Driver & Version: 5.7.28-0ubuntu0.18.04.4 - (Ubuntu)

### Description:
POST requests like login should return HTTP 422, somehow it returns 302 without validation messages in the Response section in Telescope. In another project with Laravel 5.8 and Telescope v2 it behaves the correct way.

### Steps To Reproduce:
- Laravel installation with authentication.
- Laravel Telescope installation.
- Submit login screen with non-existing credentials.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
