### ISSUE TITLE
No Authenticated User Information

### ISSUE THREAD

**Issue by JonPurvis** [laravel/telescope#836]
- Telescope Version: 3.0
- Laravel Version: 6.0.0
- PHP Version: 7.4.2
- Database Driver & Version: MySQL 5.7

### Description:
Since I updated, I haven't been getting Authenticated User information for Requests in the Telescope dashboard. I'm definitely Authenticated as I'm testing it on pages that require Authentication. 

### Steps To Reproduce:
Load up any page and check Telescope. There's no block for "Authenticated User"

**Comment by driesvints** [comment]
Seems to be working fine for me on a fresh Laravel install.

![Screenshot 2020-02-24 at 07 53 13](https://user-images.githubusercontent.com/594614/75133360-bf443900-56da-11ea-9020-e19a627a01ba.png)

**Comment by hesham-abboud** [comment]
@driesvints it used to show it at the beginning, now it totally stopped for all users

**Comment by JonPurvis** [comment]
@hesham-abboud What version of Laravel are you using? I updated to 6.16.0 and it fixed it for me.

**Comment by hesham-abboud** [comment]
@JonPurvis 5.8. After the fresh installment of telescope it was showing the user normally. I added few filters for easier debugging and it's gone. reverting back the changes doesn't seem to fix it. 
When I give it a closer look, in method register, adding tags in Telescope::tag block, the passed entry should contain user, it's always null

**Comment by driesvints** [comment]
@hesham-abboud 5.8 isn't supported anymore unfortunately. Please upgrade to 6.0 (or better: 7.0 next week).
