### ISSUE TITLE
telescope_entries still 10GiB after telescope:clear.

### ISSUE THREAD

**Issue by werthd** [laravel/telescope#837]
- Telescope Version: 2.1
- Laravel Version: 5.8
- PHP Version:  7.2
- Database Driver & Version:
Mysql 14.14
### Description:
When using 
`php artisan telescope:clear`
the Entries are deleted but the .idb file for telescope_entries still uses a lot of space.

This caused my Laravel page to  throw a 500.
Running the 
```sql
optimize table telescope_entries;
```
fixed the Problem for me.
Please add this to optimize the mysql database automatically.
This would also be interesting for the schedule command
`telescope:prune`

### Steps To Reproduce:
1. Fill up the telescope_entries table
2. run `php artisan telescope:clear`
3. check if the the table is empty
4. look at the file size (in my case it was 10GiB)

I'm sorry for any grammar mistakes!
Thanks for Telescope!

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by barryvdh** [comment]
InnoDB doesn't free the space on disk after reducing the data in your database. You could try to export + import to a new database if you need to.

**Comment by ulcuber** [comment]
To free space:
`alter table telescope_entries ENGINE=InnoDB;`
As MySQL **.idb** not reduced automatically.
Technically it creates new table (temp) then removes old table and renames temp table to old table name, so space freed, as new table not yet fragmented and not yet increased.

**Comment by tegos** [comment]
Here is post with similiar problem and explaination, check it out.
[Efficiently Managing Telescope Entries with Laravel-Telescope-Flusher](https://dev.to/tegos/efficiently-managing-telescope-entries-with-laravel-telescope-flusher-484a)
