### ISSUE TITLE
Array to string conversion

### ISSUE THREAD

**Issue by finagin** [laravel/telescope#838]
- Telescope Version: 3.1.0
- Laravel Version: 6.17.0
- PHP Version: 7.3.11
- Database Driver & Version:

### Description:
`\Laravel\Telescope\IncomingEntry::tags` expect **array of string** like `['tag1', 'tag2']` but `array_map` in `\Laravel\Telescope\Telescope::record` returns **array of array of string** like `[['tag1', 'tag2']]`

### Steps To Reproduce:
1. Create user tags in `\App\Providers\TelescopeServiceProvider::register` with `\Laravel\Telescope\Telescope::tag`
1. Enable strict mode for throw notice as exception 
1. Catch "Array to string conversion" exception

**Comment by themsaid** [comment]
Fixed in https://github.com/laravel/telescope/pull/839
