### ISSUE TITLE
Allow recording of default ignored events in configuration file

### ISSUE THREAD

**Issue by IvoMiranda** [laravel/telescope#840]
I see there is an option to ignore additional events but what about not ignoring system events? For example, I would like to record Auth events and I can't find an option for this.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by Braunson** [comment]
@IvoMiranda If you want to record internal auth events, a workaround might be to create your own listener for internal auth events, then fire your own custom "auth" event that does get recorded..

Not ideal but it's an option.

**Comment by IvoMiranda** [comment]
@Braunson thank you. I also think your suggestion is the best for a quick solution. Although I think it could be interesting as a feature to have certain events not ignored by the default ignore. I understand by default most developers will not want to bloat telescope with system events but Illuminate pattern is ignoring Auth and probably other important packages that developers will want to include sometimes.

**Comment by Braunson** [comment]
@IvoMiranda Put in a PR for a whitelist option in the Telescope config then :)
