### ISSUE TITLE
Array to string conversion

### ISSUE THREAD

**Issue by Miljan9602** [laravel/telescope#845]
- Telescope Version: v3.1.1
- Laravel Version: 6.16.0
- PHP Version: 7.3.6
- Database Driver & Version:
PhpRedis

### Description:
When using telescope with zrangebyscore with the 'limit' option.

### Steps To Reproduce:
When performing this redis operation.

```
Redis::zrangebyscore($key, 0, $fromTime, [
            'limit' => [
                'offset' => 0,
                'count' => $count
            ]
        ]);
```

```
/**
     * Format the given Redis command.
     *
     * @param  string  $command
     * @param  array  $parameters
     * @return string
     */
    private function formatCommand($command, $parameters)
    {
        $parameters = collect($parameters)->map(function ($parameter) {
            if (is_array($parameter)) {
                return collect($parameter)->map(function ($value, $key) {
                    return is_int($key) ? $value : "{$key} {$value}";
                })->implode(' ');
            }

            return $parameter;
        })->implode(' ');

        return "{$command} {$parameters}";
    }
```

This method breaks. Because  with the redis command and with this option $value is array. 
return is_int($key) ? $value : "{$key} {$value}";

Because this check fails is_int($key) because $key is  "limit". And then it will try to assign 
"{$key} {$value}" and it will throw Array to string conversion error because $value holds array value.

**Comment by Miljan9602** [comment]
Which more info do you need ? @driesvints 
Have you ever tried using telescope with 
  `Redis::zrangebyscore($key, 0, $fromTime, [
            'limit' => [
                'offset' => 0,
                'count' => $count
            ]
        ]);`
Command ?

**Comment by driesvints** [comment]
@Miljan9602 I've assigned this to @themsaid to have a look at when he finds time.

**Comment by Miljan9602** [comment]
What is happening with this ?

**Comment by driesvints** [comment]
We don't have time for this ourselves atm sorry.

**Comment by driesvints** [comment]
I've found some time to look into this and managed to reproduce it. Sent in a PR: https://github.com/laravel/telescope/pull/873
