### ISSUE TITLE
Telescope with MongoDB

### ISSUE THREAD

**Issue by oktaykalfa** [laravel/telescope#846]
- Telescope Version: 3.1.1
- Laravel Version: 6.5.0
- PHP Version: 7.2
- Database Driver & Version: MongoDB

### Description:
Can i use Telescope with MongoDB? Records can be added to DB but i can't see them on /telescope dashboard. It returns 

{message: "Call to a member function prepare() on null",…}
exception: "Symfony\Component\Debug\Exception\FatalThrowableError"
file: "/var/www/html/broc/vendor/laravel/framework/src/Illuminate/Database/Connection.php"
line: 326
message: "Call to a member function prepare() on null"
trace: [,…]

**Comment by rasim** [comment]
Hello @oktaykalfa, 

open: Storage/EntryModel.php

find: 
`
use Illuminate\Database\Eloquent\Model;
`

replace: 
`
use Jenssegers\Mongodb\Eloquent\Model;
`

and find:

```
 ->whereBeforeSequence($query, $options)
 ->filter($query, $options);
```

replace:

```
->whereBeforeSequence($query, $options);
//->filter($query, $options);
```

and find:

```
$query->where('should_display_on_index', true);
```

replace:
 ```
$query->where('should_display_on_index', false);
```

will work this way.

**Comment by oktaykalfa** [comment]
Hello @rasim, 

Thanks for your response. I thank you so much but this is not the way we wanted to use it. We are not prefering change anything in vendor so we gave up to use it.

Best Regards.
