### ISSUE TITLE
Black page

### ISSUE THREAD

**Issue by Skinka** [laravel/telescope#849]
- Telescope Version: 3.2.0
- Laravel Version: 6.18.2
- PHP Version: 7.3
- Database Driver & Version: PostgreSQL

After moving to production server i have blank page. After load app.js removed all html in body.
I don't have any errors.

I reloaded composer, make telescope:install and telescope:publish repeatedly

![photo_2020-03-19_15-15-56](https://user-images.githubusercontent.com/7543469/77066656-9c185b00-69f4-11ea-8db1-856133564b53.jpg)

**Comment by driesvints** [comment]
I can run Telescope just fine. Please try asking this on a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks.
