### ISSUE TITLE
Target class [env] does not exist. when running unit tests after Telescope is installed

### ISSUE THREAD

**Issue by jellisii** [laravel/telescope#850]
- Telescope Version: v3.2.0
- Laravel Version: v6.18.2
- PHP Version: 7.3.15-3+ubuntu18.04.1+deb.sury.org+1
- Database Driver & Version: PDO/SQLite 3.22.0

### Description:

When trying to run unit tests on my laravel project, I get errors when attempting to test anything that uses the Laravel framework.  See #347, as it is identical to that.  

A small snippet from the unit test output. 

```
 11:10:35  me@mybox 
$ phpunit
PHPUnit 8.5.2 by Sebastian Bergmann and contributors.

..EEEF                                                              6 / 6 (100%)

Time: 631 ms, Memory: 32.00 MB

There were 3 errors:

1) Tests\Unit\UserModelTest::in_can_retrieve_a_user
Illuminate\Contracts\Container\BindingResolutionException: Target class [env] does not exist.
```
I've attached files with output, as well as the .env.testing and the unit test created to trigger the error.

The fix noted [Here on #347](https://github.com/laravel/telescope/issues/347#issuecomment-504154847) does sidestep the issue.  If this is the correct fix, it may just need documenting.  

### Steps To Reproduce:
```
composer create-project --prefer-dist laravel/laravel telescopeTest "6.*"
cd telescopeTest
composer require laravel/telescope
// create a SQLite database
// create .env.testing that uses the created SQLite database
// create a CRUD test for the user table
// unit tests work as expected until this artisan command.  
php artisan telescope:install
// unit tests run after this fail as described above.  
```
### Files:

[env.testing.txt](https://github.com/laravel/telescope/files/4355503/env.testing.txt)
[UserModelTest.php.txt](https://github.com/laravel/telescope/files/4355505/UserModelTest.php.txt)
[composer_create_output.txt](https://github.com/laravel/telescope/files/4355508/composer_create_output.txt)
[telescope_install_output.txt](https://github.com/laravel/telescope/files/4355512/telescope_install_output.txt)
[phpunit_output.txt](https://github.com/laravel/telescope/files/4355518/phpunit_output.txt)

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
