### ISSUE TITLE
All Mail fails to display if any entry has a null to address

### ISSUE THREAD

**Issue by hackel** [laravel/telescope#851]
- Telescope Version: 3.2.0
- Laravel Version: 6.18.2
- PHP Version: 7.4.3
- Database Driver & Version: MySQL 8

### Description:
I accidentally sent an email without a to address.  This was recorded correctly in Telescope, however it prevents the entire list of emails from displaying.  When loading the Mail index, it just shows "Scanning..." indefinitely.  No JS console or other errors are shown.

If I check the HTTP response, the call to `/telescope/telescope-api/mail?tag=&before=&take=50&family_hash=` returns a valid response with all of my mail entries.  I started going through and removing the old mail telescope_entries until it worked again, and the discovered that the offending record contained `content->to = null`.

### Steps To Reproduce:
Create a new Notification, and return a Mailable from the `toMail` method, but fail to call `to()` on it to specify a recipient address.

**Comment by driesvints** [comment]
Telescope didn't record the mail for me. If you can add very specific sets to reproduce this we'll have another look. Thanks.
