### ISSUE TITLE
The word 'tags' is ambiguous in cache context

### ISSUE THREAD

**Issue by piperone** [laravel/telescope#852]
The word "Tags" is used in Telescope on the Cache-related pages. For new users unfamiliar with the concept of tagging in [Telescope](https://laravel.com/docs/7.x/telescope#tagging) and Horizon, this could be misleading because "tagging" is also something one does when storing items in the cache.

I suggest a disambiguation in the form of a note be added to the relevant pages to indicate that the word "tag" refers to Telescope's tags and not cache tags.

Thank you.

**Comment by driesvints** [comment]
No plans on changing this sorry
