### ISSUE TITLE
AfterRecordingHook doesn't pass the IncomingEntry object

### ISSUE THREAD

**Issue by MatanYadaev** [laravel/telescope#862]
For some reason the `AfterRecordingHook` passes the `Telescope` object instead of the `IncomingEntry` object, is that a reason for this behavior? 

For my use-case, I would prefer receiving the `IncomingEntry` itself, to be able to do some logic on it.

https://github.com/laravel/telescope/blob/b6f903533d054030f0c24def89fa7c57fd33c3ed/src/Telescope.php#L272

Origin: https://github.com/laravel/telescope/pull/462/files#r403687515

**Comment by driesvints** [comment]
No idea really. Feel free to PR. Think this might have to go into the next version branch.

**Comment by MatanYadaev** [comment]
I want to PR. Should I replace this parameter or add besides it?

**Comment by driesvints** [comment]
Replace I think

**Comment by driesvints** [comment]
Closing as it turns out that this is intentional.
