### ISSUE TITLE
Filter queries by table

### ISSUE THREAD

**Issue by lucas-santana** [laravel/telescope#864]
I don't want the Telescope to capture some queries made on some tables.
Through Telescope :: filter on TelescopeServiceProvider, I can filter by $ entry-> type === 'query'.
How can I filter the tables?
How do I know which table this query is from?
My TelescopeServiceProvider.php
```
public function register()
    {
        // Telescope::night();

        $this->hideSensitiveRequestDetails();

        Telescope::filter(function (IncomingEntry $entry) {

            if($entry->type==='query'){
                //How do I know which table this query is from?
            }

            if ($this->app->environment('local')) {
                return true;
            }


            return $entry->isReportableException() ||
                   $entry->isFailedRequest() ||
                   $entry->isFailedJob() ||
                   $entry->isScheduledTask() ||
                   $entry->hasMonitoredTag();
        });
    }
```
It would be interesting to have this functionality.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by lucas-santana** [comment]
Hi there,
I opened the issue to have this functionality in the Laravel telescope.  
Are you trying to say that the laravel telescope already filters queries by table?
 I already researched the issues and the internet and found nothing about this functionality.
