### ISSUE TITLE
Failing installation

### ISSUE THREAD

**Issue by kyobul** [laravel/telescope#868]
- Telescope Version: 3.2 / latest
- Laravel Version: 7.5 / latest
- PHP Version: 7.4.1
- Database Driver & Version: MariaDB latest / MySQL
Windows 10 / latest updates / Laragon web server / latest

### Description:
Existing or fresh installation of Laravel
`php artisan telescope:install` gives : 

```
file_get_contents(C:\laragon\www\laravel7\app\Providers/TelescopeServiceProvider.php): failed to open stream: No such file or directory

  at C:\laragon\www\laravel7\vendor\laravel\telescope\src\Console\InstallCommand.php:77
    73|
    74|         file_put_contents(app_path('Providers/TelescopeServiceProvider.php'), str_replace(
    75|             "namespace App\Providers;",
    76|             "namespace {$namespace}\Providers;",
  > 77|             file_get_contents(app_path('Providers/TelescopeServiceProvider.php'))
    78|         ));
    79|     }
    80| }
    81|

  1   C:\laragon\www\laravel7\vendor\laravel\telescope\src\Console\InstallCommand.php:77
      file_get_contents("C:\laragon\www\laravel7\app\Providers/TelescopeServiceProvider.php")

  2   C:\laragon\www\laravel7\vendor\laravel\telescope\src\Console\InstallCommand.php:40
      Laravel\Telescope\Console\InstallCommand::registerTelescopeServiceProvider(
)```

Then running  `php artisan telescope:install `again, gives : 
```
Publishing Telescope Service Provider...
Publishing Telescope Assets...
Publishing Telescope Configuration...
Telescope scaffolding installed successfully.
```
BUT no files are copied or published, anywhere

Then running `php artisan migrate` gives : 
`Nothing to migrate.`

Result : Telescope is not installed

### Steps To Reproduce:
1. Install Laravel
2. Follow the installation steps described at : https://laravel.com/docs/7.x/telescope

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by kyobul** [comment]
Ok, waiting for possible solutions from other users. Can't understand however how this is not a bug since I'm doing all from zero on clean install.

**Comment by elvendor** [comment]
Same here guys. Just upgraded Laravel from 6 to 7 and decided to install Telescope but nothing copied. Copied manually.

**Comment by elvendor** [comment]
Oops. I figured out why it happens. It seems that I had installation of Telescope earlier and disabled it in my .env file. 
@kyobul set **TELESCOPE_ENABLED=true** in .env and **php artisan config:clear** and then try to install again

**Comment by kyobul** [comment]
> Oops. I figured out why it happens. It seems that I had installation of Telescope earlier and disabled it in my .env file.
> @kyobul set **TELESCOPE_ENABLED=true** in .env and **php artisan config:clear** and then try to install again

@elvendor I tried it on a brand new install ant it fails anyway. Yes, you can tweak it manually but the intended installation process is broken.

**Comment by royartitex** [comment]
I've had the same issue with an existing Laravel v8.17.1 installation and Telescope v4.3.1. like @elvendor said, adding the `TELESCOPE_ENABLED=true` to the .env file, clearing the config cache with `php artisan config:clear` and then running `php artisan telescope:install` worked like a charm for me.

**Comment by Nuxij** [comment]
I also see this issue from fresh on a laravel 7 + telescope 3
