### ISSUE TITLE
Problem with line ending on mix-manifest.json

### ISSUE THREAD

**Issue by lucas-santana** [laravel/telescope#869]
- Telescope Version: 2.1.7
- Laravel Version: 5.8.*
- PHP Version: 7.3
- Database Driver & Version:

### Description:
It seems that when the mix-manifest.json file has the line termination as **CRLF**, Laravel Telescope identifies it as an outdated file in relation to vendor: **The published Telescope assets are not up-to-date with the installed version.**

When installing my project that already had the laravel telescope, the following message appeared:
![image](https://user-images.githubusercontent.com/23356474/79162220-45176300-7db3-11ea-835f-7445ca86dc5c.png)

As you can see, in the public folder I already have the assets of the laravel telescope:
![image](https://user-images.githubusercontent.com/23356474/79162399-8e67b280-7db3-11ea-83f7-82f08bc25131.png)

Doing some tests I realized that the file **mix-manifest.json** was configured as **CRLF**, as can be seen in the image below:
![image](https://user-images.githubusercontent.com/23356474/79163108-cc190b00-7db4-11ea-909f-26e419f8f1f4.png)

When changing only the file **mix-manifest.json** to **LF** the error disappears:
![image](https://user-images.githubusercontent.com/23356474/79163444-7729c480-7db5-11ea-8580-2a8d0899024f.png)

After that, even though the project was already working, I ran the command **php artisan telescope: publish** and when running git diff to see the differences and this message appeared, that is, difference only in the line termination:
![image](https://user-images.githubusercontent.com/23356474/79163655-df78a600-7db5-11ea-987a-71d6bac181c9.png)

For testing, I changed the file **mix-manifest.json** to **CRLF** and the error returned:
![image](https://user-images.githubusercontent.com/23356474/79163870-3ed6b600-7db6-11ea-8aca-72c86677839e.png)

I switched to **LF** and the error is gone:
![image](https://user-images.githubusercontent.com/23356474/79163909-544be000-7db6-11ea-9533-8edf7ccd5f12.png)

**Comment by driesvints** [comment]
We can only offer one sort of line ending I'm afraid.

**Comment by lucas-santana** [comment]
Why does the telescope interpret a line termination as a "not-up-to-date" file?
The only difference between the files is the line termination.
There is no point in saying that the file is out of date because of a different line termination.
