### ISSUE TITLE
"Unresolvable dependency" errors

### ISSUE THREAD

**Issue by mattias-persson** [laravel/telescope#872]
- Telescope Version: 2.7
- Laravel Version: 6.18
- PHP Version: 7.3
- Database Driver & Version: 

### Description:
Suddenly we're receiving loads of the following error:
```
Unresolvable dependency resolving [Parameter #0 [ <required> string $connection ]] in class Laravel\Telescope\Storage\DatabaseEntriesRepository
```
It seems this is triggered everytime a Telescope entry is supposed to be registered.

### Steps To Reproduce:
Not sure to be honest, we didn't really change anything to make this happen. We run on Vapor with Laravel 6 and Telescope 2.7.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by mattias-persson** [comment]
I actually found the issue shortly after reporting it 🤦 For anyone encountering this in the future, our problem was that we had an empty `DB_CONNECTION` in on of our .env files, and telescope retrieves that when booting the DatabaseEntriesRepository.

Removing the blank `DB_CONNECTION` solved it, Vapor injects it automatically anyways.
