### ISSUE TITLE
I want to extend Telescope.php and overwrite  scriptVariables function.

### ISSUE THREAD

**Issue by JamesKid** [laravel/telescope#874]
I want to extend and overwrite  scriptVariables, how can I do that ? i want to fix the path config to my url_path， scriptVariables is not a attribute , i can't overwrite it 
![图片](https://user-images.githubusercontent.com/6158899/79420919-6adb7c80-7fec-11ea-8ec9-1b8e2a1deef1.png)

**Comment by driesvints** [comment]
Use the `TELESCOPE_PATH` env variable.
