### ISSUE TITLE
Telescope keep scanning all time

### ISSUE THREAD

**Issue by Komar12124** [laravel/telescope#878]
- Telescope Version: 3.2.0
- Laravel Version: 7.0.0
- PHP Version: 7.2.5
- Database Driver & Version: 

### Description:
Telescope all time scanning and can`t get data. In my console i have this error: 

Failed to load resource: the server responded with a status of 500 (Internal Server Error)

Uncaught (in promise) Error: Request failed with status code 500
    at LYNF.t.exports (app.js?id=58d232fb9ec88bf5e0e5:68)
    at Rn+g.t.exports (app.js?id=58d232fb9ec88bf5e0e5:76)
    at XMLHttpRequest.p.onreadystatechange (app.js?id=58d232fb9ec88bf5e0e5:89)

He try to get response from this url **/telescope/telescope-api/redis?tag=&before=&take=50&family_hash=**

EntryQueryOptions.php exist and in config telescope enabled 

### Steps To Reproduce:
Just install by documentation

**Comment by Komar12124** [comment]
And i set sanctum

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by rupeszh** [comment]
Solution to the problem for me is adding telescope in VerifyCsrfToken middleware.i:e
protected $except = [
        'telescope/*'
    ];
