### ISSUE TITLE
TelescopeServiceProvider is loaded even it is not registering

### ISSUE THREAD

**Issue by kiddtang** [laravel/telescope#880]
- Telescope Version: 3.2.1
- Laravel Version: 7.6.2
- PHP Version: 7.4.4
- Database Driver & Version: MariaDB v10.4.12

### Description:
I have follow the documentation
[https://laravel.com/docs/7.x/telescope](https://laravel.com/docs/7.x/telescope)
I still always get 
`Class 'Laravel\Telescope\TelescopeApplicationServiceProvider' not found`
Untill i remove the file 
`/app/Providers/TelescopeServiceProvider.php`

### Steps To Reproduce:

**1. Install Dev Only ( Checked )**
`composer require laravel/telescope --dev`

In `composer.json`
```
"require-dev": {
        "laravel/telescope": "^3.2",
    },
```

 **2. Conditional registration ( Checked )**

 In `AppServiceProvider`
```
    public function register()
    {
        if ($this->app->isLocal()) {
            $this->app->register(\Laravel\Telescope\TelescopeServiceProvider::class);
            $this->app->register(TelescopeServiceProvider::class);
        }
    }
```

**3. Prevent Autoload ( Checked )**

In `composer.json `
```
"extra": {
        "laravel": {
            "dont-discover": [
                "laravel/telescope"
            ]
        }
    },
```
 
**4. Exclude from classmap ( Checked, Not in Documentation )**
In `composer.json `
```
"autoload": {
...
        "exclude-from-classmap": [
            "app/Providers/TelescopeServiceProvider.php"
        ],
...
    },
```

for `.env` file
```
APP_ENV=staging
APP_DEBUG=false
TELESCOPE_ENABLED=false
```

Finally, run ` composer install --no-dev --optimize-autoloader`

You will always get 
```
> @php artisan package:discover --ansi

In TelescopeServiceProvider.php line 10:

  Class 'Laravel\Telescope\TelescopeApplicationServiceProvider' not found

```
Manually remove the `/app/Providers/TelescopeServiceProvider.php` file can resolve the problem.

Even it is not registering, somehow Laravel execute the code and trying to extends the non-installed class `TelescopeApplicationServiceProvider`???

Hope someone could help.

**Comment by driesvints** [comment]
I'm currently running Telescope just fine.

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
