### ISSUE TITLE
isFailedJob not working for failed jobs

### ISSUE THREAD

**Issue by amosmos** [laravel/telescope#881]
- Telescope Version: 1.0
- Laravel Version: 5.7
- PHP Version: 7.3
- Database Driver & Version:

### Description:
When jobs fail, they don't show in Telescope, although the standard `$entry->isFailedJob()` is in the filter function in the service provider.

If I add `|| $entry->type == 'job'` there, failed jobs do show (and also pending and processed).

### Steps To Reproduce:
Intall telescope
Dispatch and run a failed job

Thanks!

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
