### ISSUE TITLE
Composer dependency moontoast/math

### ISSUE THREAD

**Issue by st3f** [laravel/telescope#883]
Can you change the requirement of moontoast/math to brick/math?
Did not find any Reference of Moontoast or BigNumber in the code...

**Comment by iruoy** [comment]
It looks like this has been fixed on master.

The moontoast package was first replaced by the brick one, but 3 weeks ago that it was removed entirely.

I'm not sure why is wasn't merged into the 3.x branch though.

**Comment by driesvints** [comment]
Doing it on 3.x is a breaking change.

**Comment by jonnott** [comment]
@driesvints @st3f If the library isn't used in the codebase, why is it still a dependency?

Also, btw, it's been marked as abandoned by the package developer @ramsey

**Comment by robtesch** [comment]
Hi guys, any update on this? We're on 3.5.1 now and it seems it's still a dependency...
