### ISSUE TITLE
ExceptionWatcher ignoring Errors

### ISSUE THREAD

**Issue by cosmorunner** [laravel/telescope#889]
Hi, I'm using laravel/telescope Version 3.1.1 and Laravel Framework Version 7.0! 
The native Laravel Helper Method `report()` in `Illuminate\Foundation\helpers` accepts a Throwable Instance. The `shouldIgnore()` Method in the ExceptionWatcher checks for an instance of Exception:

`
    private function shouldIgnore($event)
    {
        return ! isset($event->context['exception']) ||
            ! $event->context['exception'] instanceof Exception;
    }
`

..which results in Throwables (e.g. Error) not being reported. Is this intended or am I missing something?

Cheers!

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
