### ISSUE TITLE
UTF-8 Malformed Characters in JSON API response (SQL Server)

### ISSUE THREAD

**Issue by DevJMD** [laravel/telescope#897]
- Telescope Version: ^3.5
- Laravel Version: ^7.0
- PHP Version: 7.4.3
- Database Driver & Version: SQL Server (Microsoft® ODBC Driver 17 for SQL Server®)

### Description:

Error: 

`local.ERROR: Malformed UTF-8 characters, possibly incorrectly encoded {"exception":"[object]`

It appears that the data returned from the API call in `Illuminate/Http/JsonResponse.php` is returning Malformed UTF-8 Characters. I have a feeling if it was a MySQL database I wouldn't have this issue, for some reason. 

Edit: It works perfectly fine in MySQL. I wonder if the `family_hash` or `content` fields in `telescope_entries` is interpreting it as non-UTF8 string and that's why I'm seeing the Exception?

I'll do some further digging.

JS trace:

```
app.js?id=2cc598321134a0bcfac1:2 POST https://madcapengland.local/maintenance/telescope/telescope-api/views?tag=&before=&take=50&family_hash= 500
(anonymous) @ app.js?id=2cc598321134a0bcfac1:2
t.exports @ app.js?id=2cc598321134a0bcfac1:2
UnBK.t.exports @ app.js?id=2cc598321134a0bcfac1:2
Promise.then (async)
CgaS.c.request @ app.js?id=2cc598321134a0bcfac1:2
CgaS.o.forEach.c.<computed> @ app.js?id=2cc598321134a0bcfac1:2
(anonymous) @ app.js?id=2cc598321134a0bcfac1:2
loadEntries @ app.js?id=2cc598321134a0bcfac1:2
mounted @ app.js?id=2cc598321134a0bcfac1:2
Ut @ app.js?id=2cc598321134a0bcfac1:2
Ze @ app.js?id=2cc598321134a0bcfac1:2
insert @ app.js?id=2cc598321134a0bcfac1:2
T @ app.js?id=2cc598321134a0bcfac1:2
(anonymous) @ app.js?id=2cc598321134a0bcfac1:2
INkZ.t._update @ app.js?id=2cc598321134a0bcfac1:2
r @ app.js?id=2cc598321134a0bcfac1:2
INkZ.pn.get @ app.js?id=2cc598321134a0bcfac1:2
pn @ app.js?id=2cc598321134a0bcfac1:2
(anonymous) @ app.js?id=2cc598321134a0bcfac1:2
INkZ.yn.$mount @ app.js?id=2cc598321134a0bcfac1:2
INkZ.yn.$mount @ app.js?id=2cc598321134a0bcfac1:2
INkZ.t._init @ app.js?id=2cc598321134a0bcfac1:2
yn @ app.js?id=2cc598321134a0bcfac1:2
bUC5 @ app.js?id=2cc598321134a0bcfac1:2
n @ app.js?id=2cc598321134a0bcfac1:2
0 @ app.js?id=2cc598321134a0bcfac1:2
n @ app.js?id=2cc598321134a0bcfac1:2
(anonymous) @ app.js?id=2cc598321134a0bcfac1:2
(anonymous) @ app.js?id=2cc598321134a0bcfac1:2
app.js?id=2cc598321134a0bcfac1:2 Uncaught (in promise) Error: Request failed with status code 500
    at LYNF.t.exports (app.js?id=2cc598321134a0bcfac1:2)
    at Rn+g.t.exports (app.js?id=2cc598321134a0bcfac1:2)
    at XMLHttpRequest.p.onreadystatechange (app.js?id=2cc598321134a0bcfac1:2)
```

It's definitely registering data in the database fine. Just seems it can't get it through the API calls. Here's the stacktrace from `laravel.log`

https://gist.github.com/DevJMD/ac00298b8e51af53f38ab9ce307f6f67

I highly suspect there is some weird configuration around `sqlsrv` drivers not pulling/formatting data properly. ~~I've had a similar issue before when trying to return a fully valid UTF-8 string and got the same response and never figured out why then either.~~

### Steps To Reproduce:

- Followed the `Installation` section of the Docs for version 7.X
- At: https://laravel.com/docs/7.x/telescope#installation
- Visited `http://mysite.local/telescope`
- Throws javascript `Error 500`

Thanks,
J

**Comment by DevJMD** [comment]
To add to this, I figured out a previous issue on a model that was having the same issue. I simply had to add the following to the Model:

```
protected $hidden = ['SSMA_TimeStamp'];
```

SSMA TimeStamps returns a non-UTF8 string and was causing issues, but that of course isn't the same issue here. May have to look a bit deeper in to what is being returned in the response when it's making AJAX requests to fetch data.

**Comment by michastubi** [comment]
I have the exact same problem. But unfortanly no clue how to solve this...

**Comment by driesvints** [comment]
I'll need some help with this from someone who can reproduce it on sqlserver.

**Comment by driesvints** [comment]
I'm gonna close this as it seems that this is quite an edge case. We'd really appreciate a PR that fixes this problem.

**Comment by mralston** [comment]
@driesvints I can reproduce this consistently and would be happy to help troubleshoot.

I'm running SQL Server 2017. According to the following article, UTF-8 support wasn't introduced until SQL Server 2019.

https://techcommunity.microsoft.com/t5/sql-server/introducing-utf-8-support-for-sql-server/ba-p/734928

Obviously that means that my SQL Server instance will not be able to support UTF-8, and by extension the current version of Telescope, unless it is upgraded to SQL Server 2019.

If something can be done to support non-UTF-8 compliant versions of SQL Server then I'm happy to help out with a little bit of testing. Otherwise I think it would be best to say that Telescope does not support SQL Server versions prior to 2019.

**Comment by driesvints** [comment]
@mralston I guess supporting SQL Server 2017 seems problematic. If anyone's willing to work on a PR we could accept it maybe.
