### ISSUE TITLE
Styling issue on requests index

### ISSUE THREAD

**Issue by chasenyc** [laravel/telescope#898]
- Telescope Version: 3.5.0
- Laravel Version: 7.0
- PHP Version: 7.4
- Database Driver & Version: MySQL

### Description:
This only occurs for me in chrome(incognito with no extensions):
<img width="1447" alt="Screen Shot 2020-05-17 at 6 56 28 PM" src="https://user-images.githubusercontent.com/10642932/82162173-7b437900-9870-11ea-9807-0d0f855ad5ea.png">

It looks fine in firefox.

### Steps To Reproduce:
Have a very long url requested recently.

**Comment by driesvints** [comment]
I can't reproduce this. Displays fine for me in Chrome.
