### ISSUE TITLE
No requests appear on Vapor deployment

### ISSUE THREAD

**Issue by PenguinOfWar** [laravel/telescope#906]
- Telescope Version: 3.5
- Laravel Version: 6.18.13
- PHP Version: 7.4 local, Vapor Defauly remote
- Database Driver & Version: mysql, Vapor Default

### Description:

Apologies if this is better off as a Vapor question, but I assume I'm doing something wrong here.

I've followed the instructions to set up Telescope in my existing Laravel application. It works locally on homestead, but when I deploy to Vapor no requests etc appear. Is there an additional configuration step I'm missing for Vapor?

![Screenshot 2020-06-11 at 14 41 41](https://user-images.githubusercontent.com/1913241/84392374-35b96800-abf2-11ea-8eec-5451fbb55298.png)

### Steps To Reproduce:

1. Install Telescope locally
2. Verify it is working
3. Deploy app to Vapor
4. Dashboard is available but no request data is populated

**Comment by driesvints** [comment]
Heya, it's probably best that you contact Vapor support directly (using the in-app widget). Thanks.

**Comment by barryvdh** [comment]
Make sure you filter you data correctly: https://laravel.com/docs/7.x/telescope#filtering
On production you need to define what is logged and what isn't.
