### ISSUE TITLE
Getting the currently authenticated user properties

### ISSUE THREAD

**Issue by bornemisza** [laravel/telescope#907]
**Current telescope version: v3.2**

### Feature request:

The telescope getting every currently authenticated user properties in the Laravel\Telescope\IncomingEntry::user() function. Which is little bit stone written to Eloquent, because we try to get the name like this: "_$user->name_". Currently I am using [laravel-doctrine/orm](https://github.com/laravel-doctrine/orm) and I am not exactly a fun of publicating any Entity/Model properties, moreover to any specific variable name(s).

In this funcation we fills the id from the $user->getAuthIdentifier() call. Therefore, is it possible to make the fill of the name and email keys more _"customizable"_?

### Use case:

1. If someone using different ORM from Eloquent.
2. If someone using [fruitcake/laravel-telescope-toolbar](https://github.com/fruitcake/laravel-telescope-toolbar) with different ORM, could use and display more user specific information. Eg: EntryType::REQUEST(['telescope-toolbar::collectors.user']) in toolbar.

**If this request more 3rd party specific, then I am sorry for wasting your precious time.**

**Comment by driesvints** [comment]
Hmm, I'm afraid this falls a little out of scope sorry. We'd have to draw up a contract that describes a Telescope user. It'd be an extra installation step for users who aren't using a different ORM.

That being said you can always attempt a PR. But it's probably best that you'd send this to master.
