### ISSUE TITLE
Telescope creates migration in the wrong database

### ISSUE THREAD

**Issue by SerafimArts** [laravel/telescope#91]
## Step To Reproduce

1. Run `php artisan telescope:install`.
2. Change `storage` => `database` => `connection` in `telescope.php` to another (`sqlite` as example).
3. Run `php artisan migrate`.

## Expected

Сreating a structure within the specified connection.

## Actual

Creating migrations on the primary connection.

**Comment by SerafimArts** [comment]
![image](https://user-images.githubusercontent.com/2461257/47398190-a5d45b00-d73b-11e8-9b91-0dcdaa3ad5ef.png)

**Comment by enimiste** [comment]
See PR #95

**Comment by SerafimArts** [comment]
@enimiste thanks! Then it makes no sense to discuss it. Taylor don't care.

P.S. I recommend to use the [clockwork](https://github.com/itsgoingd/clockwork), it is more convenient and does not contain such problems.
