### ISSUE TITLE
ScrollUp area when page infinite scroll

### ISSUE THREAD

**Issue by finagin** [laravel/telescope#917]
With infinite scrolling, sometimes a page gets very long, ScrollUp would be helpful
Something like this:
<img width="403" alt="ScrollUp vk.com" src="https://user-images.githubusercontent.com/11045296/88145746-93829c00-cc03-11ea-957c-98fcad5f8888.png">

**Comment by driesvints** [comment]
Feel free to attempt a pr if you'd like
