### ISSUE TITLE
Query detail page shows mysql variables as "undefined"

### ISSUE THREAD

**Issue by semiherdogan** [laravel/telescope#919]
- Telescope Version: 2.1.7
- Laravel Version: 6.18.22
- PHP Version:  7.3.14
- Database Driver & Version:
mysql & 5.7.28
### Description:
When i use mysql variable in sql query telescope query detail page shows that variable as undefined.

### Steps To Reproduce:
Run this query and check telescope query detail page.
`\DB::select('select @user_id := id as id from users');`

It shows correctly at list page
![image](https://user-images.githubusercontent.com/5646041/88387073-64625b00-cdba-11ea-8ed5-da7cf6fcb37e.png)

But in detail shows like this:
![image](https://user-images.githubusercontent.com/5646041/88387114-77752b00-cdba-11ea-8a7a-2c98f546fec8.png)

**Comment by driesvints** [comment]
Seems like Telescope has some problems with session variables. Appreciating help with this or a PR until we get to this ourselves.

**Comment by derekmd** [comment]
The Telescope Vue template uses NPM package [sql-formatter](https://www.npmjs.com/package/sql-formatter) to highlight SQL queries. Digging into its code, the `@` character is treated similar to the `?` placeholder, but named. MS SQL Server, etc. support this syntax.

https://github.com/zeroturnaround/sql-formatter/blob/1062bbc278319d6bf0e2d4cc30fba427411a6dab/src/languages/StandardSqlFormatter.js#L100

With a variable _assignment_ expression, the library is trying to pull a binding value that doesn't exist.

```javascript
sqlFormatter.format('select @user_id := id as id from users', {params: []});
// select
//   undefined: = id as id
// from
//   users
```

It expects a named options parameter, e.g., `{params: {user_id: 1}`

Excluding the `params` option will stop the library from attempting to fill the placeholder.

```javascript
sqlFormatter.format('select @user_id := id as id from users');
// select
//   @user_id: = id as id
// from
//   users
```

So this branch could be submitted to fix the above case: https://github.com/laravel/telescope/compare/3.x...derekmd:fix-mysql-variable-dump

### NPM package `sql-formatter` needs a MySQL fix

However if `?` bindings are also mixed into the query, the problem still exists. That library would need to fix handling uneven placeholders/values that makes assumptions about how `@` characters are handled. Telescope is configured to use the "Standard SQL" / SQL:2011 dialect so the library probably needs a new MySQL/MariaDB dialect implementation that detects `@symbolA := symbolB` expressions and doesn't try to replace them.

**Comment by driesvints** [comment]
@derekmd thank you for the thorough investigation here! Seems like sql-formatter hasn't received updates since almost a year and there's not much response on its issue tracker either. Is there an alternative we could use that'd also solve this issue?

**Comment by barryvdh** [comment]
I think currently the SQL parameters are processed with PHP, since https://github.com/laravel/telescope/pull/706
So the bindings are always empty. Could we just remove the bindings parameter from Javascript?

**Comment by driesvints** [comment]
@barryvdh isn't that essential info here?

**Comment by barryvdh** [comment]
What do you mean? The bindings are replaced in PHP, so no need for the Javascript formatter to replace the bindings.  As you can see here: https://github.com/laravel/telescope/blob/f05c934b037de086d98cf1bf9979ee104ed16746/src/Watchers/QueryWatcher.php#L41-L42
The bindings are always just an empty array. I don't even think it's needed, but I left them to avoid any BC breaks, for when bindings was expected.

**Comment by driesvints** [comment]
@barryvdh but the problem is that `@user_id` is replaced with `undefined`. How can it be saved if our JS removes it? Maybe I'm missing something here.

**Comment by barryvdh** [comment]
@derekmd said:
> Excluding the params option will stop the library from attempting to fill the placeholder.

**Comment by barryvdh** [comment]
You can test it yourself on https://zeroturnaround.github.io/sql-formatter/ and open the console. When no params key is passed, no attempts to replace them are made. And because we already replaced them and the bindings are empty anyway, we shouldn't have to. So just replacing these lines:

https://github.com/laravel/telescope/blob/53c40e89f0de45d878665f17f2da02a05c18a394/resources/js/screens/queries/preview.vue#L17-L19

With `return sqlFormatter.format(sql);` should work, but have not tested it.

**Comment by driesvints** [comment]
@barryvdh gotcha. Appreciating a PR if anyone's up for it.

**Comment by semiherdogan** [comment]
I have tested @derekmd 's method, its working properly.
