### ISSUE TITLE
Adding filter in production for Mails and Jobs

### ISSUE THREAD

**Issue by moiz-conceptlz** [laravel/telescope#921]
I have Telescope installed on Laravel 6.x. In the Laravel app, the file `app/Providers/TelescopeServiceProvider.php` contains the `register()` method. The following code exists.

    Telescope::filter(function (IncomingEntry $entry) {

            if ($this->app->isLocal()) {
                return true;
            }

            return $entry->isReportableException() ||
                   $entry->isFailedRequest() ||
                   $entry->isFailedJob() ||
                   $entry->isScheduledTask() ||
                   $entry->hasMonitoredTag();
        });

This tells me that if env = local, all entries are recorded by if the env = production then only failed jobs, reportable exception, failed requests etc are recorded. It is also mentioned on https://laravel.com/docs/6.x/telescope#filtering-entries

But how do I add more filters - specifically to record Mails and Jobs in production? I don't want to return a true and record everything, just specifically Mails and Jobs. help!?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by moiz-conceptlz** [comment]
Thank @driesvints .. but tried 3 of those channels 10 days back and no reply on either. Hence thought of posting it here! Thanks for the suggestion.

**Comment by barryvdh** [comment]
You can check $entry->type to see which ones you also want to record.
