### ISSUE TITLE
Incorrect location for queries from database validation rules

### ISSUE THREAD

**Issue by emargareten** [laravel/telescope#925]
- Telescope Version: 3.5.1
- Laravel Version: 7.22.4
- PHP Version: 7.4.5
- Database Driver & Version: MySql 8.0

### Description:
Query watcher for database validation rules are not showing the correct location.

This is because the controller / form request is called from `call_user_func_array` so it doesn't include the filename in `debug_backtrace` (see [here](https://bugs.php.net/bug.php?id=44428)), which in turn is being ignored by Telescope's `getCallerFromStackTrace` method.

### Steps To Reproduce:

Add a  [`unique`](https://laravel.com/docs/7.x/validation#rule-unique) or [`exists`](https://laravel.com/docs/7.x/validation#rule-exists) validation rule in controller method

**Comment by driesvints** [comment]
Please provide full steps/code examples to reproduce.
