### ISSUE TITLE
Telescope receiving empty responses even though there are records in the database that it should show

### ISSUE THREAD

**Issue by RCRalph** [laravel/telescope#927]
- Telescope Version: 3.5.1
- Laravel Version: 7.22.2
- PHP Version: 7.2.5
- Database Driver & Version: Seems to be database independent, but I used SQLite3

### Description:
Telescope doesn't display any records from the `telescope_entries` table, but instead it only shows this:
![image](https://user-images.githubusercontent.com/36704328/89087668-42a63c80-d395-11ea-8b2d-417c6580716b.png)

If we take a look into the browser console, we will see that Telescope frequently sends POST requests to its API, but receives an empty array of entries:
![image](https://user-images.githubusercontent.com/36704328/89087706-71241780-d395-11ea-8b41-9da4aa234a69.png)

I am sure that there are records in the database, because I can see them using my database viewer:
![image](https://user-images.githubusercontent.com/36704328/89087743-92850380-d395-11ea-8a50-8185f3a8055e.png)
Also when I run `DB::table("telescope_entries")->get()` in Tinker I get the proper records from the database.

For debugging purposes I added `lad([$request, $storage]);` before the return statement in the `index` method in `EntryController`:
```
public function index(Request $request, EntriesRepository $storage)
{
    lad([$request, $storage]); // function comes from lanin/laravel-api-debugger
    return response()->json([
        'entries' => $storage->get(
            $this->entryType(),
            EntryQueryOptions::fromRequest($request)
        ),
        'status' => $this->status(),
    ]);
}
```
Now when the browser send the request to Telescope's API, it receives the following JSON:
```
{
    "entries": [],
    "status": "enabled",
    "debug": {
        "database": {
            "total": 1,
            "items": [
                {
                    "connection": "sqlite",
                    "query": "select * from \"telescope_entries\" where \"type\" = 'request' and \"should_display_on_index\" = '1' order by \"sequence\" desc limit 50;",
                    "time": 7.68
                }
            ]
        },
        "cache": {
            "hit": {
                "keys": [],
                "total": 0
            },
            "miss": {
                "keys": [
                    "telescope:dump-watcher",
                    "telescope:pause-recording"
                ],
                "total": 2
            },
            "write": {
                "keys": [],
                "total": 0
            },
            "forget": {
                "keys": [],
                "total": 0
            }
        },
        "profiling": [
            {
                "event": "request-time",
                "time": 0.6450369358062744
            }
        ],
        "memory": {
            "usage": 16327024,
            "peak": 16547112
        },
        "dump": [
            [
                {
                    "attributes": {},
                    "request": {},
                    "query": {},
                    "server": {},
                    "files": {},
                    "cookies": {},
                    "headers": {}
                },
                {}
            ]
        ]
    }
}
```

When I run the SQL statement provided above in my database viewer, I receive the records that I should be receiving:
![image](https://user-images.githubusercontent.com/36704328/89129137-26241480-d4fb-11ea-8ee0-be998109720b.png)

This issue seems to be database independent. I connected to an external PostgreSQL database and the same issue occurred.

I'll gladly help with any further investigating.

### Steps To Reproduce:
* Create a new Laravel project
* Set the `DB_CONNECTION` variable in `.env` file to `sqlite`
* Create a new file called `database.sqlite` in the `/database` folder
* Run commands:
    * `composer require laravel/telescope`
    * `php artisan telescope:install`
    * `php artisan migrate`

**Comment by driesvints** [comment]
Works fine for me.

<img width="1281" alt="Screenshot 2020-08-03 at 10 10 03" src="https://user-images.githubusercontent.com/594614/89160534-86559d80-d571-11ea-9670-bc4947d88bc0.png">

**Comment by dsampaolo** [comment]
I have the same problem on a project (in Production, works fine in local). Telescope says "Just empty space" but there are records in the database. couldn't reproduce on a new project. I'll keep you updated if I find the reason why.

**Comment by RCRalph** [comment]
@dsampaolo look at this post:
https://stackoverflow.com/a/63238312/9362390
Installing this virtual machine solved my problem.

**Comment by farhad321** [comment]
I worked on installing a telescope for about 2 months.
After many failures
To solve this problem, you must remove the telescope tables from the database
Execute the following commands
```
php artisan telescope:install
php artisan migrate
```

**Comment by BuglerV** [comment]
Gethostname function in \Laravel\Telescope\IncomingEntry::__construct() returs binary data. This might happen when your PC name is not in ANSI.

Then in \Laravel\Telescope\Storage\DatabaseEntriesRepository::store() when json_encode calls there is an error:

`json_last_error_msg() // Malformed UTF-8 characters, possibly incorrectly encoded`

Json_encode in this case returns false and in database stored '0' instead of correct json.

If, for example, change in \Laravel\Telescope\Storage\DatabaseEntriesRepository::store()

`                $entry->content = json_encode($entry->content,JSON_INVALID_UTF8_IGNORE);`

This is solve the problem.

**Comment by catursurapam** [comment]
> I worked on installing a telescope for about 2 months. After many failures To solve this problem, you must remove the telescope tables from the database Execute the following commands
> 
> ```
> php artisan telescope:install
> php artisan migrate
> ```
> 
> notice: remove tables because tables not have row but have volume size .

hi man i know this is old, you saved my problem, i run same problem when using docker inside my aapanel, it doesnt record anything, i jsut deleted table as you suggested and reinstall telescope then rerun the migration, and now its working thanks so much
