### ISSUE TITLE
Support hiding / not recording / masking of ip addresses (e.g. for GDPR)

### ISSUE THREAD

**Issue by SvenSchoene** [laravel/telescope#928]
I see that recording of IP adresses was added in this PR: https://github.com/laravel/telescope/pull/895

This is a useful feature to have.
Unfortunately for GDPR related purposes we're only storing ip addresses for a very limited (~12 hours) amount of time. After that we're deleting any logs with real ip-addresses. We're also keeping logs with masked ip addresses which we can use for longer.

Now that Telescope is storing IP addresses we need to find a way to deal with this.  
Personally, for some phases and feature roll-outs I love to collect Telescope-data for multiple days. However, I don't feel good doing that anymore and would have to clear the database every 12 hours now.

What we ideally need would be a config flag we can set in `.env` to disable logging of IP addresses completely. That would be really helpful.

Since we can't be the only company having to comply with GDPR laws I wonder why no other issues around this have been opened already. Maybe everybody else is clearing their logs? Or, more likely, simply not having Telescope run in a live environment? Which I get is not ideal. But again, for specific phases and feature rollouts of a project Telescope can be really essential in our debugging process.

**Comment by driesvints** [comment]
Sure thing. Feel free to send in a PR! 👍
