### ISSUE TITLE
Monitoring does not work for custom route path

### ISSUE THREAD

**Issue by SerafimArts** [laravel/telescope#93]
## Step To Reproduce

- Change `path` in `telescope.php` to another (`_profiler` as example).
- Open `yoursite.com/_profiler/monitored-tags`

## Expected

- All Ok

## Actual

- Error 404 when handling `yoursite.com/telescope/telescope-api/monitored-tags` (probably incorrect route generation)

**Comment by SerafimArts** [comment]
@enimiste kk. 

I had to remove the telescope, because it contains bugs with connections on different databases, so it’s not possible for me to use at the moment. So I can not reproduce the problem at the moment.

**Comment by enimiste** [comment]
Yeah. Maybe we need to wait for a stable version. But maintainers should listen to the users to collect a max of issues and PR to get a good solution from the Laravel ecosystem.

**Comment by SerafimArts** [comment]
@enimiste I have already sent [a lot of PR before](https://github.com/laravel/framework/pulls?q=is%3Apr+author%3ASerafimArts+is%3Aclosed) and only one have been accepted.

So I have long been disillusioned with the maintainers.
