### ISSUE TITLE
Telescope is not working under subdirectory

### ISSUE THREAD

**Issue by Billtec** [laravel/telescope#934]
- Telescope Version: 3.5.1
- Laravel Version: 6.18.35
- PHP Version: 7.4.9
- Database Driver & Version: MariaDB 10.4.14

### Description:
Telescope is not working under subdirectory like `http://localhost/laravel/telescope` . In which `http://localhost/laravel` is the entry of Laravel app. It is configured in Apache by `Alias "/laravel" "D:/www/laravel/public"`

### Steps To Reproduce:
1. Install Laravel using composer create-project.
2. Install Telescope using composer require laravel/telescope.
3. Visit `http://localhost/laravel/telescope` and it says 404 Page Not Found.

**Comment by driesvints** [comment]
We don't support running Laravel in a subdirectory: https://laravel.com/docs/7.x#directory-configuration

**Comment by luanmm** [comment]
@driesvints subdirectory and subpath are different concepts.
