### ISSUE TITLE
Composer Installation automatically selects 4.x instead of a compatible version for Laravel 7.x

### ISSUE THREAD

**Issue by cincauhangus** [laravel/telescope#941]
- Telescope Version: 3.5.1/4.0.0
- Laravel Version: 7.28.0
- PHP Version: 7.4.8
- Database Driver & Version: not relevant

### Description:
Running `composer require laravel/telescope` automatically selects 4.x instead of 3.x with laravel 7.x

### Steps To Reproduce:
![image](https://user-images.githubusercontent.com/616127/92562629-dc241080-f2a8-11ea-9054-fbdc123629f0.png)

**Comment by driesvints** [comment]
Telescope v4 requires Laravel 8. Please see. the upgrade guide. If you need telescope for Laravel 7 please require v3.

**Comment by ap-coder** [comment]
I @cincauhangus 

Guess he didnt actually read what you wrote.  I have the same issue if you find a fix.

**Comment by cincauhangus** [comment]
> I @cincauhangus
> 
> Guess he didnt actually read what you wrote. I have the same issue if you find a fix.

The workaround I used is `composer require laravel/telescope:^3.5`

**Comment by driesvints** [comment]
@ap-coder I did. Please re-read my comment.
