### ISSUE TITLE
Feature request: the ability to replay a request

### ISSUE THREAD

**Issue by Sofianio** [laravel/telescope#942]
Hello,
Big fan of telescope, I wish I found it sooner ❤️ 

A thing I thought would be useful is to be able to replay a request, I'll explain

### Idea inspired from Firefox
I saw this in Firefox browser dev tools under Network panel, you see all the requests made by that page with the headers, params and response, if your right click a request you find the option to replay a request as in resend exactly the same request with same params and headers

### Usefulness (if that's a real word)
Say you have an api in which a route is returning an error in when called with certain params / accounts
Sometimes it's easy to retest that request, but in other times for example if the request was made from a mobile app after a long process and too many screens, it would be very useful to be able to resend the same request again and check if the route is fixed and working properly

### Other solutions
You may say you should have a platform on which to test your api without having to use the app like Postman that's correct but even with that, to re-create the exact same request will be a bit of a hassle

I hope you like this idea :)
Cheers

**Comment by paras-malhotra** [comment]
Looks like a useful feature but there's a lot of data that the Request Watcher doesn't store:

1. File data: Only the file name and size are stored, not the actual file(s)
2. Hidden / sensitive session, request and header data in `Telescope::$hiddenRequestParameters`

Also, the workflow would be pretty tedious. E.g. different users making the same request could have different results. So, to make this work, we'd have to impersonate as the user, restore session data, grab all the headers and request payload, perform request, replace session with original data and switch back to the Telescope user.

**Comment by Sofianio** [comment]
I can see that keeping the file would be not doable
But keeping the headers/session should be doable in ajax call or smth

**Comment by driesvints** [comment]
Probably not something we're gonna do ourselves. You can already replay requests with your browser dev tools.

**Comment by Sofianio** [comment]
I actually can't ... as I said the call is sometimes made from mobile or from a distant machine
But if it's too much hassle to get it done .. drop it

**Comment by driesvints** [comment]
@Sofianio Telescope wasn't really meant to be used on a mobile screen.

**Comment by Sofianio** [comment]
@driesvints The request was made from a mobile app, while I check requests on telescope from desktop

**Comment by unilogica** [comment]
I wanted to humbly share a feature from Laravel Horizon that has been incredibly helpful in my experience, and suggest something similar be considered.

When debugging applications - especially in production environments - reproducing the exact failure context can be time-consuming. Copying requests, recreating conditions… it’s not always straightforward.

What Horizon offers is the ability to re-run failed jobs directly from the dashboard. This has been a game-changer for me. In some cases, I’ve been able to connect to a shell container, open Vim, tweak the code live, and re-run the job immediately. If it works, I commit the hotfix and rebuild the image properly. This approach, while used with caution, has saved me countless hours in critical situations.

I share this not to promote risky practices, but to highlight how powerful and practical this feature can be when used responsibly. Having something similar would be an incredible addition - essentially for those of us who often work on complex systems under pressure.

<img width="408" alt="Image" src="https://github.com/user-attachments/assets/9dd2f16e-0bb1-4383-917c-df2d76200c41" />

**Comment by stoll** [comment]
+1

@driesvints seems weird to close the feature request on a misunderstanding.

I have the same issue whenever I'm testing callbacks from API's. I wanna replay the exact same request my Laravel app received when fixing bugs.

**Comment by Illusionist3886** [comment]
Missing the feature.
