### ISSUE TITLE
Target class [env] does not exist  after upgrade to version 4

### ISSUE THREAD

**Issue by prosperoking** [laravel/telescope#943]
- Telescope Version: 4.0
- Laravel Version: 8.0
- PHP Version: 7.4
- Database Driver & Version:

### Description:
Target class [env] does not exist when running tests ater update to version 4.0

### Steps To Reproduce:
Install Telescope and make use of the TelescopeApplicationServiceProvider. this will totally ignore the telescope enabled config and load. 

### Workaround
A work around for this is to Override the boot method:
```php
public function boot()
    {
        if (! config('telescope.enabled')) {
            return;
        }
        $this->authorization();
    }

```

**Comment by sergiy-petrov** [comment]
The same problem here when running phpunit.

I've fixed it by adding TELESCOPE_ENABLED=false to my .env.testing
However it's weird why it didn't read this variable from phpunit.xml

**Comment by driesvints** [comment]
Works fine for me.

@sergiy-petrov That's done by default: https://github.com/laravel/laravel/blob/master/phpunit.xml#L29

**Comment by sergiy-petrov** [comment]
@driesvints I meant that I have the variable set to false in phpunit.xml but the problem is resolved only after adding the variable to .env.testing
