### ISSUE TITLE
Telescop avoid full table scan

### ISSUE THREAD

**Issue by tczaude** [laravel/telescope#946]
I recreate bug becouse i insert in horiozn but this should be there 

- Laravel Version: v6.18.35
- PHP Version: 7.3.18 
- Redis Driver & Version: predis/phpredis #.#.#
- Database Driver & Version:

### Description:

Horizon in standard use this query:

`select tag from telescope_monitoring ` 

which is putted to slow_log because this make full table scan

this is explained in first point this document

https://dev.mysql.com/doc/refman/8.0/en/table-scan-avoidance.html

simple way in some cases to eliminate above problem is extended above query to this

`select tag from telescope_monitoring where tag is not null` 

in practical above impact generate in my env 

above 1.2 mln queries to slow log which is 25 % all slow queries in my system per week

This problematic sql query is in new version.

To fix this query in file

`src/Storage/DatabaseEntriesRepository.php` 

we must change

line 297

from

`        return $this->table('telescope_monitoring')->pluck('tag')->all();`
to

`        return $this->table('telescope_monitoring')->whereNotNull('tag')->pluck('tag')->all();`

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by tczaude** [comment]
this query exist in every version.

**Comment by driesvints** [comment]
@tczaude please test with the latest version and fill out the issue template for telescope.

**Comment by paras-malhotra** [comment]
Why would tag ever be null anyway?

**Comment by tczaude** [comment]
This problem is not exactly how is telescope work.  
But how construct query to database. 
When table is small and database query optymalizer cannot determine best method and do full scan and this query put in log.
When You extend by **where** You "help" QDO avoid make table scan. 
You can put there ' !="" ' effect will be this same.

These are the basics of databases.

**Comment by paras-malhotra** [comment]
Don't see how that would optimise the query when tag is not nullable. It's basically the same query with or without the where clause.

**Comment by tczaude** [comment]
How that's happens is question for Mariadb / Mysql staff.

When You have minimum 2 records in this table that's look explain

`EXPLAIN SELECT SQL_NO_CACHE tag FROM telescope_monitoring;`
`id|select_type|table               |type |possible_keys|key|key_len|ref|rows|Extra      |
--|-----------|--------------------|-----|-------------|---|-------|---|----|-----------|
 1|SIMPLE     |telescope_monitoring|index|             |tag|767    |   |2   |Using index|`

`EXPLAIN SELECT SQL_NO_CACHE tag FROM telescope_monitoring where tag is not null;`
`id|select_type|table               |type |possible_keys|key|key_len|ref|rows|Extra                   |
--|-----------|--------------------|-----|-------------|---|-------|---|----|------------------------|
 1|SIMPLE     |telescope_monitoring|index|tag          |tag|767    |   |2   |Using where; Using index|`

And we see without where DB not determine possible_keys

**Comment by tczaude** [comment]
And next example

with where 

`Status                |Duration|Context_voluntary|Context_involuntary|
----------------------|--------|-----------------|-------------------|
Starting              |0.000176|                0|                  0|
Checking permissions  |0.000033|                0|                  0|
Opening tables        |0.000048|                0|                  0|
After opening tables  |0.000026|                0|                  0|
System lock           |0.000024|                0|                  0|
Table lock            |0.000037|                0|                  0|
Init                  |0.000049|                0|                  0|
Optimizing            |0.000038|                0|                  0|
Statistics            |0.000065|                0|                  0|
Preparing             |0.000052|                0|                  0|
Executing             |0.000024|                0|                  0|
Sending data          |0.000076|                0|                  0|
End of update loop    |0.000028|                0|                  0|
Query end             |0.000024|                0|                  0|
Commit                |0.000023|                0|                  0|
Closing tables        |0.000024|                0|                  0|
Unlocking tables      |0.000022|                0|                  0|
Closing tables        |0.000029|                0|                  0|
Starting cleanup      |0.000023|                0|                  0|
Freeing items         |0.000027|                0|                  0|
Updating status       |0.000087|                0|                  0|
Logging slow query    |0.000029|                0|                  0|
Opening tables        |0.000036|                0|                  0|
System lock           |0.000024|                0|                  0|
Table lock            |0.000027|                0|                  0|
Opening tables        |0.000022|                0|                  0|
After opening tables  |0.000525|                0|                  0|
Closing tables        |0.000025|                0|                  0|
Unlocking tables      |0.007132|                5|                  2|
Closing tables        |0.000061|                0|                  0|
Reset for next command|0.000025|                0|                  0|`

without 

`Status                |Duration|Context_voluntary|Context_involuntary|
----------------------|--------|-----------------|-------------------|
Starting              |0.000142|                0|                  0|
Checking permissions  |0.000044|                0|                  0|
Opening tables        |0.000061|                0|                  0|
After opening tables  |0.000038|                0|                  0|
System lock           |0.000032|                0|                  0|
Table lock            |0.000045|                0|                  0|
Init                  |0.000051|                0|                  0|
Optimizing            |0.000033|                0|                  0|
Statistics            |0.000042|                0|                  0|
Preparing             |0.000050|                0|                  0|
Executing             |0.000023|                0|                  0|
Sending data          |0.000079|                0|                  0|
End of update loop    |0.000027|                0|                  0|
Query end             |0.000023|                0|                  0|
Commit                |0.000025|                0|                  0|
Closing tables        |0.000023|                0|                  0|
Unlocking tables      |0.000021|                0|                  0|
Closing tables        |0.000029|                0|                  0|
Starting cleanup      |0.000022|                0|                  0|
Freeing items         |0.000027|                0|                  0|
Updating status       |0.000089|                0|                  0|
Logging slow query    |0.000028|                0|                  0|
Opening tables        |0.000037|                0|                  0|
System lock           |0.000023|                0|                  0|
Table lock            |0.000026|                0|                  0|
Opening tables        |0.000023|                0|                  0|
After opening tables  |0.000524|                0|                  0|
Closing tables        |0.000024|                0|                  0|
Unlocking tables      |0.007123|                6|                  2|
Closing tables        |0.000062|                0|                  0|
Reset for next command|0.000027|                0|                  0|`

We see with where ctx is smaller
