### ISSUE TITLE
__construct() must be of the type array, int given

### ISSUE THREAD

**Issue by spielfigur** [laravel/telescope#947]
- Telescope Version: 3.5.1
- Laravel Version: 7.28.1
- PHP Version: 7.4.10
- Database Driver & Version: mariadb Ver 15.1 Distrib 10.5.5-MariaDB, for osx10.15 (x86_64) using readline 5.1

### Description:

Got the following error when a job failed:

`Argument 6 passed to Laravel\Telescope\EntryResult::__construct() must be of the type array, int given, called in /var/www/vendor/laravel/telescope/src/Storage/DatabaseEntriesRepository.php on line 71 {"userId":2,"exception":"[object] (TypeError(code: 0): Argument 6 passed to Laravel\\Telescope\\EntryResult::__construct() must be of the type array, int given, called in /var/www/vendor/laravel/telescope/src/Storage/DatabaseEntriesRepository.php on line 71 at /var/www/vendor/laravel/telescope/src/EntryResult.php:84)"`

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by spielfigur** [comment]
Hoi Dries,

I've just upgraded to 

- Telescope Version: 4.0.0
- Laravel Version: 8.0.3

it's really a breeze :)

Sadly the error persists:

`php_1          | [10-Sep-2020 15:47:30] WARNING: [pool www] child 25 said into stderr: "[2020-09-10 15:47:30] development.ERROR: Argument 6 passed to Laravel\Telescope\EntryResult::__construct() must be of the type array, int given, called in /var/www/vendor/laravel/telescope/src/Storage/DatabaseEntriesRepository.php on line 71 {"userId":2,"exception":"[object] (TypeError(code: 0): Argument 6 passed to Laravel\\Telescope\\EntryResult::__construct() must be of the type array, int given, called in /var/www/vendor/laravel/telescope/src/Storage/DatabaseEntriesRepository.php on line 71 at /var/www/vendor/laravel/telescope/src/EntryResult.php:84)"`

**Comment by driesvints** [comment]
What is the value of `content` for this database entry?

**Comment by spielfigur** [comment]
well, I had just asked myself the same thing!?
it looks like something is missing or wrong initialized?

![Bildschirmfoto 2020-09-10 um 16 23 07](https://user-images.githubusercontent.com/6874264/92744972-39d85b80-f382-11ea-878a-4f9d5fe2c640.png)
![Bildschirmfoto 2020-09-10 um 16 23 36](https://user-images.githubusercontent.com/6874264/92744985-3cd34c00-f382-11ea-8a3d-c9f61f1051c4.png)
![Bildschirmfoto 2020-09-10 um 16 24 39](https://user-images.githubusercontent.com/6874264/92744991-3e9d0f80-f382-11ea-9e75-2aa6f283a5f2.png)

**Comment by spielfigur** [comment]
just one comment for the upgrade guide:

Don't forget to enable the new batch watcher in your config watchers array:
`Watchers\BatchWatcher::class => env('TELESCOPE_BATCH_WATCHER', true),`

**Comment by driesvints** [comment]
We'll need to figure out how that `0` got in there.

**Comment by spielfigur** [comment]
Seems like my problem with the job was the timeout value, which was to low for my minio storage...
But i have no idea how the zero gets in there.

have a nice evening!

**Comment by driesvints** [comment]
Gonna close this then and hope it's a hiccup. Will investigate if more people experience this.
