### ISSUE TITLE
New Laravel 8 event subscriber syntax not compatible with Telescope, crashes app

### ISSUE THREAD

**Issue by schwartzmj** [laravel/telescope#952]
- Telescope Version: 4.0.0
- Laravel Version: 8.5.0
- PHP Version: 7.4.9
- Database Driver & Version:

### Description:
New Laravel 8.0 event subscriber syntax not compatible with Telescope. Results in app crashing and error: `get_class() expects parameter 1 to be object, string given` at `vendor/laravel/telescope/src/Watchers/EventWatcher.php:91`

### Steps To Reproduce:

In an event subscriber, use the following Syntax:

```php
public function subscribe($events)
    {
        $events->listen(
            'Illuminate\Auth\Events\Login',
            [UserEventSubscriber::class, 'handleUserLogin']
        );

        $events->listen(
            'Illuminate\Auth\Events\Logout',
            [UserEventSubscriber::class, 'handleUserLogout']
        );
    }
```

Specifically this line: `[UserEventSubscriber::class, 'handleUserLogout']`

As a workaround, use the 7.0 syntax of `'App\Listeners\UserEventSubscriber@handleUserLogout'`

Here's the line causing issues in `vendor/laravel/telescope/src/Watchers/EventWatcher.php:91`:

```php
                } elseif (is_array($listener)) {
                    return get_class($listener[0]).'@'.$listener[1];
                }
```
I'm new to PHP and Laravel, but it seems that `get_class` is not necessary since we are already passing it a string. Unfortunately, if you remove `get_class`, it causes other pieces of code to fail since Telescope is expecting an object for other use cases.

References:
- [7.0 writing-event-subscribers](https://laravel.com/docs/7.x/events#writing-event-subscribers)
- [8.0 writing-event-subscribers](https://laravel.com/docs/8.x/events#writing-event-subscribers)

**Comment by driesvints** [comment]
@schwartzmj can you try by modifying that piece to

```php
                if (is_string($listener)) {
                    return Str::contains($listener, '@') ? $listener : $listener.'@handle';
                } elseif (is_array($listener)) {
                    $class = is_object($listener[0]) ? get_class($listener[0]) : $listener[0];

                    return $class.'@'.$listener[1];
                }
```
