### ISSUE TITLE
  There are no commands defined in the "telescope" namespace.

### ISSUE THREAD

**Issue by jud3v** [laravel/telescope#954]
- Telescope Version: 4.x.x, 4.0.0, 4.0.1
- Laravel Version: 8.6.0
- PHP Version: 7.4.10
- ZendEngine : 3.4.0
- Database Driver & Version: mysql  Ver 15.1 Distrib 10.4.14-MariaDB, for Linux (x86_64) using  EditLine wrapper

### Description:

Hello i'm using laravel telescope on my project to track bug, job, ...

- Previously i used laravel version 7.25.0 with telescope version 3.x.x every working well.
- After upgrade to a latest version of laravel 7, telescope don't work anymore i have try to uninstall, install, but nothing does work.
- So i have installed the new version of laravel 8 with following the upgrade guide available on the docs of laravel and installing the legacy factory in laravel because new factories and model are not able to work with version 8 of laravel.
- After install Laravel 8.0.1 i'm gonna try make work laravel/telescope but nothing works well.
- I have try these issue: [#336 ](https://github.com/laravel/telescope/issues/336) [#674](https://github.com/laravel/telescope/issues/674)

So i don't know how to fix this.

I have also try this:

`composer dump-auto`
`php artisan conf:clear`
`php artisan cache:clear`

nothing work, if i would interact with telescope, the return is every time the same:
>   There are no commands defined in the "telescope" namespace.

### Steps To Reproduce:

Following the docs command:

- `composer require laravel/telescope`
- `php artisan telescope:install`
> return :
` There are no commands defined in the "telescope" namespace.`

**Comment by abdulmanan7** [comment]
Remove 
`["laravel/telescope"] from dont-discover`
and then run `composer dump-auto`

**Comment by IVNtech** [comment]
> ["laravel/telescope"] from dont-discover block

thanks a lot this @jud3v code works on my laravel and worked!!!!!!!!!!

["laravel/telescope"] from dont-discover block - inside composer.json

**Comment by thomasmokuaomweri2011** [comment]
If auto-discovery is not enabled, then add `Laravel\Telescope\TelescopeServiceProvider` to config/app.php
Feel free to also add the alias

**Comment by Sagar158** [comment]
> If auto-discovery is not enabled, then add `Laravel\Telescope\TelescopeServiceProvider` to config/app.php Feel free to also add the alias

Thanks bro it worked
