### ISSUE TITLE
Cloudflare response error 

### ISSUE THREAD

**Issue by devmsh** [laravel/telescope#957]
- Telescope Version: 4.X
- Laravel Version: 8.X
- PHP Version: 7.4

### Description:

if I tried to search for a tag like `App\Models\Conversation:115` I got this.

```
content-length: 0
date: Wed, 30 Sep 2020 19:31:41 GMT
status: 400
via: 1.1 216b2e0a8a27f8fca1b540a1c4ea6922.cloudfront.net (CloudFront)
x-amz-cf-id: cc4xpg24h0KQNiQFzC0Ma-s8gedAmPS8c7NUF4TnPCzzPC8-fHJnIQ==
x-amz-cf-pop: FRA2-C2
x-cache: Error from cloudfront
```

**Comment by driesvints** [comment]
Not sure what that is about but that seems very specific to your use case. Please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks.
