### ISSUE TITLE
Feature Request: Securing Telescope without using sessions.

### ISSUE THREAD

**Issue by ssarljames** [laravel/telescope#958]
Hi there,

I'm having an issue that I must have the access on Telescope on production site without having to logon to the system.

As far as I know, we can secure Telescope with the following code

```php
    /**
     * Register the Telescope gate.
     *
     * This gate determines who can access Telescope in non-local environments.
     *
     * @return void
     */
    protected function gate()
    {
        Gate::define('viewTelescope', function ($user) {
            return in_array($user->email, [
                "admin@email.com",
            ]);
        });
    }
```

In my case, I don't have a user from the production site so the code above will not work.

Can we have another method of securing Telescope like passing a **long token** to Telescope url and that token will be also added to async requests performed on the frontend.

Then in `TelescopeServiceProvider`, we will check that token if it is on whitelist.

That would be all. Thank you.

**Comment by driesvints** [comment]
Don't think we have any plans for this, sorry.
