### ISSUE TITLE
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB serve r version for the right syntax to use near 'json not null, `created_at` datetime null) collate 'utf8mb4_unicode_ci'' at line 1"

### ISSUE THREAD

**Issue by lenard123** [laravel/telescope#96]
I got this error after running "php artisan telescope:install" and "php artisan migate".

![screenshot 59](https://user-images.githubusercontent.com/31153286/47400383-7e978100-d76f-11e8-8b74-32cc1b7da48e.png)

**Comment by Te7a-Houdini** [comment]
check #36  & #51

**Comment by warrenca** [comment]
@lenard123 I have a solution here https://github.com/laravel/telescope/issues/36#issuecomment-432905507

**Comment by YuSuFApiwi** [comment]
I have changed $table->json("name_column") to $tbale->text("name_column") But this is not the right way to work because I use MySQL InnoDB where not accepted JSON It may be due to the version 10.1.38-MariaDB
