### ISSUE TITLE
Request Logs Improvement

### ISSUE THREAD

**Issue by kingeke** [laravel/telescope#960]
Hello, so when i want to view the request logs, it takes a long time and that's mostly cause its fetching all the data per request, the sessions, the response, all the logs etc.. and this slows down the whole loading time, when we're only viewing the status code, uri, response time and created_at..

Is it possible to limit the data returned to just that so the loading time can be increased??

**Comment by driesvints** [comment]
I haven't experienced anything like this myself. If you want to improve something here feel free to send in a PR 👍

**Comment by kingeke** [comment]
@driesvints it'll only be experience if you're using a slow internet connection, cause it has to loan all the details per requests when you're viewing all requests, can the index page be limited to just the necessities ? that's the status code, uri, response time and created_at ?
