### ISSUE TITLE
Telescope should use a timezone aware database data type

### ISSUE THREAD

**Issue by logan2211** [laravel/telescope#972]
- Telescope Version: 3.5.1
- Laravel Version: 6.18.40
- PHP Version: 7.4.11
- Database Driver & Version: mariadb 10.3

### Description:
Telescope should use a timestamp column rather than [datetime](https://github.com/laravel/telescope/blob/86665787a7183f85d9e4551ec059f239e48af89c/src/Storage/migrations/2018_08_08_100000_create_telescope_entries_table.php#L51) for storing the event timestamps. Datetime columns are not accurate timestamps because they do not account for timezones.

**Comment by driesvints** [comment]
We're not sure ourselves why this was the choice back then. All other packages use the timestamp column. However, we won't be changing this as that'd be a unnecessary breaking change to our users. 

Afaik timestamp fields also don't save timezone info? In general I don't recommend saving timezone info together with any datetime/timestamp field and always save that in a separate column.
