### ISSUE TITLE
Installation on Laravel 8 does not work

### ISSUE THREAD

**Issue by martio** [laravel/telescope#976]
- Telescope Version: 4.2.0
- Laravel Version: 8.12.3
- PHP Version: 7.4
- Database Driver & Version: MySQL

### Description:

I have a new project on the latest version of Laravel. When installed, it only adds the provider to the "config/app.php" file. Does not copy "app/Providers/TelescopeServiceProvider.php" and config, migration, resources and assets files. After entering the dashboard at /telescope, it does not work.

<img width="1112" alt="telescope" src="https://user-images.githubusercontent.com/133636/97688725-d5d93600-1a9a-11eb-9de3-f4450d442d74.png">

![assets](https://user-images.githubusercontent.com/133636/97688732-d8d42680-1a9a-11eb-9d06-e9e5bc9c3893.jpg)

### Steps To Reproduce:

```
$ composer require laravel/telescope
$ php artisan telescope:install
$ php artisan telescope:publish
```

**Comment by driesvints** [comment]
Works fine for me:

<img width="894" alt="Screenshot 2020-10-30 at 10 49 09" src="https://user-images.githubusercontent.com/594614/97690642-8e07de00-1a9d-11eb-8315-df250c3b53a1.png">

**Comment by skrivitsky** [comment]
@driesvints Did you install package via register method and require-dev ?

**Comment by martio** [comment]
I'm sorry, it's my mistake :(

`TELESCOPE_ENABLED=false`

**Comment by driesvints** [comment]
@skrivitsky I used the steps to reproduce from the OP

**Comment by martio** [comment]
You can close, it's OK 👍
