### ISSUE TITLE
Add canceled lable into batch screens

### ISSUE THREAD

**Issue by neverfan** [laravel/telescope#980]
Hi. If batch was canceled, then the field `canceled_at` is set for it. I think it would be correct to display a separate status for canceled batches.

In files:
https://github.com/laravel/telescope/blob/4.x/resources/js/screens/batches/index.vue
https://github.com/laravel/telescope/blob/4.x/resources/js/screens/batches/preview.vue

**Comment by driesvints** [comment]
Could indeed maybe be useful. Feel free to attempt a PR.
