### ISSUE TITLE
Unable to locate publishable resources

### ISSUE THREAD

**Issue by martio** [laravel/telescope#981]
- Telescope Version: 4.3.1
- Laravel Version: 8.14.0
- PHP Version: 7.4

### Description:

An error occurred while updating libraries: "Unable to locate publishable resources"

<img width="630" alt="Zrzut ekranu 2020-11-11 o 18 22 52" src="https://user-images.githubusercontent.com/133636/98843540-66285b00-244b-11eb-9fd0-a06179a462b1.png">

### Steps To Reproduce:

In **composer.json** file:

```
    "scripts": {
        "post-update-cmd": [
            "@php artisan telescope:publish --ansi"
        ]
    }
```

**Comment by driesvints** [comment]
Think this is specifically related to your Docker setup because it works fine for me on my local macOS environment:

<img width="912" alt="Screenshot 2020-11-12 at 10 31 20" src="https://user-images.githubusercontent.com/594614/98922026-438d5500-24d2-11eb-97aa-0d5b1a8cfa69.png">

**Comment by martio** [comment]
I checked and I still have a bug:

```
$ php artisan telescope:publish --ansi
Unable to locate publishable resources.
Publishing complete.
Unable to locate publishable resources.
Publishing complete.
```

I have the latest version of the libraries...

**Comment by driesvints** [comment]
I think it's best that you try a support channel for this as this is not related to the library itself.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

**Comment by timacdonald** [comment]
I've just run into this as well. Happens locally and in Docker. `horizon:publish` and `nova:publish` work as expected. Trying to debug further

**Comment by timacdonald** [comment]
ahhhh, lol. My bad. I had Telescope disabled in my ENV, which means this command won't work hehe. @martio might just wanna check your haven't accidentally done the same

**Comment by martio** [comment]
@timacdonald yes, I have the same 🙈 Thanks! 😀
