### ISSUE TITLE
Allow not including SQL values in logging

### ISSUE THREAD

**Issue by johnwc** [laravel/telescope#983]
Would be very beneficial to be able to have an option to disable logging SQL values for very large queries. When running queues, we have background tasks that import large amounts of data. These telescope entries fail, as the sql text is around 300mb.

**Comment by driesvints** [comment]
I don't know how we'd know up front how large these queries are going to be? In general it seems a bad idea to have such large queries.

**Comment by johnwc** [comment]
That's why I mentioned for there to be a way to optionally disable logging the binding data. Sometime we just need to see the error, and not the actual SQL data. Please indulge me on why you think it's such a bad idea to do a MySQL recommended bulk insert. To be clear, the data being inserted is not 300MB, the text form of the SQL insert is 300MB.
