### ISSUE TITLE
RequestWatcher fails to read headers containing some characters

### ISSUE THREAD

**Issue by Jespercal** [laravel/telescope#984]
We just encountered a problem with Telescope, where we sent requests to our endpoint, but they wouldn't show up, not even as 404s.
After some digging, it turns out that they did go through Laravel, but Telescope wouldn't register them. Only after we changed map in headers to return it as utf8_encode(header[0]).
Dumping the header from the endpoint would show a corrupted json header when not using utf8_encode beforehand.

**Steps to replicate:**
- Send request to server using ex. Postman where you add a custom header entry with any non-english letters, like æ, ø or å. (In my own test, I added: "testing":"æøåÆØÅ")
* Or add username and/or password with æ,ø,å.

**Comment by driesvints** [comment]
Please resubmit this with a filled out issue template.
