### ISSUE TITLE
Telescope doesnt record some request

### ISSUE THREAD

**Issue by nogamenofun98** [laravel/telescope#989]
- Telescope Version: 3.5.1
- Laravel Version: 7.28.4
- PHP Version: 7.3
- Database Driver & Version:

### Description:
Telescope wont record some api request
Below are the request list show in telescope:
![image](https://user-images.githubusercontent.com/9070825/101116178-8ea50e80-361f-11eb-9043-8b6011c3338a.png)

Below are the request log from my own code in database, id 195740 is the /auth api in telescope log, and 195741 is the missing api log (url is /extend) in telescope, the 195750 and 195751 are the "mrspeedy/callback" record in telescope
![image](https://user-images.githubusercontent.com/9070825/101116287-c4e28e00-361f-11eb-934c-e9044b990d99.png)

The duration of the /extend to response is 21 second, the client side is received timeout error. Does telescope wont log timeout request? or this is a bug? (the response of that /extend is not large also)

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
