### ISSUE TITLE
Vendor Publishes to the wrong path if path.public has been altered

### ISSUE THREAD

**Issue by adampatterson** [laravel/telescope#992]
- Telescope Version: ^4.3
- Laravel Version: ^8.0
- PHP Version: 7.4.9
- Database Driver & Version:

### Description:
I have set a custom assets folder and have changed the path in `AppServiceProvider`.  Running `artisan telescope:publish` is still using my original public path.

### Steps To Reproduce:

```
// AppServiceProvider.php
$this->app->bind('path.public', function () {
     return base_path() . DIRECTORY_SEPARATOR . 'assets';
});
```

```
artisan telescope:publish
Publishing complete.
Copied Directory [/vendor/laravel/telescope/public] To [/public/vendor/telescope]
Publishing complete.
```

View `/telescope`
```
The Telescope assets are not published. Please run: php artisan telescope:publish
```

It looks like the path is set to `/public` regardless of changing the path. 

https://github.com/laravel/telescope/blob/266d9c3a51d5dfa202c4943f5c3466d73c949cae/src/TelescopeServiceProvider.php#L91

I get that this is an edge case and I can manually move the assets.

But Telescope is calling `public_path` which in my case is returning `/assets`

https://github.com/laravel/framework/blob/8.x/src/Illuminate/Foundation/helpers.php#L561

**Comment by driesvints** [comment]
Please post your `AppServiceProvider.php`

**Comment by adampatterson** [comment]
```
<?php

namespace App\Providers;

use App;
use Request;
use Illuminate\Support\Facades\View;
use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{

    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        if ($this->app->environment() === 'local') {
            $this->app->register(\Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider::class);
        }
    }

    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot(\Illuminate\Http\Request $request)
    {
        $this->app->bind('path.public', function () {
            return base_path() . DIRECTORY_SEPARATOR . 'assets';
        });

        // Correct the ULR for any proxy-based forwarding like Ngrok or CloudFront.
        if ($request->server->has('HTTP_X_ORIGINAL_HOST')) {
            $this->app['url']->forceRootUrl($request->server->get('HTTP_X_FORWARDED_PROTO') . '://' . $request->server->get('HTTP_X_ORIGINAL_HOST'));
        }

        if ($this->app->environment() === 'local') {
            \URL::forceScheme('https');
        }
    }
}
```

**Comment by driesvints** [comment]
Your binding of the public path is in the boot method and not in the register method. This can conflict with Telescope's boot method being loaded before your own boot method.

**Comment by adampatterson** [comment]
@driesvints Are you saying that if I move the binding to the boot method it should work properly?

**Comment by driesvints** [comment]
I think so yeah
