### ISSUE TITLE
Pause starts playing again without being clicked

### ISSUE THREAD

**Issue by FutureFutureTo** [laravel/telescope#994]
- Telescope Version: 4.3
- Laravel Version: 8.0
- PHP Version: 7.6
- Database Driver & Version: MySQL 5.6

### Description:
When clicking pause, Telescope will just start recording again after a few seconds or so

**Comment by driesvints** [comment]
Not sure what the problem here is

**Comment by FutureFutureTo** [comment]
Sorry, that wasn't super informative.

Basically, the toggle Play/Pause button just seems to reset itself. I can see it in realtime, watching it, after about 2-5 minutes, if paused, it just starts recording again.

I understand this Play/Pause is stored in cache...

I'm using a separate redis server to store cache, and am running this on production.

Just to test, I have been recording all events, and this obviously fills up the DB pretty quickly if I can't properly pause.

In the meantime, I've removed recording of Redis, and also am clearing the telescope entries every hour.

Has anyone else had any issues with the Play/Pause not working for them?

**Comment by driesvints** [comment]
No not yet. Since this is the first report we're getting for this I don't think this is a widespread issue.

**Comment by FutureFutureTo** [comment]
Okay, thanks for the prompt response - I'll keep digging on my side, but its not a huge issue either way.

This product is amazing, and I really appreciate all the work you guys put into this and the Laravel ecosystem - truly :)
