### ISSUE TITLE
Option to store the query debug trace

### ISSUE THREAD

**Issue by diogogomeswww** [laravel/telescope#998]
My suggestion is to have an option to store the query debug trace.
Option to be set to disable by default.

This would be useful to find n+1 queries, finding queries that are running on the views,...

I'm happy to make the PR if you like/want this new option.

Side question:
Why is telescope always storing an empty array for the binding?
![image](https://user-images.githubusercontent.com/11543163/101941921-97c64a80-3be0-11eb-994a-a8b257bffbe8.png)

**Comment by driesvints** [comment]
Please see Taylor's comment here: https://github.com/laravel/telescope/pull/164#issuecomment-433052383

> Why is telescope always storing an empty array for the binding?

My guess is to prevent the storage of sensitive data.
